### ISSUE TITLE
ENV file sometimes doesnt load

### ISSUE THREAD

**Issue by autaut03** [laravel/framework#10310]
Sometimes when I entered pages too fast Laravel has been giving me errors "Whoops, something went wrong". Exactly 2 errors every time, and no debug information, but it's enabled in the ENV. Then I checked my log files and found 650 thousands of rows with almost same errors:

```php
[2015-09-19 00:05:58] local.ERROR: exception 'PDOException' with message 'SQLSTATE[HY000] [1045] Access denied for user 'forge'@'localhost' (using password: NO)' in W:\domains\winezy.local\vendor\laravel\framework\src\Illuminate\Database\Connectors\Connector.php:50
Stack trace:
#0 W:\domains\winezy.local\vendor\laravel\framework\src\Illuminate\Database\Connectors\Connector.php(50): PDO->__construct('mysql:host=loca...', 'forge', '', Array)
#1 W:\domains\winezy.local\vendor\laravel\framework\src\Illuminate\Database\Connectors\MySqlConnector.php(22): Illuminate\Database\Connectors\Connector->createConnection('mysql:host=loca...', Array, Array)
#2 W:\domains\winezy.local\vendor\laravel\framework\src\Illuminate\Database\Connectors\ConnectionFactory.php(60): Illuminate\Database\Connectors\MySqlConnector->connect(Array)
#3 W:\domains\winezy.local\vendor\laravel\framework\src\Illuminate\Database\Connectors\ConnectionFactory.php(49): Illuminate\Database\Connectors\ConnectionFactory->createSingleConnection(Array)
#4 W:\domains\winezy.local\vendor\laravel\framework\src\Illuminate\Database\DatabaseManager.php(175): Illuminate\Database\Connectors\ConnectionFactory->make(Array, 'mysql')
#5 W:\domains\winezy.local\vendor\laravel\framework\src\Illuminate\Database\DatabaseManager.php(67): Illuminate\Database\DatabaseManager->makeConnection('mysql')
#6 W:\domains\winezy.local\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(3175): Illuminate\Database\DatabaseManager->connection(NULL)
#7 W:\domains\winezy.local\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(3141): Illuminate\Database\Eloquent\Model::resolveConnection(NULL)
#8 W:\domains\winezy.local\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1895): Illuminate\Database\Eloquent\Model->getConnection()
#9 W:\domains\winezy.local\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1838): Illuminate\Database\Eloquent\Model->newBaseQueryBuilder()
#10 W:\domains\winezy.local\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1812): Illuminate\Database\Eloquent\Model->newQueryWithoutScopes()
#11 W:\domains\winezy.local\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(3387): Illuminate\Database\Eloquent\Model->newQuery()
#12 [internal function]: Illuminate\Database\Eloquent\Model->__call('orderBy', Array)
#13 [internal function]: App\Game->orderBy('id', 'desc')
#14 W:\domains\winezy.local\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(3403): call_user_func_array(Array, Array)
#15 W:\domains\winezy.local\app\Providers\AppServiceProvider.php(16): Illuminate\Database\Eloquent\Model::__callStatic('orderBy', Array)
#16 W:\domains\winezy.local\app\Providers\AppServiceProvider.php(16): App\Game::orderBy('id', 'desc')
#17 [internal function]: App\Providers\AppServiceProvider->boot()
#18 W:\domains\winezy.local\vendor\laravel\framework\src\Illuminate\Container\Container.php(502): call_user_func_array(Array, Array)
#19 W:\domains\winezy.local\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(734): Illuminate\Container\Container->call(Array)
#20 W:\domains\winezy.local\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(717): Illuminate\Foundation\Application->bootProvider(Object(App\Providers\AppServiceProvider))
#21 [internal function]: Illuminate\Foundation\Application->Illuminate\Foundation\{closure}(Object(App\Providers\AppServiceProvider), 14)
#22 W:\domains\winezy.local\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(718): array_walk(Array, Object(Closure))
#23 W:\domains\winezy.local\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\BootProviders.php(17): Illuminate\Foundation\Application->boot()
#24 W:\domains\winezy.local\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(203): Illuminate\Foundation\Bootstrap\BootProviders->bootstrap(Object(Illuminate\Foundation\Application))
#25 W:\domains\winezy.local\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(222): Illuminate\Foundation\Application->bootstrapWith(Array)
#26 W:\domains\winezy.local\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(117): Illuminate\Foundation\Http\Kernel->bootstrap()
#27 W:\domains\winezy.local\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(87): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#28 W:\domains\winezy.local\public\index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#29 {main}  
[2015-09-19 00:05:58] local.ERROR: exception 'RuntimeException' with message 'No supported encrypter found. The cipher and / or key length are invalid.' in W:\domains\winezy.local\vendor\laravel\framework\src\Illuminate\Encryption\EncryptionServiceProvider.php:29
Stack trace:
#0 W:\domains\winezy.local\vendor\laravel\framework\src\Illuminate\Container\Container.php(733): Illuminate\Encryption\EncryptionServiceProvider->Illuminate\Encryption\{closure}(Object(Illuminate\Foundation\Application), Array)
#1 W:\domains\winezy.local\vendor\laravel\framework\src\Illuminate\Container\Container.php(626): Illuminate\Container\Container->build(Object(Closure), Array)
#2 W:\domains\winezy.local\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(674): Illuminate\Container\Container->make('encrypter', Array)
#3 W:\domains\winezy.local\vendor\laravel\framework\src\Illuminate\Container\Container.php(837): Illuminate\Foundation\Application->make('Illuminate\\Cont...')
#4 W:\domains\winezy.local\vendor\laravel\framework\src\Illuminate\Container\Container.php(800): Illuminate\Container\Container->resolveClass(Object(ReflectionParameter))
#5 W:\domains\winezy.local\vendor\laravel\framework\src\Illuminate\Container\Container.php(771): Illuminate\Container\Container->getDependencies(Array, Array)
#6 W:\domains\winezy.local\vendor\laravel\framework\src\Illuminate\Container\Container.php(626): Illuminate\Container\Container->build('App\\Http\\Middle...', Array)
#7 W:\domains\winezy.local\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(674): Illuminate\Container\Container->make('App\\Http\\Middle...', Array)
#8 W:\domains\winezy.local\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(142): Illuminate\Foundation\Application->make('App\\Http\\Middle...')
#9 W:\domains\winezy.local\public\index.php(58): Illuminate\Foundation\Http\Kernel->terminate(Object(Illuminate\Http\Request), Object(Illuminate\Http\Response))
#10 {main}  
```

I checked the internet and found information, that some people have same problem. ENV file sometimes just doesnt load, and laravel uses default config options > cant connect so gives errors. FIX this please)

http://stackoverflow.com/questions/31859601/whoops-looks-like-something-went-wrong-laravel-5-1

**Comment by Sladewill** [comment]
Yeah we also get this a lot on Bugsnag reporting but this is a dotenv issue and not a laravel issue the the only thing laravle could do is revert back to using the old method of .env.php file like in laravel 4 which actually worked fine.

**Comment by autaut03** [comment]
Or cache the ENV settings and call them if they are not avaliable

**Comment by crynobone** [comment]
> Or cache the ENV settings and call them if they are not avaliable

It's already available via `php artisan config:cache`.
