### ISSUE TITLE
Faker Provider fails when using PHPUnit

### ISSUE THREAD

**Issue by greenleafmedia** [laravel/framework#10345]
I have created a custom faker provider as defined on the Faker github:

```
<?php
namespace database\factories\faker;

use Faker\Provider\Base;

class Inspections extends Base
{
    //Features
    protected static $f_measurement = ['.531" Diameter Holes','.9.75"','Burrs and Cosmetics','Threads','13.750"',
        '5.Lip thickness'];
    protected static $f_location = ['center of part','Bottom','Height','Width','Thickness','Face of Part','Varies'];

    //Measurements
    protected static $m_measurement = ['.7865','1.0002','9.765','No Burrs','OK','13.755','9.748'];


    public function featureMeasurement()
    {
        return static::randomElement(static::$f_measurement);
    }

    public function featureLocation()
    {
        return static::randomElement(static::$f_location);
    }

    public function measurementMeasurement()
    {
        return static::randomElement(static::$m_measurement);
    }
}
```
This provider works fine in my seeder.  However, now whenever I use any factory in PHPUnit I get fatal errors:

```
PHPUnit 4.7.7 by Sebastian Bergmann and contributors.

..PHP Fatal error:  Cannot redeclare class database\factories\faker\Inspections in /home/vagrant/laravel/my-project/database/factories/faker/Inspections.php on line 31
PHP Stack trace:
PHP   1. {main}() /home/vagrant/laravel/my-project/vendor/phpunit/phpunit/phpunit:0
PHP   2. PHPUnit_TextUI_Command::main() /home/vagrant/laravel/my-project/vendor/phpunit/phpunit/phpunit:36
PHP   3. PHPUnit_TextUI_Command->run() /home/vagrant/laravel/my-project/vendor/phpunit/phpunit/src/TextUI/Command.php:99
PHP   4. PHPUnit_TextUI_TestRunner->doRun() /home/vagrant/laravel/my-project/vendor/phpunit/phpunit/src/TextUI/Command.php:147
PHP   5. PHPUnit_Framework_TestSuite->run() /home/vagrant/laravel/my-project/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:428
PHP   6. PHPUnit_Framework_TestSuite->run() /home/vagrant/laravel/my-project/vendor/phpunit/phpunit/src/Framework/TestSuite.php:738
PHP   7. PHPUnit_Framework_TestCase->run() /home/vagrant/laravel/my-project/vendor/phpunit/phpunit/src/Framework/TestSuite.php:738
PHP   8. PHPUnit_Framework_TestResult->run() /home/vagrant/laravel/my-project/vendor/phpunit/phpunit/src/Framework/TestCase.php:702
PHP   9. PHPUnit_Framework_TestCase->runBare() /home/vagrant/laravel/my-project/vendor/phpunit/phpunit/src/Framework/TestResult.php:601
PHP  10. PHPUnit_Framework_TestCase->runTest() /home/vagrant/laravel/my-project/vendor/phpunit/phpunit/src/Framework/TestCase.php:746
PHP  11. ReflectionMethod->invokeArgs() /home/vagrant/laravel/my-project/vendor/phpunit/phpunit/src/Framework/TestCase.php:881
PHP  12. DropdownAPITest->a_dropdown_can_only_be_deleted_if_its_id_is_in_the_model() /home/vagrant/laravel/my-project/vendor/phpunit/phpunit/src/Framework/TestCase.php:881
PHP  13. factory() /home/vagrant/laravel/my-project/phpunit/DropdownAPITest.php:98
PHP  14. app() /home/vagrant/laravel/my-project/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php:268
PHP  15. Illuminate\Foundation\Application->make() /home/vagrant/laravel/my-project/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php:54
PHP  16. Illuminate\Container\Container->make() /home/vagrant/laravel/my-project/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:674
PHP  17. Illuminate\Container\Container->build() /home/vagrant/laravel/my-project/vendor/laravel/framework/src/Illuminate/Container/Container.php:626
PHP  18. Illuminate\Database\DatabaseServiceProvider->Illuminate\Database\{closure}() /home/vagrant/laravel/my-project/vendor/laravel/framework/src/Illuminate/Container/Container.php:733
PHP  19. Illuminate\Database\Eloquent\Factory::construct() /home/vagrant/laravel/my-project/vendor/laravel/framework/src/Illuminate/Database/DatabaseServiceProvider.php:69
PHP Fatal error:  Uncaught exception 'Illuminate\Contracts\Container\BindingResolutionException' with message 'Target [Illuminate\Contracts\Debug\ExceptionHandler] is not instantiable.' in /home/vagrant/laravel/my-project/vendor/laravel/framework/src/Illuminate/Container/Container.php:744
Stack trace:
#0 /home/vagrant/laravel/my-project/vendor/laravel/framework/src/Illuminate/Container/Container.php(626): Illuminate\Container\Container->build('Illuminate\\Cont...', Array)
#1 /home/vagrant/laravel/my-project/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(674): Illuminate\Container\Container->make('Illuminate\\Cont...', Array)
#2 /home/vagrant/laravel/my-project/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(154): Illuminate\Foundation\Application->make('Illuminate\\Cont...')
#3 /home/vagrant/laravel/my-project/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(79): Illuminate\Foundation\Bootstrap\HandleExceptions->getExcept in /home/vagrant/laravel/my-project/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 744
PHP Stack trace:
PHP   1. {main}() /home/vagrant/laravel/my-project/vendor/phpunit/phpunit/phpunit:0
PHP   2. PHPUnit_TextUI_Command::main() /home/vagrant/laravel/my-project/vendor/phpunit/phpunit/phpunit:36
PHP   3. PHPUnit_TextUI_Command->run() /home/vagrant/laravel/my-project/vendor/phpunit/phpunit/src/TextUI/Command.php:99
PHP   4. PHPUnit_TextUI_TestRunner->doRun() /home/vagrant/laravel/my-project/vendor/phpunit/phpunit/src/TextUI/Command.php:147
PHP   5. PHPUnit_Framework_TestSuite->run() /home/vagrant/laravel/my-project/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:428
PHP   6. PHPUnit_Framework_TestSuite->run() /home/vagrant/laravel/my-project/vendor/phpunit/phpunit/src/Framework/TestSuite.php:738
PHP   7. PHPUnit_Framework_TestCase->run() /home/vagrant/laravel/my-project/vendor/phpunit/phpunit/src/Framework/TestSuite.php:738
PHP   8. PHPUnit_Framework_TestResult->run() /home/vagrant/laravel/my-project/vendor/phpunit/phpunit/src/Framework/TestCase.php:702
PHP   9. PHPUnit_Framework_TestCase->runBare() /home/vagrant/laravel/my-project/vendor/phpunit/phpunit/src/Framework/TestResult.php:601
PHP  10. PHPUnit_Framework_TestCase->runTest() /home/vagrant/laravel/my-project/vendor/phpunit/phpunit/src/Framework/TestCase.php:746
PHP  11. ReflectionMethod->invokeArgs() /home/vagrant/laravel/my-project/vendor/phpunit/phpunit/src/Framework/TestCase.php:881
PHP  12. DropdownAPITest->a_dropdown_can_only_be_deleted_if_its_id_is_in_the_model() /home/vagrant/laravel/my-project/vendor/phpunit/phpunit/src/Framework/TestCase.php:881
PHP  13. factory() /home/vagrant/laravel/my-project/phpunit/DropdownAPITest.php:98
PHP  14. app() /home/vagrant/laravel/my-project/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php:268
PHP  15. Illuminate\Foundation\Application->make() /home/vagrant/laravel/my-project/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php:54
PHP  16. Illuminate\Container\Container->make() /home/vagrant/laravel/my-project/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:674
PHP  17. Illuminate\Container\Container->build() /home/vagrant/laravel/my-project/vendor/laravel/framework/src/Illuminate/Container/Container.php:626
PHP  18. Illuminate\Database\DatabaseServiceProvider->Illuminate\Database\{closure}() /home/vagrant/laravel/my-project/vendor/laravel/framework/src/Illuminate/Container/Container.php:733
PHP  19. Illuminate\Database\Eloquent\Factory::construct() /home/vagrant/laravel/my-project/vendor/laravel/framework/src/Illuminate/Database/DatabaseServiceProvider.php:69
```
Upon digging, the part that seems to be causing trouble is in the  `\Illuminate\Database\Eloquent\Factory` constructor.

Where am I going wrong?

**Comment by GrahamCampbell** [comment]
Please ask on the forums.
