### ISSUE TITLE
[Request] Forward compatibility for PHPUnit 5

### ISSUE THREAD

**Issue by shehi** [laravel/framework#10829]
Unit-tests created for PHPUnit 4 generally work in v5, but I experienced problems in context of Binding and Resolution of providers. Example would be:

My app utilizes Cartalyst/Sentinel package and I use it via ```app('sentinel')``` initiator. Whenever unit-test works flawlessly, nothing wrong happens. But the moment you have counter-assertion (failing assertion) in tests, an exception similar to this happens:

```exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Uncaught exception 'Illuminate\Contracts\Container\BindingResolutionException' with message 'Target [Illuminate\Contracts\Debug\ExceptionHandler] is not instantiable.' in /home/shehi/Projects/Basis/vendor/laravel/framework/src/Illuminate/Container/Container.php:745 
Stack trace: 
#0 /home/shehi/Projects/Basis/vendor/laravel/framework/src/Illuminate/Container/Container.php(627): Illuminate\Container\Container->build('Illuminate\\Cont...', Array) 
#1 /home/shehi/Projects/Basis/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(674): Illuminate\Container\Container->make('Illuminate\\Cont...', Array) 
#2 /home/shehi/Projects/Basis/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(154): Illuminate\Foundation\Application->make('Illuminate\\Cont...') 
#3 /home/shehi/Projects/Basis/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(79): Illuminate\Foundation\Bootstrap\HandleExceptions->getExceptionHandler() 
#4 [internal function]: Illuminate\Fo' in /home/shehi/Projects/Basis/vendor/laravel/framework/src/Illuminate/Container/Container.php:745 
Stack trace: 
#0 /home/shehi/Projects/Basis/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(133): Symfony\Component\Debug\Exception\FatalErrorException->__construct() 
#1 /home/shehi/Projects/Basis/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(118): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError() 
#2 /home/shehi/Projects/Basis/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(0): Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown() #3 {main} [] []```

This exception, by the looks of it, has nothing to do with actual test, as when I downgrade, real assertion errors show up. Also notice in TRACE after #4, it somehow gets concatenated and new trace starts. Kinda weird as an internal function trace pops up there :) 

My project in question is: http://github.com/AudithSoftworks/Basis

In any way, I recommend thorough testing of PHPUnit 5 for upcoming Laravel release, including service container, bindings and resolutions scopes especially for cases of failing-assertions.

**Comment by sebastianbergmann** [comment]
Maybe related to #10808?

**Comment by shehi** [comment]
Closed in favor of #10808

**Comment by shehi** [comment]
@taylorotwell can you confirm that my case is related to #10808? In either case though, are there any possible solutions for this?

**Comment by GrahamCampbell** [comment]
We can continue everything on #10808 then. :)
