### ISSUE TITLE
Laravel sometimes changes the environment automatically 

### ISSUE THREAD

**Issue by punchi** [laravel/framework#10989]
While pressing some links in my local/dev website (maybe too quick?) suddenly appears a "Whoops, looks like something went wrong." so I check the logs, and this is what I get:

```
[2015-11-16 15:13:59] production.ERROR: exception 'PDOException' with message 'SQLSTATE[HY000] [1044] Access denied for user ''@'localhost' to database 'forge'' in C:\wamp\www\site\vendor\laravel\framework\src\Illuminate\Database\Connectors\Connector.php:55
Stack trace:
#0 C:\wamp\www\site\vendor\laravel\framework\src\Illuminate\Database\Connectors\Connector.php(55): PDO->__construct('mysql:host=loca...', 'forge', '', Array)
#1 C:\wamp\www\site\vendor\laravel\framework\src\Illuminate\Database\Connectors\MySqlConnector.php(22): Illuminate\Database\Connectors\Connector->createConnection('mysql:host=loca...', Array, Array)
#2 C:\wamp\www\site\vendor\laravel\framework\src\Illuminate\Database\Connectors\ConnectionFactory.php(60): Illuminate\Database\Connectors\MySqlConnector->connect(Array)
#3 C:\wamp\www\site\vendor\laravel\framework\src\Illuminate\Database\Connectors\ConnectionFactory.php(49): Illuminate\Database\Connectors\ConnectionFactory->createSingleConnection(Array)
#4 C:\wamp\www\site\vendor\laravel\framework\src\Illuminate\Database\DatabaseManager.php(175): Illuminate\Database\Connectors\ConnectionFactory->make(Array, 'mysql')
#5 C:\wamp\www\site\vendor\laravel\framework\src\Illuminate\Database\DatabaseManager.php(67): Illuminate\Database\DatabaseManager->makeConnection('mysql')
#6 C:\wamp\www\site\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(3268): Illuminate\Database\DatabaseManager->connection(NULL)
#7 C:\wamp\www\site\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(3234): Illuminate\Database\Eloquent\Model::resolveConnection(NULL)
#8 C:\wamp\www\site\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1914): Illuminate\Database\Eloquent\Model->getConnection()
#9 C:\wamp\www\site\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1857): Illuminate\Database\Eloquent\Model->newBaseQueryBuilder()
#10 C:\wamp\www\site\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1831): Illuminate\Database\Eloquent\Model->newQueryWithoutScopes()
#11 C:\wamp\www\site\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(3480): Illuminate\Database\Eloquent\Model->newQuery()
#12 C:\wamp\www\site\app\Permiso.php(14): Illuminate\Database\Eloquent\Model->__call('select', Array)
#13 C:\wamp\www\site\app\Permiso.php(14): site\Permiso->select('id_permiso', 'nombre')
#14 C:\wamp\www\site\app\Providers\AuthServiceProvider.php(38): site\Permiso->getPermisos()
#15 [internal function]: site\Providers\AuthServiceProvider->boot(Object(Illuminate\Auth\Access\Gate))
#16 C:\wamp\www\site\vendor\laravel\framework\src\Illuminate\Container\Container.php(503): call_user_func_array(Array, Array)
#17 C:\wamp\www\site\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(734): Illuminate\Container\Container->call(Array)
#18 C:\wamp\www\site\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(717): Illuminate\Foundation\Application->bootProvider(Object(site\Providers\AuthServiceProvider))
#19 [internal function]: Illuminate\Foundation\Application->Illuminate\Foundation\{closure}(Object(site\Providers\AuthServiceProvider), 16)
#20 C:\wamp\www\site\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(718): array_walk(Array, Object(Closure))
#21 C:\wamp\www\site\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\BootProviders.php(17): Illuminate\Foundation\Application->boot()
#22 C:\wamp\www\site\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(203): Illuminate\Foundation\Bootstrap\BootProviders->bootstrap(Object(Illuminate\Foundation\Application))
#23 C:\wamp\www\site\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(222): Illuminate\Foundation\Application->bootstrapWith(Array)
#24 C:\wamp\www\site\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(117): Illuminate\Foundation\Http\Kernel->bootstrap()
#25 C:\wamp\www\site\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(87): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#26 C:\wamp\www\site\public\index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#27 {main}  
[2015-11-16 15:13:59] production.ERROR: exception 'RuntimeException' with message 'No supported encrypter found. The cipher and / or key length are invalid.' in C:\wamp\www\site\vendor\laravel\framework\src\Illuminate\Encryption\EncryptionServiceProvider.php:29
Stack trace:
#0 C:\wamp\www\site\vendor\laravel\framework\src\Illuminate\Container\Container.php(734): Illuminate\Encryption\EncryptionServiceProvider->Illuminate\Encryption\{closure}(Object(Illuminate\Foundation\Application), Array)
#1 C:\wamp\www\site\vendor\laravel\framework\src\Illuminate\Container\Container.php(627): Illuminate\Container\Container->build(Object(Closure), Array)
#2 C:\wamp\www\site\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(674): Illuminate\Container\Container->make('encrypter', Array)
#3 C:\wamp\www\site\vendor\laravel\framework\src\Illuminate\Container\Container.php(838): Illuminate\Foundation\Application->make('Illuminate\\Cont...')
#4 C:\wamp\www\site\vendor\laravel\framework\src\Illuminate\Container\Container.php(801): Illuminate\Container\Container->resolveClass(Object(ReflectionParameter))
#5 C:\wamp\www\site\vendor\laravel\framework\src\Illuminate\Container\Container.php(772): Illuminate\Container\Container->getDependencies(Array, Array)
#6 C:\wamp\www\site\vendor\laravel\framework\src\Illuminate\Container\Container.php(627): Illuminate\Container\Container->build('site\\Http\\Mi...', Array)
#7 C:\wamp\www\site\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(674): Illuminate\Container\Container->make('site\\Http\\Mi...', Array)
#8 C:\wamp\www\site\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(142): Illuminate\Foundation\Application->make('site\\Http\\Mi...')
#9 C:\wamp\www\site\public\index.php(58): Illuminate\Foundation\Http\Kernel->terminate(Object(Illuminate\Http\Request), Object(Illuminate\Http\Response))
#10 {main}  
```
"production" ???
''@'localhost'  ???
database 'forge'' ???

The only "production" coincidence in all the project, it's on ".env", on the first line:

```
APP_ENV=local #production, testing
```

The other "forge" it's the default MySQL database name in config/database.php

```
env('DB_DATABASE', 'forge'),
```

Pressing again F5, all goes fine. This happens once a week, like 4 times in a month, is not very often but... changing the environment? it's dangerous I think, the comment symbol # maybe is the bug?

The version is: "5.1.22 (LTS)"

**Comment by GrahamCampbell** [comment]
Known bug. Please see the other issues.

**Comment by dipakagile** [comment]
how to solve this issue .

**Comment by dipakagile** [comment]
how to solve this issue .

in my .enve file i have

APP_ENV=local .please help me

**Comment by punchi** [comment]
Do not work with "env" library, work with environment variables

**Comment by Vainglory07** [comment]
@punchi Hello, I don't have idea how am I going to fix this issue using the environment variables at Apache/Nginx. Can you please enlighten me? I'm experiencing same issue on Laravel 5.2.45 with also same freequency stated by the OP.

**Comment by punchi** [comment]
No problem @Vainglory07 for Apache you should work this way:
```
<VirtualHost hostname:80>
   ...
   SetEnv VARIABLE_NAME variable_value
   ...
</VirtualHost>
```
And for Nginx and php-fpm, like this:
```
location / {
    ...
    fastcgi_param APP_ENV production; 
    ...
}
```
You can search now for more details! =)
