### ISSUE TITLE
No space left on device Laravel 4.2 error (2000+ user app)

### ISSUE THREAD

**Issue by aligajani** [laravel/framework#11233]
Since my application has grown to over 2000+ users now, I am facing this strange issue on Laravel 4.2 every 2 weeks or so, sometimes more frequent, where I get this error.

```
[2015-11-19 12:29:19] production.ERROR: exception 'ErrorException' with message 'file_put_contents(/home/forge/default/app/storage/sessions/764dc5150bd00eafb9b032c57f9dd16b1b278d8d): failed to open stream: No space left on device' in /home/forge/default/bootstrap/compiled.php:4221
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleError(2, 'file_put_conten...', '/home/forge/def...', 4221, Array)
#1 /home/forge/default/bootstrap/compiled.php(4221): file_put_contents('/home/forge/def...', 'a:4:{s:6:"_toke...', 2)
#2 /home/forge/default/vendor/laravel/framework/src/Illuminate/Session/FileSessionHandler.php(69): Illuminate\Filesystem\Filesystem->put('/home/forge/def...', 'a:4:{s:6:"_toke...', true)
#3 /home/forge/default/bootstrap/compiled.php(7999): Illuminate\Session\FileSessionHandler->write('764dc5150bd00ea...', 'a:4:{s:6:"_toke...')
#4 /home/forge/default/bootstrap/compiled.php(7849): Illuminate\Session\Store->save()
#5 /home/forge/default/bootstrap/compiled.php(7827): Illuminate\Session\Middleware->closeSession(Object(Illuminate\Session\Store))
#6 /home/forge/default/bootstrap/compiled.php(8432): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#7 /home/forge/default/bootstrap/compiled.php(8379): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#8 /home/forge/default/bootstrap/compiled.php(11049): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#9 /home/forge/default/bootstrap/compiled.php(657): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#10 /home/forge/default/public/index.php(49): Illuminate\Foundation\Application->run()
#11 {main} [] []

```

I am temporarily able to resolve this by clearing application cache. The disk space is a non issue, I have checked I have gigs of space left. Also, sometimes clearing the cache doesn't work so I have to purge all files in the sessions folder. I am using file drivers for both cache and session. 

Do you know what's up?

**Comment by rkgrep** [comment]
This is not Laravel problem, actually. Don't use `file` session driver on production - it is for development only and causes fileystem overflows on high-loaded apps.

**Comment by rkgrep** [comment]
It also might be that iNodes limit is reached. Try `df -i` command.

**Comment by aligajani** [comment]
Thanks for the reply @rkgrep , iNodes is OK .

Memcached might be better, but the docs say the File driver should be good for most apps.

```
Filesystem      Inodes  IUsed   IFree IUse% Mounted on
/dev/xvda1      524288 522856    1432  100% /
none           1021954      2 1021952    1% /sys/fs/cgroup
udev           1020659    388 1020271    1% /dev
tmpfs          1021954    330 1021624    1% /run
none           1021954      1 1021953    1% /run/lock
none           1021954      2 1021952    1% /run/shm
none           1021954      2 1021952    1% /run/user

```

**Comment by rkgrep** [comment]
Well, you do have only 1432 inodes left - which is small amount. If you have at least 1000 users logged in and add all the cache generated by the app, you will run out of iNodes pretty fast.

**Comment by aligajani** [comment]
I see, how do I increase them and what are those other 100% of them below? Are they not relevant in this case. Thanks for your insight @rkgrep

**Comment by rkgrep** [comment]
You probably should ask your hosting support for it.

**Comment by aligajani** [comment]
I am actually using AWS..
