### ISSUE TITLE
[5.2] Session store not set on request

### ISSUE THREAD

**Issue by nayzawoo** [laravel/framework#11494]
I try to upgrade form laravel5.1 to 5.2,
But I got an error

`Session store not set on request. (View: ../resources/views/auth/login.blade.php)
`

Here is my codes and error log

`routes.php`

```php
<?php

Route::group([
    'namespace' => 'Auth',
    'middleware' => ['web'],
], function () {

    Route::get('backend/login', [
        'as'         => 'getLogin',
        'middleware' => 'guest',
        'uses'       => 'AuthController@getLogin',
    ]);
});

?>
```

`Kernel.php`

```php
<?php 

namespace App\Http;

class Kernel extends HttpKernel
{
    
    /**
     * The application's global HTTP middleware stack.
     *
     * @var array
     */
    protected $middleware = [
        CheckForMaintenanceMode::class,
    ];

    /**
     * The application's route middleware groups.
     *
     * @var array
     */
    protected $middlewareGroups = [
        'web' => [
            EncryptCookies::class,
            AddQueuedCookiesToResponse::class,
            StartSession::class,
            ShareErrorsFromSession::class,
        ],
        'api' => [
            'throttle:60,1',
        ],
    ];
}

?>
```

`laravel.log`

```javascript
[2015-12-24 00:56:16] production.ERROR: exception 'RuntimeException' with message 'Session store not set on request.' in /var/www/html/my_project/vendor/laravel/framework/src/Illuminate/Http/Request.php:775
Stack trace:
#0 /var/www/html/my_project/vendor/laravel/framework/src/Illuminate/Http/Request.php(446): Illuminate\Http\Request->session()
#1 /var/www/html/my_project/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(216): Illuminate\Http\Request->old('email')
#2 /var/www/html/my_project/storage/framework/views/0907db24d3fe924df9e42907128563e2ca0bfa4e.php(38): Illuminate\Support\Facades\Facade::__callStatic('old', Array)
#3 /var/www/html/my_project/storage/framework/views/0907db24d3fe924df9e42907128563e2ca0bfa4e.php(38): Illuminate\Support\Facades\Input::old('email')
#4 /var/www/html/my_project/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(42): include('/var/www/html/z...')
#5 /var/www/html/my_project/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(59): Illuminate\View\Engines\PhpEngine->evaluatePath('/var/www/html/z...', Array)
#6 /var/www/html/my_project/vendor/laravel/framework/src/Illuminate/View/View.php(135): Illuminate\View\Engines\CompilerEngine->get('/var/www/html/z...', Array)
#7 /var/www/html/my_project/vendor/laravel/framework/src/Illuminate/View/View.php(106): Illuminate\View\View->getContents()
#8 /var/www/html/my_project/vendor/laravel/framework/src/Illuminate/View/View.php(80): Illuminate\View\View->renderContents()
#9 /var/www/html/my_project/vendor/laravel/framework/src/Illuminate/Http/Response.php(52): Illuminate\View\View->render()
#10 /var/www/html/my_project/vendor/symfony/http-foundation/Response.php(197): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
#11 /var/www/html/my_project/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1030): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View))
#12 /var/www/html/my_project/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(95): Illuminate\Routing\Router->prepareResponse(Object(Dingo\Api\Http\Request), Object(Illuminate\View\View))
#13 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Dingo\Api\Http\Request))
#14 /var/www/html/my_project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Dingo\Api\Http\Request))
#15 /var/www/html/my_project/app/Http/Middleware/RedirectIfAuthenticated.php(41): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Dingo\Api\Http\Request))
#16 [internal function]: App\Http\Middleware\RedirectIfAuthenticated->handle(Object(Dingo\Api\Http\Request), Object(Closure))
#17 /var/www/html/my_project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#18 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Dingo\Api\Http\Request))
#19 /var/www/html/my_project/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): call_user_func(Object(Closure), Object(Dingo\Api\Http\Request))
#20 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Dingo\Api\Http\Request))
#21 /var/www/html/my_project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Dingo\Api\Http\Request))
#22 /var/www/html/my_project/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(96): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#23 /var/www/html/my_project/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(54): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(App\Http\Controllers\Auth\AuthController), Object(Illuminate\Routing\Route), Object(Dingo\Api\Http\Request), 'getLogin')
#24 /var/www/html/my_project/vendor/laravel/framework/src/Illuminate/Routing/Route.php(174): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Dingo\Api\Http\Request), 'App\\Http\\Contro...', 'getLogin')
#25 /var/www/html/my_project/vendor/laravel/framework/src/Illuminate/Routing/Route.php(140): Illuminate\Routing\Route->runController(Object(Dingo\Api\Http\Request))
#26 /var/www/html/my_project/vendor/laravel/framework/src/Illuminate/Routing/Router.php(703): Illuminate\Routing\Route->run(Object(Dingo\Api\Http\Request))
#27 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Dingo\Api\Http\Request))
#28 /var/www/html/my_project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Dingo\Api\Http\Request))
#29 /var/www/html/my_project/app/Http/Middleware/RedirectIfAuthenticated.php(41): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Dingo\Api\Http\Request))
#30 [internal function]: App\Http\Middleware\RedirectIfAuthenticated->handle(Object(Dingo\Api\Http\Request), Object(Closure))
#31 /var/www/html/my_project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#32 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Dingo\Api\Http\Request))
#33 /var/www/html/my_project/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): call_user_func(Object(Closure), Object(Dingo\Api\Http\Request))
#34 /var/www/html/my_project/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Dingo\Api\Http\Request))
#35 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Dingo\Api\Http\Request), Object(Closure))
#36 /var/www/html/my_project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#37 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Dingo\Api\Http\Request))
#38 /var/www/html/my_project/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): call_user_func(Object(Closure), Object(Dingo\Api\Http\Request))
#39 /var/www/html/my_project/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(62): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Dingo\Api\Http\Request))
#40 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Dingo\Api\Http\Request), Object(Closure))
#41 /var/www/html/my_project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#42 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Dingo\Api\Http\Request))
#43 /var/www/html/my_project/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): call_user_func(Object(Closure), Object(Dingo\Api\Http\Request))
#44 /var/www/html/my_project/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Dingo\Api\Http\Request))
#45 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Dingo\Api\Http\Request), Object(Closure))
#46 /var/www/html/my_project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#47 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Dingo\Api\Http\Request))
#48 /var/www/html/my_project/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): call_user_func(Object(Closure), Object(Dingo\Api\Http\Request))
#49 /var/www/html/my_project/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Dingo\Api\Http\Request))
#50 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Dingo\Api\Http\Request), Object(Closure))
#51 /var/www/html/my_project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#52 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Dingo\Api\Http\Request))
#53 /var/www/html/my_project/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): call_user_func(Object(Closure), Object(Dingo\Api\Http\Request))
#54 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Dingo\Api\Http\Request))
#55 /var/www/html/my_project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Dingo\Api\Http\Request))
#56 /var/www/html/my_project/vendor/laravel/framework/src/Illuminate/Routing/Router.php(705): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#57 /var/www/html/my_project/vendor/laravel/framework/src/Illuminate/Routing/Router.php(678): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Dingo\Api\Http\Request))
#58 /var/www/html/my_project/vendor/laravel/framework/src/Illuminate/Routing/Router.php(654): Illuminate\Routing\Router->dispatchToRoute(Object(Dingo\Api\Http\Request))
#59 /var/www/html/my_project/vendor/dingo/api/src/Routing/Adapter/Laravel.php(65): Illuminate\Routing\Router->dispatch(Object(Dingo\Api\Http\Request))
#60 /var/www/html/my_project/vendor/dingo/api/src/Routing/Router.php(559): Dingo\Api\Routing\Adapter\Laravel->dispatch(Object(Dingo\Api\Http\Request), 'v1')
#61 /var/www/html/my_project/vendor/dingo/api/src/Http/Middleware/Request.php(110): Dingo\Api\Routing\Router->dispatch(Object(Dingo\Api\Http\Request))
#62 [internal function]: Dingo\Api\Http\Middleware\Request->Dingo\Api\Http\Middleware\{closure}(Object(Dingo\Api\Http\Request))
#63 /var/www/html/my_project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Dingo\Api\Http\Request))
#64 /var/www/html/my_project/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(44): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Dingo\Api\Http\Request))
#65 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Dingo\Api\Http\Request), Object(Closure))
#66 /var/www/html/my_project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#67 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Dingo\Api\Http\Request))
#68 /var/www/html/my_project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Dingo\Api\Http\Request))
#69 /var/www/html/my_project/vendor/dingo/api/src/Http/Middleware/Request.php(111): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#70 /var/www/html/my_project/vendor/dingo/api/src/Http/Middleware/Request.php(89): Dingo\Api\Http\Middleware\Request->sendRequestThroughRouter(Object(Dingo\Api\Http\Request))
#71 [internal function]: Dingo\Api\Http\Middleware\Request->handle(Object(Illuminate\Http\Request), Object(Closure))
#72 /var/www/html/my_project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#73 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#74 /var/www/html/my_project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#75 /var/www/html/my_project/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(132): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#76 /var/www/html/my_project/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(99): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#77 /var/www/html/my_project/public/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#78 {main}

Next exception 'ErrorException' with message 'Session store not set on request. (View: /var/www/html/my_project/resources/views/auth/login.blade.php)' in /var/www/html/my_project/vendor/laravel/framework/src/Illuminate/Http/Request.php:775
Stack trace:
#0 /var/www/html/my_project/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(44): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(RuntimeException), 1)
#1 /var/www/html/my_project/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(59): Illuminate\View\Engines\PhpEngine->evaluatePath('/var/www/html/z...', Array)
#2 /var/www/html/my_project/vendor/laravel/framework/src/Illuminate/View/View.php(135): Illuminate\View\Engines\CompilerEngine->get('/var/www/html/z...', Array)
#3 /var/www/html/my_project/vendor/laravel/framework/src/Illuminate/View/View.php(106): Illuminate\View\View->getContents()
#4 /var/www/html/my_project/vendor/laravel/framework/src/Illuminate/View/View.php(80): Illuminate\View\View->renderContents()
#5 /var/www/html/my_project/vendor/laravel/framework/src/Illuminate/Http/Response.php(52): Illuminate\View\View->render()
#6 /var/www/html/my_project/vendor/symfony/http-foundation/Response.php(197): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
#7 /var/www/html/my_project/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1030): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View))
#8 /var/www/html/my_project/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(95): Illuminate\Routing\Router->prepareResponse(Object(Dingo\Api\Http\Request), Object(Illuminate\View\View))
#9 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Dingo\Api\Http\Request))
#10 /var/www/html/my_project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Dingo\Api\Http\Request))
#11 /var/www/html/my_project/app/Http/Middleware/RedirectIfAuthenticated.php(41): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Dingo\Api\Http\Request))
#12 [internal function]: App\Http\Middleware\RedirectIfAuthenticated->handle(Object(Dingo\Api\Http\Request), Object(Closure))
#13 /var/www/html/my_project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#14 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Dingo\Api\Http\Request))
#15 /var/www/html/my_project/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): call_user_func(Object(Closure), Object(Dingo\Api\Http\Request))
#16 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Dingo\Api\Http\Request))
#17 /var/www/html/my_project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Dingo\Api\Http\Request))
#18 /var/www/html/my_project/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(96): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#19 /var/www/html/my_project/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(54): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(App\Http\Controllers\Auth\AuthController), Object(Illuminate\Routing\Route), Object(Dingo\Api\Http\Request), 'getLogin')
#20 /var/www/html/my_project/vendor/laravel/framework/src/Illuminate/Routing/Route.php(174): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Dingo\Api\Http\Request), 'App\\Http\\Contro...', 'getLogin')
#21 /var/www/html/my_project/vendor/laravel/framework/src/Illuminate/Routing/Route.php(140): Illuminate\Routing\Route->runController(Object(Dingo\Api\Http\Request))
#22 /var/www/html/my_project/vendor/laravel/framework/src/Illuminate/Routing/Router.php(703): Illuminate\Routing\Route->run(Object(Dingo\Api\Http\Request))
#23 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Dingo\Api\Http\Request))
#24 /var/www/html/my_project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Dingo\Api\Http\Request))
#25 /var/www/html/my_project/app/Http/Middleware/RedirectIfAuthenticated.php(41): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Dingo\Api\Http\Request))
#26 [internal function]: App\Http\Middleware\RedirectIfAuthenticated->handle(Object(Dingo\Api\Http\Request), Object(Closure))
#27 /var/www/html/my_project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#28 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Dingo\Api\Http\Request))
#29 /var/www/html/my_project/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): call_user_func(Object(Closure), Object(Dingo\Api\Http\Request))
#30 /var/www/html/my_project/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Dingo\Api\Http\Request))
#31 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Dingo\Api\Http\Request), Object(Closure))
#32 /var/www/html/my_project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#33 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Dingo\Api\Http\Request))
#34 /var/www/html/my_project/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): call_user_func(Object(Closure), Object(Dingo\Api\Http\Request))
#35 /var/www/html/my_project/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(62): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Dingo\Api\Http\Request))
#36 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Dingo\Api\Http\Request), Object(Closure))
#37 /var/www/html/my_project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#38 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Dingo\Api\Http\Request))
#39 /var/www/html/my_project/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): call_user_func(Object(Closure), Object(Dingo\Api\Http\Request))
#40 /var/www/html/my_project/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Dingo\Api\Http\Request))
#41 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Dingo\Api\Http\Request), Object(Closure))
#42 /var/www/html/my_project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#43 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Dingo\Api\Http\Request))
#44 /var/www/html/my_project/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): call_user_func(Object(Closure), Object(Dingo\Api\Http\Request))
#45 /var/www/html/my_project/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Dingo\Api\Http\Request))
#46 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Dingo\Api\Http\Request), Object(Closure))
#47 /var/www/html/my_project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#48 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Dingo\Api\Http\Request))
#49 /var/www/html/my_project/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): call_user_func(Object(Closure), Object(Dingo\Api\Http\Request))
#50 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Dingo\Api\Http\Request))
#51 /var/www/html/my_project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Dingo\Api\Http\Request))
#52 /var/www/html/my_project/vendor/laravel/framework/src/Illuminate/Routing/Router.php(705): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#53 /var/www/html/my_project/vendor/laravel/framework/src/Illuminate/Routing/Router.php(678): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Dingo\Api\Http\Request))
#54 /var/www/html/my_project/vendor/laravel/framework/src/Illuminate/Routing/Router.php(654): Illuminate\Routing\Router->dispatchToRoute(Object(Dingo\Api\Http\Request))
#55 /var/www/html/my_project/vendor/dingo/api/src/Routing/Adapter/Laravel.php(65): Illuminate\Routing\Router->dispatch(Object(Dingo\Api\Http\Request))
#56 /var/www/html/my_project/vendor/dingo/api/src/Routing/Router.php(559): Dingo\Api\Routing\Adapter\Laravel->dispatch(Object(Dingo\Api\Http\Request), 'v1')
#57 /var/www/html/my_project/vendor/dingo/api/src/Http/Middleware/Request.php(110): Dingo\Api\Routing\Router->dispatch(Object(Dingo\Api\Http\Request))
#58 [internal function]: Dingo\Api\Http\Middleware\Request->Dingo\Api\Http\Middleware\{closure}(Object(Dingo\Api\Http\Request))
#59 /var/www/html/my_project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Dingo\Api\Http\Request))
#60 /var/www/html/my_project/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(44): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Dingo\Api\Http\Request))
#61 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Dingo\Api\Http\Request), Object(Closure))
#62 /var/www/html/my_project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#63 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Dingo\Api\Http\Request))
#64 /var/www/html/my_project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Dingo\Api\Http\Request))
#65 /var/www/html/my_project/vendor/dingo/api/src/Http/Middleware/Request.php(111): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#66 /var/www/html/my_project/vendor/dingo/api/src/Http/Middleware/Request.php(89): Dingo\Api\Http\Middleware\Request->sendRequestThroughRouter(Object(Dingo\Api\Http\Request))
#67 [internal function]: Dingo\Api\Http\Middleware\Request->handle(Object(Illuminate\Http\Request), Object(Closure))
#68 /var/www/html/my_project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#69 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#70 /var/www/html/my_project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#71 /var/www/html/my_project/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(132): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#72 /var/www/html/my_project/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(99): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#73 /var/www/html/my_project/public/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#74 {main}  
```

**Comment by heisian** [comment]
The way Laravel is set up, you need to move your `StartSession::class` and `ShareErrorsFromSession::class` middleware to the `protected $middleware` section.  You cannot have those under `$middlewareGroups` or `$routeMiddleware`.

**Comment by GrahamCampbell** [comment]
> Session middleware MUST be placed as default

**Comment by GrahamCampbell** [comment]
> Session middleware MUST be placed as default

No, that's not true at all?

**Comment by GrahamCampbell** [comment]
Infact, Laravel 5.2 recommends that you DO NOT make it global.

**Comment by heisian** [comment]
I haven't tried 5.2 yet, but in 5.1, moving session to route/group middleware as the OP did causes the exact error he's describing.  And after sorting through many a StackOverflow (http://stackoverflow.com/questions/26473106/prevent-sessions-for-routes-in-laravel-custom-on-demand-session-handling <- this and many more threads), the solution I posted is what ended up working for me.

Additional links with others attempting to accomplish a similar goal:
https://laracasts.com/discuss/channels/general-discussion/api-disabling-sessions-and-csrf?page=1
http://laravel.io/forum/03-28-2014-build-api-with-laravel-how-to-disable-cookie-output
https://github.com/laravel/framework/issues/726

Something that does NOT work:
http://laravel-tricks.com/tricks/filter-remove-sessions

**Comment by GrahamCampbell** [comment]
Sounds like this isn't really a bug, and is more just asking about how this stuff works. Feel free to talk in greater detail on the forums.

**Comment by heisian** [comment]
Definitely not a bug - I was posting solutions to help out OP so he could spend less time trying to find an answer :]

**Comment by knabity** [comment]
I'm using Laravel 5.2.  I set the session middleware as default and still got the error in the Laravel log.  I can't get your kernel example to work while unit testing.   Is it not compatible with PHPUnit.

**Comment by knabity** [comment]
Nm, I figured out a workaround.

**Comment by amit-kumar88** [comment]
@knabity I 'am using Laravel 5.1. i am facing same issue which you have mentioned above "Session store not set on request". can you give me the workaround so i can fix that issue. Thankx.

**Comment by faniuta** [comment]
To avoid problems when you have other exception or recive request with api middleware,change the render function In App/Exceptions/Handler.php to :
```
public function render ($request, Exception $exception)
{
    if ($this->isHttpException($exception)) {
        switch ($exception->getStatusCode()) {
            case '404':
                \Route::any(request()->path(), function () use ($exception, $request) {
                    return parent::render($request, $exception);
                })->middleware('web');
                return app()->make(Kernel::class)->handle($request);
                break;
            default:
                return $this->renderHttpException($exception);
                break;
        }
    } else {

        return parent::render($request, $exception);
    }
}
```

**Comment by jenga201** [comment]
Within unit tests, I was able to use this as a workaround in the setUp() method;
request()->setLaravelSession(session());
