### ISSUE TITLE
[5.2.15] FileNotFoundException when uploading file through XHR

### ISSUE THREAD

**Issue by cre8websolutions** [laravel/framework#12299]
Before updating Laravel (5.2.12), my files (images) were uploading correctly through XHR.
After updating to 5.2.15, I get a **`FileNotFoundException in File.php line 37`** with the following message:
**The file "" does not exist**

Some more details:
```
 1. in File.php line 37
 2. at File->__construct(false, true) in UploadedFile.php line 96
 3. at UploadedFile->__construct(false, 'logo-400x400.png', 'image/png', '17215', '0') in UploadedFile.php line 52
 4. at UploadedFile::createFromBase(object(UploadedFile)) in Request.php line 415
 5. at Request->Illuminate\Http\{closure}(object(UploadedFile))
 6. at array_map(object(Closure), array('image_file' => object(UploadedFile))) in Request.php line 416
 7. at Request->convertUploadedFiles(array('image_file' => object(UploadedFile))) in Request.php line 401
 8. at Request->allFiles() in Request.php line 304
 9. at Request->all() in Request.php line 1011
10. at Request->__get('image_src') in TeamController.php line 111
11. at TeamController->saveLogo(object(Request))
```

**Comment by vinkla** [comment]
+1 I'm having the same issue.

**Comment by taylorotwell** [comment]
Hmm `getRealPath` must be returning false for the file.

**Comment by taylorotwell** [comment]
Pushed a commit to fix.

**Comment by vinkla** [comment]
:+1:

**Comment by cre8websolutions** [comment]
Thank you, Taylor! :+1:

**Comment by rajeshtandukar** [comment]
I still have this error with my Laravel 5.2
FileNotFoundException in File.php line 37: 
The file "/tmp/phpSkmSn7" does not exist

**Comment by rajeshtandukar** [comment]
I follow  the instruction at https://github.com/laravel/framework/issues/12350  and it works fine.
laravel/framework/src/Illuminate/Http/UploadedFile.php
at Line 50
remove instanceof static

**Comment by kingpabel** [comment]
I was also fall on this problem in 5.2.16 and in now i am using 5.2.29 and this is solved

**Comment by CrixuAMG** [comment]
> I follow the instruction at #12350 and it works fine.
laravel/framework/src/Illuminate/Http/UploadedFile.php
at Line 50
remove instanceof static

Doing this fixed the same issue for me in V5.4.35.

**Comment by JuliusB** [comment]
I have this issue on 5.5.11. And removing instanceof static doesn't help.

**Comment by poseso** [comment]
I have the same issue on 5.5.19 and removing instanceof static fixes the problem for me, please fix @taylorotwell

**Comment by cyrrill** [comment]
Same here:

`The file "" does not exist {"exception":"[object] (Symfony\\Component\\HttpFoundation\\File\\Exception\\FileNotFoundException(code: 0): The file \"\" does not exist at /(...)/vendor/symfony/http-foundation/File/MimeType/MimeTypeGuesser.php:123)
[stacktrace]
#0 /(...)/vendor/symfony/http-foundation/File/File.php(79): Symfony\\Component\\HttpFoundation\\File\\MimeType\\MimeTypeGuesser->guess('')
#1 /(...)/app/Services/UploadService.php(59): Symfony\\Component\\HttpFoundation\\File\\File->getMimeType()
#2 /(...)/app/Http/Controllers/UploadController.php(21): App\\Services\\UploadService->store(Object(Illuminate\\Http\\UploadedFile), 5, 23)
#3 [internal function]: App\\Http\\Controllers\\UploadController->store(Object(Illuminate\\Http\\Request), Object(App\\Services\\UploadService))
`

Using Laravel 5.5.20

**Comment by kevinreynolds** [comment]
@cyrrill I'm having the same issue as well (using Laravel v5.5.26). Did you manage to find a solution to this one?

**Comment by Mr-Anonymous** [comment]
I have the same issue in laravel 5.3. Has anyone found a solution for this? The error I get in some cases when user tries to upload a video is:

```
Error: The file "" does not exist inFile/MimeType/MimeTypeGuesser.php:123
```

**Comment by MightyPork** [comment]
Same error today, does not look fixed

```
Symfony\Component\HttpFoundation\File\Exception\FileNotFoundException: The file &quot;&quot; does not exist in file /srv/fb3/vendor/symfony/http-foundation/File/MimeType/MimeTypeGuesser.php on line 121
Stack trace:
  1. Symfony\Component\HttpFoundation\File\Exception\FileNotFoundException-&gt;() /srv/fb3/vendor/symfony/http-foundation/File/MimeType/MimeTypeGuesser.php:121
  2. Symfony\Component\HttpFoundation\File\MimeType\MimeTypeGuesser-&gt;guess() /srv/fb3/vendor/symfony/http-foundation/File/File.php:79
  3. Symfony\Component\HttpFoundation\File\File-&gt;getMimeType() /srv/fb3/vendor/symfony/http-foundation/File/File.php:58
  4. Symfony\Component\HttpFoundation\File\File-&gt;guessExtension() /srv/fb3/vendor/laravel/framework/src/Illuminate/Http/FileHelpers.php:60
  5. Illuminate\Http\UploadedFile-&gt;hashName() /srv/fb3/vendor/laravel/framework/src/Illuminate/Http/UploadedFile.php:34
  6. Illuminate\Http\UploadedFile-&gt;store() /srv/fb3/app/Http/Controllers/Setup/StorageController.php:39
  7. FlowBox\Http\Controllers\Setup\StorageController-&gt;testUpload() /srv/fb3/vendor/laravel/framework/src/Illuminate/Routing/Controller.php:54
  8. call_user_func_array() /srv/fb3/vendor/laravel/framework/src/Illuminate/Routing/Controller.php:54
  9. Illuminate\Routing\Controller-&gt;callAction() /srv/fb3/app/Http/Controllers/Controller.php:87
 10. FlowBox\Http\Controllers\Controller-&gt;callAction() /srv/fb3/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php:45
 11. Illuminate\Routing\ControllerDispatcher-&gt;dispatch() /srv/fb3/vendor/laravel/framework/src/Illuminate/Routing/Route.php:212
 12. Illuminate\Routing\Route-&gt;runController() /srv/fb3/vendor/laravel/framework/src/Illuminate/Routing/Route.php:169
 13. Illuminate\Routing\Route-&gt;run() /srv/fb3/vendor/laravel/framework/src/Illuminate/Routing/Router.php:658
 14. Illuminate\Routing\Router-&gt;Illuminate\Routing\{closure}() /srv/fb3/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:30
 15. Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}() /srv/fb3/app/Http/Middleware/Authenticate.php:33
 16. FlowBox\Http\Middleware\Authenticate-&gt;handle() /srv/fb3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
 17. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() /srv/fb3/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
 18. Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}() /srv/fb3/app/Http/Middleware/OverrideAppLanguage.php:44
 19. FlowBox\Http\Middleware\OverrideAppLanguage-&gt;handle() /srv/fb3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
 20. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() /srv/fb3/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
 21. Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}() /srv/fb3/app/Http/Middleware/RecordPageVisit.php:21
 22. FlowBox\Http\Middleware\RecordPageVisit-&gt;handle() /srv/fb3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
 23. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() /srv/fb3/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
 24. Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}() /srv/fb3/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php:41
 25. Illuminate\Routing\Middleware\SubstituteBindings-&gt;handle() /srv/fb3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
 26. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() /srv/fb3/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
 27. Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}() /srv/fb3/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php:67
 28. Illuminate\Foundation\Http\Middleware\VerifyCsrfToken-&gt;handle() /srv/fb3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
 29. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() /srv/fb3/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
 30. Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}() /srv/fb3/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php:49
 31. Illuminate\View\Middleware\ShareErrorsFromSession-&gt;handle() /srv/fb3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
 32. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() /srv/fb3/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
 33. Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}() /srv/fb3/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php:63
 34. Illuminate\Session\Middleware\StartSession-&gt;handle() /srv/fb3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
 35. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() /srv/fb3/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
 36. Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}() /srv/fb3/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php:37
 37. Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse-&gt;handle() /srv/fb3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
 38. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() /srv/fb3/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
 39. Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}() /srv/fb3/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php:59
 40. Illuminate\Cookie\Middleware\EncryptCookies-&gt;handle() /srv/fb3/app/Http/Middleware/EncryptCookies.php:20
 41. FlowBox\Http\Middleware\EncryptCookies-&gt;handle() /srv/fb3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
 42. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() /srv/fb3/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
 43. Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}() /srv/fb3/app/Http/Middleware/FBPjaxFilter.php:20
 44. FlowBox\Http\Middleware\FBPjaxFilter-&gt;handle() /srv/fb3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
 45. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() /srv/fb3/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
 46. Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}() /srv/fb3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:102
 47. Illuminate\Pipeline\Pipeline-&gt;then() /srv/fb3/vendor/laravel/framework/src/Illuminate/Routing/Router.php:660
 48. Illuminate\Routing\Router-&gt;runRouteWithinStack() /srv/fb3/vendor/laravel/framework/src/Illuminate/Routing/Router.php:635
 49. Illuminate\Routing\Router-&gt;runRoute() /srv/fb3/vendor/laravel/framework/src/Illuminate/Routing/Router.php:601
 50. Illuminate\Routing\Router-&gt;dispatchToRoute() /srv/fb3/vendor/laravel/framework/src/Illuminate/Routing/Router.php:590
 51. Illuminate\Routing\Router-&gt;dispatch() /srv/fb3/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:176
 52. Illuminate\Foundation\Http\Kernel-&gt;Illuminate\Foundation\Http\{closure}() /srv/fb3/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:30
 53. Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}() /srv/fb3/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php:30
 54. Illuminate\Foundation\Http\Middleware\TransformsRequest-&gt;handle() /srv/fb3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
 55. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() /srv/fb3/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
 56. Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}() /srv/fb3/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php:30
 57. Illuminate\Foundation\Http\Middleware\TransformsRequest-&gt;handle() /srv/fb3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
 58. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() /srv/fb3/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
 59. Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}() /srv/fb3/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php:27
 60. Illuminate\Foundation\Http\Middleware\ValidatePostSize-&gt;handle() /srv/fb3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
 61. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() /srv/fb3/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
 62. Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}() /srv/fb3/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php:46
 63. Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode-&gt;handle() /srv/fb3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
 64. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() /srv/fb3/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
 65. Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}() /srv/fb3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:102
 66. Illuminate\Pipeline\Pipeline-&gt;then() /srv/fb3/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:151
 67. Illuminate\Foundation\Http\Kernel-&gt;sendRequestThroughRouter() /srv/fb3/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:116
 68. Illuminate\Foundation\Http\Kernel-&gt;handle() /srv/fb3/public/index.php:53
```

**Comment by Mr-Anonymous** [comment]
I got a similar error in Laravel 5.3 and I resolved it just recently: https://github.com/laravel/framework/issues/23492

**Comment by MightyPork** [comment]
Ah i found my fix - I set `upload_max_filesize` but then the system unexpectedly rebooted before I could restart httpd, and the change somehow got reverted to 2M.

So - this can happen also when you have too small `upload_max_filesize` and are uploading a big file. I guess we have to manually check the file object before trying to store it, somehow

**Comment by shenAmit** [comment]
Symfony\\Component\\HttpFoundation\\File\\Exception\\FileNotFoundException"
file
: 
"E:\\Trainer Portal\\tka-trainer-portal\\vendor\\symfony\\http-foundation\\File\\File.php"
line
: 
36
message
: 
"The file \"C:\\xampp\\tmp\\php1BAA.tmp\" does not exist"


when i try to upload a file  in chunk
