### ISSUE TITLE
Target [Illuminate\Contracts\Routing\ResponseFactory] is not instantiable while building [[...]\Http\Middleware\Extensions\JWTAuth\GetUserFromToken].

### ISSUE THREAD

**Issue by GiampaoloFalqui** [laravel/framework#12368]
Upon updating Illuminate dependencies of Lumen from 5.2.7 to 5.2.19, everytime I make a request of any kind, Illuminate finds issues at building a custom middleware of a library ([JWTAuth](https://github.com/tymondesigns/jwt-auth)) I am using to check JSON Web Tokens.

Using the original library middleware still gives me the isssue, so it's not an issue of the custom middleware.

This is how I register the middleware:

```php
$app->routeMiddleware([
    'jwt.auth'    => Cambiomarcia\Http\Middleware\Extensions\JWTAuth\GetUserFromToken::class
]);
```

This is the error with the stack trace as well:
```
[2016-02-18 15:54:59] lumen.ERROR: exception 'Illuminate\Contracts\Container\BindingResolutionException' with message 'Target [Illuminate\Contracts\Routing\ResponseFactory] is not instantiable while building [Cambiomarcia\Http\Middleware\Extensions\JWTAuth\GetUserFromToken].' in /home/vagrant/Code/cmarcia_webservice/vendor/illuminate/container/Container.php:752
Stack trace:
#0 /home/vagrant/Code/cmarcia_webservice/vendor/illuminate/container/Container.php(633): Illuminate\Container\Container->build('Illuminate\\Cont...', Array)
#1 /home/vagrant/Code/cmarcia_webservice/vendor/laravel/lumen-framework/src/Application.php(205): Illuminate\Container\Container->make('Illuminate\\Cont...', Array)
#2 /home/vagrant/Code/cmarcia_webservice/vendor/illuminate/container/Container.php(853): Laravel\Lumen\Application->make('Illuminate\\Cont...')
#3 /home/vagrant/Code/cmarcia_webservice/vendor/illuminate/container/Container.php(808): Illuminate\Container\Container->resolveClass(Object(ReflectionParameter))
#4 /home/vagrant/Code/cmarcia_webservice/vendor/illuminate/container/Container.php(779): Illuminate\Container\Container->getDependencies(Array, Array)
#5 /home/vagrant/Code/cmarcia_webservice/vendor/illuminate/container/Container.php(633): Illuminate\Container\Container->build('Cambiomarcia\\Ht...', Array)
#6 /home/vagrant/Code/cmarcia_webservice/vendor/laravel/lumen-framework/src/Application.php(205): Illuminate\Container\Container->make('Cambiomarcia\\Ht...', Array)
#7 /home/vagrant/Code/cmarcia_webservice/vendor/illuminate/pipeline/Pipeline.php(123): Laravel\Lumen\Application->make('Cambiomarcia\\Ht...')
#8 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#9 /home/vagrant/Code/cmarcia_webservice/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#10 [internal function]: Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#11 /home/vagrant/Code/cmarcia_webservice/vendor/illuminate/pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#12 /home/vagrant/Code/cmarcia_webservice/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(621): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#13 /home/vagrant/Code/cmarcia_webservice/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(470): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#14 /home/vagrant/Code/cmarcia_webservice/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(376): Laravel\Lumen\Application->handleFoundRoute(Array)
#15 /home/vagrant/Code/cmarcia_webservice/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(624): Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}()
#16 /home/vagrant/Code/cmarcia_webservice/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(382): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#17 /home/vagrant/Code/cmarcia_webservice/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(327): Laravel\Lumen\Application->dispatch(NULL)
#18 /home/vagrant/Code/cmarcia_webservice/public/index.php(28): Laravel\Lumen\Application->run()
#19 {main}
```

I cannot understand why the update started to give me these issues.

Cheers,
Giampaolo.

**Comment by GrahamCampbell** [comment]
Looks like a bug in your package since lumen doesn't implement this, and never has done?

**Comment by GiampaoloFalqui** [comment]
The bug has appeared only after the `composer update` - the package worked perfectly beforehand. How would that make any sense if it was a package's bug?

**Comment by bertheyman** [comment]
People experiencing the same issue might want to have a look here: https://github.com/tymondesigns/jwt-auth/issues/731
