### ISSUE TITLE
Ajax Validation Response Not Working In Production

### ISSUE THREAD

**Issue by seivad** [laravel/framework#13765]
My responses come back fine on my Homestead box and render out to AngularJS fine. But in production, Laravel continues bail out using the HttpResponseException response, I've logged the response using this within the handler.php file:

```
if ($e instanceof Exception) {
                Log::info($e);
                if ($request->ajax() || $request->wantsJson()) {
                    Log::info($e->getResponse());
                    Log::info($e->getMessage());
                    return response()->json(['error' => 'Sorry there has been a server error! Please try again!'], 500);
                } else {
                    Flash::warning('Sorry there was an error loading the page!');

                    return redirect()->back()->withInput();
                }
            }
```

```
[2016-05-30 00:51:55] production.INFO: exception 'Illuminate\Http\Exception\HttpResponseException' in /home/stellar/stellar/bootstrap/cache/compiled.php:5539
Stack trace:
#0 /home/stellar/stellar/bootstrap/cache/compiled.php(5459): Illuminate\Foundation\Http\FormRequest->failedValidation(Object(Illuminate\Validation\Validator))
#1 /home/stellar/stellar/bootstrap/cache/compiled.php(5634): Illuminate\Foundation\Http\FormRequest->validate()
#2 /home/stellar/stellar/bootstrap/cache/compiled.php(1480): Illuminate\Foundation\Providers\FoundationServiceProvider->Illuminate\Foundation\Providers\{closure}(Object(StellarHome\Http\Requests\ContactUsFormRequest), Object(Illuminate\Foundation\Application))
#3 /home/stellar/stellar/bootstrap/cache/compiled.php(1465): Illuminate\Container\Container->fireCallbackArray(Object(StellarHome\Http\Requests\ContactUsFormRequest), Array)
#4 /home/stellar/stellar/bootstrap/cache/compiled.php(1305): Illuminate\Container\Container->fireResolvingCallbacks('StellarHome\\Htt...', Object(StellarHome\Http\Requests\ContactUsFormRequest))
#5 /home/stellar/stellar/bootstrap/cache/compiled.php(1857): Illuminate\Container\Container->make('StellarHome\\Htt...', Array)
#6 /home/stellar/stellar/bootstrap/cache/compiled.php(7871): Illuminate\Foundation\Application->make('StellarHome\\Htt...')
#7 /home/stellar/stellar/bootstrap/cache/compiled.php(7860): Illuminate\Routing\ControllerDispatcher->transformDependency(Object(ReflectionParameter), Array, Array)
#8 /home/stellar/stellar/bootstrap/cache/compiled.php(7854): Illuminate\Routing\ControllerDispatcher->resolveMethodDependencies(Array, Object(ReflectionMethod))
#9 /home/stellar/stellar/bootstrap/cache/compiled.php(9418): Illuminate\Routing\ControllerDispatcher->resolveClassMethodDependencies(Array, Object(StellarHome\Http\Controllers\FormRequestController), 'store')
#10 /home/stellar/stellar/bootstrap/cache/compiled.php(9399): Illuminate\Routing\ControllerDispatcher->call(Object(StellarHome\Http\Controllers\FormRequestController), Object(Illuminate\Routing\Route), 'store')
#11 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#12 /home/stellar/stellar/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#13 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#14 /home/stellar/stellar/bootstrap/cache/compiled.php(9876): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#15 /home/stellar/stellar/bootstrap/cache/compiled.php(9400): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#16 /home/stellar/stellar/bootstrap/cache/compiled.php(9387): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(StellarHome\Http\Controllers\FormRequestController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'store')
#17 /home/stellar/stellar/bootstrap/cache/compiled.php(8455): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'StellarHome\\Htt...', 'store')
#18 /home/stellar/stellar/bootstrap/cache/compiled.php(8442): Illuminate\Routing\Route->runController(Object(Illuminate\Http\Request))
#19 /home/stellar/stellar/bootstrap/cache/compiled.php(8156): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#20 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#21 /home/stellar/stellar/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#22 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#23 /home/stellar/stellar/bootstrap/cache/compiled.php(9876): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#24 /home/stellar/stellar/bootstrap/cache/compiled.php(8157): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#25 /home/stellar/stellar/bootstrap/cache/compiled.php(8148): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#26 /home/stellar/stellar/bootstrap/cache/compiled.php(8138): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#27 /home/stellar/stellar/bootstrap/cache/compiled.php(2400): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#28 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#29 /home/stellar/stellar/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#30 /home/stellar/stellar/bootstrap/cache/compiled.php(13334): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#31 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#32 /home/stellar/stellar/bootstrap/cache/compiled.php(9891): call_user_func_array(Array, Array)
#33 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 /home/stellar/stellar/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#35 /home/stellar/stellar/bootstrap/cache/compiled.php(11876): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#36 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#37 /home/stellar/stellar/bootstrap/cache/compiled.php(9891): call_user_func_array(Array, Array)
#38 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#39 /home/stellar/stellar/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#40 /home/stellar/stellar/bootstrap/cache/compiled.php(3246): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#41 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#42 /home/stellar/stellar/bootstrap/cache/compiled.php(9891): call_user_func_array(Array, Array)
#43 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#44 /home/stellar/stellar/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#45 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#46 /home/stellar/stellar/bootstrap/cache/compiled.php(9876): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#47 /home/stellar/stellar/bootstrap/cache/compiled.php(2347): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#48 /home/stellar/stellar/bootstrap/cache/compiled.php(2331): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#49 /home/stellar/stellar/public/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#50 {main}  
[2016-05-30 00:51:55] production.INFO: HTTP/1.0 422 Unprocessable Entity
Cache-Control: no-cache
Content-Type:  application/json

{"name":["The name field is required."],"email":["The email field is required."],"phone_number":["The phone number field is required."]}  
[2016-05-30 00:51:55] production.INFO:   

```

Any ideas, I've looked everywhere on this and it's just using a standard request generated through Artisan, nothing special and works fine locally. Seemed like there was an issue with earlier 5.2.x versions but this is on 5.2.30 for both local and prod.

**Comment by minhchu** [comment]
Could you try `php artisan clear-compiled` and see if it would work ?
