### ISSUE TITLE
Exception on use dd(collect(array())) 

### ISSUE THREAD

**Issue by akeinhell** [laravel/framework#14332]
[ErrorException] A non well formed numeric value encountered

```
[2016-07-16 14:12:47] local.ERROR: ErrorException: A non well formed numeric value encountered in /var/www/ruvi/vendor/symfony/var-dumper/Cloner/VarCloner.php:298

Stack trace:

#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'A non well form...', '/var/www/ruvi/v...', 298, Array)

#1 /var/www/ruvi/vendor/symfony/var-dumper/Cloner/AbstractCloner.php(195): call_user_func(Array, 8, 'A non well form...', '/var/www/ruvi/v...', 298, Array)

#2 /var/www/ruvi/vendor/symfony/var-dumper/Cloner/VarCloner.php(298): Symfony\Component\VarDumper\Cloner\AbstractCloner->Symfony\Component\VarDumper\Cloner\{closure}(8, 'A non well form...', '/var/www/ruvi/v...', 298, Array)

#3 /var/www/ruvi/vendor/symfony/var-dumper/Cloner/VarCloner.php(55): Symfony\Component\VarDumper\Cloner\VarCloner::initHashMask()

#4 /var/www/ruvi/vendor/symfony/var-dumper/Cloner/AbstractCloner.php(203): Symfony\Component\VarDumper\Cloner\VarCloner->doClone(Object(App\Facades\VkApi\Models\Post))

#5 /var/www/ruvi/vendor/laravel/framework/src/Illuminate/Support/Debug/Dumper.php(21): Symfony\Component\VarDumper\Cloner\AbstractCloner->cloneVar(Object(App\Facades\VkApi\Models\Post))

#6 /var/www/ruvi/vendor/laravel/framework/src/Illuminate/Support/helpers.php(511): Illuminate\Support\Debug\Dumper->dump(Object(App\Facades\VkApi\Models\Post))

#7 [internal function]: {closure}(Object(App\Facades\VkApi\Models\Post))

#8 /var/www/ruvi/vendor/laravel/framework/src/Illuminate/Support/helpers.php(512): array_map(Object(Closure), Array)

#9 /var/www/ruvi/app/Console/Commands/SourceWatcher.php(153): dd(Object(App\Facades\VkApi\Models\Post))

#10 /var/www/ruvi/vendor/laravel/framework/src/Illuminate/Support/Collection.php(146): App\Console\Commands\SourceWatcher->App\Console\Commands\{closure}(Object(App\Facades\VkApi\Models\Post), 0)

#11 /var/www/ruvi/app/Console/Commands/SourceWatcher.php(156): Illuminate\Support\Collection->each(Object(Closure))

#12 /var/www/ruvi/app/Console/Commands/SourceWatcher.php(105): App\Console\Commands\SourceWatcher->getPosts('evil_incorparat...', 0)

#13 /var/www/ruvi/app/Console/Commands/SourceWatcher.php(73): App\Console\Commands\SourceWatcher->parseSource(Object(App\Source))

#14 [internal function]: App\Console\Commands\SourceWatcher->handle()

#15 /var/www/ruvi/vendor/laravel/framework/src/Illuminate/Container/Container.php(507): call_user_func_array(Array, Array)

#16 /var/www/ruvi/vendor/laravel/framework/src/Illuminate/Console/Command.php(169): Illuminate\Container\Container->call(Array)

#17 /var/www/ruvi/vendor/symfony/console/Command/Command.php(256): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

#18 /var/www/ruvi/vendor/laravel/framework/src/Illuminate/Console/Command.php(155): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

#19 /var/www/ruvi/vendor/symfony/console/Application.php(791): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

#20 /var/www/ruvi/vendor/symfony/console/Application.php(186): Symfony\Component\Console\Application->doRunCommand(Object(App\Console\Commands\SourceWatcher), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

#21 /var/www/ruvi/vendor/symfony/console/Application.php(117): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

#22 /var/www/ruvi/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(107): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

#23 /var/www/ruvi/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

#24 {main} 
```

**Comment by akeinhell** [comment]
Versions:
laravel/framework                     v5.2.39
symfony/var-dumper                    v3.0.8
PHP 7.1.0alpha3 (cli) ( NTS )
Ubuntu 16.04 LTS

**Comment by GrahamCampbell** [comment]
Please report this issue to symfony.
