### ISSUE TITLE
[5.1] support phpunit 5.2?

### ISSUE THREAD

**Issue by JKair** [laravel/framework#14471]
My env:
`laravel 5.1`
`phpunit 5.2`

but when I use `actingAs($user)`,It does not work.

```
PHP Fatal error:  Uncaught exception 'Illuminate\Contracts\Container\BindingResolutionException' with message 'Target [Illuminate\Contracts\Debug\ExceptionHandler] is not instantiable.' in /Applications/XAMPP/xamppfiles/htdocs/caugooV4/vendor/laravel/framework/src/Illuminate/Container/Container.php:749
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/caugooV4/vendor/laravel/framework/src/Illuminate/Container/Container.php(631): Illuminate\Container\Container->build('Illuminate\\Cont...', Array)
#1 /Applications/XAMPP/xamppfiles/htdocs/caugooV4/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(674): Illuminate\Container\Container->make('Illuminate\\Cont...', Array)
#2 /Applications/XAMPP/xamppfiles/htdocs/caugooV4/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(154): Illuminate\Foundation\Application->make('Illuminate\\Cont...')
#3 /Applications/XAMPP/xamppfiles/htdocs/caugooV4/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(79): Illuminat in /Applications/XAMPP/xamppfiles/htdocs/caugooV4/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 749
```

Does it is the problem of the version?

**Comment by GrahamCampbell** [comment]
Laravel 5.1 only officially supports PHHUnit 4.x. Laravel 5.3 support PHPUnit 5.x. This is due to the requirement of Laravel 5.1 and 5.2 to support PHP 5.5.

**Comment by JKair** [comment]
@GrahamCampbell OK.Thanks.

**Comment by JKair** [comment]
@GrahamCampbell 
I remove the phpunit5.2 and install 4.8,the problem also....
now,the env:
```
PHP 5.6.18
laravel 5.1
phpunit 4.8
```

```
PHP Fatal error:  Uncaught exception 'Illuminate\Contracts\Container\BindingResolutionException' with message 'Target [Illuminate\Contracts\Debug\ExceptionHandler] is not instantiable.' in /Applications/XAMPP/xamppfiles/htdocs/caugooV4/vendor/laravel/framework/src/Illuminate/Container/Container.php:749
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/caugooV4/vendor/laravel/framework/src/Illuminate/Container/Container.php(631): Illuminate\Container\Container->build('Illuminate\\Cont...', Array)
#1 /Applications/XAMPP/xamppfiles/htdocs/caugooV4/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(674): Illuminate\Container\Container->make('Illuminate\\Cont...', Array)
#2 /Applications/XAMPP/xamppfiles/htdocs/caugooV4/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(154): Illuminate\Foundation\Application->make('Illuminate\\Cont...')
#3 /Applications/XAMPP/xamppfiles/htdocs/caugooV4/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(79): Illuminat in /Applications/XAMPP/xamppfiles/htdocs/caugooV4/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 749
```

when I use `actingAs($user)`,but other function normal.

**Comment by GrahamCampbell** [comment]
Are you only seeing this with code coverage enabled?

**Comment by JKair** [comment]
and `Fatal error: Call to a member function myfun() on null`,I think it should not matter with this error.

**Comment by JKair** [comment]
and `Fatal error: Call to a member function myfun() on null`,I think it should not matter with this error.

**Comment by JKair** [comment]
@GrahamCampbell 
sorry,I found out it was my mistake to use the function.
thanks for your help.
I'm sorry to waste your time.
