### ISSUE TITLE
[5.3] Error after updating with eager loading

### ISSUE THREAD

**Issue by infernobass7** [laravel/framework#14898]
After I updated to Laravel 5.3, I get the following error when trying to eager load.

```
[2016-08-19 08:38:04] local.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function all() on array in /home/vagrant/data-ms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php:617
Stack trace:
#0 /home/vagrant/data-ms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(322): Illuminate\Database\Eloquent\Builder->getModels(Array)
#1 /home/vagrant/data-ms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(632): Illuminate\Database\Eloquent\Builder->get(Array)
#2 /home/vagrant/data-ms/app/Providers/AuthServiceProvider.php(45): Illuminate\Database\Eloquent\Model::all()
#3 /home/vagrant/data-ms/app/Providers/AuthServiceProvider.php(36): App\Providers\AuthServiceProvider->getPermissions()
#4 [internal function]: App\Providers\AuthServiceProvider->boot(Object(Illuminate\Auth\Access\Gate))
#5 /home/vagrant/data-ms/vendor/laravel/framework/src/Illuminate/Container/Container.php(507): call_user_func_array(Array, Array)
#6 /home/vagrant/data-ms/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(759): Illuminate\Container\Container->call(Array)
#7 /home/vagrant/data-ms/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(742): Illuminate\Foundation\Application->bootProvider(Object(App\Providers\AuthServiceProvider))
#8 [internal function]: Illuminate\Foundation\Application->Illuminate\Foundation\{closure}(Object(App\Providers\AuthServiceProvider), 18)
#9 /home/vagrant/data-ms/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(743): array_walk(Array, Object(Closure))
#10 /home/vagrant/data-ms/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\Foundation\Application->boot()
#11 /home/vagrant/data-ms/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(203): Illuminate\Foundation\Bootstrap\BootProviders->bootstrap(Object(Illuminate\Foundation\Application))
#12 /home/vagrant/data-ms/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(249): Illuminate\Foundation\Application->bootstrapWith(Array)
#13 /home/vagrant/data-ms/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(144): Illuminate\Foundation\Http\Kernel->bootstrap()
#14 /home/vagrant/data-ms/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#15 /home/vagrant/data-ms/public/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#16 {main}  
```

Here is the spot that the code fails:
```
    protected function getPermissions()
    {
        return Permission::with('groups')->get();
    }
```
Switching it to the following gives the same error:
```
    protected function getPermissions()
    {
        return Permission::all()->load('groups');
    }
```

**Comment by GrahamCampbell** [comment]
I don't think you're using this correctly. Please ask on the forums.

**Comment by infernobass7** [comment]
It was working before updating and it matches the documentation on Laravel.com

**Comment by GrahamCampbell** [comment]
Ping @taylorotwell.

**Comment by GrahamCampbell** [comment]
What does your groups method look like?

**Comment by JosephSilber** [comment]
Can you show us the full model?

**Comment by infernobass7** [comment]
```
<?php

namespace App;

use App\Model;

class Permission extends Model
{
    protected $fillable = ['display','name'];

	protected $primaryKey = 'name';
	public $incrementing = false;

	public function groups() {
		return $this->belongsToMany(Group::class,null,'permission_ids','group_ids');
	}

	public function module() {
		return $this->belongsTo(\App\Module::class);
	}
}
```

**Comment by infernobass7** [comment]
I found the issue. I am using laravel-mongodb and the log never showed that it was in the Mongo package.
