### ISSUE TITLE
[5.3] Custom Auth Guards do not load

### ISSUE THREAD

**Issue by VinceG** [laravel/framework#14972]
We are currently using Laravel 5.2 and we have a custom Auth Guard 'admin', i've changed the laravel to 5.3 locally to test things out, once passed the initial composer dependencies error, routes changes and some minor errors regarding method declaration compatibility i got to a point where it redirects me to /admin/login once i try to access the admin module.

The thing is it throws the below error since the $this->guards is empty. for some reason it did not load the guards from the auth.php config file as it previously did.

There are some changes to the Auth service provider which i saw and updated our code to accommodate those changes, However the 'guards' class property is still empty. at what point is that populated?

Our modules/Admin/Auth/AdminAuthProvider.php looks like this:

```
<?php

namespace Modules\Admin\Auth;

use App\Models\User;
use Modules\Admin\Auth\AdminUserProvider;
use Illuminate\Foundation\Support\Providers\AuthServiceProvider as ServiceProvider;
use App\Hash\Hasher;

class AdminAuthProvider extends ServiceProvider {

    /**
     * Bootstrap the application services.
     *
     * @return void
     */
    public function register()
    {
        $this->app['auth']->provider('admin', function()
        {
            return new AdminUserProvider(new Hasher, (new User)->with(['userData']));
        });
    }
}
```

Most likely something is missed but i am not sure if i am missing something or the order in which the classes are loaded is incorrect causing the script to reach the AuthManager@guard method while the 'guards' property is still empty.

Thank You.

```
[2016-08-23 08:38:19] local.ERROR: ErrorException: Illegal offset type in isset or empty in /Users/vincentgabriel/Sites/landmark-beta/vendor/laravel/framework/src/Illuminate/Auth/AuthManager.php:68
Stack trace:
#0 /Users/vincentgabriel/Sites/landmark-beta/vendor/laravel/framework/src/Illuminate/Auth/AuthManager.php(68): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'Illegal offset ...', '/Users/vincentg...', 68, Array)
#1 /Users/vincentgabriel/Sites/landmark-beta/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(149): Illuminate\Auth\AuthManager->guard(Object(Illuminate\Auth\SessionGuard))
#2 /Users/vincentgabriel/Sites/landmark-beta/modules/Admin/Http/Controllers/Auth/AuthController.php(45): auth(Object(Illuminate\Auth\SessionGuard))
#3 [internal function]: Modules\Admin\Http\Controllers\Auth\AuthController->login(Object(Illuminate\Http\Request))
#4 /Users/vincentgabriel/Sites/landmark-beta/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(52): call_user_func_array(Array, Array)
#5 /Users/vincentgabriel/Sites/landmark-beta/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(44): Illuminate\Routing\Controller->callAction('login', Array)
#6 /Users/vincentgabriel/Sites/landmark-beta/vendor/laravel/framework/src/Illuminate/Routing/Route.php(189): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Modules\Admin\Http\Controllers\Auth\AuthController), 'login')
#7 /Users/vincentgabriel/Sites/landmark-beta/vendor/laravel/framework/src/Illuminate/Routing/Route.php(144): Illuminate\Routing\Route->runController()
#8 /Users/vincentgabriel/Sites/landmark-beta/vendor/laravel/framework/src/Illuminate/Routing/Router.php(642): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#9 /Users/vincentgabriel/Sites/landmark-beta/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#10 /Users/vincentgabriel/Sites/landmark-beta/app/Http/Middleware/RedirectIfAuthenticated.php(24): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#11 /Users/vincentgabriel/Sites/landmark-beta/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): App\Http\Middleware\RedirectIfAuthenticated->handle(Object(Illuminate\Http\Request), Object(Closure))
#12 /Users/vincentgabriel/Sites/landmark-beta/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#13 /Users/vincentgabriel/Sites/landmark-beta/modules/Admin/Http/Middleware/Authenticate.php(31): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#14 /Users/vincentgabriel/Sites/landmark-beta/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Modules\Admin\Http\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#15 /Users/vincentgabriel/Sites/landmark-beta/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#16 /Users/vincentgabriel/Sites/landmark-beta/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#17 /Users/vincentgabriel/Sites/landmark-beta/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#18 /Users/vincentgabriel/Sites/landmark-beta/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#19 /Users/vincentgabriel/Sites/landmark-beta/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(64): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#20 /Users/vincentgabriel/Sites/landmark-beta/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#21 /Users/vincentgabriel/Sites/landmark-beta/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#22 /Users/vincentgabriel/Sites/landmark-beta/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#23 /Users/vincentgabriel/Sites/landmark-beta/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#24 /Users/vincentgabriel/Sites/landmark-beta/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#25 /Users/vincentgabriel/Sites/landmark-beta/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#26 /Users/vincentgabriel/Sites/landmark-beta/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#27 /Users/vincentgabriel/Sites/landmark-beta/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#28 /Users/vincentgabriel/Sites/landmark-beta/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#29 /Users/vincentgabriel/Sites/landmark-beta/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#30 /Users/vincentgabriel/Sites/landmark-beta/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#31 /Users/vincentgabriel/Sites/landmark-beta/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#32 /Users/vincentgabriel/Sites/landmark-beta/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#33 /Users/vincentgabriel/Sites/landmark-beta/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 /Users/vincentgabriel/Sites/landmark-beta/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#35 /Users/vincentgabriel/Sites/landmark-beta/vendor/laravel/framework/src/Illuminate/Routing/Router.php(644): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#36 /Users/vincentgabriel/Sites/landmark-beta/vendor/laravel/framework/src/Illuminate/Routing/Router.php(618): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#37 /Users/vincentgabriel/Sites/landmark-beta/vendor/laravel/framework/src/Illuminate/Routing/Router.php(596): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#38 /Users/vincentgabriel/Sites/landmark-beta/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(263): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#39 /Users/vincentgabriel/Sites/landmark-beta/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#40 /Users/vincentgabriel/Sites/landmark-beta/vendor/barryvdh/laravel-debugbar/src/Middleware/Debugbar.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#41 /Users/vincentgabriel/Sites/landmark-beta/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Barryvdh\Debugbar\Middleware\Debugbar->handle(Object(Illuminate\Http\Request), Object(Closure))
#42 /Users/vincentgabriel/Sites/landmark-beta/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#43 /Users/vincentgabriel/Sites/landmark-beta/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#44 /Users/vincentgabriel/Sites/landmark-beta/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#45 /Users/vincentgabriel/Sites/landmark-beta/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#46 /Users/vincentgabriel/Sites/landmark-beta/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#47 /Users/vincentgabriel/Sites/landmark-beta/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(149): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#48 /Users/vincentgabriel/Sites/landmark-beta/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#49 /Users/vincentgabriel/Sites/landmark-beta/public/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#50 {main}
```

**Comment by VinceG** [comment]
Reading the upgrade guide it states that the controllers were split and method names have changed too. that was the issue for me. Closing this.
