### ISSUE TITLE
illiminate/database, DB::insertGetId() catch Exception on multiple insert rows

### ISSUE THREAD

**Issue by ntvsx193** [laravel/framework#15412]
- Laravel Version: 5.4.3
- PHP Version: PHP 7.0.10-2+deb.sury.org~xenial+1
- Database Driver & Version: pgsql, PostgreSQL 9.5

### Description:
I use composer package `illuminate/database`.
DB::insertGetId() catch Exception on multiple insert rows.

Exception:
```
PHP Notice:  Array to string conversion in /var/www/<project>/vendor/illuminate/database/Connection.php on line 410

Notice: Array to string conversion in /var/www/<project>/vendor/illuminate/database/Connection.php on line 410
PHP Notice:  Array to string conversion in /var/www/<project>/vendor/illuminate/database/Connection.php on line 410

Notice: Array to string conversion in /var/www/<project>/vendor/illuminate/database/Connection.php on line 410
PHP Notice:  Array to string conversion in /var/www/<project>/vendor/illuminate/database/Connection.php on line 410

Notice: Array to string conversion in /var/www/<project>/vendor/illuminate/database/Connection.php on line 410
PHP Notice:  Array to string conversion in /var/www/<project>/vendor/illuminate/database/Connection.php on line 410

Notice: Array to string conversion in /var/www/<project>/vendor/illuminate/database/Connection.php on line 410
PHP Fatal error:  Uncaught PDOException: SQLSTATE[08P01]: <<Unknown error>>: 7 ERROR:  bind message supplies 4 parameters, but prepared statement "pdo_stmt_00000002" requires 16 in /var/www/<project>/vendor/illuminate/database/Connection.php:337
Stack trace:
#0 /var/www/<project>/vendor/illuminate/database/Connection.php(337): PDOStatement->execute()
#1 /var/www/<project>/vendor/illuminate/database/Connection.php(754): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\PostgresConnection), 'insert into "vm...', Array)
#2 /var/www/<project>/vendor/illuminate/database/Connection.php(717): Illuminate\Database\Connection->runQueryCallback('insert into "vm...', Array, Object(Closure))
#3 /var/www/<project>/vendor/illuminate/database/Connection.php(351): Illuminate\Database\Connection->run('insert into "vm...', Array, Object(Closure))
#4 /var/www/<project>/vendor/illuminate/database/Connection.php(312): Illuminate\Database\Connection->s in /var/www/<project>/vendor/illuminate/database/Connection.php on line 761

Fatal error: Uncaught PDOException: SQLSTATE[08P01]: <<Unknown error>>: 7 ERROR:  bind message supplies 4 parameters, but prepared statement "pdo_stmt_00000002" requires 16 in /var/www/<project>/vendor/illuminate/database/Connection.php:337
Stack trace:
#0 /var/www/<project>/vendor/illuminate/database/Connection.php(337): PDOStatement->execute()
#1 /var/www/<project>/vendor/illuminate/database/Connection.php(754): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\PostgresConnection), 'insert into "vm...', Array)
#2 /var/www/<project>/vendor/illuminate/database/Connection.php(717): Illuminate\Database\Connection->runQueryCallback('insert into "vm...', Array, Object(Closure))
#3 /var/www/<project>/vendor/illuminate/database/Connection.php(351): Illuminate\Database\Connection->run('insert into "vm...', Array, Object(Closure))
#4 /var/www/<project>/vendor/illuminate/database/Connection.php(312): Illuminate\Database\Connection->s in /var/www/<project>/vendor/illuminate/database/Connection.php on line 761
```

### Steps To Reproduce:
```php
<?php

$capsule = new \Illuminate\Database\Capsule\Manager;

$capsule->addConnection([
    'driver'    => 'pgsql',
    'host'      => '...',
    'database'  => '...',
    'username'  => '...',
    'password'  => '...',
    'charset'   => 'utf8',
    'collation' => 'utf8_unicode_ci',
    'prefix'    => '',
]);

$capsule->setAsGlobal();

$rows = [
    [
        'vm_id' => 7043,
        'tube' => 2,
        'denomination' => 10,
        'number' => 25
    ],
    [
        'vm_id' => 7043,
        'tube' => 3,
        'denomination' => 10,
        'number' => 36
    ],
    [
        'vm_id' => 7043,
        'tube' => 4,
        'denomination' => 5,
        'number' => 3
    ],
    [
        'vm_id' => 7043,
        'tube' => 4,
        'denomination' => 1,
        'number' => 34
    ],
];

///
/// ..other file
/// 

$query = \Illuminate\Database\Capsule\Manager::table('vm.money_tubes');

$ids = $query->insertGetId($rows);

print_r($ids);
```

**Comment by themsaid** [comment]
`insertGetId()` should be used to create a single record, it accepts an array of record column values and returns an integer, which is the row primary key.

**Comment by devcronix** [comment]
So does it possible to retrieve multiple IDs? I think it's very big issue in many cases.
