### ISSUE TITLE
[5.3] Got exception while running queues using redis driver

### ISSUE THREAD

**Issue by serg6854** [laravel/framework#15674]
- Laravel Version: **5.3.6**
- PHP Version: **7.0.8**
- Database Driver & Version: **postgresql 9.5.3**

### Description:
I've created job for generating and sending emails and start artisan command `queue:work`. After that all time trows exceptions like this:

<details>
  <summary>Click to expand</summary>
```
Next Doctrine\DBAL\Driver\PDOException: SQLSTATE[HY000]: General error: 7 SSL SYSCALL error: EOF detected in /home/vagrant/Code/sms/src/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93
Stack trace:
#0 /home/vagrant/Code/sms/src/vendor/laravel/framework/src/Illuminate/Database/Connection.php(337): Doctrine\DBAL\Driver\PDOStatement->execute()
#1 /home/vagrant/Code/sms/src/vendor/laravel/framework/src/Illuminate/Database/Connection.php(754): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\PostgresConnection), 'select * from "...', Array)
#2 /home/vagrant/Code/sms/src/vendor/laravel/framework/src/Illuminate/Database/Connection.php(717): Illuminate\Database\Connection->runQueryCallback('select * from "...', Array, Object(Closure))
#3 /home/vagrant/Code/sms/src/vendor/laravel/framework/src/Illuminate/Database/Connection.php(351): Illuminate\Database\Connection->run('select * from "...', Array, Object(Closure))
#4 /home/vagrant/Code/sms/src/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1645): Illuminate\Database\Connection->select('select * from "...', Array, false)
#5 /home/vagrant/Code/sms/src/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1631): Illuminate\Database\Query\Builder->runSelect()
#6 /home/vagrant/Code/sms/src/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(613): Illuminate\Database\Query\Builder->get(Array)
#7 /home/vagrant/Code/sms/src/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(318): Illuminate\Database\Eloquent\Builder->getModels(Array)
#8 /home/vagrant/Code/sms/src/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(288): Illuminate\Database\Eloquent\Builder->get(Array)
#9 /home/vagrant/Code/sms/src/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(168): Illuminate\Database\Eloquent\Builder->first(Array)
#10 /home/vagrant/Code/sms/src/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(200): Illuminate\Database\Eloquent\Builder->find(14, Array)
#11 /home/vagrant/Code/sms/src/vendor/laravel/framework/src/Illuminate/Queue/SerializesAndRestoresModelIdentifiers.php(45): Illuminate\Database\Eloquent\Builder->findOrFail(14)
#12 /home/vagrant/Code/sms/src/vendor/laravel/framework/src/Illuminate/Queue/SerializesModels.php(41): App\Mail\CampaignTransmit->getRestoredPropertyValue(Object(Illuminate\Contracts\Database\ModelIdentifier))
#13 [internal function]: App\Mail\CampaignTransmit->__wakeup()
#14 /home/vagrant/Code/sms/src/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(38): unserialize('O:34:"Illuminat...')
#15 /home/vagrant/Code/sms/src/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(72): Illuminate\Queue\CallQueuedHandler->call(Object(Illuminate\Queue\Jobs\RedisJob), Array)
#16 /home/vagrant/Code/sms/src/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(207): Illuminate\Queue\Jobs\Job->fire()
#17 /home/vagrant/Code/sms/src/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(160): Illuminate\Queue\Worker->process('redis', Object(Illuminate\Queue\Jobs\RedisJob), Object(Illuminate\Queue\WorkerOptions))
#18 /home/vagrant/Code/sms/src/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(111): Illuminate\Queue\Worker->runNextJob('redis', 'default', Object(Illuminate\Queue\WorkerOptions))
#19 /home/vagrant/Code/sms/src/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(74): Illuminate\Queue\Worker->runNextJobForDaemon('redis', 'default', Object(Illuminate\Queue\WorkerOptions))
#20 /home/vagrant/Code/sms/src/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(97): Illuminate\Queue\Worker->daemon('redis', 'default', Object(Illuminate\Queue\WorkerOptions))
#21 /home/vagrant/Code/sms/src/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(78): Illuminate\Queue\Console\WorkCommand->runWorker('redis', 'default')
#22 [internal function]: Illuminate\Queue\Console\WorkCommand->fire()
#23 /home/vagrant/Code/sms/src/vendor/laravel/framework/src/Illuminate/Container/Container.php(507): call_user_func_array(Array, Array)
#24 /home/vagrant/Code/sms/src/vendor/laravel/framework/src/Illuminate/Console/Command.php(169): Illuminate\Container\Container->call(Array)
#25 /home/vagrant/Code/sms/src/vendor/symfony/console/Command/Command.php(256): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#26 /home/vagrant/Code/sms/src/vendor/laravel/framework/src/Illuminate/Console/Command.php(155): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#27 /home/vagrant/Code/sms/src/vendor/symfony/console/Application.php(818): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#28 /home/vagrant/Code/sms/src/vendor/symfony/console/Application.php(186): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Queue\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#29 /home/vagrant/Code/sms/src/vendor/symfony/console/Application.php(117): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#30 /home/vagrant/Code/sms/src/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#31 /home/vagrant/Code/sms/src/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#32 {main}
```
</details>

When i restarted the command `queue:work`, job works fine.
I am using redis driver for queues.
If change queue driver to sync - everything works fine.

**Comment by krcgk** [comment]
I'm having a similar problem, but a little different.

`php artisan queue:work redis`

output

```
[2016-09-29 17:13:29] local.ERROR: Symfony\Component\Console\Exception\RuntimeException: Too many arguments, expected arguments "command". in /home/vagrant/Code/core/vendor/symfony/console/Input/ArgvInput.php:181
Stack trace:
#0 /home/vagrant/Code/core/vendor/symfony/console/Input/ArgvInput.php(88): Symfony\Component\Console\Input\ArgvInput->parseArgument('redis')
#1 /home/vagrant/Code/core/vendor/symfony/console/Input/Input.php(62): Symfony\Component\Console\Input\ArgvInput->parse()
#2 /home/vagrant/Code/core/vendor/symfony/console/Command/Command.php(221): Symfony\Component\Console\Input\Input->bind(Object(Symfony\Component\Console\Input\InputDefinition))
#3 /home/vagrant/Code/core/vendor/laravel/framework/src/Illuminate/Console/Command.php(155): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /home/vagrant/Code/core/vendor/symfony/console/Application.php(818): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /home/vagrant/Code/core/vendor/symfony/console/Application.php(186): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Queue\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /home/vagrant/Code/core/vendor/symfony/console/Application.php(117): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /home/vagrant/Code/core/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /home/vagrant/Code/core/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 {main}  
```

**Comment by playerrtwo** [comment]
I'm getting the same problem with database driver.

**Comment by themsaid** [comment]
Guys the two exceptions are completely different, I imagine this isn't a single issue.

> When i restarted the command queue:work, job works fine.

@serg6854 so why are you reporting it as a problem since it's working fine now?

@krcgk please open a separate issue.

@playerrtwo please share the exception you receive.

**Comment by playerrtwo** [comment]
Restarting the queues did not resolve the problem for me. I had to revert to an earlier version of Laravel Framework. Good thing I was paying attention to my production system to realize this happened. My queues are critical!

`[2016-09-29 12:26:39] dev.ERROR: exception 'Symfony\Component\Console\Exception\RuntimeException' with message 'Too many arguments, expected arguments "command".' in /home/contactl/public_html/vendor/symfony/console/Input/ArgvInput.php:181
Stack trace:
#0 /home/contactl/public_html/vendor/symfony/console/Input/ArgvInput.php(88): Symfony\Component\Console\Input\ArgvInput->parseArgument('database')
#1 /home/contactl/public_html/vendor/symfony/console/Input/Input.php(62): Symfony\Component\Console\Input\ArgvInput->parse()
#2 /home/contactl/public_html/vendor/symfony/console/Command/Command.php(221): Symfony\Component\Console\Input\Input->bind(Object(Symfony\Component\Console\Input\InputDefinition))
#3 /home/contactl/public_html/vendor/laravel/framework/src/Illuminate/Console/Command.php(155): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /home/contactl/public_html/vendor/symfony/console/Application.php(818): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /home/contactl/public_html/vendor/symfony/console/Application.php(186): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Queue\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /home/contactl/public_html/vendor/symfony/console/Application.php(117): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /home/contactl/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /home/contactl/public_html/artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 {main} `

**Comment by themsaid** [comment]
What's your laravel version @playerrtwo?

**Comment by playerrtwo** [comment]
5.3.12 was generating the exception above.

I reverted to 5.3.10 which resolved the issue.

**Comment by serg6854** [comment]
@themsaid Sorry, maybe I poorly explained. Yes, after restarting queue works fine, but for a short time,  then exception continues throws to log file.

**Comment by serg6854** [comment]
@themsaid seems that after upgrading laravel to 5.3.12 problem has been resolved

**Comment by themsaid** [comment]
@playerrtwo just released a new patch, please upgrade and your command would work like normal 👍

**Comment by themsaid** [comment]
@serg6854 nice :)
