### ISSUE TITLE
homestead.rb:109:in `read': No such file or directory @ rb_sysopen

### ISSUE THREAD

**Issue by hao203** [laravel/framework#16092]
- Laravel Version: 5.3
- PHP Version:7.0
- Database Driver & Version:

### Description:

I try to use homestead via the document 5.3 from the offical website https://laravel.com/docs/5.3/homestead but it doesn't work, the details were as follows:

The snapshot
![qq 20161025155009](https://cloud.githubusercontent.com/assets/6681974/19677655/e0eb71fe-9acc-11e6-9e32-a6dea23b7370.jpg)

Who can help me! Thank you

**Comment by hao203** [comment]
@GrahamCampbell why close my issue? Can u give any help?

**Comment by hao203** [comment]
C:\Users\liang\Homestead>vagrant up
C:/Users/liang/Homestead/scripts/homestead.rb:109:in `read': No such file or directory @ rb_sysopen - C:/Users/liang/.ssh/id_rsa (Errno::ENOENT)
        from C:/Users/liang/Homestead/scripts/homestead.rb:109:in `block (2 levels) in configure'
        from D:/Program Files/vagrant/embedded/gems/gems/vagrant-1.8.4/plugins/kernel_v2/config/vm_provisioner.rb:72:in `call'
        from D:/Program Files/vagrant/embedded/gems/gems/vagrant-1.8.4/plugins/kernel_v2/config/vm_provisioner.rb:72:in `add_config'
        from D:/Program Files/vagrant/embedded/gems/gems/vagrant-1.8.4/plugins/kernel_v2/config/vm.rb:321:in `provision'
        from C:/Users/liang/Homestead/scripts/homestead.rb:106:in `block in configure'
        from C:/Users/liang/Homestead/scripts/homestead.rb:105:in `each'
        from C:/Users/liang/Homestead/scripts/homestead.rb:105:in `configure'
        from C:/Users/liang/Homestead/Vagrantfile:30:in `block in <top (required)>'
        from D:/Program Files/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/config/v2/loader.rb:37:in `call'
        from D:/Program Files/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/config/v2/loader.rb:37:in `load'
        from D:/Program Files/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/config/loader.rb:113:in `block (2 levels) in load'
        from D:/Program Files/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/config/loader.rb:107:in `each'
        from D:/Program Files/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/config/loader.rb:107:in `block in load'
        from D:/Program Files/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/config/loader.rb:104:in `each'
        from D:/Program Files/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/config/loader.rb:104:in `load'
        from D:/Program Files/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/vagrantfile.rb:28:in `initialize'
        from D:/Program Files/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/environment.rb:740:in `new'
        from D:/Program Files/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/environment.rb:740:in `vagrantfile'
        from D:/Program Files/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/environment.rb:486:in `host'
        from D:/Program Files/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/environment.rb:208:in `block in action_runner'
        from D:/Program Files/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/action/runner.rb:33:in `call'
        from D:/Program Files/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/action/runner.rb:33:in `run'
        from D:/Program Files/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/environment.rb:473:in `hook'
        from D:/Program Files/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/environment.rb:722:in `unload'
        from D:/Program Files/vagrant/embedded/gems/gems/vagrant-1.8.4/bin/vagrant:177:in `ensure in <main>'
        from D:/Program Files/vagrant/embedded/gems/gems/vagrant-1.8.4/bin/vagrant:177:in `<main>'
