### ISSUE TITLE
CSRF token mismatch error

### ISSUE THREAD

**Issue by mikey0000** [laravel/framework#16214]
- Laravel Version: 5.3.*
- PHP Version:56
- Database Driver & Version:

### Description:
when logging into the admin over https it works but when I log in over http it throws this error

### Steps To Reproduce:
Login over https, log out, then log back in using http

```
production.ERROR: exception 'Illuminate\Session\TokenMisma
tchException' in /website/vendor/laravel/f
ramework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php:68
Stack trace:
#0 /website/vendor/laravel/framework/src/I
lluminate/Pipeline/Pipeline.php(137): Illuminate\Foundation\Http\Middleware\Veri
fyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#1 /website/vendor/laravel/framework/src/I
lluminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pip
eline\{closure}(Object(Illuminate\Http\Request))
#2 /website/core/anomaly/users-module/src/
Http/Middleware/AuthorizeRoutePermission.php(79): Illuminate\Routing\Pipeline->I
lluminate\Routing\{closure}(Object(Illuminate\Http\Request))
#3 /website/vendor/laravel/framework/src/I
lluminate/Pipeline/Pipeline.php(137): Anomaly\UsersModule\Http\Middleware\Author
izeRoutePermission->handle(Object(Illuminate\Http\Request), Object(Closure))
#4 /website/vendor/laravel/framework/src/I
lluminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pip
eline\{closure}(Object(Illuminate\Http\Request))
#5 /website/core/anomaly/users-module/src/
Http/Middleware/AuthorizeControlPanel.php(44): Illuminate\Routing\Pipeline->Illu
minate\Routing\{closure}(Object(Illuminate\Http\Request))
#6 /website/vendor/laravel/framework/src/I
lluminate/Pipeline/Pipeline.php(137): Anomaly\UsersModule\Http\Middleware\Author
izeControlPanel->handle(Object(Illuminate\Http\Request), Object(Closure))
#7 /website/vendor/laravel/framework/src/I
lluminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pip
eline\{closure}(Object(Illuminate\Http\Request))
#8 /website/core/anomaly/users-module/src/
Http/Middleware/AuthorizeModuleAccess.php(54): Illuminate\Routing\Pipeline->Illu
minate\Routing\{closure}(Object(Illuminate\Http\Request))
#9 /website/vendor/laravel/framework/src/I
lluminate/Pipeline/Pipeline.php(137): Anomaly\UsersModule\Http\Middleware\Author
izeModuleAccess->handle(Object(Illuminate\Http\Request), Object(Closure))
#10 /website/vendor/laravel/framework/src/
Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pi
peline\{closure}(Object(Illuminate\Http\Request))
#11 /website/core/anomaly/users-module/src
/Http/Middleware/AuthorizeRouteRoles.php(75): Illuminate\Routing\Pipeline->Illum
inate\Routing\{closure}(Object(Illuminate\Http\Request))
#12 /website/vendor/laravel/framework/src/
Illuminate/Pipeline/Pipeline.php(137): Anomaly\UsersModule\Http\Middleware\Autho
rizeRouteRoles->handle(Object(Illuminate\Http\Request), Object(Closure))
#13 /website/vendor/laravel/framework/src/
Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pi
peline\{closure}(Object(Illuminate\Http\Request))
#14 /website/core/anomaly/users-module/src
/Http/Middleware/CheckSecurity.php(86): Illuminate\Routing\Pipeline->Illuminate\
Routing\{closure}(Object(Illuminate\Http\Request))
#15 /website/vendor/laravel/framework/src/
Illuminate/Pipeline/Pipeline.php(137): Anomaly\UsersModule\Http\Middleware\Check
Security->handle(Object(Illuminate\Http\Request), Object(Closure))
#16 /website/vendor/laravel/framework/src/
Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pi
peline\{closure}(Object(Illuminate\Http\Request))
#17 /website/vendor/laravel/framework/src/
Illuminate/Pipeline/Pipeline.php(104): Illuminate\Routing\Pipeline->Illuminate\R
outing\{closure}(Object(Illuminate\Http\Request))
#18 /website/vendor/laravel/framework/src/
Illuminate/Routing/Router.php(644): Illuminate\Pipeline\Pipeline->then(Object(Cl
osure))
#19 /website/vendor/laravel/framework/src/
Illuminate/Routing/Router.php(618): Illuminate\Routing\Router->runRouteWithinSta
ck(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#20 /website/vendor/laravel/framework/src/
Illuminate/Routing/Router.php(596): Illuminate\Routing\Router->dispatchToRoute(O
bject(Illuminate\Http\Request))
#21 /website/vendor/laravel/framework/src/
Illuminate/Foundation/Http/Kernel.php(267): Illuminate\Routing\Router->dispatch(
Object(Illuminate\Http\Request))
#22 /website/vendor/laravel/framework/src/
Illuminate/Routing/Pipeline.php(53): Illuminate\Foundation\Http\Kernel->Illumina
te\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#23 /website/vendor/laravel/framework/src/
Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Routing\Pi
peline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#24 website/vendor/laravel/framework/src/
Illuminate/Pipeline/Pipeline.php(137): Illuminate\View\Middleware\ShareErrorsFro
mSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#25/website/vendor/laravel/framework/src/
Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pi
peline\{closure}(Object(Illuminate\Http\Request))
#26 /website/vendor/laravel/framework/src/
Illuminate/Session/Middleware/StartSession.php(64): Illuminate\Routing\Pipeline-
>Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#27 /website/vendor/laravel/framework/src/
Illuminate/Pipeline/Pipeline.php(137): Illuminate\Session\Middleware\StartSessio
n->handle(Object(Illuminate\Http\Request), Object(Closure))
#28 /website/vendor/laravel/framework/src/
Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pi
peline\{closure}(Object(Illuminate\Http\Request))
#29 website/vendor/laravel/framework/src/
Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Rout
ing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#30 /website/vendor/laravel/framework/src/
Illuminate/Pipeline/Pipeline.php(137): Illuminate\Cookie\Middleware\AddQueuedCoo
kiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#31 /website/vendor/laravel/framework/src/
Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pi
peline\{closure}(Object(Illuminate\Http\Request))
#32 /website/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#33 /website/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#34 /website/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#35 /website/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#36 /website/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(149): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#37 /website/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#38 /website/public/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#39 {main}
```

**Comment by geoherna** [comment]
How are you logging in? HTML Form? Ajax? API?

**Comment by mikey0000** [comment]
Login, into pyrocms admin so I believe it is an html form.

**Comment by GrahamCampbell** [comment]
Probably due to the cookies being sent for https only.

**Comment by geoherna** [comment]
Yep, not a Laravel issue.
