### ISSUE TITLE
[5.3] InvalidArgumentException: No handler registered for command

### ISSUE THREAD

**Issue by amberlampsio** [laravel/framework#16374]
- Laravel Version: 5.3.22
- PHP Version: 7.0.8
- Database Driver & Version: MySql 5.7

### Description:

Experiencing this issue after upgrading from 5.1 to 5.3.22  Work just fine on local server, but breaks down on forge production. Been looking at this for hours, not sure whats going on.  I am **not** using LaravelCollective\Bus

`[2016-11-11 18:15:09] production.ERROR: InvalidArgumentException: No handler registered for command [App\Jobs\Emails\Messages\NewMessageEmail] in /home/forge/local/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php:333
Stack trace:
#0 /home/forge/local/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(298): Illuminate\Bus\Dispatcher->inflectSegment(Object(App\Jobs\Emails\Messages\NewMessageEmail), 0)
#1 /home/forge/local/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(283): Illuminate\Bus\Dispatcher->getHandlerClass(Object(App\Jobs\Emails\Messages\NewMessageEmail))
#2 /home/forge/local/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(195): Illuminate\Bus\Dispatcher->resolveHandler(Object(App\Jobs\Emails\Messages\NewMessageEmail))
#3 [internal function]: Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(App\Jobs\Emails\Messages\NewMessageEmail))
#4 /home/forge/local/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(App\Jobs\Emails\Messages\NewMessageEmail))
#5 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(App\Jobs\Emails\Messages\NewMessageEmail))
#6 /home/forge/local/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(App\Jobs\Emails\Messages\NewMessageEmail))
#7 /home/forge/local/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(204): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#8 /home/forge/local/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(43): Illuminate\Bus\Dispatcher->dispatchNow(Object(App\Jobs\Emails\Messages\NewMessageEmail), Object(Closure))
#9 /home/forge/local/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(129): Illuminate\Queue\CallQueuedHandler->call(Object(Illuminate\Queue\Jobs\DatabaseJob), Array)
#10 /home/forge/local/vendor/laravel/framework/src/Illuminate/Queue/Jobs/DatabaseJob.php(50): Illuminate\Queue\Jobs\Job->resolveAndFire(Array)
#11 /home/forge/local/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(208): Illuminate\Queue\Jobs\DatabaseJob->fire()
#12 /home/forge/local/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(158): Illuminate\Queue\Worker->process('database', Object(Illuminate\Queue\Jobs\DatabaseJob), '3', 0)
#13 /home/forge/local/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(111): Illuminate\Queue\Worker->pop('database', 'default', 0, '10', '3')
#14 /home/forge/local/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(85): Illuminate\Queue\Worker->runNextJobForDaemon('database', 'default', 0, '10', '3')
#15 /home/forge/local/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(102): Illuminate\Queue\Worker->daemon('database', 'default', 0, 128, '10', '3')
#16 /home/forge/local/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(70): Illuminate\Queue\Console\WorkCommand->runWorker('database', 'default', 0, 128, true)
#17 [internal function]: Illuminate\Queue\Console\WorkCommand->fire()
#18 /home/forge/local/vendor/laravel/framework/src/Illuminate/Container/Container.php(507): call_user_func_array(Array, Array)
#19 /home/forge/local/vendor/laravel/framework/src/Illuminate/Console/Command.php(150): Illuminate\Container\Container->call(Array)
#20 /home/forge/local/vendor/symfony/console/Command/Command.php(256): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 /home/forge/local/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /home/forge/local/vendor/symfony/console/Application.php(841): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 /home/forge/local/vendor/symfony/console/Application.php(189): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Queue\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 /home/forge/local/vendor/symfony/console/Application.php(120): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 /home/forge/local/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(107): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#26 /home/forge/local/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#27 {main}
`

**Comment by amberlampsio** [comment]
**Resolved.**

Initially I was restarting queue via 'php artisan queue:restart' --- although I then deleted the Queue Worker from Forge & created a new worked, solved this for me.

Hope this helps someone in the future.
