### ISSUE TITLE
FormRequest validation is throwing a 500 server error

### ISSUE THREAD

**Issue by MichaelDeBoey** [laravel/framework#16630]
- Laravel Version: 5.3.26
- PHP Version: N/A
- Database Driver & Version: N/A

### Description:
After updating from `v5.3.16` to `v5.3.26` I came across a problem.
When I create a new Request and I implement the `rules`-method (uploaded files can only be pdf's), I get a 500 with following error when the Request isn't as prescribed according to the rules:  
```
[error] 1467#1467: *662 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught ErrorException: Undefined variable: e in /[ROOT_DIRECTORY]/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php:130
Stack trace:
#0 /[ROOT_DIRECTORY]/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(130): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Undefined varia...', '/[ROOT_DIRECTORY]...', 130, Array)
#1 /[ROOT_DIRECTORY]/app/Exceptions/Handler.php(67): Illuminate\Foundation\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(ErrorException))
#2 /[ROOT_DIRECTORY]/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(107): App\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(ErrorException))
#3 /[ROOT_DIRECTORY]/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(84): Illuminate\Foundation\Bootstrap\HandleExceptions->renderHttpResponse(Object(ErrorException))
#4 [internal function]: Illumin...
PHP message: PHP Fatal error:  Uncaught ErrorException: Undefined variable: e in /[ROOT_DIRECTORY]/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php:130
Stack trace:
#0 /[ROOT_DIRECTORY]/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(130): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Undefined varia...', '/[ROOT_DIRECTORY]...', 130, Array)
#1 /[ROOT_DIRECTORY]/app/Exceptions/Handler.php(67): Illuminate\Foundation\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(Symfony\Component\Debug\Exception\FatalErrorException))
#2 /[ROOT_DIRECTORY]/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(107): App\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(Symfony\Component\Debug\Exception\FatalErrorException))
#3 /[ROOT_DIRECTORY]/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/Handle
```

### Steps To Reproduce:
- Create a new FormRequest  
`php artisan create:request CreateDocumentRequest`
- Implement the `rules`-method  
`return ['file' => ['required', 'file', 'mimes:pdf']];`
- Add new Request to Controller

**Comment by themsaid** [comment]
Can't replicate on a fresh installation. Error doesn't make sense as well, the undefined variable mentioned is a method mandatory argument.

Please share the full stack trace.

**Comment by MichaelDeBoey** [comment]
That was the full stack trace I got from `/var/log/nginx`.

I updated my initial post:
>I get a 500 with following error **when the Request isn't as prescribed according to the rules**:

**Comment by themsaid** [comment]
What's in the laravel.log file?

**Comment by MichaelDeBoey** [comment]
```
[2016-12-02 11:22:39] local.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function where() on null in /[ROOT_DIRECTORY]/app/Http/Controllers/CarDocumentController.php:43
Stack trace:
#0 /[ROOT_DIRECTORY]/app/Http/Controllers/CarController.php(90): App\Http\Controllers\CarDocumentController->showDocument('1', 'new')
#1 [internal function]: App\Http\Controllers\CarController->showDocument('1', 'new')
#2 /[ROOT_DIRECTORY]/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(55): call_user_func_array(Array, Array)
#3 /[ROOT_DIRECTORY]/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(44): Illuminate\Routing\Controller->callAction('showDocument', Array)
#4 /[ROOT_DIRECTORY]/vendor/laravel/framework/src/Illuminate/Routing/Route.php(189): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(App\Http\Controllers\CarController), 'showDocument')
#5 /[ROOT_DIRECTORY]/vendor/laravel/framework/src/Illuminate/Routing/Route.php(144): Illuminate\Routing\Route->runController()
#6 /[ROOT_DIRECTORY]/vendor/laravel/framework/src/Illuminate/Routing/Router.php(642): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#7 /[ROOT_DIRECTORY]/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#8 /[ROOT_DIRECTORY]/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#9 /[ROOT_DIRECTORY]/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#10 /[ROOT_DIRECTORY]/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#11 /[ROOT_DIRECTORY]/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(43): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#12 /[ROOT_DIRECTORY]/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Auth\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#13 /[ROOT_DIRECTORY]/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#14 /[ROOT_DIRECTORY]/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(65): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#15 /[ROOT_DIRECTORY]/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#16 /[ROOT_DIRECTORY]/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#17 /[ROOT_DIRECTORY]/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#18 /[ROOT_DIRECTORY]/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#19 /[ROOT_DIRECTORY]/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#20 /[ROOT_DIRECTORY]/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#21 /[ROOT_DIRECTORY]/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#22 /[ROOT_DIRECTORY]/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#23 /[ROOT_DIRECTORY]/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#24 /[ROOT_DIRECTORY]/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#25 /[ROOT_DIRECTORY]/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#26 /[ROOT_DIRECTORY]/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#27 /[ROOT_DIRECTORY]/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#28 /[ROOT_DIRECTORY]/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#29 /[ROOT_DIRECTORY]/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#30 /[ROOT_DIRECTORY]/vendor/laravel/framework/src/Illuminate/Routing/Router.php(644): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#31 /[ROOT_DIRECTORY]/vendor/laravel/framework/src/Illuminate/Routing/Router.php(618): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#32 /[ROOT_DIRECTORY]/vendor/laravel/framework/src/Illuminate/Routing/Router.php(596): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#33 /[ROOT_DIRECTORY]/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(267): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#34 /[ROOT_DIRECTORY]/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#35 /[ROOT_DIRECTORY]/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#36 /[ROOT_DIRECTORY]/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#37 /[ROOT_DIRECTORY]/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#38 /[ROOT_DIRECTORY]/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#39 /[ROOT_DIRECTORY]/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(149): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#40 /[ROOT_DIRECTORY]/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#41 /[ROOT_DIRECTORY]/public/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#42 {main}  
```

**Comment by themsaid** [comment]
Here you go:

```
Call to a member function where() on null in .../CarDocumentController.php:43
```

I don't think it's a framework issue since I can't replicate on any of my running applications, I'm closing the issue but feel free to ping me if you want.
