### ISSUE TITLE
[5.4] RuntimeException: Invalid filename provided.

### ISSUE THREAD

**Issue by diogoazevedos** [laravel/framework#16974]
- Laravel Version: 5.4
- PHP Version: 7.1
- Database Driver & Version: MySQL 5.7

### Description:

```
 [2016-12-25 15:19:06] production.ERROR: RuntimeException: Invalid filename provided. in /path/to/vendor/classpreloader/classpreloader/src/ClassPreloader.php:114
Stack trace:
#0 /path/to/vendor/laravel/framework/src/Illuminate/Foundation/Console/OptimizeCommand.php(83): ClassPreloader\ClassPreloader->getCode(false, false)
#1 /path/to/vendor/laravel/framework/src/Illuminate/Foundation/Console/OptimizeCommand.php(64): Illuminate\Foundation\Console\OptimizeCommand->compileClasses()
#2 [internal function]: Illuminate\Foundation\Console\OptimizeCommand->fire()
#3 /path/to/bootstrap/cache/compiled.php(1591): call_user_func_array(Array, Array)
#4 /path/to/vendor/laravel/framework/src/Illuminate/Support/helpers.php(897): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#5 /path/to/bootstrap/cache/compiled.php(1612): value(Object(Closure))
#6 /path/to/bootstrap/cache/compiled.php(1592): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#7 /path/to/bootstrap/cache/compiled.php(1342): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#8 /path/to/vendor/laravel/framework/src/Illuminate/Console/Command.php(182): Illuminate\Container\Container->call(Array)
#9 /path/to/vendor/symfony/console/Command/Command.php(255): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#10 /path/to/vendor/laravel/framework/src/Illuminate/Console/Command.php(167): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#11 /path/to/vendor/symfony/console/Application.php(830): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /path/to/vendor/symfony/console/Application.php(191): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Foundation\Console\OptimizeCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /path/to/vendor/symfony/console/Application.php(122): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /path/to/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /path/to/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 {main}  
````

### Steps To Reproduce:

```
$ php artisan optimize
```

**Comment by diogoazevedos** [comment]
I think this issue occurs because it can't found the file `/path/to/vendor/laravel/framework/src/Illuminate/Session/SessionInterface.php`.

**Comment by GrahamCampbell** [comment]
Thanks, but we're planning on removing class preloader out of 5.4 soon.

**Comment by GrahamCampbell** [comment]
A PR to fix this was already turned down because of this.
