### ISSUE TITLE
At least one valid recipient is required

### ISSUE THREAD

**Issue by arthurkirkosa** [laravel/framework#17277]
- Laravel Version: 5.4.0-dev
- PHP Version: 7.1
- Database Driver & Version:

### Description:
When reseting the user's password, with a default installation, using `sparkpost` the email is not sent

```
Client error: `POST https://api.sparkpost.com/api/v1/transmissions` resulted in a `400 Bad Request` response:
{ "errors": [ { "message": "At least one valid recipient is required", "code": 5002 } ] }
```

```
at Client->request('post', 'https://api.sparkpost.com/api/v1/transmissions', array('headers' => array('Authorization' => 'xxx'), 'json' => array('recipients' => array(), 'content' => array('email_rfc822' => 'Message-ID: <85c297e946da719796dee811cbc34905@swift.generated> Date: Wed, 11 Jan 2017 20:51:35 +0000 Subject: Reset Password From:
```

As you can see, the `recipients` is empty.

Am I missing something?

**Comment by Francismori7** [comment]
This also happens with notifications on a bare-bones application: 

```
[2017-01-12 22:39:42] local.ERROR: GuzzleHttp\Exception\ClientException: Client error: `POST https://api.sparkpost.com/api/v1/transmissions` resulted in a `400 Bad Request` response:
{ "errors": [ { "message": "At least one valid recipient is required", "code": 5002 } ] }
 in /home/vagrant/PhpstormProjects/TryciaCreation/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:111
Stack trace:
#0 /home/vagrant/PhpstormProjects/TryciaCreation/vendor/guzzlehttp/guzzle/src/Middleware.php(65): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
#1 /home/vagrant/PhpstormProjects/TryciaCreation/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#2 /home/vagrant/PhpstormProjects/TryciaCreation/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array)
#3 /home/vagrant/PhpstormProjects/TryciaCreation/vendor/guzzlehttp/promises/src/TaskQueue.php(47): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()
#4 /home/vagrant/PhpstormProjects/TryciaCreation/vendor/guzzlehttp/promises/src/Promise.php(246): GuzzleHttp\Promise\TaskQueue->run(true)
#5 /home/vagrant/PhpstormProjects/TryciaCreation/vendor/guzzlehttp/promises/src/Promise.php(223): GuzzleHttp\Promise\Promise->invokeWaitFn()
#6 /home/vagrant/PhpstormProjects/TryciaCreation/vendor/guzzlehttp/promises/src/Promise.php(267): GuzzleHttp\Promise\Promise->waitIfPending()
#7 /home/vagrant/PhpstormProjects/TryciaCreation/vendor/guzzlehttp/promises/src/Promise.php(225): GuzzleHttp\Promise\Promise->invokeWaitList()
#8 /home/vagrant/PhpstormProjects/TryciaCreation/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending()
#9 /home/vagrant/PhpstormProjects/TryciaCreation/vendor/guzzlehttp/guzzle/src/Client.php(129): GuzzleHttp\Promise\Promise->wait()
#10 /home/vagrant/PhpstormProjects/TryciaCreation/vendor/guzzlehttp/guzzle/src/Client.php(87): GuzzleHttp\Client->request('post', 'https://api.spa...', Array)
#11 /home/vagrant/PhpstormProjects/TryciaCreation/vendor/laravel/framework/src/Illuminate/Mail/Transport/SparkPostTransport.php(65): GuzzleHttp\Client->__call('post', Array)
#12 /home/vagrant/PhpstormProjects/TryciaCreation/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php(85): Illuminate\Mail\Transport\SparkPostTransport->send(Object(Swift_Message), Array)
#13 /home/vagrant/PhpstormProjects/TryciaCreation/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(423): Swift_Mailer->send(Object(Swift_Message), Array)
#14 /home/vagrant/PhpstormProjects/TryciaCreation/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(208): Illuminate\Mail\Mailer->sendSwiftMessage(Object(Swift_Message))
#15 /home/vagrant/PhpstormProjects/TryciaCreation/vendor/laravel/framework/src/Illuminate/Notifications/Channels/MailChannel.php(60): Illuminate\Mail\Mailer->send(Object(Illuminate\Support\HtmlString), Array, Object(Closure))
#16 /home/vagrant/PhpstormProjects/TryciaCreation/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(112): Illuminate\Notifications\Channels\MailChannel->send(Object(App\User), Object(App\Notifications\WelcomeNotification))
#17 /home/vagrant/PhpstormProjects/TryciaCreation/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(88): Illuminate\Notifications\NotificationSender->sendToNotifiable(Object(App\User), 'b62b79a9-b2fe-4...', Object(App\Notifications\WelcomeNotification), 'mail')
#18 /home/vagrant/PhpstormProjects/TryciaCreation/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(64): Illuminate\Notifications\NotificationSender->sendNow(Object(Illuminate\Database\Eloquent\Collection), Object(App\Notifications\WelcomeNotification))
#19 /home/vagrant/PhpstormProjects/TryciaCreation/vendor/laravel/framework/src/Illuminate/Notifications/ChannelManager.php(36): Illuminate\Notifications\NotificationSender->send(Object(Illuminate\Database\Eloquent\Collection), Object(App\Notifications\WelcomeNotification))
#20 /home/vagrant/PhpstormProjects/TryciaCreation/vendor/laravel/framework/src/Illuminate/Notifications/RoutesNotifications.php(18): Illuminate\Notifications\ChannelManager->send(Object(App\User), Object(App\Notifications\WelcomeNotification))
#21 /home/vagrant/PhpstormProjects/TryciaCreation/app/Listeners/SendWelcomeEmail.php(40): App\User->notify(Object(App\Notifications\WelcomeNotification))
#22 [internal function]: App\Listeners\SendWelcomeEmail->handle(Object(App\Events\UserCreatedAccount))
#23 /home/vagrant/PhpstormProjects/TryciaCreation/vendor/laravel/framework/src/Illuminate/Events/CallQueuedHandler.php(42): call_user_func_array(Array, Array)
#24 /home/vagrant/PhpstormProjects/TryciaCreation/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(62): Illuminate\Events\CallQueuedHandler->call(Object(Illuminate\Queue\Jobs\RedisJob), Array)
#25 /home/vagrant/PhpstormProjects/TryciaCreation/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(247): Illuminate\Queue\Jobs\Job->fire()
#26 /home/vagrant/PhpstormProjects/TryciaCreation/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(214): Illuminate\Queue\Worker->process('redis', Object(Illuminate\Queue\Jobs\RedisJob), Object(Illuminate\Queue\WorkerOptions))
#27 /home/vagrant/PhpstormProjects/TryciaCreation/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(175): Illuminate\Queue\Worker->runJob(Object(Illuminate\Queue\Jobs\RedisJob), 'redis', Object(Illuminate\Queue\WorkerOptions))
#28 /home/vagrant/PhpstormProjects/TryciaCreation/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(100): Illuminate\Queue\Worker->runNextJob('redis', 'default', Object(Illuminate\Queue\WorkerOptions))
#29 /home/vagrant/PhpstormProjects/TryciaCreation/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(83): Illuminate\Queue\Console\WorkCommand->runWorker('redis', 'default')
#30 [internal function]: Illuminate\Queue\Console\WorkCommand->fire()
#31 /home/vagrant/PhpstormProjects/TryciaCreation/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(28): call_user_func_array(Array, Array)
#32 /home/vagrant/PhpstormProjects/TryciaCreation/vendor/laravel/framework/src/Illuminate/Support/helpers.php(897): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#33 /home/vagrant/PhpstormProjects/TryciaCreation/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(86): value(Object(Closure))
#34 /home/vagrant/PhpstormProjects/TryciaCreation/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(30): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#35 /home/vagrant/PhpstormProjects/TryciaCreation/vendor/laravel/framework/src/Illuminate/Container/Container.php(524): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#36 /home/vagrant/PhpstormProjects/TryciaCreation/vendor/laravel/framework/src/Illuminate/Console/Command.php(182): Illuminate\Container\Container->call(Array)
#37 /home/vagrant/PhpstormProjects/TryciaCreation/vendor/symfony/console/Command/Command.php(255): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#38 /home/vagrant/PhpstormProjects/TryciaCreation/vendor/laravel/framework/src/Illuminate/Console/Command.php(167): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#39 /home/vagrant/PhpstormProjects/TryciaCreation/vendor/symfony/console/Application.php(830): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#40 /home/vagrant/PhpstormProjects/TryciaCreation/vendor/symfony/console/Application.php(191): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Queue\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#41 /home/vagrant/PhpstormProjects/TryciaCreation/vendor/symfony/console/Application.php(122): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#42 /home/vagrant/PhpstormProjects/TryciaCreation/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#43 /home/vagrant/PhpstormProjects/TryciaCreation/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#44 {main}  
```

**Comment by Francismori7** [comment]
Also, apparently, even Mailtrap gets no recipient, not only SparkPost is broken it seems:

![image](https://cloud.githubusercontent.com/assets/520647/21918360/7eddbd24-d91e-11e6-8f9c-0fcda58f383d.png)

It also appears that the default layouts are broken? @taylorotwell

**Comment by themsaid** [comment]
Thank you for reporting everyone, will take a look.

**Comment by themsaid** [comment]
Layout looks fine to me, please pull the latest commit and give it a try. As for the `to` parameter, in 5.4 the message is sent to recipients via BCC, that's why there's no `to` recipient in MailTrap, but it should work on SparkPost though!

**Comment by Francismori7** [comment]
Original error was from SparkPost, @themsaid. Layout was an issue on my side. Mailtrap works fine IMO. But SparkPost really wants a To param it seems

**Comment by themsaid** [comment]
But afaik it's completely fine to send an email to a group of addresses via BCC and not to use TO at all, it's a valid case.

**Comment by arthurkirkosa** [comment]
I'm getting the same error;

Install a fresh L5.4, add a user and try to reset the password through the forms Laravel provides.

**Comment by Francismori7** [comment]
@themsaid the RFC rules it okay, however the the API from SparkPost rules it out pretty drastically.

Can you make sure that the BCCs are being sent? Because it doesn't seem like it and I do remember something about resetting the BCC in the SparkPost driver

**Comment by Francismori7** [comment]
@themsaid https://github.com/laravel/framework/blob/5.4/src/Illuminate/Mail/Transport/SparkPostTransport.php#L53

**Comment by themsaid** [comment]
Do you know why it's set to an empty array for SparkPost?

**Comment by Francismori7** [comment]
No idea. I just think that the `getRecipients()` method down under just sets the To: to be `[]` as well because of that. SparkPost API docs state that all emails sent to someone needs to be part of recipients, either with the `header_to` param to override the To for that recipient, but also it needs to declare headers for CC and BCC to work properly. See https://support.sparkpost.com/customer/en/portal/articles/2432290-using-cc-and-bcc-with-the-rest-api?b_id=7411

The SparkPost transport needs work.

**Comment by themsaid** [comment]
@billmn can you please take a look at this?

**Comment by arthurkirkosa** [comment]
Regular `Mail::send(...)` calls work fine;

Only the `$this->notify(new ...);` stuff fails

**Comment by Francismori7** [comment]
@arthurkirkosa is right.

**Comment by themsaid** [comment]
Yeah because notifications use only `bcc`, that's the kernel of the issue :)

**Comment by billmn** [comment]
I have tried to reset password on a fresh installation of Laravel (5.3.29)  and all works fine with SparkPost service.

I have also tried to send an email (bcc) with Email:: and with notifications ... no problems here.

@arthurkirkosa Can you give me some code example?

/cc @themsaid

**Comment by Francismori7** [comment]
@billmn the issue resides in Laravel 5.4, since it changed the way notifications are sent by email. (BCC)

**Comment by billmn** [comment]
@Francismori7 I'll take a look this evening ...

**Comment by themsaid** [comment]
@billmn the thing is that in 5.4 email notifications are sent via BCC, and it looks like you set the message bcc to an empty array in your original implementation of SparkPost.

**Comment by billmn** [comment]
@themsaid BCC is set to an empty array because, using **email_rfc822**, addresses (in bcc) are visible in the email header.

I'm looking now for a fix.

**Comment by billmn** [comment]
I have made some tests and seems works fine now.

@arthurkirkosa @Francismori7 can you give me some feedback?

**Comment by arthurkirkosa** [comment]
It worked

**Comment by Francismori7** [comment]
I'll test tonight but code looks good
