### ISSUE TITLE
zero-length delimited identifier pgsql

### ISSUE THREAD

**Issue by amirmasoud** [laravel/framework#17578]
- Laravel Version: 5.4
- PHP Version: 7
- Database Driver & Version: pgsql 9.4

### Description:
`insetGetId` method returns zero length
```
local.ERROR: PDOException: SQLSTATE[42601]: Syntax error: 7 ERROR:  zero-length delimited identifier at or near """"
LINE 1: ...alues ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10) returning ""
                                                                     ^ in /vendor/laravel/framework/src/Illuminate/Database/Connection.php:323
Stack trace:
#0 /vendor/laravel/framework/src/Illuminate/Database/Connection.php(323): PDOStatement->execute()
#1 /vendor/laravel/framework/src/Illuminate/Database/Connection.php(640): Illuminate\Database\Connection->Illuminate\Database\{closure}('insert into "tr...', Array)
#2 /vendor/laravel/framework/src/Illuminate/Database/Connection.php(607): Illuminate\Database\Connection->runQueryCallback('insert into "tr...', Array, Object(Closure))
#3 /vendor/laravel/framework/src/Illuminate/Database/Connection.php(326): Illuminate\Database\Connection->run('insert into "tr...', Array, Object(Closure))
#4 /vendor/laravel/framework/src/Illuminate/Database/Connection.php(297): Illuminate\Database\Connection->select('insert into "tr...', Array, false)
#5 /vendor/laravel/framework/src/Illuminate/Database/Query/Processors/PostgresProcessor.php(20): Illuminate\Database\Connection->selectFromWriteConnection('insert into "tr...', Array)
#6 /vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2196): Illuminate\Database\Query\Processors\PostgresProcessor->processInsertGetId(Object(Illuminate\Database\Query\Builder), 'insert into "tr...', Array, NULL)
#7 /app/Repositories/TripRepository.php(74): Illuminate\Database\Query\Builder->insertGetId(Array)
```

**Comment by sisve** [comment]
You say you use Laravel 5.4; can you be more specific and include the full version number? There has been some postgresql-related fixes in 5.4.4.

**Comment by amirmasoud** [comment]
5.4.3

**Comment by amirmasoud** [comment]
Just updated to v5.4.5, problem fixed.

**Comment by tylercubell** [comment]
I updated to 5.4.5 and I'm still getting this error. I don't know if it matters but my model doesn't have a primary key.

**Comment by amirmasoud** [comment]
@tylercubell  My assumption is that  when you try `insetGetId` method you're intending to get the PK after the record inserted. I suggest to use `Model::forceCreate([...])` instead of `insertGetId` method any way.
