### ISSUE TITLE
FileSessionHandler tries to read non-existing session file

### ISSUE THREAD

**Issue by timvdalen** [laravel/framework#18258]
- Laravel Version: 5.2.45
- PHP Version: 5.6
- Database Driver & Version: MySQL PDO

### Description:

I get the following fatal error, seemingly at random, quite a lot:

```
[2017-03-08 13:16:07] local.ERROR: exception 'ErrorException' with message 'file_get_contents(/myapp/storage/framework/sessions/1ab19e392734aa1191529ab9b857b1aba94aa5c5): failed to open stream: No such file or directory' in /myapp/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:38
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'file_get_conten...', '/myapp...', 38, Array)
#1 /myapp/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(38): file_get_contents('/myapp...')
#2 /myapp/vendor/laravel/framework/src/Illuminate/Session/FileSessionHandler.php(71): Illuminate\Filesystem\Filesystem->get('/myapp...')
#3 /myapp/vendor/laravel/framework/src/Illuminate/Session/Store.php(124): Illuminate\Session\FileSessionHandler->read('1ab19e392734aa1...')
#4 /myapp/vendor/laravel/framework/src/Illuminate/Session/Store.php(108): Illuminate\Session\Store->readFromHandler()
#5 /myapp/vendor/laravel/framework/src/Illuminate/Session/Store.php(92): Illuminate\Session\Store->loadSession()
#6 /myapp/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(104): Illuminate\Session\Store->start()
#7 /myapp/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(57): Illuminate\Session\Middleware\StartSession->startSession(Object(Illuminate\Http\Request))
#8 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#9 /myapp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(136): call_user_func_array(Array, Array)
#10 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#11 /myapp/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#12 /myapp/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#13 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#14 /myapp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(136): call_user_func_array(Array, Array)
#15 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#16 /myapp/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#17 /myapp/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#18 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#19 /myapp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(136): call_user_func_array(Array, Array)
#20 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#21 /myapp/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#22 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#23 /myapp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#24 /myapp/vendor/laravel/framework/src/Illuminate/Routing/Router.php(726): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#25 /myapp/vendor/laravel/framework/src/Illuminate/Routing/Router.php(699): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#26 /myapp/vendor/laravel/framework/src/Illuminate/Routing/Router.php(675): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#27 /myapp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(246): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#28 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#29 /myapp/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#30 /myapp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(44): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#31 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#32 /myapp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(136): call_user_func_array(Array, Array)
#33 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 /myapp/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#35 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#36 /myapp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#37 /myapp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(132): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#38 /myapp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(99): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#39 /myapp/public/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#40 {main}
```

Looking at the trace, it seems like the session file was deleted between these lines: https://github.com/laravel/framework/blob/5.2/src/Illuminate/Session/FileSessionHandler.php#L69-L71
I can't figure out why that would happen.

The only thing I can think of that makes this app interesting in this regard is that there is middleware that creates a `User` for everyone that doesn't have a cookie with user id in it (and logs those that do in).

### Steps To Reproduce:

Seems to happen at random for all requests in the application.

**Comment by themsaid** [comment]
Please ask on the forums, I'm sure someone will be able to help you there. We try to keep this repo for bug reporting only.

I also recommend that you upgrade to a more recent version since 5.2 is not supported anymore, many fixes was added to the framework since that release.

**Comment by timvdalen** [comment]
I'll try to migrate to a more recent version then, but what makes you think this is not a bug in the framework?

**Comment by Yorannn** [comment]
I updated Laravel to version 5.4.15.
PHP version: 7.0.16

Although a little bit different, the error persists.

```
[2017-03-09 15:44:55] local.ERROR: exception 'ErrorException' with message 'fopen(/myapp/storage/framework/sessions/DsYiDF6umqNGGxAVyXIxWCHy9KqaT1H1nIFNlgfH): failed to open stream: No such file or directory' in /myapp/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:54
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'fopen(/home/tim...', '/myapp...', 54, Array)
#1 /myapp/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(54): fopen('/myapp...', 'rb')
#2 /myapp/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(38): Illuminate\Filesystem\Filesystem->sharedGet('/myapp...')
#3 /myapp/vendor/laravel/framework/src/Illuminate/Session/FileSessionHandler.php(71): Illuminate\Filesystem\Filesystem->get('/myapp...', true)
#4 /myapp/vendor/laravel/framework/src/Illuminate/Session/Store.php(96): Illuminate\Session\FileSessionHandler->read('DsYiDF6umqNGGxA...')
#5 /myapp/vendor/laravel/framework/src/Illuminate/Session/Store.php(86): Illuminate\Session\Store->readFromHandler()
#6 /myapp/vendor/laravel/framework/src/Illuminate/Session/Store.php(70): Illuminate\Session\Store->loadSession()
#7 /myapp/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(103): Illuminate\Session\Store->start()
#8 /myapp/vendor/laravel/framework/src/Illuminate/Support/helpers.php(878): Illuminate\Session\Middleware\StartSession->Illuminate\Session\Middleware\{closure}(Object(Illuminate\Session\Store))
#9 /myapp/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(104): tap(Object(Illuminate\Session\Store), Object(Closure))
#10 /myapp/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(58): Illuminate\Session\Middleware\StartSession->startSession(Object(Illuminate\Http\Request))
#11 /myapp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#12 /myapp/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#13 /myapp/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#14 /myapp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#15 /myapp/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#16 /myapp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#17 /myapp/vendor/laravel/framework/src/Illuminate/Routing/Router.php(561): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#18 /myapp/vendor/laravel/framework/src/Illuminate/Routing/Router.php(520): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#19 /myapp/vendor/laravel/framework/src/Illuminate/Routing/Router.php(498): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#20 /myapp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(174): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#21 /myapp/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#22 /myapp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#23 /myapp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#24 /myapp/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#25 /myapp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#26 /myapp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(149): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#27 /myapp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#28 /myapp/public/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#29 {main}  
```
