### ISSUE TITLE
FileSessionHandler tries to read non-existing session file

### ISSUE THREAD

**Issue by Yorannn** [laravel/framework#18282]
- Laravel Version: 5.4.15
- PHP Version: 7.0.16
- Database Driver & Version: MySQL PDO

### Description:

As described earlier here: https://github.com/laravel/framework/issues/18258

I have updated Laravel and PHP but the issue persists.

```
[2017-03-09 15:44:55] local.ERROR: exception 'ErrorException' with message 'fopen(/myapp/storage/framework/sessions/DsYiDF6umqNGGxAVyXIxWCHy9KqaT1H1nIFNlgfH): failed to open stream: No such file or directory' in /myapp/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:54
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'fopen(/myapp...', '/myapp...', 54, Array)
#1 /myapp/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(54): fopen('/myapp...', 'rb')
#2 /myapp/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(38): Illuminate\Filesystem\Filesystem->sharedGet('/myapp...')
#3 /myapp/vendor/laravel/framework/src/Illuminate/Session/FileSessionHandler.php(71): Illuminate\Filesystem\Filesystem->get('/myapp...', true)
#4 /myapp/vendor/laravel/framework/src/Illuminate/Session/Store.php(96): Illuminate\Session\FileSessionHandler->read('DsYiDF6umqNGGxA...')
#5 /myapp/vendor/laravel/framework/src/Illuminate/Session/Store.php(86): Illuminate\Session\Store->readFromHandler()
#6 /myapp/vendor/laravel/framework/src/Illuminate/Session/Store.php(70): Illuminate\Session\Store->loadSession()
#7 /myapp/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(103): Illuminate\Session\Store->start()
#8 /myapp/vendor/laravel/framework/src/Illuminate/Support/helpers.php(878): Illuminate\Session\Middleware\StartSession->Illuminate\Session\Middleware\{closure}(Object(Illuminate\Session\Store))
#9 /myapp/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(104): tap(Object(Illuminate\Session\Store), Object(Closure))
#10 /myapp/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(58): Illuminate\Session\Middleware\StartSession->startSession(Object(Illuminate\Http\Request))
#11 /myapp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#12 /myapp/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#13 /myapp/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#14 /myapp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#15 /myapp/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#16 /myapp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#17 /myapp/vendor/laravel/framework/src/Illuminate/Routing/Router.php(561): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#18 /myapp/vendor/laravel/framework/src/Illuminate/Routing/Router.php(520): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#19 /myapp/vendor/laravel/framework/src/Illuminate/Routing/Router.php(498): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#20 /myapp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(174): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#21 /myapp/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#22 /myapp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#23 /myapp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#24 /myapp/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#25 /myapp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#26 /myapp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(149): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#27 /myapp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#28 /myapp/public/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#29 {main}  
```

### Steps To Reproduce:

Seems to happen at random for all requests in the application.

**Comment by themsaid** [comment]
Again, Please ask on the forums :) You'll need to include more details about your setup so people can help, using load balancers? What's the OS? etc...

**Comment by themsaid** [comment]
I'm sorry but really these type of issues that happen "randomly" aren't considered as bugs in the framework, there could be several reasons for why they happen and it's nearly impossible for the contributors to find out what's wrong in your environment.
