### ISSUE TITLE
Cross Env on Windows (Possibly Other Platforms?)

### ISSUE THREAD

**Issue by lloy0076** [laravel/framework#18363]
- Laravel Version: v5.4.15 (according to `composer info`)
- PHP Version: 	php-7.1.1-nts-Win32-VC14-x64
- Database Driver & Version:

N/A

### Description:

Scripts contain:

`"dev": "node node_modules/cross-env/dist/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js # more options`

I notice that https://github.com/laravel/laravel/blob/master/package.json has:

```
  "devDependencies": {
    "axios": "^0.15.3",
    "bootstrap-sass": "^3.3.7",
    "cross-env": "^3.2.3",
    "jquery": "^3.1.1",
    "laravel-mix": "^0.8.3",
    "lodash": "^4.17.4",
    "vue": "^2.1.10"
}
```

But when I updated (with yarn) I see:

```
  "devDependencies": {
    "axios": "^0.15.3",
    "bootstrap-sass": "^3.3.7",
    "cross-env": "^3.2.4",
    "jquery": "^3.1.1",
    "laravel-mix": "^0.8.1",
    "lodash": "^4.17.4",
    "vue": "^2.1.10"
  }
```

It seems that cross-env.js has "moved" to:

`"dev": "node node_modules/cross-env/dist/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js # more options`

i.e. there's a `dist` directory!

### Steps To Reproduce:

1. Find a Windows 10 system - I use a setup by "http://www.laragon.org" but I suspect any Windows 10 system with "nodejs" and either "npm" or "yarn" would do this;
2. Run `npm run dev` (or one of the other scripts)
3. See result below.

```
c:\laragon\www\drakes-auth (master)
λ npm run dev

> @ dev c:\laragon\www\drakes-auth
> node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

module.js:471
    throw err;
    ^

Error: Cannot find module 'c:\laragon\www\drakes-auth\node_modules\cross-env\bin\cross-env.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\laragon\\bin\\nodejs\\node.exe" "C:\\laragon\\bin\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! @ dev: `node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ dev script 'node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     c:\laragon\www\drakes-auth\npm-debug.log

[composer_package_json.zip](https://github.com/laravel/framework/files/845980/composer_package_json.zip)
```

### How I Fixed It

1. Insert `dist` so that `cross-env.js` can be found.

*Note:* The attached package.json _already_ has the fixes...

**Comment by themsaid** [comment]
Update your package.json to reflect the changes in https://github.com/laravel/laravel/blob/master/package.json

Notice that we now use `cross-env NODE_ENV=development` instead of the absolute path.

**Comment by slavicd** [comment]
cross-env invoked without a path only works if it's installed globally. This does not work with 5.4

**Comment by f0rtis** [comment]
@slavicd +1. Same issue from WIndows 10.
