### ISSUE TITLE
SesException in Queued Notifications doesn't result in a failed job?

### ISSUE THREAD

**Issue by broadstreetboy** [laravel/framework#18449]
- Laravel Version: 5.4
- PHP Version: 7.1
- Queue Driver: Redis
- Mail Driver: AWS SES
- Database: MySQL 

### Description:

Today we found emails not being sent for a period of time.  Why? The log files show errors like the one below where the server was unable connect to AWS for a period of time. 

```[2017-03-21 18:19:23] production.ERROR: exception 'Aws\Ses\Exception\SesException' with message 'Error executing "SendRawEmail" on "https://email.us-east-1.amazonaws.com"; AWS HTTP error: cURL error 6: Could not resolve host: email.us-east-1.amazonaws.com (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)'

GuzzleHttp\Exception\ConnectException: cURL error 6: Could not resolve host: email.us-east-1.amazonaws.com (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) in /home/domain.com/storage/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:186
Stack trace:
#0 /home/domain.com/storage/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(150): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
#1 /home/domain.com/storage/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(103): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlMultiHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#2 /home/domain.com/storage/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(179): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlMultiHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#3 /home/domain.com/storage/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(108): GuzzleHttp\Handler\CurlMultiHandler->processMessages()
#4 /home/domain.com/storage/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(123): GuzzleHttp\Handler\CurlMultiHandler->tick()
#5 /home/domain.com/storage/vendor/guzzlehttp/promises/src/Promise.php(246): GuzzleHttp\Handler\CurlMultiHandler->execute(true)
#6 /home/domain.com/storage/vendor/guzzlehttp/promises/src/Promise.php(223): GuzzleHttp\Promise\Promise->invokeWaitFn()
#7 /home/domain.com/storage/vendor/guzzlehttp/promises/src/Promise.php(267): GuzzleHttp\Promise\Promise->waitIfPending()
#8 /home/domain.com/storage/vendor/guzzlehttp/promises/src/Promise.php(225): GuzzleHttp\Promise\Promise->invokeWaitList()
#9 /home/domain.com/storage/vendor/guzzlehttp/promises/src/Promise.php(267): GuzzleHttp\Promise\Promise->waitIfPending()
#10 /home/domain.com/storage/vendor/guzzlehttp/promises/src/Promise.php(225): GuzzleHttp\Promise\Promise->invokeWaitList()
#11 /home/domain.com/storage/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending()
#12 /home/domain.com/storage/vendor/aws/aws-sdk-php/src/AwsClientTrait.php(59): GuzzleHttp\Promise\Promise->wait()
#13 /home/domain.com/storage/vendor/aws/aws-sdk-php/src/AwsClientTrait.php(78): Aws\AwsClient->execute(Object(Aws\Command))
#14 /home/domain.com/storage/vendor/laravel/framework/src/Illuminate/Mail/Transport/SesTransport.php(40): Aws\AwsClient->__call('sendRawEmail', Array)
#15 /home/domain.com/storage/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php(85): Illuminate\Mail\Transport\SesTransport->send(Object(Swift_Message), Array)
#16 /home/domain.com/storage/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(423): Swift_Mailer->send(Object(Swift_Message), Array)
#17 /home/domain.com/storage/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(208): Illuminate\Mail\Mailer->sendSwiftMessage(Object(Swift_Message))
#18 /home/domain.com/storage/vendor/laravel/framework/src/Illuminate/Notifications/Channels/MailChannel.php(60): Illuminate\Mail\Mailer->send('layouts.email', Array, Object(Closure))
```

In our case we have a controller that fires a queued user notification:

``` 
$user->notify(new OurNotification($data));
```

```
class OurNotification extends Notification
{
    use Queueable;
}
```

In turn this builds and attempts to send the ``Illuminate\Notifications\Messages\MailMessage`` which was recently introduced.

---

What's odd though is that despite us catching the error, there were no failed jobs found in the database.  The emails were not sent.  A SesException was thrown however it didn't seem to result in a job failure -- so we were not notified.

Is there anything I am doing wrong or should Laravel catch this exception, retry perhaps and cause the job to fail?  I need to implement a solution ASAP to prevent again so would appreciate any guidance from others before I go down any route.

### Steps To Reproduce:

Read above.

**Comment by snsanich** [comment]
Looks like you have problem with network. Could you test your accessibility to email.us-east-1.amazonaws.com? Try `ping email.us-east-1.amazonaws.com`, than run aws command in cli to check email service.

**Comment by broadstreetboy** [comment]
@snsanich Yes - you are correct.  There was a temporary network issues connecting to AWS but all is good now.  No dispute about that.

The question is: why would this not result in a failed job since an exception was thrown?  This is using the laravel notification system and the default AWS package.

**Comment by snsanich** [comment]
To answer the question above, it is necessary to reproduce your environment.
It will be great if you provide something like docker image, vagrant config or ansible config to run your environment 

In other case, php info and all extensions' info might help.

**Comment by themsaid** [comment]
What's the maximum tries set for the job?

**Comment by themsaid** [comment]
That's because the job fails while being queued not while running, when you dispatch the job it failed to communicate with Amazon and threw the exception, a job is considered failed only when it fails while running.
