### ISSUE TITLE
Call to a member function beginTransaction() on null error

### ISSUE THREAD

**Issue by chadidi** [laravel/framework#18852]
- Laravel Version: 5.4.19
- PHP Version: 7
- Database Driver & Version: `MySql v5.7.17-0ubuntu0.16.04.2`
### Description:
i get an error printed a lot of times every minute to `laravel.log` file and if i let it print the file will became 10 Gigabytes within 1 day. this is my [laravel.log](https://gist.github.com/chadidi/b14b5fb861caf8a279efe684d4213068) after clean it up within 1 minute .
_**sorry for my english**_

**Comment by m1guelpf** [comment]
```
[2017-04-18 14:42:50] production.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function beginTransaction() on null in /var/www/fevrok.com/vendor/laravel/framework/src/Illuminate/Database/Concerns/ManagesTransactions.php:108
Stack trace:
#0 /var/www/fevrok.com/vendor/laravel/framework/src/Illuminate/Database/Concerns/ManagesTransactions.php(92): Illuminate\Database\Connection->createTransaction()
#1 /var/www/fevrok.com/vendor/laravel/framework/src/Illuminate/Queue/DatabaseQueue.php(192): Illuminate\Database\Connection->beginTransaction()
#2 /var/www/fevrok.com/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(236): Illuminate\Queue\DatabaseQueue->pop('default')
#3 /var/www/fevrok.com/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(101): Illuminate\Queue\Worker->getNextJob(Object(Illuminate\Queue\DatabaseQueue), 'default')
#4 /var/www/fevrok.com/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(100): Illuminate\Queue\Worker->daemon('database', 'default', Object(Illuminate\Queue\WorkerOptions))
#5 /var/www/fevrok.com/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(83): Illuminate\Queue\Console\WorkCommand->runWorker('database', 'default')
#6 [internal function]: Illuminate\Queue\Console\WorkCommand->fire()
#7 /var/www/fevrok.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#8 /var/www/fevrok.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#9 /var/www/fevrok.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#10 /var/www/fevrok.com/vendor/laravel/framework/src/Illuminate/Container/Container.php(531): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#11 /var/www/fevrok.com/vendor/laravel/framework/src/Illuminate/Console/Command.php(182): Illuminate\Container\Container->call(Array)
#12 /var/www/fevrok.com/vendor/symfony/console/Command/Command.php(265): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#13 /var/www/fevrok.com/vendor/laravel/framework/src/Illuminate/Console/Command.php(167): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#14 /var/www/fevrok.com/vendor/symfony/console/Application.php(826): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /var/www/fevrok.com/vendor/symfony/console/Application.php(189): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Queue\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /var/www/fevrok.com/vendor/symfony/console/Application.php(120): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /var/www/fevrok.com/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(123): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /var/www/fevrok.com/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 {main}
```

**Comment by chadidi** [comment]
The error has been fixed after restarting the server so the error comes from the server but I want to know why this error occurred so that I do not drop in the same error again or to fix it if there is a way without restarting

**Comment by m1guelpf** [comment]
@chadidi It seems to be related with MySQL being killed to free memory...
See [this Laracasts thread](https://laracasts.com/discuss/channels/laravel/productionerror-call-to-a-member-function-begintransaction-on-null)

**Comment by chadidi** [comment]
@m1guelpf in my case it happened because I deleted PHP logs folder/files so when I restarted my server apache failed to start because logs files not exist, so if anyone has the same problem Just check if you can restart your apache/Nginx server if not then that's the problem.
and it's could be something else like MySQL as you said.

**Comment by Ravaelles** [comment]
I got this error using MongoDb with jenssegers package. This part of config fixed it:
https://github.com/jenssegers/laravel-mongodb#queues
