### ISSUE TITLE
Database driver does not support attribute renaming a column

### ISSUE THREAD

**Issue by MarioPerezEsteso** [laravel/framework#18865]
- Laravel Version: 5.4.19 and 5.3.31
- PHP Version: 7.0.16-3
- Database Driver & Version: Database SQL Server 12.0.2000.8 with driver sqlsrv.
- OS: Ubuntu 16.04

### Description:

I am not able to execute a migration with a `renameColumn` with versions 5.3 and 5.4, but it works with Laravel 5.2.

### Steps To Reproduce:

I have added **doctrine/dbal v2.5.12** as a Composer dependency but when I run `php artisan migrate` it throws the following error:

```
  [PDOException]
  SQLSTATE[IM001]: Driver does not support this function: driver does not support that attribute
```

The migration that I want to execute is:

```
    public function up()
    {
        Schema::table('posts', function (Blueprint $table) {
            $table->renameColumn('content', 'body');
        });
    }

    public function down()
    {
        Schema::table('posts', function (Blueprint $table) {
            $table->renameColumn('body', 'content');
        });
    }
```

I am using the PHP extensions **pdo_sqlsrv 4.0.8.0** and **sqlsrv 4.0.8.0**.

As I said in the description, this migration works with Laravel 5.2 but it fails with 5.3 and 5.4.

This is the log:

```
[2017-04-19 12:26:40] local.ERROR: PDOException: SQLSTATE[IM001]: Driver does not support this function: driver does not support that attribute in /data/laravelrepo/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:68
Stack trace:
#0 /data/laravelrepo/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(68): PDO->getAttribute(4)
#1 /data/laravelrepo/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(436): Doctrine\DBAL\Driver\PDOConnection->getServerVersion()
#2 /data/laravelrepo/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(389): Doctrine\DBAL\Connection->getDatabasePlatformVersion()
#3 /data/laravelrepo/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(328): Doctrine\DBAL\Connection->detectDatabasePlatform()
#4 /data/laravelrepo/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/AbstractSchemaManager.php(64): Doctrine\DBAL\Connection->getDatabasePlatform()
#5 /data/laravelrepo/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractSQLServerDriver.php(102): Doctrine\DBAL\Schema\AbstractSchemaManager->__construct(Object(Doctrine\DBAL\Connection))
#6 /data/laravelrepo/vendor/laravel/framework/src/Illuminate/Database/Connection.php(853): Doctrine\DBAL\Driver\AbstractSQLServerDriver->getSchemaManager(Object(Doctrine\DBAL\Connection))
#7 /data/laravelrepo/vendor/laravel/framework/src/Illuminate/Database/Connection.php(841): Illuminate\Database\Connection->getDoctrineSchemaManager()
#8 /data/laravelrepo/vendor/laravel/framework/src/Illuminate/Database/Schema/Grammars/RenameColumn.php(26): Illuminate\Database\Connection->getDoctrineColumn('posts', 'content')
#9 /data/laravelrepo/vendor/laravel/framework/src/Illuminate/Database/Schema/Grammars/Grammar.php(32): Illuminate\Database\Schema\Grammars\RenameColumn::compile(Object(Illuminate\Database\Schema\Grammars\SqlServerGrammar), Object(Illuminate\Database\Schema\Blueprint), Object(Illuminate\Support\Fluent), Object(Illuminate\Database\SqlServerConnection))
#10 /data/laravelrepo/vendor/laravel/framework/src/Illuminate/Database/Schema/Blueprint.php(107): Illuminate\Database\Schema\Grammars\Grammar->compileRenameColumn(Object(Illuminate\Database\Schema\Blueprint), Object(Illuminate\Support\Fluent), Object(Illuminate\Database\SqlServerConnection))
#11 /data/laravelrepo/vendor/laravel/framework/src/Illuminate/Database/Schema/Blueprint.php(82): Illuminate\Database\Schema\Blueprint->toSql(Object(Illuminate\Database\SqlServerConnection), Object(Illuminate\Database\Schema\Grammars\SqlServerGrammar))
#12 /data/laravelrepo/vendor/laravel/framework/src/Illuminate/Database/Schema/Builder.php(239): Illuminate\Database\Schema\Blueprint->build(Object(Illuminate\Database\SqlServerConnection), Object(Illuminate\Database\Schema\Grammars\SqlServerGrammar))
#13 /data/laravelrepo/vendor/laravel/framework/src/Illuminate/Database/Schema/Builder.php(148): Illuminate\Database\Schema\Builder->build(Object(Illuminate\Database\Schema\Blueprint))
#14 /data/laravelrepo/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(221): Illuminate\Database\Schema\Builder->table('posts', Object(Closure))
#15 /data/laravelrepo/database/migrations/2017_04_19_120309_rename_column_content_posts_table.php(18): Illuminate\Support\Facades\Facade::__callStatic('table', Array)
#16 /data/laravelrepo/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(353): RenameColumnContentPostsTable->up()
#17 /data/laravelrepo/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(359): Illuminate\Database\Migrations\Migrator->Illuminate\Database\Migrations\{closure}()
#18 /data/laravelrepo/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(177): Illuminate\Database\Migrations\Migrator->runMigration(Object(RenameColumnContentPostsTable), 'up')
#19 /data/laravelrepo/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(146): Illuminate\Database\Migrations\Migrator->runUp('/data/laravelrepo...', 3, false)
#20 /data/laravelrepo/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(95): Illuminate\Database\Migrations\Migrator->runPending(Array, Array)
#21 /data/laravelrepo/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(69): Illuminate\Database\Migrations\Migrator->run(Array, Array)
#22 [internal function]: Illuminate\Database\Console\Migrations\MigrateCommand->fire()
#23 /data/laravelrepo/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#24 /data/laravelrepo/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#25 /data/laravelrepo/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#26 /data/laravelrepo/vendor/laravel/framework/src/Illuminate/Container/Container.php(531): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#27 /data/laravelrepo/vendor/laravel/framework/src/Illuminate/Console/Command.php(182): Illuminate\Container\Container->call(Array)
#28 /data/laravelrepo/vendor/symfony/console/Command/Command.php(262): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#29 /data/laravelrepo/vendor/laravel/framework/src/Illuminate/Console/Command.php(167): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#30 /data/laravelrepo/vendor/symfony/console/Application.php(826): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#31 /data/laravelrepo/vendor/symfony/console/Application.php(190): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Database\Console\Migrations\MigrateCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#32 /data/laravelrepo/vendor/symfony/console/Application.php(121): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#33 /data/laravelrepo/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(123): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#34 /data/laravelrepo/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#35 {main}  
```

**Comment by themsaid** [comment]
Sorry but this doesn't look like an issue with laravel core.

**Comment by ruudy-es** [comment]
An option could be to do it raw:

`DB::statement("sp_rename 'pay_subscriptions.account_type', 'name', 'COLUMN'");`
