### ISSUE TITLE
Error Call to undefined method Illuminate\View\Factory::getLastLoop()

### ISSUE THREAD

**Issue by alfonsobries** [laravel/framework#19075]
- Laravel Version: 5.4 updated from 5.3
- PHP Version: 7.1

### Description:
i constantly having this error when sending email notification with the notification template, i updated from laravel 5.3 to laravel 5.4, 

I know there is a common problem with the "getFirstLoop" (not getLastLoop) function, (actually it's documented in the upgrade guide) and fixs when running:

```
php artisan cache:clear
php artisan view:clear
```

Actually this instruction fix the problem momentanially and the email message sends again but sooner or later the problem appears again, seems that once the view is recompiled the problem appears again

Any idea?

Here is the full trace:

```

Next ErrorException: Call to undefined method Illuminate\View\Factory::getLastLoop() (View: /home/..../resources/views/vendor/notifications/email.blade.php) in /home/..../storage/framework/views/a311e2ff016c0b061744817e6e96ac50251a8ecd.php:103
Stack trace:
#0 /home/..../vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(46): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(Symfony\Component\Debug\Exception\FatalThrowableError), 0)
#1 /home/..../vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(59): Illuminate\View\Engines\PhpEngine->evaluatePath('/home/micochini...', Array)
#2 /home/..../vendor/laravel/framework/src/Illuminate/View/View.php(149): Illuminate\View\Engines\CompilerEngine->get('/home/micochini...', Array)
#3 /home/..../vendor/laravel/framework/src/Illuminate/View/View.php(120): Illuminate\View\View->getContents()
#4 /home/..../vendor/laravel/framework/src/Illuminate/View/View.php(85): Illuminate\View\View->renderContents()
#5 /home/..../vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(458): Illuminate\View\View->render()
#6 /home/..../vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(331): Illuminate\Mail\Mailer->getView('notifications::...', Array)
#7 /home/..../vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(205): Illuminate\Mail\Mailer->addContent(Object(Illuminate\Mail\Message), 'notifications::...', 'notifications::...', NULL, Array)
#8 /home/..../vendor/laravel/framework/src/Illuminate/Notifications/Channels/MailChannel.php(85): Illuminate\Mail\Mailer->send('notifications::...', Array, Object(Closure))
#9 /home/..../vendor/laravel/framework/src/Illuminate/Notifications/ChannelManager.php(79): Illuminate\Notifications\Channels\MailChannel->send(Object(App\Models\User), Object(App\Notifications\AccountActivationNotification))
#10 /home/..../vendor/laravel/framework/src/Illuminate/Notifications/ChannelManager.php(43): Illuminate\Notifications\ChannelManager->sendNow(Object(Illuminate\Database\Eloquent\Collection), Object(App\Notifications\AccountActivationNotification))
#11 /home/..../vendor/laravel/framework/src/Illuminate/Notifications/RoutesNotifications.php(18): Illuminate\Notifications\ChannelManager->send(Object(Illuminate\Database\Eloquent\Collection), Object(App\Notifications\AccountActivationNotification))
#12 /home/..../app/Models/User.php(315): App\Models\User->notify(Object(App\Notifications\AccountActivationNotification))
#13 /home/..../app/Jobs/SendAccountActivationNotification.php(39): App\Models\User->sendAccountActivactionNotification('38fa0d84d184017...')
#14 [internal function]: App\Jobs\SendAccountActivationNotification->handle()
#15 /home/..../vendor/laravel/framework/src/Illuminate/Container/Container.php(508): call_user_func_array(Array, Array)
#16 /home/..../vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\Container\Container->call(Array)
#17 /home/..../vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(App\Jobs\SendAccountActivationNotification))
#18 /home/..../vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(App\Jobs\SendAccountActivationNotification))
#19 /home/..../vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#20 /home/..../vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(47): Illuminate\Bus\Dispatcher->dispatchNow(Object(App\Jobs\SendAccountActivationNotification), false)
#21 /home/..../vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(73): Illuminate\Queue\CallQueuedHandler->call(Object(Illuminate\Queue\Jobs\DatabaseJob), Array)
#22 /home/..../vendor/laravel/framework/src/Illuminate/Queue/Worker.php(203): Illuminate\Queue\Jobs\Job->fire()
#23 /home/..../vendor/laravel/framework/src/Illuminate/Queue/Worker.php(152): Illuminate\Queue\Worker->process('database', Object(Illuminate\Queue\Jobs\DatabaseJob), Object(Illuminate\Queue\WorkerOptions))
#24 /home/..../vendor/laravel/framework/src/Illuminate/Queue/Worker.php(75): Illuminate\Queue\Worker->runNextJob('database', 'default', Object(Illuminate\Queue\WorkerOptions))
#25 /home/..../vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(100): Illuminate\Queue\Worker->daemon('database', 'default', Object(Illuminate\Queue\WorkerOptions))
#26 /home/..../vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(83): Illuminate\Queue\Console\WorkCommand->runWorker('database', 'default')
#27 [internal function]: Illuminate\Queue\Console\WorkCommand->fire()
#28 /home/..../vendor/laravel/framework/src/Illuminate/Container/Container.php(508): call_user_func_array(Array, Array)
#29 /home/..../vendor/laravel/framework/src/Illuminate/Console/Command.php(169): Illuminate\Container\Container->call(Array)
#30 /home/..../vendor/symfony/console/Command/Command.php(261): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#31 /home/..../vendor/laravel/framework/src/Illuminate/Console/Command.php(155): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#32 /home/..../vendor/symfony/console/Application.php(817): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#33 /home/..../vendor/symfony/console/Application.php(185): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Queue\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#34 /home/..../vendor/symfony/console/Application.php(116): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#35 /home/..../vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#36 /home/..../artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#37 {main}, 2017-05-05 17:15:52)) in /home/..../vendor/laravel/framework/src/Illuminate/Database/Connection.php:770
```

### Steps To Reproduce:

seems than in the email notification template (created in the version 5.3) has the loop the related with the error in the compiled view
resources/views/vendor/notifications/email.blade.php

```
@foreach ($introLines as $line)
<p style="{{ $style['paragraph'] }}">
 {!! $line !!}
</p>
@endforeach
```

**Comment by themsaid** [comment]
Looks like a caching issue to me, closing since mail sending appears to be working fine, we haven't seen similar reports since the release.

**Comment by zahirzohair** [comment]
[ErrorException]
  count(): Parameter must be an array or an object that implements Countable
i got the same error when trying to install composer. 
"php": ">=5.5.9",
"laravel/framework": "5.3.*",
when i run the app on browser i get this error : 
Call to undefined method Illuminate\View\Factory::getLastLoop()

any solution please ?
