### ISSUE TITLE
Segmentation fault on db:seed

### ISSUE THREAD

**Issue by mistre83** [laravel/framework#19176]
- Laravel Version: 5.3.31
- PHP Version: 7.1.3-3+deb.sury.org~xenial+1 (cli) (built: Mar 25 2017 14:00:03) ( NTS )

Hi,
since saturday i was running my seeder many times. This week i did run` composer update` (i dont remember what library has been updated). Now, my seeder have a `Segmentation fault`.

My seeder read a csv and then compute some operation and perform some insert.
I did tried to exclude all insert statements (so now, seeder perform only selects - using MyModel::find and so on).

Because the seeder take some time, i have a progress bar on it (i tried to disable it, just to see if this was the problem, but isnt...). This is the result:

**- Seeder with insert and select: Segmentation fault at 23%
- Seeder with just select: Segmentation fault at 50%**

So, i think the problem is something about PDO or something similar, but i really cant understand what can be wrong. The seeder dont have recursion, i just read a CSV line and perform a select.

**I tried to run seeder across different machines, but the result is always the same**:

Machine 1:
Ubuntu, PHP 7.1, Homestead, MySQL

Machine 2:
Mac OSX, PHP 7.1, Valet, MariaDB

With many diffucult, i have done a core dump (but.. i think is very incomplete... i dont know how to generate a readable core dump). This is the stack:

```
GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.04) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from php...(no debugging symbols found)...done.

warning: core file may not match specified executable file.
[New LWP 2913]

warning: Unexpected size of section `.reg-xstate/2913' in core file.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `php artisan db:seed'.
Program terminated with signal SIGSEGV, Segmentation fault.

warning: Unexpected size of section `.reg-xstate/2913' in core file.
#0  0x000055f02902e6c4 in _emalloc ()
(gdb) 

(gdb) bt
#0  0x000055f02902e6c4 in _emalloc ()
#1  0x00007f6a709a3fb1 in ?? () from /usr/lib/php/20160303/mysqlnd.so
#2  0x00007f6a709ab531 in ?? () from /usr/lib/php/20160303/mysqlnd.so
#3  0x00007f6a66259cb8 in ?? () from /usr/lib/php/20160303/pdo_mysql.so
#4  0x00007f6a707751b0 in ?? () from /usr/lib/php/20160303/pdo.so
#5  0x000055f0290f6f2c in ?? ()
#6  0x000055f02909e79b in execute_ex ()
#7  0x000055f0290f746a in ?? ()
#8  0x000055f02909e79b in execute_ex ()
#9  0x000055f0290f6ffe in ?? ()
#10 0x000055f02909e79b in execute_ex ()
#11 0x000055f0290f6ffe in ?? ()
#12 0x000055f02909e79b in execute_ex ()
#13 0x000055f0290f6ffe in ?? ()
#14 0x000055f02909e79b in execute_ex ()
#15 0x000055f0290f6ffe in ?? ()
#16 0x000055f02909e79b in execute_ex ()
#17 0x000055f0290f6ffe in ?? ()
#18 0x000055f02909e79b in execute_ex ()
#19 0x000055f0290f6ffe in ?? ()
#20 0x000055f02909e79b in execute_ex ()
#21 0x000055f0290f6ffe in ?? ()
#22 0x000055f02909e79b in execute_ex ()
#23 0x000055f0290f6ffe in ?? ()
#24 0x000055f02909e79b in execute_ex ()
#25 0x000055f0290f6ffe in ?? ()
#26 0x000055f02909e79b in execute_ex ()
#27 0x000055f0290f6ffe in ?? ()
#28 0x000055f02909e79b in execute_ex ()
#29 0x000055f0290f746a in ?? ()
#30 0x000055f02909e79b in execute_ex ()
#31 0x000055f0290f746a in ?? ()
#32 0x000055f02909e79b in execute_ex ()
#33 0x000055f0290f746a in ?? ()
#34 0x000055f02909e79b in execute_ex ()
#35 0x000055f0290f746a in ?? ()
#36 0x000055f02909e79b in execute_ex ()
#37 0x000055f0290f6ffe in ?? ()
#38 0x000055f02909e79b in execute_ex ()
#39 0x000055f0290f746a in ?? ()
#40 0x000055f02909e79b in execute_ex ()
#41 0x000055f029044d6b in zend_call_function ()
#42 0x000055f028f8be8b in zif_call_user_func_array ()
#43 0x000055f0290f6f2c in ?? ()
#44 0x000055f02909e79b in execute_ex ()
#45 0x000055f0290f6ffe in ?? ()
#46 0x000055f02909e79b in execute_ex ()
#47 0x000055f0290f6ffe in ?? ()
#48 0x000055f02909e79b in execute_ex ()
#49 0x000055f0290f6ffe in ?? ()
#50 0x000055f02909e79b in execute_ex ()
#51 0x000055f0290f6ffe in ?? ()
#52 0x000055f02909e79b in execute_ex ()
#53 0x000055f0290f6ffe in ?? ()
#54 0x000055f02909e79b in execute_ex ()
#55 0x000055f0290f6ffe in ?? ()
#56 0x000055f02909e79b in execute_ex ()

```

**Comment by sisve** [comment]
Core dumps has best effect with php versions compiled for debugging. There are more instructions at https://bugs.php.net/bugs-generating-backtrace.php

This is probably a fault in PHP. Your next steps are usually something like ...

1. Try upgrading to the latest version of PHP 7.1 (currently 7.1.5).
2. Try compiling and using the latest PHP version for source code (with debug symbols!)
3. Reduce your code sample to the smallest possible code to reproduce the issue.
4. File a bug report with the PHP guys.

Relevant: https://secure.php.net/manual/en/install.problems.bugs.php

**Comment by Dylan-DPC** [comment]
Can you share the code you tried?

**Comment by themsaid** [comment]
Please ask on the forums
