### ISSUE TITLE
queue:work asks for Redis, but my queue driver is database

### ISSUE THREAD

**Issue by chimit** [laravel/framework#19458]
- Laravel Version: 5.4
- PHP Version: 5.7
- Database Driver & Version: MySQL 5.7

### Description:

Everytime I try to run `php artisan queue:work` I get an error:

```
[Predis\Connection\ConnectionException]
Connection refused [tcp://127.0.0.1:6379]
```

But I use database as a queue driver, not Redis:

**.env**
```
CACHE_DRIVER=redis
QUEUE_DRIVER=database

REDIS_HOST=192.168.10.10
REDIS_PORT=6379
```
But php artisan `queue:listen` works without problems.

**Comment by themsaid** [comment]
The Queue system uses the Cache store to keep some values, so you need to make sure the connection is correct as well and the correct driver is used.

**Comment by sisve** [comment]
I'm not sure that @themsaid is correct on this one. I don't know of any place in the queue system where the cache is used. Also, it doesn't make sense that `queue:listen` works, but not `queue:work`. The error message indicates another address than the configured REDIS_HOST.

@chimit, can you share a full stack trace of the problem? Does the error still occur if you rebuild your cached configuration file with `php artisan config:cache`?

**Comment by chimit** [comment]
@sisve sorry, apparently I posted an error message after commenting out
```
REDIS_HOST=192.168.10.10
REDIS_PORT=6379
```
So the IP mismatch is my mistake.

If I comment out `CACHE_DRIVER=redis` it throws a Memcache error:
```
[Symfony\Component\Debug\Exception\FatalThrowableError]  
Class 'Memcached' not found 
```
So it looks like cache is really required for queues. But in the whole [queues documentation](https://laravel.com/docs/5.4/queues) I can't find a single word about the need of cache.

P.S. I'm using Lumen 5.4, but it doesn't matter in this situation I guess.

**Comment by sisve** [comment]
@chimit And what is the full stack trace of the error?

**Comment by decadence** [comment]
So maybe you will make PR to docs for this note?

**Comment by sisve** [comment]
So, @themsaid was correct after all. The queue system uses the cache to support the `php artisan queue:restart` functionality, and only if there is a cache configured. This does not explain why `queue:listen` would work without the cache, but at least we've tracked down the cache usage.

Basically; the Worker can run without a cache, or with the null/array cache. But if you've told Laravel to use redis without setting it up correctly, then it fails.

Ref: [Worker::getTimestampofLastQueueRestart](https://github.com/laravel/framework/blob/5.4/src/Illuminate/Queue/Worker.php#L495-L500)
Ref: [WorkCommand::runWorker](https://github.com/laravel/framework/blob/9173ede778cd0d300db94a37aceca6e4a93805e0/src/Illuminate/Queue/Console/WorkCommand.php#L98)

**Comment by chimit** [comment]
@sisve 
```
[2017-06-03 08:13:13] lumen.ERROR: Predis\Connection\ConnectionException: Error while reading line from the server. [tcp://192.168.10.10:6379] in /project/vendor/predis/predis/src/Connection/AbstractConnection.php:155
Stack trace:
#0 /project/vendor/predis/predis/src/Connection/StreamConnection.php(314): Predis\Connection\AbstractConnection->onConnectionError('Error while rea...')
#1 /project/vendor/predis/predis/src/Connection/AbstractConnection.php(120): Predis\Connection\StreamConnection->read()
#2 /project/vendor/predis/predis/src/Connection/AbstractConnection.php(112): Predis\Connection\AbstractConnection->readResponse(Object(Predis\Command\StringGet))
#3 /project/vendor/predis/predis/src/Client.php(331): Predis\Connection\AbstractConnection->executeCommand(Object(Predis\Command\StringGet))
#4 /project/vendor/predis/predis/src/Client.php(314): Predis\Client->executeCommand(Object(Predis\Command\StringGet))
#5 /project/vendor/illuminate/redis/Connections/Connection.php(69): Predis\Client->__call('get', Array)
#6 /project/vendor/illuminate/redis/Connections/Connection.php(81): Illuminate\Redis\Connections\Connection->command('get', Array)
#7 /project/vendor/illuminate/cache/RedisStore.php(54): Illuminate\Redis\Connections\Connection->__call('get', Array)
#8 /project/vendor/illuminate/cache/Repository.php(81): Illuminate\Cache\RedisStore->get('illuminate:queu...')
#9 /project/vendor/illuminate/queue/Worker.php(472): Illuminate\Cache\Repository->get('illuminate:queu...')
#10 /project/vendor/illuminate/queue/Worker.php(461): Illuminate\Queue\Worker->getTimestampOfLastQueueRestart()
#11 /project/vendor/illuminate/queue/Worker.php(196): Illuminate\Queue\Worker->queueShouldRestart('1496476689')
#12 /project/vendor/illuminate/queue/Worker.php(118): Illuminate\Queue\Worker->stopIfNecessary(Object(Illuminate\Queue\WorkerOptions), '1496476689')
#13 /project/vendor/illuminate/queue/Console/WorkCommand.php(101): Illuminate\Queue\Worker->daemon('database', 'default', Object(Illuminate\Queue\WorkerOptions))
#14 /project/vendor/illuminate/queue/Console/WorkCommand.php(84): Illuminate\Queue\Console\WorkCommand->runWorker('database', 'default')
#15 [internal function]: Illuminate\Queue\Console\WorkCommand->fire()
#16 /project/vendor/illuminate/container/BoundMethod.php(29): call_user_func_array(Array, Array)
#17 /project/vendor/illuminate/container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#18 /project/vendor/illuminate/container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Laravel\Lumen\Application), Array, Object(Closure))
#19 /project/vendor/illuminate/container/Container.php(531): Illuminate\Container\BoundMethod::call(Object(Laravel\Lumen\Application), Array, Array, NULL)
#20 /project/vendor/illuminate/console/Command.php(182): Illuminate\Container\Container->call(Array)
#21 /project/vendor/symfony/console/Command/Command.php(264): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#22 /project/vendor/illuminate/console/Command.php(167): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#23 /project/vendor/symfony/console/Application.php(835): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 /project/vendor/symfony/console/Application.php(200): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Queue\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 /project/vendor/symfony/console/Application.php(124): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#26 /project/vendor/laravel/lumen-framework/src/Console/Kernel.php(84): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#27 /project/artisan(35): Laravel\Lumen\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#28 {main}  
```
