### ISSUE TITLE
'npm run dev' Error with Laravel

### ISSUE THREAD

**Issue by ayatorii** [laravel/framework#19525]
- Laravel Version: 5.4.24
- PHP Version: 7.0.10
- Database Driver & Version: PDO, #

### Description:
I'm not sure if i should post it here.
Following the tutorial on Laracasts, this episode in particular:
https://laracasts.com/series/laravel-from-scratch-2017/episodes/14?autoplay=true
i came across an error while tried to run '_npm run dev_'
```
@ dev C:\wamp64\www\projects\blog
> npm run development


> @ development C:\wamp64\www\projects\blog
> cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

fs.js:638
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'C:\wamp64\www\projects\blog\schema\loader.json'
    at Object.fs.openSync (fs.js:638:18)
    at Object.fs.readFileSync (fs.js:540:33)
    at validateOptions (C:\wamp64\www\projects\blog\node_modules\schema-utils\dist\validateOptions.js:35:27)
    at ExtractTextPlugin.extract (C:\wamp64\www\projects\blog\node_modules\extract-text-webpack-plugin\index.js:206:3)
    at Sass.rules (C:\wamp64\www\projects\blog\node_modules\laravel-mix\src\Preprocessors\Preprocessor.js:46:42)
    at Mix.preprocessors.forEach.preprocessor (C:\wamp64\www\projects\blog\node_modules\laravel-mix\setup\webpack.config.js:243:33)
    at Array.forEach (native)
    at Object.<anonymous> (C:\wamp64\www\projects\blog\node_modules\laravel-mix\setup\webpack.config.js:242:23)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ development script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\169\AppData\Roaming\npm-cache\_logs\2017-06-08T07_18_05_000Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ dev: `npm run development`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```
I have just installed Laravel recently on Windows using Composer and now trying to follow the tutorial, getting this. The _schema/loader.json_ is not present in my project at all.
I can't find any mentions of this file or 'schema' folder in a Laravel project.
As far as i remember, i didn't do anything special about the project, just followed the tutorial
I have updated Node and npm to the latest version, reinstalled node_modules, restarted the terminal, but again, not working

### Steps To Reproduce:
https://laracasts.com/series/laravel-from-scratch-2017/episodes/14?autoplay=true

**Comment by decadence** [comment]
I think you should post it here
https://github.com/JeffreyWay/laravel-mix/issues
