### ISSUE TITLE
[5.5] Bug - Updating date casted attribute that has a value of NULL throws `Carbon missing data InvalidArgumentException`

### ISSUE THREAD

**Issue by Omranic** [laravel/framework#19653]
- Laravel Version: 5.5-dev
- PHP Version: 7.1.3
- Database Driver & Version: MySQL 5.7.17

### Description:
Updating date casted attribute that has a value of NULL throws `Carbon missing data InvalidArgumentException`

### Steps To Reproduce:
On a clean and fresh Laravel 5.5 installation..
1. In the `App\User` model add a new fillable attribute `date_at`
2. In the same `App\User` model add the new attribute as a date casted attribute `protected $dates = ['date_at'];`
3. Make sure to update the `users` table schema to match the newly added field ``` `date_at` timestamp NULL DEFAULT NULL,```
4. Create a new user record as normal `\App\User::create(['email' => rand(), 'password' => rand(), 'name' => rand()]);`
5. **Now** try to update the `date_at` field of that record `\App\User::find(1)->fill(['date_at' => new \Carbon\Carbon()])->save();` **You will get the `InvalidArgumentException Data missing` from carbon instance** The issue originates from the newly introduces code inside `originalIsEquivalent` method here: https://github.com/laravel/framework/blob/master/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php#L1007-L1009

Error Stack
```
InvalidArgumentException thrown with message "Data missing"

Stacktrace:
#54 InvalidArgumentException in /home/vagrant/Code/test/laravelup/vendor/nesbot/carbon/src/Carbon/Carbon.php:582
#53 Carbon\Carbon:createFromFormat in /home/vagrant/Code/test/laravelup/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php:708
#52 Illuminate\Database\Eloquent\Model:asDateTime in /home/vagrant/Code/test/laravelup/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php:731
#51 Illuminate\Database\Eloquent\Model:fromDateTime in /home/vagrant/Code/test/laravelup/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php:1009
#50 Illuminate\Database\Eloquent\Model:originalIsEquivalent in /home/vagrant/Code/test/laravelup/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php:980
#49 Illuminate\Database\Eloquent\Model:getDirty in /home/vagrant/Code/test/laravelup/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php:935
#48 Illuminate\Database\Eloquent\Model:isDirty in /home/vagrant/Code/test/laravelup/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:510
#47 Illuminate\Database\Eloquent\Model:save in /home/vagrant/Code/test/laravelup/routes/web.php:19
#46 Illuminate\Routing\Router:{closure} in /home/vagrant/Code/test/laravelup/vendor/laravel/framework/src/Illuminate/Routing/Route.php:189
#45 Illuminate\Routing\Route:runCallable in /home/vagrant/Code/test/laravelup/vendor/laravel/framework/src/Illuminate/Routing/Route.php:163
#44 Illuminate\Routing\Route:run in /home/vagrant/Code/test/laravelup/vendor/laravel/framework/src/Illuminate/Routing/Router.php:582
#43 Illuminate\Routing\Router:Illuminate\Routing\{closure} in /home/vagrant/Code/test/laravelup/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:30
#42 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /home/vagrant/Code/test/laravelup/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php:41
#41 Illuminate\Routing\Middleware\SubstituteBindings:handle in /home/vagrant/Code/test/laravelup/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#40 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /home/vagrant/Code/test/laravelup/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#39 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /home/vagrant/Code/test/laravelup/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php:65
#38 Illuminate\Foundation\Http\Middleware\VerifyCsrfToken:handle in /home/vagrant/Code/test/laravelup/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#37 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /home/vagrant/Code/test/laravelup/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#36 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /home/vagrant/Code/test/laravelup/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php:49
#35 Illuminate\View\Middleware\ShareErrorsFromSession:handle in /home/vagrant/Code/test/laravelup/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#34 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /home/vagrant/Code/test/laravelup/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#33 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /home/vagrant/Code/test/laravelup/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php:64
#32 Illuminate\Session\Middleware\StartSession:handle in /home/vagrant/Code/test/laravelup/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#31 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /home/vagrant/Code/test/laravelup/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#30 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /home/vagrant/Code/test/laravelup/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php:37
#29 Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse:handle in /home/vagrant/Code/test/laravelup/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#28 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /home/vagrant/Code/test/laravelup/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#27 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /home/vagrant/Code/test/laravelup/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php:59
#26 Illuminate\Cookie\Middleware\EncryptCookies:handle in /home/vagrant/Code/test/laravelup/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#25 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /home/vagrant/Code/test/laravelup/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#24 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /home/vagrant/Code/test/laravelup/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:102
#23 Illuminate\Pipeline\Pipeline:then in /home/vagrant/Code/test/laravelup/vendor/laravel/framework/src/Illuminate/Routing/Router.php:584
#22 Illuminate\Routing\Router:runRouteWithinStack in /home/vagrant/Code/test/laravelup/vendor/laravel/framework/src/Illuminate/Routing/Router.php:543
#21 Illuminate\Routing\Router:dispatchToRoute in /home/vagrant/Code/test/laravelup/vendor/laravel/framework/src/Illuminate/Routing/Router.php:521
#20 Illuminate\Routing\Router:dispatch in /home/vagrant/Code/test/laravelup/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:174
#19 Illuminate\Foundation\Http\Kernel:Illuminate\Foundation\Http\{closure} in /home/vagrant/Code/test/laravelup/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:30
#18 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /home/vagrant/Code/test/laravelup/vendor/fideloper/proxy/src/TrustProxies.php:55
#17 Fideloper\Proxy\TrustProxies:handle in /home/vagrant/Code/test/laravelup/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#16 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /home/vagrant/Code/test/laravelup/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#15 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /home/vagrant/Code/test/laravelup/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php:30
#14 Illuminate\Foundation\Http\Middleware\TransformsRequest:handle in /home/vagrant/Code/test/laravelup/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#13 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /home/vagrant/Code/test/laravelup/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#12 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /home/vagrant/Code/test/laravelup/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php:30
#11 Illuminate\Foundation\Http\Middleware\TransformsRequest:handle in /home/vagrant/Code/test/laravelup/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#10 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /home/vagrant/Code/test/laravelup/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#9 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /home/vagrant/Code/test/laravelup/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php:27
#8 Illuminate\Foundation\Http\Middleware\ValidatePostSize:handle in /home/vagrant/Code/test/laravelup/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#7 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /home/vagrant/Code/test/laravelup/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#6 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /home/vagrant/Code/test/laravelup/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php:46
#5 Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode:handle in /home/vagrant/Code/test/laravelup/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#4 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /home/vagrant/Code/test/laravelup/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#3 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /home/vagrant/Code/test/laravelup/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:102
#2 Illuminate\Pipeline\Pipeline:then in /home/vagrant/Code/test/laravelup/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:149
#1 Illuminate\Foundation\Http\Kernel:sendRequestThroughRouter in /home/vagrant/Code/test/laravelup/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:116
#0 Illuminate\Foundation\Http\Kernel:handle in /home/vagrant/Code/test/laravelup/public/index.php:55
```

**Comment by themsaid** [comment]
fixed in https://github.com/laravel/framework/compare/master...themsaid:fix/nullable/dates?expand=1

**Comment by snapple42** [comment]
I'm still running into this on current 5.5-dev branch, verified the updates were there:  
```
  
[2017-08-04 01:30:36] local.ERROR: Data missing {"exception":"[object] (InvalidArgumentException(code: 0): Data missing at /home/derrickb/Work/Bridgepoint/plevin_test/vendor/nesbot/carbon/src/Carbon/Carbon.php:582)
[stacktrace]
#0 Illuminate/Database/Eloquent/Concerns/HasAttributes.php(715): Carbon\\Carbon::createFromFormat('Y-m-d H:i:s.000', '2017-08-04 01:3...')
#1 Illuminate/Database/Eloquent/Concerns/HasAttributes.php(738): Illuminate\\Database\\Eloquent\\Model->asDateTime('2017-08-04 01:3...')
#2 Illuminate/Database/Eloquent/Concerns/HasAttributes.php(1062): Illuminate\\Database\\Eloquent\\Model->fromDateTime('2017-08-04 01:3...')
#3 Illuminate/Database/Eloquent/Concerns/HasAttributes.php(1023): Illuminate\\Database\\Eloquent\\Model->originalIsEquivalent('updated_at', '2017-08-04 01:3...')
#4 Illuminate/Database/Eloquent/Model.php(593): Illuminate\\Database\\Eloquent\\Model->getDirty()
#5 Illuminate/Database/Eloquent/Model.php(516): Illuminate\\Database\\Eloquent\\Model->performUpdate(Object(Illuminate\\Database\\Eloquent\\Builder))
#6 /home/derrickb/Work/Bridgepoint/plevin_test/app/Http/Controllers/Auth/RegisterController.php(108): Illuminate\\Database\\Eloquent\\Model->save()
#7 [internal function]: App\\Http\\Controllers\\Auth\\RegisterController->confirm('D2IQ4gWEMvTvmtF...')
#8 Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#9 Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('confirm', Array)
#10 Illuminate/Routing/Route.php(204): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Http\\Controllers\\Auth\\RegisterController), 'confirm')
#11 Illuminate/Routing/Route.php(161): Illuminate\\Routing\\Route->runController()
#12 Illuminate/Routing/Router.php(612): Illuminate\\Routing\\Route->run()
#13 Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#14 /home/derrickb/Work/Bridgepoint/plevin_test/app/Http/Middleware/RedirectIfAuthenticated.php(24): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#15 Illuminate/Pipeline/Pipeline.php(149): App\\Http\\Middleware\\RedirectIfAuthenticated->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#16 Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#17 Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#18 Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#19 Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#20 Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(67): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#21 Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#22 Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#23 Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#24 Illuminate/Pipeline/Pipeline.php(149): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#25 Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#26 Illuminate/Session/Middleware/StartSession.php(63): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#27 Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#28 Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#29 Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#30 Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#31 Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#32 Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#33 Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#34 Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#35 Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#36 Illuminate/Routing/Router.php(614): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#37 Illuminate/Routing/Router.php(573): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#38 Illuminate/Routing/Router.php(551): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#39 Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#40 Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#41 /home/derrickb/Work/Bridgepoint/plevin_test/vendor/fideloper/proxy/src/TrustProxies.php(56): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#42 Illuminate/Pipeline/Pipeline.php(149): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#43 Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#44 Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#45 Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#46 Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#47 Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#48 Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#49 Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#50 Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#51 Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#52 Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#53 Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#54 Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#55 Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#56 Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#57 Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#58 Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#59 /public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#60 /server.php(21): require_once('/home/derrickb/...')
#61 {main}

```

**Comment by snapple42** [comment]
It's close, it was a data formatting error:  
  
When updating a model timestamp the timestamp passed in was "Y-m-d H:i:s" and the default dateformat was "Y-m-d H:i:s.000"  
  
Illuminate/Database/Eloquent/Concerns/HasAttributes.php(715) 

The date passed in didn't have the ".000" at the end:  

[2017-08-04 03:23:16] local.INFO: VAL: 2017-08-04 03:23:16  Y-m-d H:i:s.000 - .000  

generated an error, concatenate a ".000" at the end and it worked.  
```
  if (substr($value,-4) != ".000") { $value = $value . '.000'; }
```
  
Not sure what the proper solution would be here though...
