### ISSUE TITLE
Laravel says: class **/.stub doesn't not exists but it's text file. Worked with Laravel 5.5.1

### ISSUE THREAD

**Issue by savander** [laravel/framework#20993]
- Laravel Version: `5.5.2`
- PHP Version: `PHP 7.1.9-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Sep  2 2017 05:56:43) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.9-1+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2017, by Zend Technologies`

### Description:
With previous version of laravel, (5.5.1) `.stub` file was normaly recognized and copied to specific directory, now laravel output error:
```console
[2017-09-04 22:32:44] local.ERROR: Class App\Console\Commands\stubs\test.stub does not exist {"exception":"[object] (ReflectionException(code: -1): Class App\\Console\\Commands\\stubs\\test.stub does not exist at /mnt/f/Projekty/PHP/codrig-cms/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:217)
[stacktrace]
#0 /mnt/f/Projekty/PHP/codrig-cms/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(217): ReflectionClass->__construct('App\\\\Console\\\\Com...')
#1 /mnt/f/Projekty/PHP/codrig-cms/app/Console/Kernel.php(38): Illuminate\\Foundation\\Console\\Kernel->load(Array)
#2 /mnt/f/Projekty/PHP/codrig-cms/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(303): App\\Console\\Kernel->commands()
#3 /mnt/f/Projekty/PHP/codrig-cms/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(119): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
#4 /mnt/f/Projekty/PHP/codrig-cms/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#5 {main}
"} 
```

No idea what's going on

### Steps To Reproduce:

**ModuleTestMakeCommand.php** file (it's generally copy of TestMakeCommand, with small change)
```php
<?php

namespace App\Console\Commands;

use Illuminate\Support\Str;
use Illuminate\Console\GeneratorCommand;

class ModuleTestMakeCommand extends GeneratorCommand
{
    /**
     * The console command name.
     *
     * @var string
     */
    protected $signature = 'module:make-test {moduleName : The name of module} {name : The name of the class} {--unit : Create a unit test}';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Create a new module test class';

    /**
     * The type of class being generated.
     *
     * @var string
     */
    protected $type = 'Module test';

    
    /**
     * Get the stub file for the generator.
     *
     * @return string
     */
    protected function getStub()
    {
        if ($this->option('unit')) {
            return __DIR__.'/stubs/unit-test.stub';
        } else {
            return __DIR__.'/stubs/test.stub';
        }
    }

    /**
     * Get the destination class path.
     *
     * @param  string  $name
     * @return string
     */
    protected function getPath($name)
    {
        $name = Str::replaceFirst($this->rootNamespace(), '', $name);

        return $this->laravel->basePath().'/Modules/'.$this->argument('moduleName').'/Tests/'.str_replace('\\', '/', $name).'.php';
    }

    /**
     * Get the default namespace for the class.
     *
     * @param  string  $rootNamespace
     * @return string
     */
    protected function getDefaultNamespace($rootNamespace)
    {
        if ($this->option('unit')) {
            return $rootNamespace.'\Unit';
        } else {
            return $rootNamespace.'\Feature';
        }
    }

    /**
     * Get the root namespace for the class.
     *
     * @return string
     */
    protected function rootNamespace()
    {
        return 'Modules\\'.$this->argument('moduleName').'\\Tests';
    }
}
```

stubs are stored in:
**app/Console/Commands/stubs**

It should copy stubs to `Modules/<module_name>/Tests/(Feature|Unit)`

I found a temporary fix, I disabled `//$this->load(__DIR__.'/Commands');` in `Console/Kernel.php`,
and added it to `$commands` array. 

I think, the problem is somewhere here [Foundation/Console/Kernel.php](https://github.com/laravel/framework/blob/5.5/src/Illuminate/Foundation/Console/Kernel.php#L210-L224)
Cause `$reflector = new ReflectionClass($command);`, wants to interpret .stub file as a .php class

**Comment by themsaid** [comment]
Fixed in https://github.com/laravel/framework/pull/20998

**Comment by dpslwk** [comment]
Even with 5.5.2 I'm having issue with the new `load()` function and stub files

```
vagrant@hmsdev:/vagrant$ php artisan                                                                      
  [ReflectionException]                                                          
  Class App\Console\Commands\Make\stubs\doctrine-repository.stub does not exist 
```

the stub file in question is, but have a few more that are the similar

```
<?php

namespace DummyRepositoryImplementationNamespace;

use DummyNamespace\DummyClass;
use Doctrine\ORM\EntityRepository;
use NamespacedDummyRepositoryInterface;

class DoctrineDummyClassRepository extends EntityRepository implements DummyClassRepository
{
    /**
     * save DummyClass to the DB. 
     * @param  DummyClass $dummyClass
     */
    public function save(DummyClass $dummyClass)
    {
        $this->_em->persist($dummyClass);
        $this->_em->flush();
    }
}

```

also have another stub 

```
# NamspacedDummmyMapping.dcm.yml
DummyNamespace\DummyClass:
  type: entity
  repositoryClass: NamespacedDummyRepositoryInterface
  table: dummyTable
  id:
    id:
      type: integer
      options:
        unsigned: true
      generator:
        strategy: AUTO
```

at this point I wonder is adding a `exceptFolder` or `exceptFileExtension` option to the `load()` function would help to skip unwanted files

**Comment by themsaid** [comment]
@dpslwk changes aren't tagged yet

**Comment by dpslwk** [comment]
Ah sorry, jumping the gun at updating

Matt
