### ISSUE TITLE
SIGSEGV on php-fpm

### ISSUE THREAD

**Issue by Anorlondo448** [laravel/framework#21029]
- Laravel Version: 5.5.2
- PHP Version: 7.1.7

### Description:
- error : `SIGSEGV` 

on `/var/log/php-fpm/7.1/error.log`
```
[06-Sep-2017 12:12:25] WARNING: [pool www] child 19250 exited on signal 11 (SIGSEGV) after 1.315077 seconds from start
[06-Sep-2017 12:12:25] NOTICE: [pool www] child 19263 started
```

- core dump

```
#0  0x00007f3196dc96fa in nr_php_scope_get () at /home/hudson/slave-workspace/workspace/php-release-agent/label/centos5-64-nrcamp/agent/php_wrapper.c:118
#1  0x00007f3196d9bd38 in nr_laravel_router_method_with_request () at /home/hudson/slave-workspace/workspace/php-release-agent/label/centos5-64-nrcamp/agent/fw_laravel.c:804
#2  0x00007f3196dc8b56 in nr_zend_call_orig_execute_special () at /home/hudson/slave-workspace/workspace/php-release-agent/label/centos5-64-nrcamp/agent/php_user_instrument.c:62
#3  0x00007f3196daeb04 in nr_php_execute_enabled () at /home/hudson/slave-workspace/workspace/php-release-agent/label/centos5-64-nrcamp/agent/php_execute.c:1117
#4  0x00007f3196daf462 in nr_php_execute () at /home/hudson/slave-workspace/workspace/php-release-agent/label/centos5-64-nrcamp/agent/php_execute.c:1297
#5  0x00000000006393f5 in ?? ()
#6  0x00000000005e86cb in execute_ex ()
#7  0x00007f3196daee1b in nr_php_execute_enabled () at /home/hudson/slave-workspace/workspace/php-release-agent/label/centos5-64-nrcamp/agent/php_execute.c:1187
#8  0x00007f3196daf462 in nr_php_execute () at /home/hudson/slave-workspace/workspace/php-release-agent/label/centos5-64-nrcamp/agent/php_execute.c:1297
#9  0x00000000006393f5 in ?? ()
#10 0x00000000005e86cb in execute_ex ()
#11 0x00007f3196daee1b in nr_php_execute_enabled () at /home/hudson/slave-workspace/workspace/php-release-agent/label/centos5-64-nrcamp/agent/php_execute.c:1187
#12 0x00007f3196daf462 in nr_php_execute () at /home/hudson/slave-workspace/workspace/php-release-agent/label/centos5-64-nrcamp/agent/php_execute.c:1297
#13 0x00000000006393f5 in ?? ()
#14 0x00000000005e86cb in execute_ex ()
#15 0x00007f3196daee1b in nr_php_execute_enabled () at /home/hudson/slave-workspace/workspace/php-release-agent/label/centos5-64-nrcamp/agent/php_execute.c:1187
#16 0x00007f3196daf462 in nr_php_execute () at /home/hudson/slave-workspace/workspace/php-release-agent/label/centos5-64-nrcamp/agent/php_execute.c:1297
#17 0x00000000006393f5 in ?? ()
#18 0x00000000005e86cb in execute_ex ()
#19 0x00007f3196daee1b in nr_php_execute_enabled () at /home/hudson/slave-workspace/workspace/php-release-agent/label/centos5-64-nrcamp/agent/php_execute.c:1187
#20 0x00007f3196daf462 in nr_php_execute () at /home/hudson/slave-workspace/workspace/php-release-agent/label/centos5-64-nrcamp/agent/php_execute.c:1297
#21 0x00000000006393f5 in ?? ()
#22 0x00000000005e86cb in execute_ex ()
#23 0x00007f3196daee1b in nr_php_execute_enabled () at /home/hudson/slave-workspace/workspace/php-release-agent/label/centos5-64-nrcamp/agent/php_execute.c:1187
#24 0x00007f3196daf462 in nr_php_execute () at /home/hudson/slave-workspace/workspace/php-release-agent/label/centos5-64-nrcamp/agent/php_execute.c:1297
#25 0x00000000006393f5 in ?? ()
#26 0x00000000005e86cb in execute_ex ()
#27 0x00007f3196daee1b in nr_php_execute_enabled () at /home/hudson/slave-workspace/workspace/php-release-agent/label/centos5-64-nrcamp/agent/php_execute.c:1187
#28 0x00007f3196daf462 in nr_php_execute () at /home/hudson/slave-workspace/workspace/php-release-agent/label/centos5-64-nrcamp/agent/php_execute.c:1297
#29 0x00000000006393f5 in ?? ()
#30 0x00000000005e86cb in execute_ex ()
#31 0x00007f3196daee1b in nr_php_execute_enabled () at /home/hudson/slave-workspace/workspace/php-release-agent/label/centos5-64-nrcamp/agent/php_execute.c:1187
#32 0x00007f3196daf462 in nr_php_execute () at /home/hudson/slave-workspace/workspace/php-release-agent/label/centos5-64-nrcamp/agent/php_execute.c:1297
#33 0x00000000006393f5 in ?? ()
#34 0x00000000005e86cb in execute_ex ()
#35 0x00007f3196daee1b in nr_php_execute_enabled () at /home/hudson/slave-workspace/workspace/php-release-agent/label/centos5-64-nrcamp/agent/php_execute.c:1187
#36 0x00007f3196daf462 in nr_php_execute () at /home/hudson/slave-workspace/workspace/php-release-agent/label/centos5-64-nrcamp/agent/php_execute.c:1297
#37 0x00000000006393f5 in ?? ()
#38 0x00000000005e86cb in execute_ex ()
#39 0x00007f3196daee1b in nr_php_execute_enabled () at /home/hudson/slave-workspace/workspace/php-release-agent/label/centos5-64-nrcamp/agent/php_execute.c:1187
#40 0x00007f3196daf462 in nr_php_execute () at /home/hudson/slave-workspace/workspace/php-release-agent/label/centos5-64-nrcamp/agent/php_execute.c:1297
#41 0x00000000006393f5 in ?? ()
#42 0x00000000005e86cb in execute_ex ()
#43 0x00007f3196daee1b in nr_php_execute_enabled () at /home/hudson/slave-workspace/workspace/php-release-agent/label/centos5-64-nrcamp/agent/php_execute.c:1187
#44 0x00007f3196daf462 in nr_php_execute () at /home/hudson/slave-workspace/workspace/php-release-agent/label/centos5-64-nrcamp/agent/php_execute.c:1297
#45 0x00000000006393f5 in ?? ()
#46 0x00000000005e86cb in execute_ex ()
#47 0x00007f3196daee1b in nr_php_execute_enabled () at /home/hudson/slave-workspace/workspace/php-release-agent/label/centos5-64-nrcamp/agent/php_execute.c:1187
#48 0x00007f3196daf462 in nr_php_execute () at /home/hudson/slave-workspace/workspace/php-release-agent/label/centos5-64-nrcamp/agent/php_execute.c:1297
#49 0x00000000006393f5 in ?? ()
#50 0x00000000005e86cb in execute_ex ()
#51 0x00007f3196daee1b in nr_php_execute_enabled () at /home/hudson/slave-workspace/workspace/php-release-agent/label/centos5-64-nrcamp/agent/php_execute.c:1187
#52 0x00007f3196daf462 in nr_php_execute () at /home/hudson/slave-workspace/workspace/php-release-agent/label/centos5-64-nrcamp/agent/php_execute.c:1297
#53 0x00000000006393f5 in ?? ()
#54 0x00000000005e86cb in execute_ex ()
#55 0x00007f3196daee1b in nr_php_execute_enabled () at /home/hudson/slave-workspace/workspace/php-release-agent/label/centos5-64-nrcamp/agent/php_execute.c:1187
#56 0x00007f3196daf462 in nr_php_execute () at /home/hudson/slave-workspace/workspace/php-release-agent/label/centos5-64-nrcamp/agent/php_execute.c:1297
---Type <return> to continue, or q <return> to quit---
#57 0x00000000006393f5 in ?? ()
#58 0x00000000005e86cb in execute_ex ()
#59 0x00007f3196daee1b in nr_php_execute_enabled () at /home/hudson/slave-workspace/workspace/php-release-agent/label/centos5-64-nrcamp/agent/php_execute.c:1187
#60 0x00007f3196daf462 in nr_php_execute () at /home/hudson/slave-workspace/workspace/php-release-agent/label/centos5-64-nrcamp/agent/php_execute.c:1297
#61 0x00000000006393f5 in ?? ()
#62 0x00000000005e86cb in execute_ex ()
#63 0x00007f3196dc8afa in nr_zend_call_orig_execute () at /home/hudson/slave-workspace/workspace/php-release-agent/label/centos5-64-nrcamp/agent/php_user_instrument.c:49
#64 0x00007f3196d9a937 in nr_laravel5_middleware_handle () at /home/hudson/slave-workspace/workspace/php-release-agent/label/centos5-64-nrcamp/agent/fw_laravel.c:643
#65 0x00007f3196dc8b56 in nr_zend_call_orig_execute_special () at /home/hudson/slave-workspace/workspace/php-release-agent/label/centos5-64-nrcamp/agent/php_user_instrument.c:62
#66 0x00007f3196daeb04 in nr_php_execute_enabled () at /home/hudson/slave-workspace/workspace/php-release-agent/label/centos5-64-nrcamp/agent/php_execute.c:1117
#67 0x00007f3196daf462 in nr_php_execute () at /home/hudson/slave-workspace/workspace/php-release-agent/label/centos5-64-nrcamp/agent/php_execute.c:1297
#68 0x00000000006393f5 in ?? ()
#69 0x00000000005e86cb in execute_ex ()
#70 0x00007f3196daee1b in nr_php_execute_enabled () at /home/hudson/slave-workspace/workspace/php-release-agent/label/centos5-64-nrcamp/agent/php_execute.c:1187
#71 0x00007f3196daf462 in nr_php_execute () at /home/hudson/slave-workspace/workspace/php-release-agent/label/centos5-64-nrcamp/agent/php_execute.c:1297
#72 0x00000000006393f5 in ?? ()
#73 0x00000000005e86cb in execute_ex ()
#74 0x00007f3196daee1b in nr_php_execute_enabled () at /home/hudson/slave-workspace/workspace/php-release-agent/label/centos5-64-nrcamp/agent/php_execute.c:1187
#75 0x00007f3196daf462 in nr_php_execute () at /home/hudson/slave-workspace/workspace/php-release-agent/label/centos5-64-nrcamp/agent/php_execute.c:1297
#76 0x00000000006393f5 in ?? ()
#77 0x00000000005e86cb in execute_ex ()
#78 0x00007f3196dc8afa in nr_zend_call_orig_execute () at /home/hudson/slave-workspace/workspace/php-release-agent/label/centos5-64-nrcamp/agent/php_user_instrument.c:49
#79 0x00007f3196d9a937 in nr_laravel5_middleware_handle () at /home/hudson/slave-workspace/workspace/php-release-agent/label/centos5-64-nrcamp/agent/fw_laravel.c:643
#80 0x00007f3196dc8b56 in nr_zend_call_orig_execute_special () at /home/hudson/slave-workspace/workspace/php-release-agent/label/centos5-64-nrcamp/agent/php_user_instrument.c:62
#81 0x00007f3196daeb04 in nr_php_execute_enabled () at /home/hudson/slave-workspace/workspace/php-release-agent/label/centos5-64-nrcamp/agent/php_execute.c:1117
#82 0x00007f3196daf462 in nr_php_execute () at /home/hudson/slave-workspace/workspace/php-release-agent/label/centos5-64-nrcamp/agent/php_execute.c:1297
#83 0x00000000006393f5 in ?? ()
#84 0x00000000005e86cb in execute_ex ()
#85 0x00007f3196daee1b in nr_php_execute_enabled () at /home/hudson/slave-workspace/workspace/php-release-agent/label/centos5-64-nrcamp/agent/php_execute.c:1187
#86 0x00007f3196daf462 in nr_php_execute () at /home/hudson/slave-workspace/workspace/php-release-agent/label/centos5-64-nrcamp/agent/php_execute.c:1297
#87 0x00000000006393f5 in ?? ()
#88 0x00000000005e86cb in execute_ex ()
#89 0x00007f3196daee1b in nr_php_execute_enabled () at /home/hudson/slave-workspace/workspace/php-release-agent/label/centos5-64-nrcamp/agent/php_execute.c:1187
#90 0x00007f3196daf462 in nr_php_execute () at /home/hudson/slave-workspace/workspace/php-release-agent/label/centos5-64-nrcamp/agent/php_execute.c:1297
#91 0x00000000006393f5 in ?? ()
#92 0x00000000005e86cb in execute_ex ()
#93 0x00007f3196dc8afa in nr_zend_call_orig_execute () at /home/hudson/slave-workspace/workspace/php-release-agent/label/centos5-64-nrcamp/agent/php_user_instrument.c:49
#94 0x00007f3196d9a937 in nr_laravel5_middleware_handle () at /home/hudson/slave-workspace/workspace/php-release-agent/label/centos5-64-nrcamp/agent/fw_laravel.c:643
#95 0x00007f3196dc8b56 in nr_zend_call_orig_execute_special () at /home/hudson/slave-workspace/workspace/php-release-agent/label/centos5-64-nrcamp/agent/php_user_instrument.c:62
#96 0x00007f3196daeb04 in nr_php_execute_enabled () at /home/hudson/slave-workspace/workspace/php-release-agent/label/centos5-64-nrcamp/agent/php_execute.c:1117
#97 0x00007f3196daf462 in nr_php_execute () at /home/hudson/slave-workspace/workspace/php-release-agent/label/centos5-64-nrcamp/agent/php_execute.c:1297
#98 0x00000000006393f5 in ?? ()
#99 0x00000000005e86cb in execute_ex ()
#100 0x00007f3196daee1b in nr_php_execute_enabled () at /home/hudson/slave-workspace/workspace/php-release-agent/label/centos5-64-nrcamp/agent/php_execute.c:1187
#101 0x00007f3196daf462 in nr_php_execute () at /home/hudson/slave-workspace/workspace/php-release-agent/label/centos5-64-nrcamp/agent/php_execute.c:1297
#102 0x00000000006393f5 in ?? ()
#103 0x00000000005e86cb in execute_ex ()
#104 0x00007f3196daee1b in nr_php_execute_enabled () at /home/hudson/slave-workspace/workspace/php-release-agent/label/centos5-64-nrcamp/agent/php_execute.c:1187
#105 0x00007f3196daf462 in nr_php_execute () at /home/hudson/slave-workspace/workspace/php-release-agent/label/centos5-64-nrcamp/agent/php_execute.c:1297
#106 0x00000000006393f5 in ?? ()
#107 0x00000000005e86cb in execute_ex ()
#108 0x00007f3196dc8afa in nr_zend_call_orig_execute () at /home/hudson/slave-workspace/workspace/php-release-agent/label/centos5-64-nrcamp/agent/php_user_instrument.c:49
#109 0x00007f3196d9a937 in nr_laravel5_middleware_handle () at /home/hudson/slave-workspace/workspace/php-release-agent/label/centos5-64-nrcamp/agent/fw_laravel.c:643
#110 0x00007f3196dc8b56 in nr_zend_call_orig_execute_special () at /home/hudson/slave-workspace/workspace/php-release-agent/label/centos5-64-nrcamp/agent/php_user_instrument.c:62
#111 0x00007f3196daeb04 in nr_php_execute_enabled () at /home/hudson/slave-workspace/workspace/php-release-agent/label/centos5-64-nrcamp/agent/php_execute.c:1117
#112 0x00007f3196daf462 in nr_php_execute () at /home/hudson/slave-workspace/workspace/php-release-agent/label/centos5-64-nrcamp/agent/php_execute.c:1297
#113 0x00000000006393f5 in ?? ()
---Type <return> to continue, or q <return> to quit---
#114 0x00000000005e86cb in execute_ex ()
#115 0x00007f3196daee1b in nr_php_execute_enabled () at /home/hudson/slave-workspace/workspace/php-release-agent/label/centos5-64-nrcamp/agent/php_execute.c:1187
#116 0x00007f3196daf462 in nr_php_execute () at /home/hudson/slave-workspace/workspace/php-release-agent/label/centos5-64-nrcamp/agent/php_execute.c:1297
#117 0x00000000006393f5 in ?? ()
#118 0x00000000005e86cb in execute_ex ()
#119 0x00007f3196daee1b in nr_php_execute_enabled () at /home/hudson/slave-workspace/workspace/php-release-agent/label/centos5-64-nrcamp/agent/php_execute.c:1187
#120 0x00007f3196daf462 in nr_php_execute () at /home/hudson/slave-workspace/workspace/php-release-agent/label/centos5-64-nrcamp/agent/php_execute.c:1297
#121 0x00000000006393f5 in ?? ()
#122 0x00000000005e86cb in execute_ex ()
#123 0x00007f3196daee1b in nr_php_execute_enabled () at /home/hudson/slave-workspace/workspace/php-release-agent/label/centos5-64-nrcamp/agent/php_execute.c:1187
#124 0x00007f3196daf462 in nr_php_execute () at /home/hudson/slave-workspace/workspace/php-release-agent/label/centos5-64-nrcamp/agent/php_execute.c:1297
#125 0x00000000006393f5 in ?? ()
#126 0x00000000005e86cb in execute_ex ()
#127 0x00007f3196daee1b in nr_php_execute_enabled () at /home/hudson/slave-workspace/workspace/php-release-agent/label/centos5-64-nrcamp/agent/php_execute.c:1187
#128 0x00007f3196daf462 in nr_php_execute () at /home/hudson/slave-workspace/workspace/php-release-agent/label/centos5-64-nrcamp/agent/php_execute.c:1297
#129 0x00000000006393f5 in ?? ()
#130 0x00000000005e86cb in execute_ex ()
#131 0x00007f3196daee1b in nr_php_execute_enabled () at /home/hudson/slave-workspace/workspace/php-release-agent/label/centos5-64-nrcamp/agent/php_execute.c:1187
#132 0x00007f3196daf462 in nr_php_execute () at /home/hudson/slave-workspace/workspace/php-release-agent/label/centos5-64-nrcamp/agent/php_execute.c:1297
#133 0x00000000006393f5 in ?? ()
#134 0x00000000005e86cb in execute_ex ()
#135 0x00007f3196daef5a in nr_php_execute_file () at /home/hudson/slave-workspace/workspace/php-release-agent/label/centos5-64-nrcamp/agent/php_execute.c:847
#136 nr_php_execute_enabled () at /home/hudson/slave-workspace/workspace/php-release-agent/label/centos5-64-nrcamp/agent/php_execute.c:1069
#137 0x00007f3196daf462 in nr_php_execute () at /home/hudson/slave-workspace/workspace/php-release-agent/label/centos5-64-nrcamp/agent/php_execute.c:1297
#138 0x000000000063b884 in zend_execute ()
#139 0x00000000005a3694 in zend_execute_scripts ()
#140 0x0000000000543748 in php_execute_script ()
#141 0x000000000042cc6c in ?? ()
#142 0x00007f31a9a7bb35 in __libc_start_main () from /lib64/libc.so.6
#143 0x000000000042dd75 in _start ()
```

## Environments
- reverse proxy : nginx(1.11.3)
- cgi :  php-fpm 

### Steps To Reproduce:
- nginx + php-fpm + laravel5.5

* laravel5.4 do not occur

**Comment by themsaid** [comment]
Please ask on the forums, this repo is for bug reporting only. You can use https://laracasts.com/discuss or https://laravel.io/forum which are forums with a very large community of developers helping each other.
