### ISSUE TITLE
tearDownAfterClass is not usable.

### ISSUE THREAD

**Issue by MicroDroid** [laravel/framework#21088]
- Laravel Version: 5.4.36
- PHP Version: 7.1.9
- Database Driver & Version: MariaDB 10.1.26

### Description:

Cannot use a facade or a model in `tearDownAfterClass` in a feature test.

```
PHPUnit 5.7.21 by Sebastian Bergmann and contributors.

......................                                            22 / 22 (100%)
PHP Fatal error:  Uncaught Illuminate\Contracts\Container\BindingResolutionException: Target [Illuminate\Contracts\Debug\ExceptionHandler] is not instantiable. in /usr/share/nginx/someproject/vendor/laravel/framework/src/Illuminate/Container/Container.php:895
Stack trace:
#0 /usr/share/nginx/someproject/vendor/laravel/framework/src/Illuminate/Container/Container.php(735): Illuminate\Container\Container->notInstantiable('Illuminate\\Cont...')
#1 /usr/share/nginx/someproject/vendor/laravel/framework/src/Illuminate/Container/Container.php(608): Illuminate\Container\Container->build('Illuminate\\Cont...')
#2 /usr/share/nginx/someproject/vendor/laravel/framework/src/Illuminate/Container/Container.php(575): Illuminate\Container\Container->resolve('Illuminate\\Cont...')
#3 /usr/share/nginx/someproject/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(728): Illuminate\Container\Container->make('Illuminate\\Cont...')
#4 /usr/share/nginx/someproject/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions in /usr/share/nginx/someproject/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 895
PHP Fatal error:  Uncaught Illuminate\Contracts\Container\BindingResolutionException: Target [Illuminate\Contracts\Debug\ExceptionHandler] is not instantiable. in /usr/share/nginx/someproject/vendor/laravel/framework/src/Illuminate/Container/Container.php:895
Stack trace:
#0 /usr/share/nginx/someproject/vendor/laravel/framework/src/Illuminate/Container/Container.php(735): Illuminate\Container\Container->notInstantiable('Illuminate\\Cont...')
#1 /usr/share/nginx/someproject/vendor/laravel/framework/src/Illuminate/Container/Container.php(608): Illuminate\Container\Container->build('Illuminate\\Cont...')
#2 /usr/share/nginx/someproject/vendor/laravel/framework/src/Illuminate/Container/Container.php(575): Illuminate\Container\Container->resolve('Illuminate\\Cont...')
#3 /usr/share/nginx/someproject/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(728): Illuminate\Container\Container->make('Illuminate\\Cont...')
#4 /usr/share/nginx/someproject/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions in /usr/share/nginx/someproject/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 895
```

Turns out this is due to application instance being cleared out in `tearDown` in `TestCase`

See: https://github.com/laravel/framework/blob/d00031ff0e4c29450a1727b7aedb582d5d9858e2/src/Illuminate/Foundation/Testing/TestCase.php#L138-L140

### Steps To Reproduce:

1. Create a feature test `php artisan make:test SomeTest`
2. Use a model or facade or anything in the `tearDownAfterClass` of `SomeTest`

**Comment by themsaid** [comment]
Yes the entire application is flushed on teardown, don't use `tearDownAfterClass` or you'll have to extend Laravel's test case to your own class and change the behaviour as you wish.

**Comment by MicroDroid** [comment]
@themsaid So how else would I execute some code after the whole test suite has finished?

Currently I am using:

```
	public function tearDown()
	{
		if ($this->getName() === 'testMyFancyStuff') {
			// execute
		}

		// should be called at the beginning..
		parent::tearDown();
	}
```

but this guarantees that it works after a certain test, not all tests, so I used the `@depends`

This is so messy I believe.

**Comment by mattford** [comment]
@themsaid it doesn't seem like the issue is really resolved, at the very least a clearer error message should be given, or some mention in the docs?
