### ISSUE TITLE
Invalid Argument Exception for foreach(

### ISSUE THREAD

**Issue by basherr** [laravel/framework#21372]
- Laravel Version: 5.4.36
- PHP Version: 7.1
- Database Driver & Version: mysql

### Description:
I've console command that runs with no error when try to call it from `cmd` but the same command throws error when set a call with cron tab.
`php /home/path/to/public_html/artisan company-validity:run >/dev/null 2>&1`

**Error**
```
[2017-09-25 06:48:01] local.ERROR: ErrorException: Invalid argument supplied for foreach() in /home/esignmein/public_html/vendor/symfony/console/Input/ArgvInput.php:282
Stack trace:
#0 /home/esignmein/public_html/vendor/symfony/console/Input/ArgvInput.php(282): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'Invalid argumen...', '/home/esignmein...', 282, Array)
#1 /home/esignmein/public_html/vendor/symfony/console/Application.php(827): Symfony\Component\Console\Input\ArgvInput->hasParameterOption(Array, true)
#2 /home/esignmein/public_html/vendor/symfony/console/Application.php(121): Symfony\Component\Console\Application->configureIO(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /home/esignmein/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /home/esignmein/public_html/artisan(34): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 {main}  
[2017-09-25 06:49:01] local.ERROR: ErrorException: Invalid argument supplied for foreach() in /home/esignmein/public_html/vendor/symfony/console/Input/ArgvInput.php:282
Stack trace:
#0 /home/esignmein/public_html/vendor/symfony/console/Input/ArgvInput.php(282): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'Invalid argumen...', '/home/esignmein...', 282, Array)
#1 /home/esignmein/public_html/vendor/symfony/console/Application.php(827): Symfony\Component\Console\Input\ArgvInput->hasParameterOption(Array, true)
#2 /home/esignmein/public_html/vendor/symfony/console/Application.php(121): Symfony\Component\Console\Application->configureIO(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /home/esignmein/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /home/esignmein/public_html/artisan(34): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 {main}  
```

The console command code
```
<?php

namespace App\Console\Commands;

use Carbon\Carbon;
use App\Company;
use Illuminate\Console\Command;

class CompanySubscriptionValidity extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'company:validate {id?}';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Cancel company subscription on expire';

    /**
     * Create a new command instance.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();
    }

    /**
     * Execute the console command.
     *
     * @return mixed
     */
    public function handle()
    {
        $this->info("validating all companies subscription");
        $companies = Company::where('subscription_end', '<',  Carbon::now())
                            ->update(['active' => false]);
        $this->info("validated all companies subscription");
    }
}
```
Have a look at the following error after modifying the code of `symfony ArgvInput.php` just for testing purpose. [Error Log](https://kopy.io/q9FO3)

**Comment by themsaid** [comment]
Please ask on the forums, this repo is for bug reporting only. You can use https://laracasts.com/discuss or https://laravel.io/forum which are forums with a very large community of developers helping each other.
