### ISSUE TITLE
The force option does not exist

### ISSUE THREAD

**Issue by vesper8** [laravel/framework#21373]
Running into this problem when trying to use the Spatie/db-snapshots package with the .env set to Production

It works fine if I change the .env to local

I've looked carefully in the package code and can't find where the package itself is calling ->force() so I think the problem might maybe be to do with confirmToProceed or ConfirmableTrait below?

```
[2017-09-25 15:21:28] production.ERROR: The "force" option does not exist. {"exception":"[object] (Symfony\\Component\\Console\\Exception\\InvalidArgumentException(code: 0): The \"force\" option does not exist. at /home/forge/xxx.xxx/current/vendor/symfony/console/Input/Input.php:158)
[stacktrace]
#0 /home/forge/xxx.xxx/current/vendor/laravel/framework/src/Illuminate/Console/Command.php(274): Symfony\\Component\\Console\\Input\\Input->getOption('force')
#1 /home/forge/xxx.xxx/current/vendor/laravel/framework/src/Illuminate/Console/ConfirmableTrait.php(25): Illuminate\\Console\\Command->option('force')
#2 /home/forge/xxx.xxx/current/vendor/spatie/laravel-db-snapshots/src/Commands/Load.php(29): Spatie\\DbSnapshots\\Commands\\Load->confirmToProceed()
#3 [internal function]: Spatie\\DbSnapshots\\Commands\\Load->handle()
```

**Comment by Kyslik** [comment]
Perhaps report it to https://github.com/spatie/laravel-db-snapshots
