### ISSUE TITLE
[5.5] PHP Warning:  failed to open stream: Too many open files in /var/www/html/x/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Factory.php:203

### ISSUE THREAD

**Issue by andhikayuana** [laravel/framework#21824]
- Laravel Version: 5.5.18
- PHP Version: 7.0.24
- Database Driver & Version: mysql
- Module package using : https://github.com/caffeinated/modules

Im trying to load factory permodule to Module like this : 
```php
<?php

use Faker\Generator as Faker;

foreach(Module::enabled() as $moduleEnabled){
    $factory->load('app/Modules/'.$moduleEnabled['basename'].'/Database/Factories');
...
}
...
```
when im execute `php artisan module:seed` im get this error : 
```
PHP Warning:  Uncaught ErrorException: require(/var/www/html/ajaro/simdes/simdes-api/app/Modules/Core/Database/Factories/CoreFactory.php): failed to open stream: Too many open files in /var/www/html/ajaro/simdes/simdes-api/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Factory.php:203
Stack trace:
#0 /var/www/html/ajaro/simdes/simdes-api/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Factory.php(203): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'require(/var/ww...', '/var/www/html/a...', 203, Array)
#1 /var/www/html/ajaro/simdes/simdes-api/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Factory.php(203): require()
#2 /var/www/html/ajaro/simdes/simdes-api/database/factories/ModelFactory.php(8): Illuminate\Database\Eloquent\Factory->load('app/Modules/Cor...')
#3 /var/www/html/ajaro/simdes/simdes-api/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Factory.php(203): require('/var/www/html/a...')
#4 /var/www/html/ajaro/simdes/simdes-api/vendor/laravel/framework/src/ in /var/www/html/ajaro/simdes/simdes-api/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Factory.php on line 203
PHP Fatal error:  Illuminate\Database\Eloquent\Factory::load(): Failed opening required '/var/www/html/ajaro/simdes/simdes-api/app/Modules/Core/Database/Factories/CoreFactory.php' (include_path='.:/usr/share/php') in /var/www/html/ajaro/simdes/simdes-api/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Factory.php on line 203
PHP Fatal error:  Uncaught ErrorException: include(/var/www/html/ajaro/simdes/simdes-api/vendor/symfony/debug/Exception/FatalErrorException.php): failed to open stream: Too many open files in /var/www/html/ajaro/simdes/simdes-api/vendor/composer/ClassLoader.php:444
Stack trace:
#0 /var/www/html/ajaro/simdes/simdes-api/vendor/composer/ClassLoader.php(444): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'include(/var/ww...', '/var/www/html/a...', 444, Array)
#1 /var/www/html/ajaro/simdes/simdes-api/vendor/composer/ClassLoader.php(444): include()
#2 /var/www/html/ajaro/simdes/simdes-api/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/var/www/html/a...')
#3 [internal function]: Composer\Autoload\ClassLoader->loadClass('Symfony\\Compone...')
#4 /var/www/html/ajaro/simdes/simdes-api/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(136): spl_autoload_call('Symfony\\Compone...')
#5 /var/www/html/ajaro/simdes/simdes-api/vendor/laravel/framework/src/Illuminate/Foun in /var/www/html/ajaro/simdes/simdes-api/vendor/composer/ClassLoader.php on line 444
```
its behaviour load 1 file in multiple ? and how to load factory manual ?
thanks

**Comment by sisve** [comment]
Report this to the package owner at https://github.com/caffeinated/modules/issues instead.

**Comment by andhikayuana** [comment]
oke thanks
