### ISSUE TITLE
Job cannot find the sqlsrv driver but the web can?

### ISSUE THREAD

**Issue by Francismori7** [laravel/framework#22200]
- Laravel Version: 5.5.21 Latest 
- PHP Version: 7.2 (Homestead)
- Database Driver & Version: Using mysql, as well as sqlsrv

### Description: 
In my job, I'm using DB::connection('sqlsrv') to run a select query against a different DB setting than the generic mysql driver.

It works for every incoming request through API routes, regular WEB routes. However, when scheduling, running the same dispatch command (or even in tinker), I get a driver not found error:

```
[2017-11-24 00:00:02] local.DEBUG: Retrieve all products inventory was called.  
[2017-11-24 00:00:02] local.ERROR: could not find driver {"exception":"[object] (PDOException(code: 0): could not find driver at /home/vagrant/PhpstormProjects/stockapi/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:67)
[stacktrace]
#0 /home/vagrant/PhpstormProjects/stockapi/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(67): PDO->__construct('sqlsrv:Server=1...', 'WebUser', '*****************', Array)
#1 /home/vagrant/PhpstormProjects/stockapi/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(43): Illuminate\\Database\\Connectors\\Connector->createPdoConnection('sqlsrv:Server=1...', 'WebUser', '*****************', Array)
#2 /home/vagrant/PhpstormProjects/stockapi/vendor/laravel/framework/src/Illuminate/Database/Connectors/SqlServerConnector.php(32): Illuminate\\Database\\Connectors\\Connector->createConnection('sqlsrv:Server=1...', Array, Array)
#3 /home/vagrant/PhpstormProjects/stockapi/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php(183): Illuminate\\Database\\Connectors\\SqlServerConnector->connect(Array)
#4 [internal function]: Illuminate\\Database\\Connectors\\ConnectionFactory->Illuminate\\Database\\Connectors\\{closure}()
#5 /home/vagrant/PhpstormProjects/stockapi/vendor/laravel/framework/src/Illuminate/Database/Connection.php(915): call_user_func(Object(Closure))
#6 /home/vagrant/PhpstormProjects/stockapi/vendor/laravel/framework/src/Illuminate/Database/Connection.php(940): Illuminate\\Database\\Connection->getPdo()
#7 /home/vagrant/PhpstormProjects/stockapi/vendor/laravel/framework/src/Illuminate/Database/Connection.php(399): Illuminate\\Database\\Connection->getReadPdo()
#8 /home/vagrant/PhpstormProjects/stockapi/vendor/laravel/framework/src/Illuminate/Database/Connection.php(325): Illuminate\\Database\\Connection->getPdoForSelect(true)
#9 /home/vagrant/PhpstormProjects/stockapi/vendor/laravel/framework/src/Illuminate/Database/Connection.php(657): Illuminate\\Database\\Connection->Illuminate\\Database\\{closure}('SELECT\
\
  dbo.A...', Array)
#10 /home/vagrant/PhpstormProjects/stockapi/vendor/laravel/framework/src/Illuminate/Database/Connection.php(624): Illuminate\\Database\\Connection->runQueryCallback('SELECT\
\
  dbo.A...', Array, Object(Closure))
#11 /home/vagrant/PhpstormProjects/stockapi/vendor/laravel/framework/src/Illuminate/Database/Connection.php(333): Illuminate\\Database\\Connection->run('SELECT\
\
  dbo.A...', Array, Object(Closure))
#12 /home/vagrant/PhpstormProjects/stockapi/app/Services/G2.php(132): Illuminate\\Database\\Connection->select('SELECT\
\
  dbo.A...')
#13 /home/vagrant/PhpstormProjects/stockapi/app/Jobs/RetrieveAllProductsInventory.php(42): App\\Services\\G2->retrieveAllActiveProducts()
#14 /home/vagrant/PhpstormProjects/stockapi/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(327): App\\Jobs\\RetrieveAllProductsInventory->App\\Jobs\\{closure}()
#15 /home/vagrant/PhpstormProjects/stockapi/vendor/laravel/framework/src/Illuminate/Cache/CacheManager.php(304): Illuminate\\Cache\\Repository->remember('allStocks', 30, Object(Closure))
#16 /home/vagrant/PhpstormProjects/stockapi/app/Jobs/RetrieveAllProductsInventory.php(51): Illuminate\\Cache\\CacheManager->__call('remember', Array)
#17 [internal function]: App\\Jobs\\RetrieveAllProductsInventory->handle()
#18 /home/vagrant/PhpstormProjects/stockapi/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#19 /home/vagrant/PhpstormProjects/stockapi/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#20 /home/vagrant/PhpstormProjects/stockapi/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#21 /home/vagrant/PhpstormProjects/stockapi/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#22 /home/vagrant/PhpstormProjects/stockapi/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\\Container\\Container->call(Array)
#23 /home/vagrant/PhpstormProjects/stockapi/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(114): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}(Object(App\\Jobs\\RetrieveAllProductsInventory))
#24 /home/vagrant/PhpstormProjects/stockapi/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(App\\Jobs\\RetrieveAllProductsInventory))
#25 /home/vagrant/PhpstormProjects/stockapi/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#26 /home/vagrant/PhpstormProjects/stockapi/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(75): Illuminate\\Bus\\Dispatcher->dispatchNow(Object(App\\Jobs\\RetrieveAllProductsInventory))
#27 /home/vagrant/PhpstormProjects/stockapi/vendor/laravel/framework/src/Illuminate/Foundation/Bus/PendingDispatch.php(112): Illuminate\\Bus\\Dispatcher->dispatch(Object(App\\Jobs\\RetrieveAllProductsInventory))
#28 /home/vagrant/PhpstormProjects/stockapi/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(383): Illuminate\\Foundation\\Bus\\PendingDispatch->__destruct()
#29 /home/vagrant/PhpstormProjects/stockapi/app/Console/Kernel.php(35): dispatch(Object(App\\Jobs\\RetrieveAllProductsInventory))
#30 [internal function]: App\\Console\\Kernel->App\\Console\\{closure}()
#31 /home/vagrant/PhpstormProjects/stockapi/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Object(Closure), Array)
#32 /home/vagrant/PhpstormProjects/stockapi/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(75): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#33 /home/vagrant/PhpstormProjects/stockapi/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Object(Closure), Object(Closure))
#34 /home/vagrant/PhpstormProjects/stockapi/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Object(Closure), Array, NULL)
#35 /home/vagrant/PhpstormProjects/stockapi/vendor/laravel/framework/src/Illuminate/Console/Scheduling/CallbackEvent.php(70): Illuminate\\Container\\Container->call(Object(Closure), Array)
#36 /home/vagrant/PhpstormProjects/stockapi/vendor/laravel/framework/src/Illuminate/Console/Scheduling/ScheduleRunCommand.php(59): Illuminate\\Console\\Scheduling\\CallbackEvent->run(Object(Illuminate\\Foundation\\Application))
#37 [internal function]: Illuminate\\Console\\Scheduling\\ScheduleRunCommand->handle()
#38 /home/vagrant/PhpstormProjects/stockapi/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#39 /home/vagrant/PhpstormProjects/stockapi/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#40 /home/vagrant/PhpstormProjects/stockapi/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#41 /home/vagrant/PhpstormProjects/stockapi/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#42 /home/vagrant/PhpstormProjects/stockapi/vendor/laravel/framework/src/Illuminate/Console/Command.php(180): Illuminate\\Container\\Container->call(Array)
#43 /home/vagrant/PhpstormProjects/stockapi/vendor/symfony/console/Command/Command.php(240): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#44 /home/vagrant/PhpstormProjects/stockapi/vendor/laravel/framework/src/Illuminate/Console/Command.php(167): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#45 /home/vagrant/PhpstormProjects/stockapi/vendor/symfony/console/Application.php(858): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#46 /home/vagrant/PhpstormProjects/stockapi/vendor/symfony/console/Application.php(216): Symfony\\Component\\Console\\Application->doRunCommand(Object(Illuminate\\Console\\Scheduling\\ScheduleRunCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#47 /home/vagrant/PhpstormProjects/stockapi/vendor/symfony/console/Application.php(122): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#48 /home/vagrant/PhpstormProjects/stockapi/vendor/laravel/framework/src/Illuminate/Console/Application.php(88): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#49 /home/vagrant/PhpstormProjects/stockapi/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#50 /home/vagrant/PhpstormProjects/stockapi/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#51 {main}
"} 
[2017-11-24 00:00:02] local.ERROR: could not find driver (SQL: SELECT
  dbo.Articles.NoArticle,
  dbo.Articles.Description,
  dbo.Articles.Manufacturier,
  dbo.Articles.NoArticleManufacturier,
  dbo.Articles.Catégorie1,
  dbo.Articles.Actif,
  RIGHT(dbo.Articles.Alias1, 1) AS 'Saison',
  dbo.[PDVO CatégorieCodeGL].Description AS 'DescriptionProduit'
FROM dbo.Articles
LEFT JOIN dbo.[PDVO CatégorieCodeGL] ON dbo.Articles.Catégorie1 = dbo.[PDVO CatégorieCodeGL].Catégorie1
WHERE dbo.Articles.Actif = 1
      AND dbo.Articles.Alias2 = 'PNEUS'
      AND dbo.Articles.Manufacturier NOT IN ('ODESSA', 'NOKIAN')
      AND dbo.Articles.Catégorie1 <> 'PLOURDS'
ORDER BY dbo.Articles.NoArticle) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 0): could not find driver (SQL: SELECT
  dbo.Articles.NoArticle,
  dbo.Articles.Description,
  dbo.Articles.Manufacturier,
  dbo.Articles.NoArticleManufacturier,
  dbo.Articles.Catégorie1,
  dbo.Articles.Actif,
  RIGHT(dbo.Articles.Alias1, 1) AS 'Saison',
  dbo.[PDVO CatégorieCodeGL].Description AS 'DescriptionProduit'
FROM dbo.Articles
LEFT JOIN dbo.[PDVO CatégorieCodeGL] ON dbo.Articles.Catégorie1 = dbo.[PDVO CatégorieCodeGL].Catégorie1
WHERE dbo.Articles.Actif = 1
      AND dbo.Articles.Alias2 = 'PNEUS'
      AND dbo.Articles.Manufacturier NOT IN ('ODESSA', 'NOKIAN')
      AND dbo.Articles.Catégorie1 <> 'PLOURDS'
ORDER BY dbo.Articles.NoArticle) at /home/vagrant/PhpstormProjects/stockapi/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664, PDOException(code: 0): could not find driver at /home/vagrant/PhpstormProjects/stockapi/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:67)
[stacktrace]
#0 /home/vagrant/PhpstormProjects/stockapi/vendor/laravel/framework/src/Illuminate/Database/Connection.php(624): Illuminate\\Database\\Connection->runQueryCallback('SELECT\
\
  dbo.A...', Array, Object(Closure))
#1 /home/vagrant/PhpstormProjects/stockapi/vendor/laravel/framework/src/Illuminate/Database/Connection.php(333): Illuminate\\Database\\Connection->run('SELECT\
\
  dbo.A...', Array, Object(Closure))
#2 /home/vagrant/PhpstormProjects/stockapi/app/Services/G2.php(132): Illuminate\\Database\\Connection->select('SELECT\
\
  dbo.A...')
#3 /home/vagrant/PhpstormProjects/stockapi/app/Jobs/RetrieveAllProductsInventory.php(42): App\\Services\\G2->retrieveAllActiveProducts()
#4 /home/vagrant/PhpstormProjects/stockapi/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(327): App\\Jobs\\RetrieveAllProductsInventory->App\\Jobs\\{closure}()
#5 /home/vagrant/PhpstormProjects/stockapi/vendor/laravel/framework/src/Illuminate/Cache/CacheManager.php(304): Illuminate\\Cache\\Repository->remember('allStocks', 30, Object(Closure))
#6 /home/vagrant/PhpstormProjects/stockapi/app/Jobs/RetrieveAllProductsInventory.php(51): Illuminate\\Cache\\CacheManager->__call('remember', Array)
#7 [internal function]: App\\Jobs\\RetrieveAllProductsInventory->handle()
#8 /home/vagrant/PhpstormProjects/stockapi/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#9 /home/vagrant/PhpstormProjects/stockapi/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#10 /home/vagrant/PhpstormProjects/stockapi/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#11 /home/vagrant/PhpstormProjects/stockapi/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#12 /home/vagrant/PhpstormProjects/stockapi/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\\Container\\Container->call(Array)
#13 /home/vagrant/PhpstormProjects/stockapi/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(114): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}(Object(App\\Jobs\\RetrieveAllProductsInventory))
#14 /home/vagrant/PhpstormProjects/stockapi/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(App\\Jobs\\RetrieveAllProductsInventory))
#15 /home/vagrant/PhpstormProjects/stockapi/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#16 /home/vagrant/PhpstormProjects/stockapi/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(75): Illuminate\\Bus\\Dispatcher->dispatchNow(Object(App\\Jobs\\RetrieveAllProductsInventory))
#17 /home/vagrant/PhpstormProjects/stockapi/vendor/laravel/framework/src/Illuminate/Foundation/Bus/PendingDispatch.php(112): Illuminate\\Bus\\Dispatcher->dispatch(Object(App\\Jobs\\RetrieveAllProductsInventory))
#18 /home/vagrant/PhpstormProjects/stockapi/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(383): Illuminate\\Foundation\\Bus\\PendingDispatch->__destruct()
#19 /home/vagrant/PhpstormProjects/stockapi/app/Console/Kernel.php(35): dispatch(Object(App\\Jobs\\RetrieveAllProductsInventory))
#20 [internal function]: App\\Console\\Kernel->App\\Console\\{closure}()
#21 /home/vagrant/PhpstormProjects/stockapi/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Object(Closure), Array)
#22 /home/vagrant/PhpstormProjects/stockapi/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(75): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#23 /home/vagrant/PhpstormProjects/stockapi/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Object(Closure), Object(Closure))
#24 /home/vagrant/PhpstormProjects/stockapi/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Object(Closure), Array, NULL)
#25 /home/vagrant/PhpstormProjects/stockapi/vendor/laravel/framework/src/Illuminate/Console/Scheduling/CallbackEvent.php(70): Illuminate\\Container\\Container->call(Object(Closure), Array)
#26 /home/vagrant/PhpstormProjects/stockapi/vendor/laravel/framework/src/Illuminate/Console/Scheduling/ScheduleRunCommand.php(59): Illuminate\\Console\\Scheduling\\CallbackEvent->run(Object(Illuminate\\Foundation\\Application))
#27 [internal function]: Illuminate\\Console\\Scheduling\\ScheduleRunCommand->handle()
#28 /home/vagrant/PhpstormProjects/stockapi/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#29 /home/vagrant/PhpstormProjects/stockapi/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#30 /home/vagrant/PhpstormProjects/stockapi/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#31 /home/vagrant/PhpstormProjects/stockapi/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#32 /home/vagrant/PhpstormProjects/stockapi/vendor/laravel/framework/src/Illuminate/Console/Command.php(180): Illuminate\\Container\\Container->call(Array)
#33 /home/vagrant/PhpstormProjects/stockapi/vendor/symfony/console/Command/Command.php(240): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#34 /home/vagrant/PhpstormProjects/stockapi/vendor/laravel/framework/src/Illuminate/Console/Command.php(167): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#35 /home/vagrant/PhpstormProjects/stockapi/vendor/symfony/console/Application.php(858): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#36 /home/vagrant/PhpstormProjects/stockapi/vendor/symfony/console/Application.php(216): Symfony\\Component\\Console\\Application->doRunCommand(Object(Illuminate\\Console\\Scheduling\\ScheduleRunCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#37 /home/vagrant/PhpstormProjects/stockapi/vendor/symfony/console/Application.php(122): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#38 /home/vagrant/PhpstormProjects/stockapi/vendor/laravel/framework/src/Illuminate/Console/Application.php(88): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#39 /home/vagrant/PhpstormProjects/stockapi/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#40 /home/vagrant/PhpstormProjects/stockapi/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#41 {main}
"} 
```

Note that I'm using the Redis cache and queue in Homestead.

Here is the code for both the API controller, the scheduler, and the job itself:

```
// Controller
return dispatch_now(new RetrieveAllProductsInventory());

// Scheduler
$schedule->call(function() {
    dispatch(new RetrieveAllProductsInventory());
})->everyMinute();

// Job
class RetrieveAllProductsInventory
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    /**
     * Execute the job.
     * @throws \Exception
     */
    public function handle()
    {
        \Log::debug('Retrieve all products inventory was called.');

        return cache()->remember('allStocks', 30, function () {
            $data = collect();
            collect(app(G2::class)->retrieveAllActiveProducts())
                ->chunk(1000)
                ->each(function ($products) use ($data) {
                    collect(app(StocksFinder::class)->findMultiple($products->pluck('NoArticle')->toArray()))
                        ->each(function ($qty, $product) use ($data) {
                            $data->put($product, $qty);
                        });
                });
            return $data;
        });
    }
}

// retrieveAllActiveProducts() in G2::class (where it fails)
public function retrieveAllActiveProducts()
{
    return \DB::connection('g2')->select("SELECT
dbo.Articles.NoArticle,
dbo.Articles.Description,
dbo.Articles.Manufacturier,
dbo.Articles.NoArticleManufacturier,
dbo.Articles.Catégorie1,
dbo.Articles.Actif,
RIGHT(dbo.Articles.Alias1, 1) AS 'Saison',
dbo.[PDVO CatégorieCodeGL].Description AS 'DescriptionProduit'
FROM dbo.Articles
LEFT JOIN dbo.[PDVO CatégorieCodeGL] ON dbo.Articles.Catégorie1 = dbo.[PDVO CatégorieCodeGL].Catégorie1
WHERE dbo.Articles.Actif = 1
  AND dbo.Articles.Alias2 = 'PNEUS'
  AND dbo.Articles.Manufacturier NOT IN ('ODESSA', 'NOKIAN')
  AND dbo.Articles.Catégorie1 <> 'PLOURDS'
ORDER BY dbo.Articles.NoArticle");
}
```

**Comment by sisve** [comment]
Many distributions has two separate php.ini files, one for web requests (fpm) and one for console (cli). It sounds like you've only enabled the sqlsrv extension/driver in the php.ini that controls your fpm process.

**Comment by themsaid** [comment]
Please ask on the forums, this repo is for bug reporting only. You can use https://laracasts.com/discuss or https://laravel.io/forum which are forums with a very large community of developers helping each other.

**Comment by Francismori7** [comment]
@sisve Thanks, you were right.

Weird how I cannot select php7.2 as the cli using update-alternatives though, it says it's not registered...
