### ISSUE TITLE
Redis as session storage "Cannot assign requested address"

### ISSUE THREAD

**Issue by avengerweb** [laravel/framework#22258]
- Laravel Version: 5.5.21
- PHP Version: 7.1
- Database Driver & Version: mysql 5.7, Redis server v=3.2.11 sha=00000000:0 malloc=jemalloc-4.0.3 bits=64 build=c9f2a36594be9567

### Description:
```
[2017-11-29 07:00:56] production.ERROR: Cannot assign requested address [tcp://localhost:6379] {"exception":"[object] (Predis\\Connection\\ConnectionException(code: 99): Cannot assign requested address [tcp://localhost:6379] at /home/www/blabla/data/www/blabla.su/vendor/predis/predis/src/Connection/AbstractConnection.php:155)
[stacktrace]
#0 /home/www/blabla/data/www/blabla.su/vendor/predis/predis/src/Connection/StreamConnection.php(128): Predis\\Connection\\AbstractConnection->onConnectionError('Cannot assign r...', 99)
#1 /home/www/blabla/data/www/blabla.su/vendor/predis/predis/src/Connection/StreamConnection.php(178): Predis\\Connection\\StreamConnection->createStreamSocket(Object(Predis\\Connection\\Parameters), 'tcp://localhost...', 4)
#2 /home/www/blabla/data/www/blabla.su/vendor/predis/predis/src/Connection/StreamConnection.php(100): Predis\\Connection\\StreamConnection->tcpStreamInitializer(Object(Predis\\Connection\\Parameters))
#3 /home/www/blabla/data/www/blabla.su/vendor/predis/predis/src/Connection/AbstractConnection.php(81): Predis\\Connection\\StreamConnection->createResource()
#4 /home/www/blabla/data/www/blabla.su/vendor/predis/predis/src/Connection/StreamConnection.php(258): Predis\\Connection\\AbstractConnection->connect()
#5 /home/www/blabla/data/www/blabla.su/vendor/predis/predis/src/Connection/AbstractConnection.php(180): Predis\\Connection\\StreamConnection->connect()
#6 /home/www/blabla/data/www/blabla.su/vendor/predis/predis/src/Connection/StreamConnection.php(288): Predis\\Connection\\AbstractConnection->getResource()
\7 /home/www/blabla/data/www/blabla.su/vendor/predis/predis/src/Connection/StreamConnection.php(394): Predis\\Connection\\StreamConnection->write('*2\
\3\
\ET\
$4...')
#8 /home/www/blabla/data/www/blabla.su/vendor/predis/predis/src/Connection/AbstractConnection.php(110): Predis\\Connection\\StreamConnection->writeRequest(Object(Predis\\Command\\StringGet))
#9 /home/www/blabla/data/www/blabla.su/vendor/predis/predis/src/Client.php(331): Predis\\Connection\\AbstractConnection->executeCommand(Object(Predis\\Command\\StringGet))
#10 /home/www/blabla/data/www/blabla.su/vendor/predis/predis/src/Client.php(314): Predis\\Client->executeCommand(Object(Predis\\Command\\StringGet))
#11 /home/www/blabla/data/www/blabla.su/vendor/laravel/framework/src/Illuminate/Redis/Connections/Connection.php(96): Predis\\Client->__call('get', Array)
#12 /home/www/blabla/data/www/blabla.su/vendor/laravel/framework/src/Illuminate/Redis/Connections/Connection.php(108): Illuminate\\Redis\\Connections\\Connection->command('get', Array)
#13 /home/www/blabla/data/www/blabla.su/vendor/laravel/framework/src/Illuminate/Cache/RedisStore.php(54): Illuminate\\Redis\\Connections\\Connection->__call('get', Array)
#14 /home/www/blabla/data/www/blabla.su/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(86): Illuminate\\Cache\\RedisStore->get('TCFD6grn56t21IK...')
#15 /home/www/blabla/data/www/blabla.su/vendor/laravel/framework/src/Illuminate/Session/CacheBasedSessionHandler.php(58): Illuminate\\Cache\\Repository->get('TCFD6grn56t21IK...', '')
#16 /home/www/blabla/data/www/blabla.su/vendor/laravel/framework/src/Illuminate/Session/Store.php(96): Illuminate\\Session\\CacheBasedSessionHandler->read('TCFD6grn56t21IK...')
#17 /home/www/blabla/data/www/blabla.su/vendor/laravel/framework/src/Illuminate/Session/Store.php(86): Illuminate\\Session\\Store->readFromHandler()
#18 /home/www/blabla/data/www/blabla.su/vendor/laravel/framework/src/Illuminate/Session/Store.php(70): Illuminate\\Session\\Store->loadSession()
#19 /home/www/blabla/data/www/blabla.su/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(102): Illuminate\\Session\\Store->start()
#20 /home/www/blabla/data/www/blabla.su/vendor/laravel/framework/src/Illuminate/Support/helpers.php(1035): Illuminate\\Session\\Middleware\\StartSession->Illuminate\\Session\\Middleware\\{closure}(Object(Illuminate\\Session\\Store))
#21 /home/www/blabla/data/www/blabla.su/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(103): tap(Object(Illuminate\\Session\\Store), Object(Closure))
#22 /home/www/blabla/data/www/blabla.su/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(57): Illuminate\\Session\\Middleware\\StartSession->startSession(Object(Illuminate\\Http\\Request))
#23 /home/www/blabla/data/www/blabla.su/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#24 /home/www/blabla/data/www/blabla.su/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#25 /home/www/blabla/data/www/blabla.su/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#26 /home/www/blabla/data/www/blabla.su/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#27 /home/www/blabla/data/www/blabla.su/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#28 /home/www/blabla/data/www/blabla.su/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#29 /home/www/blabla/data/www/blabla.su/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#30 /home/www/blabla/data/www/blabla.su/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#31 /home/www/blabla/data/www/blabla.su/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#32 /home/www/blabla/data/www/blabla.su/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#33 /home/www/blabla/data/www/blabla.su/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#34 /home/www/blabla/data/www/blabla.su/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#35 /home/www/blabla/data/www/blabla.su/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#36 /home/www/blabla/data/www/blabla.su/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#37 /home/www/blabla/data/www/blabla.su/public/index.php(53): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#38 {main}
"}
```
### Steps To Reproduce:
no idea...

**Comment by avengerweb** [comment]
Ok, maybe that is not laravel or redis problems.

https://redis4you.com/articles.php?id=012&name=redis

**Comment by themsaid** [comment]
Please ask on the forums, this repo is for bug reporting only. You can use https://laracasts.com/discuss or https://laravel.io/forum which are forums with a very large community of developers helping each other.
