### ISSUE TITLE
PHP 7.2 Fatal error: Uncaught Illuminate\Contracts\Container\BindingResolutionException

### ISSUE THREAD

**Issue by brendt** [laravel/framework#22270]
- Laravel Version: 5.5.22
- PHP Version: 7.2.0RC6
- Database Driver & Version: /

### Description:

I saw this fatal error occur when running PHPUnit tests for a Laravel package.

```
PHP Fatal error:  Uncaught Illuminate\Contracts\Container\BindingResolutionException: Target [Illuminate\Contracts\Debug\ExceptionHandler] is not instantiable. in /home/travis/build/spatie/laravel-binary-uuid/vendor/laravel/framework/src/Illuminate/Container/Container.php:918
Stack trace:
#0 /home/travis/build/spatie/laravel-binary-uuid/vendor/laravel/framework/src/Illuminate/Container/Container.php(758): Illuminate\Container\Container->notInstantiable('Illuminate\\Cont...')
#1 /home/travis/build/spatie/laravel-binary-uuid/vendor/laravel/framework/src/Illuminate/Container/Container.php(631): Illuminate\Container\Container->build('Illuminate\\Cont...')
#2 /home/travis/build/spatie/laravel-binary-uuid/vendor/laravel/framework/src/Illuminate/Container/Container.php(586): Illuminate\Container\Container->resolve('Illuminate\\Cont...', Array)
#3 /home/travis/build/spatie/laravel-binary-uuid/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(732): Illuminate\Container\Container->make('Illuminate\\Cont...', Array)
#4 / in /home/travis/build/spatie/laravel-binary-uuid/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 918
```

### Steps To Reproduce:

An example of this error in the wild: https://travis-ci.org/spatie/laravel-binary-uuid/jobs/309911937

**Comment by crynobone** [comment]
You have a warning on deprecated `each()` usage and only the code coverage generation failed. Depending on your setup this would typical failed on parsing none class based file such as routes etc.

**Comment by brendt** [comment]
Updating PHPUnit to ^6.5 also gets rid of this error.
