### ISSUE TITLE
UploadFile::fake() not working when moving the created file

### ISSUE THREAD

**Issue by hamzaali00001** [laravel/framework#23157]
- Laravel Version: 5.5.34
- PHP Version:7.1.9
- Database Driver & Version:

When moving the UploadedFile::fake() created image, php thrown an exception. I am testing file uploads. My store method is perfectly fine and it is working in the browser. Here is the response of the request that I debugged:

```
[2018-02-14 10:59:24] local.ERROR: Could not move the file "C:\Users\Hamza\AppData\Local\Temp\phpED39.tmp" to "C:\wamp64\www\laravel\file-upload\public\/images\912aebff117ca7a325d99ef55261c4940e5c9c7c.jpeg" () {"exception":"[object] (Symfony\\Component\\HttpFoundation\\File\\Exception\\FileException(code: 0): Could not move the file \"C:\\Users\\Hamza\\AppData\\Local\\Temp\\phpED39.tmp\" to \"C:\\wamp64\\www\\laravel\\file-upload\\public\\/images\\912aebff117ca7a325d99ef55261c4940e5c9c7c.jpeg\" () at C:\\wamp64\\www\\laravel\\file-upload\\vendor\\symfony\\http-foundation\\File\\File.php:98)
[stacktrace]
#0 C:\\wamp64\\www\\laravel\\file-upload\\vendor\\symfony\\http-foundation\\File\\UploadedFile.php(190): Symfony\\Component\\HttpFoundation\\File\\File->move('C:\\\\wamp64\\\\www\\\\l...', '912aebff117ca7a...')
#1 C:\\wamp64\\www\\laravel\\file-upload\\app\\Http\\Controllers\\UploadImagesController.php(72): Symfony\\Component\\HttpFoundation\\File\\UploadedFile->move('C:\\\\wamp64\\\\www\\\\l...', '912aebff117ca7a...')
#2 [internal function]: App\\Http\\Controllers\\UploadImagesController->store(Object(Illuminate\\Http\\Request))
#3 C:\\wamp64\\www\\laravel\\file-upload\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Controller.php(54): call_user_func_array(Array, Array)
#4 C:\\wamp64\\www\\laravel\\file-upload\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('store', Array)
#5 C:\\wamp64\\www\\laravel\\file-upload\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php(212): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Http\\Controllers\\UploadImagesController), 'store')
#6 C:\\wamp64\\www\\laravel\\file-upload\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php(169): Illuminate\\Routing\\Route->runController()
#7 C:\\wamp64\\www\\laravel\\file-upload\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(658): Illuminate\\Routing\\Route->run()
#8 C:\\wamp64\\www\\laravel\\file-upload\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#9 C:\\wamp64\\www\\laravel\\file-upload\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Middleware\\SubstituteBindings.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#10 C:\\wamp64\\www\\laravel\\file-upload\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(149): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#11 C:\\wamp64\\www\\laravel\\file-upload\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#12 C:\\wamp64\\www\\laravel\\file-upload\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken.php(67): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#13 C:\\wamp64\\www\\laravel\\file-upload\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#14 C:\\wamp64\\www\\laravel\\file-upload\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#15 C:\\wamp64\\www\\laravel\\file-upload\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(49): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#16 C:\\wamp64\\www\\laravel\\file-upload\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(149): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#17 C:\\wamp64\\www\\laravel\\file-upload\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#18 C:\\wamp64\\www\\laravel\\file-upload\\vendor\\laravel\\framework\\src\\Illuminate\\Session\\Middleware\\StartSession.php(63): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#19 C:\\wamp64\\www\\laravel\\file-upload\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(149): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#20 C:\\wamp64\\www\\laravel\\file-upload\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#21 C:\\wamp64\\www\\laravel\\file-upload\\vendor\\laravel\\framework\\src\\Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse.php(37): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#22 C:\\wamp64\\www\\laravel\\file-upload\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(149): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#23 C:\\wamp64\\www\\laravel\\file-upload\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#24 C:\\wamp64\\www\\laravel\\file-upload\\vendor\\laravel\\framework\\src\\Illuminate\\Cookie\\Middleware\\EncryptCookies.php(59): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#25 C:\\wamp64\\www\\laravel\\file-upload\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(149): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#26 C:\\wamp64\\www\\laravel\\file-upload\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#27 C:\\wamp64\\www\\laravel\\file-upload\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#28 C:\\wamp64\\www\\laravel\\file-upload\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(660): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#29 C:\\wamp64\\www\\laravel\\file-upload\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(635): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#30 C:\\wamp64\\www\\laravel\\file-upload\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(601): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#31 C:\\wamp64\\www\\laravel\\file-upload\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(590): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#32 C:\\wamp64\\www\\laravel\\file-upload\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#33 C:\\wamp64\\www\\laravel\\file-upload\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#34 C:\\wamp64\\www\\laravel\\file-upload\\vendor\\fideloper\\proxy\\src\\TrustProxies.php(56): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#35 C:\\wamp64\\www\\laravel\\file-upload\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(149): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#36 C:\\wamp64\\www\\laravel\\file-upload\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#37 C:\\wamp64\\www\\laravel\\file-upload\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(30): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#38 C:\\wamp64\\www\\laravel\\file-upload\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#39 C:\\wamp64\\www\\laravel\\file-upload\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#40 C:\\wamp64\\www\\laravel\\file-upload\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(30): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#41 C:\\wamp64\\www\\laravel\\file-upload\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#42 C:\\wamp64\\www\\laravel\\file-upload\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#43 C:\\wamp64\\www\\laravel\\file-upload\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#44 C:\\wamp64\\www\\laravel\\file-upload\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#45 C:\\wamp64\\www\\laravel\\file-upload\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#46 C:\\wamp64\\www\\laravel\\file-upload\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode.php(46): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#47 C:\\wamp64\\www\\laravel\\file-upload\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#48 C:\\wamp64\\www\\laravel\\file-upload\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#49 C:\\wamp64\\www\\laravel\\file-upload\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#50 C:\\wamp64\\www\\laravel\\file-upload\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#51 C:\\wamp64\\www\\laravel\\file-upload\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#52 C:\\wamp64\\www\\laravel\\file-upload\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Testing\\Concerns\\MakesHttpRequests.php(345): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#53 C:\\wamp64\\www\\laravel\\file-upload\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Testing\\Concerns\\MakesHttpRequests.php(317): Illuminate\\Foundation\\Testing\\TestCase->call('post', '/images-save', Array, Array, Array, Array, '{\"file\":[]}')
#54 C:\\wamp64\\www\\laravel\\file-upload\\tests\\Feature\\UploadTest.php(25): Illuminate\\Foundation\\Testing\\TestCase->json('post', '/images-save', Array)
#55 [internal function]: Tests\\Feature\\UploadTest->testImagesUpload()
#56 C:\\wamp64\\www\\laravel\\file-upload\\vendor\\phpunit\\phpunit\\src\\Framework\\TestCase.php(1071): ReflectionMethod->invokeArgs(Object(Tests\\Feature\\UploadTest), Array)
#57 C:\\wamp64\\www\\laravel\\file-upload\\vendor\\phpunit\\phpunit\\src\\Framework\\TestCase.php(939): PHPUnit\\Framework\\TestCase->runTest()
#58 C:\\wamp64\\www\\laravel\\file-upload\\vendor\\phpunit\\phpunit\\src\\Framework\\TestResult.php(698): PHPUnit\\Framework\\TestCase->runBare()
#59 C:\\wamp64\\www\\laravel\\file-upload\\vendor\\phpunit\\phpunit\\src\\Framework\\TestCase.php(894): PHPUnit\\Framework\\TestResult->run(Object(Tests\\Feature\\UploadTest))
#60 C:\\wamp64\\www\\laravel\\file-upload\\vendor\\phpunit\\phpunit\\src\\Framework\\TestSuite.php(755): PHPUnit\\Framework\\TestCase->run(Object(PHPUnit\\Framework\\TestResult))
#61 C:\\wamp64\\www\\laravel\\file-upload\\vendor\\phpunit\\phpunit\\src\\Framework\\TestSuite.php(755): PHPUnit\\Framework\\TestSuite->run(Object(PHPUnit\\Framework\\TestResult))
#62 C:\\wamp64\\www\\laravel\\file-upload\\vendor\\phpunit\\phpunit\\src\\Framework\\TestSuite.php(755): PHPUnit\\Framework\\TestSuite->run(Object(PHPUnit\\Framework\\TestResult))
#63 C:\\wamp64\\www\\laravel\\file-upload\\vendor\\phpunit\\phpunit\\src\\TextUI\\TestRunner.php(546): PHPUnit\\Framework\\TestSuite->run(Object(PHPUnit\\Framework\\TestResult))
#64 C:\\wamp64\\www\\laravel\\file-upload\\vendor\\phpunit\\phpunit\\src\\TextUI\\Command.php(195): PHPUnit\\TextUI\\TestRunner->doRun(Object(PHPUnit\\Framework\\TestSuite), Array, true)
#65 C:\\wamp64\\www\\laravel\\file-upload\\vendor\\phpunit\\phpunit\\src\\TextUI\\Command.php(148): PHPUnit\\TextUI\\Command->run(Array, true)
#66 C:\\wamp64\\www\\laravel\\file-upload\\vendor\\phpunit\\phpunit\\phpunit(53): PHPUnit\\TextUI\\Command::main()
#67 {main}
"} 
```

### Steps To Reproduce:

**testImagesUpload**

```php
<?php

namespace Tests\Feature;

use App\Upload;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Http\UploadedFile;
use Tests\TestCase;

class UploadTest extends TestCase
{

    use RefreshDatabase;

    public function testImagesUpload()
    {
        $response = $this->json('post', '/images-save', [
            'file' => [
                UploadedFile::fake()->image('testing.jpeg'),
            ]
        ]);

        $files = Upload::all();

        $this->assertDatabaseHas('uploads', ['original_name' => 'testing.jpeg']);
        $this->assertDatabaseHas('uploads', ['original_name' => '123.jpeg']);

        foreach ($files as $file) {
            $this->assertFileExists(public_path('/images') . $file->filename);
            $this->assertFileExists(public_path('/images/') . $file->resized_name);
        }
    }
}
```

**Here is my store method which is called when `/images-save` endpoint is hit:**

```php
public function store(Request $request)
    {
        $photos = $request->file('file');

        if (!is_array($photos)) {
            $photos = [$photos];
        }

        if (!is_dir($this->photos_path)) {
            mkdir($this->photos_path, 0777);
        }

        for ($i = 0; $i < count($photos); $i++) {
            $photo = $photos[$i];
            $name = sha1(date('YmdHis') . str_random(30));
            $save_name = $name . '.' . $photo->getClientOriginalExtension();
            $resize_name = $name . str_random(2) . '.' . $photo->getClientOriginalExtension();

            Image::make($photo)
                ->resize(250, null, function ($constraints) {
                    $constraints->aspectRatio();
                })
                ->save($this->photos_path . '/' . $resize_name);
            $photo->move($this->photos_path, $save_name);

            $upload = new Upload();
            $upload->filename = $save_name;
            $upload->resized_name = $resize_name;
            $upload->original_name = basename($photo->getClientOriginalName());
            $upload->save();
        }

        return Response::json([
            'message' => 'Image saved Successfully'
        ], 200);
    }
```

**App\Upload model is empty. Also, one important thing is that, resizing using intervention library works perfectly and resize image is stored in public/images directory. It also passes it's test. Problem is coming on the $photo->move($this->photos_path, $save_name);**

**Comment by mcklayin** [comment]
Hi @hamzaali00001 
Did you try it like in docs:
`$response = $this->json('post', '/images-save', [
        'file' => UploadedFile::fake()->image('testing.jpeg'),
    ]);`

**Comment by driesvints** [comment]
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.

**Comment by oluebubesyd** [comment]
@hamzaali00001  @driesvints Please what is the fix for this issue?

**Comment by frank505** [comment]
please what is the fix?

**Comment by poovarasudev** [comment]
@driesvints Please let us know what is the fix ?
