### ISSUE TITLE
Error when upgrading to PHPUnit 6.5 (from 5.5) w/ Laravel 5.1 LTS

### ISSUE THREAD

**Issue by mfour-merickson** [laravel/framework#23673]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 6.5.3
| PHP version         | 7.0.22
| Installation Method | Composer
| Laravel                     | 5.1.11 (LTS)

```
PHP Fatal error:  Uncaught Illuminate\Contracts\Container\BindingResolutionException: Target [Illuminate\Contracts\Debug\ExceptionHandler] is not instantiable. in /var/www/mfour_docker/vendor/laravel/framework/src/Illuminate/Container/Container.php:744
Stack trace:
#0 /var/www/mfour_docker/vendor/laravel/framework/src/Illuminate/Container/Container.php(626): Illuminate\Container\Container->build('Illuminate\\Cont...', Array)
#1 /var/www/mfour_docker/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(674): Illuminate\Container\Container->make('Illuminate\\Cont...', Array)
#2 /var/www/mfour_docker/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(154): Illuminate\Foundation\Application->make('Illuminate\\Cont...')
#3 /var/www/mfour_docker/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(79): Illuminate\Foundation\Bootstrap\HandleExceptions->getExceptionHandler()
#4 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleExceptio in /var/www/mfour_docker/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 744
PHP Fatal error:  Uncaught Illuminate\Contracts\Container\BindingResolutionException: Target [Illuminate\Contracts\Debug\ExceptionHandler] is not instantiable. in /var/www/mfour_docker/vendor/laravel/framework/src/Illuminate/Container/Container.php:744
Stack trace:
#0 /var/www/mfour_docker/vendor/laravel/framework/src/Illuminate/Container/Container.php(626): Illuminate\Container\Container->build('Illuminate\\Cont...', Array)
#1 /var/www/mfour_docker/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(674): Illuminate\Container\Container->make('Illuminate\\Cont...', Array)
#2 /var/www/mfour_docker/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(154): Illuminate\Foundation\Application->make('Illuminate\\Cont...')
#3 /var/www/mfour_docker/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(79): Illuminate\Foundation\Bootstrap\HandleExceptions->getExceptionHandler()
#4 /var/www/mfour_docker/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/Ha in /var/www/mfour_docker/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 744
```

**Comment by mfn** [comment]
> 5.1.11 (LTS)

This version isn't supported anymore (it would also receive "security fixes" until June 2018), please upgrade!
