### ISSUE TITLE
When running `npm run dev` getting this error `dep.getResourceIdentifier is not a function`

### ISSUE THREAD

**Issue by bulgariamitko** [laravel/framework#23943]
- Laravel Version: 5.6.17
- PHP Version: PHP 7.1.15-0ubuntu0.17.10.1 (cli)
- Database Driver & Version: mysql  Ver 14.14 Distrib 5.7.21, for Linux (x86_64) using  EditLine wrapper
- Node Version: 9.11.1
- NPM Version: 5.8.0
- Webpack Version: 4.6.0

### Description:
When running `npm run dev` I am getting this error `dep.getResourceIdentifier is not a function`
```
10% building modules 0/1 modules 1 active …ue-forms/resources/assets/sass/app.s 10% building modules 1/2 modules 1 active …JS/vue-forms/resources/assets/js/app 10% building modules 1/3 modules 2 active …ue-forms/resources/assets/sass/app.s 10% building modules 2/3 modules 1 active …JS/vue-forms/resources/assets/js/app 10% building modules 2/4 modules 2 active …ue-forms/resources/assets/sass/app.s 10% building modules 2/5 modules 3 active …e_modules/style-loader/lib/addStyles 10% building modules 3/5 modules 2 active …ue-forms/resources/assets/sass/app.s 10% building modules 4/5 modules 1 active …ue-forms/resources/assets/sass/app.s 10% building modules 4/6 modules 2 active …s/node_modules/style-loader/lib/urls 10% building modules 4/7 modules 3 active …-forms/resources/assets/js/bootstrap 10% building modules 5/7 modules 2 active …-forms/resources/assets/js/bootstrap 10% building modules 5/8 modules 3 active …rms/node_modules/vue/dist/vue.common 10% building modules 6/8 modules 2 active …-forms/resources/assets/js/bootstrap.jsTypeError: dep.getResourceIdentifier is not a function
    at addDependency (/var/www/html/demos/laracastSerials/22VueJS/vue-forms/node_modules/webpack/lib/Compilation.js:403:30)
    at iterationOfArrayCallback (/var/www/html/demos/laracastSerials/22VueJS/vue-forms/node_modules/webpack/lib/Compilation.js:88:3)
    at addDependenciesBlock (/var/www/html/demos/laracastSerials/22VueJS/vue-forms/node_modules/webpack/lib/Compilation.js:423:5)
    at Compilation.processModuleDependencies (/var/www/html/demos/laracastSerials/22VueJS/vue-forms/node_modules/webpack/lib/Compilation.js:434:4)
    at afterBuild (/var/www/html/demos/laracastSerials/22VueJS/vue-forms/node_modules/webpack/lib/Compilation.js:556:15)
    at buildModule.err (/var/www/html/demos/laracastSerials/22VueJS/vue-forms/node_modules/webpack/lib/Compilation.js:600:11)
    at callback (/var/www/html/demos/laracastSerials/22VueJS/vue-forms/node_modules/webpack/lib/Compilation.js:358:35)
    at module.build.error (/var/www/html/demos/laracastSerials/22VueJS/vue-forms/node_modules/webpack/lib/Compilation.js:394:12)
    at handleParseResult (/var/www/html/demos/laracastSerials/22VueJS/vue-forms/node_modules/webpack/lib/NormalModule.js:371:12)
    at doBuild.err (/var/www/html/demos/laracastSerials/22VueJS/vue-forms/node_modules/webpack/lib/NormalModule.js:393:6)
    at runLoaders (/var/www/html/demos/laracastSerials/22VueJS/vue-forms/node_modules/webpack/lib/NormalModule.js:272:12)
    at /var/www/html/demos/laracastSerials/22VueJS/vue-forms/node_modules/loader-runner/lib/LoaderRunner.js:370:3
    at iterateNormalLoaders (/var/www/html/demos/laracastSerials/22VueJS/vue-forms/node_modules/loader-runner/lib/LoaderRunner.js:211:10)
    at Array.<anonymous> (/var/www/html/demos/laracastSerials/22VueJS/vue-forms/node_modules/loader-runner/lib/LoaderRunner.js:202:4)
    at Storage.finished (/var/www/html/demos/laracastSerials/22VueJS/vue-forms/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:43:16)
    at provider (/var/www/html/demos/laracastSerials/22VueJS/vue-forms/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:79:9)
    at /var/www/html/demos/laracastSerials/22VueJS/vue-forms/node_modules/graceful-fs/graceful-fs.js:78:16
```

### Steps To Reproduce:
- run `npm install`
- then run `npm run dev`

[Connected to this issue](https://github.com/webpack/webpack/issues/6675)

**Comment by wilburpowery** [comment]
This looks like an issue that should be in the Laravel Mix repo. Try opening an issue (there)[https://github.com/jeffreyWay/laravel-mix], you might get a better response.
