### ISSUE TITLE
Issue with config:cache and collect()

### ISSUE THREAD

**Issue by leenooks** [laravel/framework#23984]
- Laravel Version: 5.6.17
- PHP Version: 7.2.0
- Database Driver & Version: N/A

### Description:
In `config/app.php` I have used many collections, eg:

```
        // Details on the financial periods for each key
        'financial_periods' => collect([
                0=>['name'=>'1Q','tag'=>'q1'],
                1=>['name'=>'2Q','tag'=>'q2'],
                2=>['name'=>'3Q','tag'=>'q3'],
                3=>['name'=>'4Q','tag'=>'q4'],
        ]),
```
And while this works fine for the application (HTTP or console), if I use `artisan config:cache` which completes successfully, the app (HTTP or Console) then fails with 

```
Fatal error: Uncaught ReflectionException: Class config does not exist in /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:767
Stack trace:
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(767): ReflectionClass->__construct('config')
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(646): Illuminate\Container\Container->build('config')
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(601): Illuminate\Container\Container->resolve('config', Array)
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(734): Illuminate\Container\Container->make('config', Array)
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(1210): Illuminate\Foundation\Application->make('config')
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(436): Illuminate\Container\Container->offsetGet('config')
#6 /var/www/html/vendor/laravel/framework/src/I in /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 767
```
 
Removing `bootstrap/cache/config.php` clears the problem.

Is it not possible to use collections in `config/app.php`?

### Steps To Reproduce:
In config/app.php just add a value using a collect().

**Comment by tillkruss** [comment]
Nope.
