### ISSUE TITLE
Sql error when Model::where()->first()

### ISSUE THREAD

**Issue by loic-lopez** [laravel/framework#24085]
Hi,

- Laravel Version: 5.6.20
- PHP Version: 7.2
- Database Driver & Version: 
`mysql  Ver 14.14 Distrib 5.7.22, for Linux (x86_64) using  EditLine wrapper`

### Description:
Migration : 
```
Schema::create('google_places', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->string('place_id');
});
```

Here is the code : ```GooglePlace::where('place_id', $place_id)->first();```

Error produced by Eloquent Model : 
```
SQLSTATE[HY000]: General error:  (SQL: select * from `google_places` where `place_id` = ChIJ_bzdbKTazRIR4-0ippvrlZo limit 1)
```

I have tested the sql statement on mysql cli and added quotes around the place_id: 
```
select * from `google_places` where `place_id` = 'ChIJ_bzdbKTazRIR4-0ippvrlZo' limit 1
```

and the query works.
How i can add quotes with an Eloquent Model?

Thanks for reply.

**Comment by sisve** [comment]
Does this happen with `GooglePlace::where('place_id', 'ChIJ_bzdbKTazRIR4-0ippvrlZo')->first()` too? If not, can you `dd($place_id);` and tell us what it is?

**Comment by loic-lopez** [comment]
Thanks for reply : 
I have tried with ```"'{$place_id}'"``` and with the same result: 
```
GooglePlace::where('place_id', "'{$place_id}'")->first();
```

```
dd($place_id);
```
<img width="317" alt="capture d ecran 2018-05-02 a 18 15 01" src="https://user-images.githubusercontent.com/17724398/39535674-d35b8e12-4e34-11e8-82da-6aa79f7abd87.png">

**Comment by loic-lopez** [comment]
So i tried with postgresql-9.6 and the query is working so the error comes from mysql.

**Comment by staudenmeir** [comment]
What's the result of `dd(GooglePlace::where('place_id', $place_id)->toSql());`?
Do you have any additional packages installed?
Can you reproduce the error with a fresh Laravel installation?

**Comment by loic-lopez** [comment]
Hello, 
my composer.json dependencies : 
```
"require": {
    "php": "^7.1.3",
    "asvae/laravel-api-tester": "^2.0",
    "dingo/api": "2.0.0-alpha2",
    "fideloper/proxy": "^4.0",
    "guzzlehttp/guzzle": "^6.3",
    "laravel/framework": "5.6.*",
    "laravel/tinker": "^1.0",
    "tymon/jwt-auth": "1.0.0-rc.2",
    "webpatser/laravel-uuid": "^3.0"
  },
  "require-dev": {
    "doctrine/dbal": "^2.7",
    "barryvdh/laravel-ide-helper": "^2.4",
    "filp/whoops": "^2.0",
    "fzaninotto/faker": "^1.4",
    "mockery/mockery": "^1.0",
    "nunomaduro/collision": "^2.0",
    "phpunit/phpunit": "^7.0"
  },
```

Output of ```dd(GooglePlace::where('place_id', $place_id)->toSql());``` : 
<img width="384" alt="capture d ecran 2018-05-03 a 09 37 03" src="https://user-images.githubusercontent.com/17724398/39564755-ca4ea2ce-4eb5-11e8-936d-9ebb097b5a27.png">

**Comment by staudenmeir** [comment]
Did you post the complete error message?

Do other queries like `GooglePlace::first()` work?

**Comment by loic-lopez** [comment]
Yes i did it,

It's really strange with ```GooglePlace::first()```

it still does not work : 
```
SQLSTATE[HY000]: General error:  (SQL: select * from `google_places` limit 1)
```

**Comment by staudenmeir** [comment]
Do queries with other models work?

**Comment by loic-lopez** [comment]
```
 $place = GooglePlace::create([
            "place_id" => $placeDetails['place_id']
        ]);
``` works well

**Comment by loic-lopez** [comment]
But it happen only with mysql with pgsql everything work

**Comment by loic-lopez** [comment]
I am using HHVM also

**Comment by 36864** [comment]
Did you define any casts, mutators, etc. in your model class?

It would be easier to figure out what's going on if we could see your code and a full stack trace of the error.

**Comment by loic-lopez** [comment]
```
{
  "message": "SQLSTATE[HY000]: General error:  (SQL: select * from `google_places` limit 1)",
  "code": "HY000",
  "status_code": 500,
  "debug": {
    "line": 666,
    "file": "/mnt/hgfs/lyl_google_local_storage_api/vendor/laravel/framework/src/Illuminate/Database/Connection.php",
    "class": "Illuminate\\Database\\QueryException",
    "trace": [
      "#0 /mnt/hgfs/lyl_google_local_storage_api/vendor/laravel/framework/src/Illuminate/Database/Connection.php(624): Illuminate\\Database\\Connection->runQueryCallback()",
      "#1 /mnt/hgfs/lyl_google_local_storage_api/vendor/laravel/framework/src/Illuminate/Database/Connection.php(333): Illuminate\\Database\\Connection->run()",
      "#2 /mnt/hgfs/lyl_google_local_storage_api/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1910): Illuminate\\Database\\Connection->select()",
      "#3 /mnt/hgfs/lyl_google_local_storage_api/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1894): Illuminate\\Database\\Query\\Builder->runSelect()",
      "#4 /mnt/hgfs/lyl_google_local_storage_api/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(483): Illuminate\\Database\\Query\\Builder->get()",
      "#5 /mnt/hgfs/lyl_google_local_storage_api/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(467): Illuminate\\Database\\Eloquent\\Builder->getModels()",
      "#6 /mnt/hgfs/lyl_google_local_storage_api/vendor/laravel/framework/src/Illuminate/Database/Concerns/BuildsQueries.php(77): Illuminate\\Database\\Eloquent\\Builder->get()",
      "#7 /mnt/hgfs/lyl_google_local_storage_api/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1511): Illuminate\\Database\\Eloquent\\Builder->first()",
      "#8 /mnt/hgfs/lyl_google_local_storage_api/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1523): Illuminate\\Database\\Eloquent\\Model->__call()",
      "#9 /mnt/hgfs/lyl_google_local_storage_api/app/Http/Controllers/API/APIGooglePlaceLocalStorageController.php(20): Illuminate\\Database\\Eloquent\\Model::__callStatic()",
      "#10 /mnt/hgfs/lyl_google_local_storage_api/app/Http/Controllers/API/APIGooglePlaceDetailsController.php(30): App\\Http\\Controllers\\API\\APIGooglePlaceLocalStorageController::getPlaceFromLocalDB()",
      "#11 (): App\\Http\\Controllers\\API\\APIGooglePlaceDetailsController->details()",
      "#12 /mnt/hgfs/lyl_google_local_storage_api/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array()",
      "#13 /mnt/hgfs/lyl_google_local_storage_api/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()",
      "#14 /mnt/hgfs/lyl_google_local_storage_api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(213): Illuminate\\Routing\\ControllerDispatcher->dispatch()",
      "#15 /mnt/hgfs/lyl_google_local_storage_api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(169): Illuminate\\Routing\\Route->runController()",
      "#16 /mnt/hgfs/lyl_google_local_storage_api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(660): Illuminate\\Routing\\Route->run()",
      "#17 /mnt/hgfs/lyl_google_local_storage_api/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Closure$Illuminate\\Routing\\Router::runRouteWithinStack()",
      "#18 /mnt/hgfs/lyl_google_local_storage_api/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Closure$Illuminate\\Routing\\Pipeline::prepareDestination()",
      "#19 /mnt/hgfs/lyl_google_local_storage_api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()",
      "#20 /mnt/hgfs/lyl_google_local_storage_api/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Closure$Illuminate\\Pipeline\\Pipeline::carry()",
      "#21 /mnt/hgfs/lyl_google_local_storage_api/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(57): Closure$Illuminate\\Routing\\Pipeline::carry()",
      "#22 /mnt/hgfs/lyl_google_local_storage_api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Routing\\Middleware\\ThrottleRequests->handle()",
      "#23 /mnt/hgfs/lyl_google_local_storage_api/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Closure$Illuminate\\Pipeline\\Pipeline::carry()",
      "#24 /mnt/hgfs/lyl_google_local_storage_api/vendor/dingo/api/src/Http/Middleware/PrepareController.php(45): Closure$Illuminate\\Routing\\Pipeline::carry()",
      "#25 /mnt/hgfs/lyl_google_local_storage_api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Dingo\\Api\\Http\\Middleware\\PrepareController->handle()",
      "#26 /mnt/hgfs/lyl_google_local_storage_api/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Closure$Illuminate\\Pipeline\\Pipeline::carry()",
      "#27 /mnt/hgfs/lyl_google_local_storage_api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Closure$Illuminate\\Routing\\Pipeline::carry()",
      "#28 /mnt/hgfs/lyl_google_local_storage_api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(661): Illuminate\\Pipeline\\Pipeline->then()",
      "#29 /mnt/hgfs/lyl_google_local_storage_api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(637): Illuminate\\Routing\\Router->runRouteWithinStack()",
      "#30 /mnt/hgfs/lyl_google_local_storage_api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(602): Illuminate\\Routing\\Router->runRoute()",
      "#31 /mnt/hgfs/lyl_google_local_storage_api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(591): Illuminate\\Routing\\Router->dispatchToRoute()",
      "#32 /mnt/hgfs/lyl_google_local_storage_api/vendor/dingo/api/src/Routing/Adapter/Laravel.php(81): Illuminate\\Routing\\Router->dispatch()",
      "#33 /mnt/hgfs/lyl_google_local_storage_api/vendor/dingo/api/src/Routing/Router.php(512): Dingo\\Api\\Routing\\Adapter\\Laravel->dispatch()",
      "#34 /mnt/hgfs/lyl_google_local_storage_api/vendor/dingo/api/src/Http/Middleware/Request.php(126): Dingo\\Api\\Routing\\Router->dispatch()",
      "#35 /mnt/hgfs/lyl_google_local_storage_api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(114): Closure$Dingo\\Api\\Http\\Middleware\\Request::sendRequestThroughRouter()",
      "#36 /mnt/hgfs/lyl_google_local_storage_api/vendor/fideloper/proxy/src/TrustProxies.php(57): Closure$Illuminate\\Pipeline\\Pipeline::prepareDestination()",
      "#37 /mnt/hgfs/lyl_google_local_storage_api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Fideloper\\Proxy\\TrustProxies->handle()",
      "#38 /mnt/hgfs/lyl_google_local_storage_api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Closure$Illuminate\\Pipeline\\Pipeline::carry()",
      "#39 /mnt/hgfs/lyl_google_local_storage_api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()",
      "#40 /mnt/hgfs/lyl_google_local_storage_api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Closure$Illuminate\\Pipeline\\Pipeline::carry()",
      "#41 /mnt/hgfs/lyl_google_local_storage_api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()",
      "#42 /mnt/hgfs/lyl_google_local_storage_api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Closure$Illuminate\\Pipeline\\Pipeline::carry()",
      "#43 /mnt/hgfs/lyl_google_local_storage_api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()",
      "#44 /mnt/hgfs/lyl_google_local_storage_api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Closure$Illuminate\\Pipeline\\Pipeline::carry()",
      "#45 /mnt/hgfs/lyl_google_local_storage_api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle()",
      "#46 /mnt/hgfs/lyl_google_local_storage_api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Closure$Illuminate\\Pipeline\\Pipeline::carry()",
      "#47 /mnt/hgfs/lyl_google_local_storage_api/vendor/dingo/api/src/Http/Middleware/Request.php(127): Illuminate\\Pipeline\\Pipeline->then()",
      "#48 /mnt/hgfs/lyl_google_local_storage_api/vendor/dingo/api/src/Http/Middleware/Request.php(103): Dingo\\Api\\Http\\Middleware\\Request->sendRequestThroughRouter()",
      "#49 /mnt/hgfs/lyl_google_local_storage_api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Dingo\\Api\\Http\\Middleware\\Request->handle()",
      "#50 /mnt/hgfs/lyl_google_local_storage_api/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Closure$Illuminate\\Pipeline\\Pipeline::carry()",
      "#51 /mnt/hgfs/lyl_google_local_storage_api/vendor/asvae/laravel-api-tester/src/Http/Middleware/DetectRoute.php(46): Closure$Illuminate\\Routing\\Pipeline::carry()",
      "#52 /mnt/hgfs/lyl_google_local_storage_api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Asvae\\ApiTester\\Http\\Middleware\\DetectRoute->handle()",
      "#53 /mnt/hgfs/lyl_google_local_storage_api/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Closure$Illuminate\\Pipeline\\Pipeline::carry()",
      "#54 /mnt/hgfs/lyl_google_local_storage_api/vendor/asvae/laravel-api-tester/src/Http/Middleware/PreventRedirect.php(17): Closure$Illuminate\\Routing\\Pipeline::carry()",
      "#55 /mnt/hgfs/lyl_google_local_storage_api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Asvae\\ApiTester\\Http\\Middleware\\PreventRedirect->handle()",
      "#56 /mnt/hgfs/lyl_google_local_storage_api/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Closure$Illuminate\\Pipeline\\Pipeline::carry()",
      "#57 /mnt/hgfs/lyl_google_local_storage_api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Closure$Illuminate\\Routing\\Pipeline::carry()",
      "#58 /mnt/hgfs/lyl_google_local_storage_api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then()",
      "#59 /mnt/hgfs/lyl_google_local_storage_api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()",
      "#60 /mnt/hgfs/lyl_google_local_storage_api/public/index.php(56): Illuminate\\Foundation\\Http\\Kernel->handle()",
      "#61 {main}"
    ]
  }
```

**Comment by loic-lopez** [comment]
Model : 
```
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;

/**
 * Class GooglePlace
 * @package App\Models
 * @property integer id
 * @property string place_id
 * @property string website
 * @property string rating
 * @property string phone
 * @property string address
 * @property string name
 * @property json week_text
 * @property float latitude
 * @property integer longitude
 */
class GooglePlace extends Model
{

    public $timestamps = false;

    /**
     * @var array
     */
    protected $fillable = [
        'place_id', 'website', 'rating', 'phone', 'address',
        'name', 'week_text', "latitude", "longitude"
    ];

    protected $casts = [
        'week_text' => 'array',
        "latitude" => "double",
        "longitude" => "double"
    ];

    /**
     * @var array
     */
    protected $hidden = [
        'id'
    ];

    public function placePicture()
    {
        return $this->hasMany('App\Models\GooglePlacePicture', 'google_places_id');
    }

    public function placeReview()
    {
        return $this->hasMany('App\Models\GooglePlaceReview', 'google_places_id');
    }

    protected static function boot() {
        parent::boot();

        static::deleting(function(GooglePlace $place) { // before delete() method call this
            $place->placeReview()->delete();
            $place->placePicture()->delete();
            Storage::delete($place->place_id);
        });
    }
}
```

**Comment by loic-lopez** [comment]
Sorry i think it's an issue related to HHVM because i rollback my configuration to use php7.2-fpm and it is working

**Comment by staudenmeir** [comment]
The only cause for your problem I can think of is the BIGINT column. Can you try an INT column instead?

**Comment by loic-lopez** [comment]
@staudenmeir on php7.2-fpm all of the sql statements works

**Comment by staudenmeir** [comment]
I meant on HHVM (if you want to keep using it).

**Comment by loic-lopez** [comment]
no i will leave it thanks 👍

**Comment by staudenmeir** [comment]
Can you close the issue?

**Comment by loic-lopez** [comment]
Thanks again for your support.

Have a nice day :).
