### ISSUE TITLE
ErrorException: Error while sending STMT_PREPARE packet.

### ISSUE THREAD

**Issue by Yahav** [laravel/framework#25071]
- Laravel Version: 5.6.28
- PHP Version: 7.2.2
- Database Driver & Version: 5.5.56-MariaDB

### Description:
I have a queued jobs that can sometime be long running, i'm talking 12-18 hours in some cases, depends on the amount of data needs to be processed. this script process data received from an API and eventually store most of it at the database. When the job has a lot of data i get the following error:

```
ErrorException: Error while sending STMT_PREPARE packet. PID=291 in /home/yahav/www/console/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:80
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'Error while sen...', '/home/yahav/www...', 80, Array)
#1 /home/yahav/www/console/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(80): PDO->prepare('insert into `co...', Array)
#2 /home/yahav/www/console/vendor/laravel/framework/src/Illuminate/Database/Connection.php(452): Doctrine\DBAL\Driver\PDOConnection->prepare('insert into `co...')
#3 /home/yahav/www/console/vendor/laravel/framework/src/Illuminate/Database/Connection.php(657): Illuminate\Database\Connection->Illuminate\Database\{closure}('insert into `co...', Array)
#4 /home/yahav/www/console/vendor/laravel/framework/src/Illuminate/Database/Connection.php(624): Illuminate\Database\Connection->runQueryCallback('insert into `co...', Array, Object(Closure))
#5 /home/yahav/www/console/vendor/laravel/framework/src/Illuminate/Database/Connection.php(459): Illuminate\Database\Connection->run('insert into `co...', Array, Object(Closure))
#6 /home/yahav/www/console/vendor/laravel/framework/src/Illuminate/Database/Connection.php(411): Illuminate\Database\Connection->statement('insert into `co...', Array)
#7 /home/yahav/www/console/vendor/laravel/framework/src/Illuminate/Database/Query/Processors/Processor.php(32): Illuminate\Database\Connection->insert('insert into `co...', Array)
#8 /home/yahav/www/console/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2494): Illuminate\Database\Query\Processors\Processor->processInsertGetId(Object(Illuminate\Database\Query\Builder), 'insert into `co...', Array, 'id')
#9 /home/yahav/www/console/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1283): Illuminate\Database\Query\Builder->insertGetId(Array, 'id')
#10 /home/yahav/www/console/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(794): Illuminate\Database\Eloquent\Builder->__call('insertGetId', Array)
#11 /home/yahav/www/console/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(759): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(Illuminate\Database\Eloquent\Builder), Array)
#12 /home/yahav/www/console/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(622): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder))
#13 /home/yahav/www/console/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(755): Illuminate\Database\Eloquent\Model->save()
#14 /home/yahav/www/console/vendor/laravel/framework/src/Illuminate/Support/helpers.php(1041): Illuminate\Database\Eloquent\Builder->Illuminate\Database\Eloquent\{closure}(Object(App\Models\CommentableItem))
#15 /home/yahav/www/console/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(756): tap(Object(App\Models\CommentableItem), Object(Closure))
#16 /home/yahav/www/console/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1577): Illuminate\Database\Eloquent\Builder->create(Array)
#17 /home/yahav/www/console/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1589): Illuminate\Database\Eloquent\Model->__call('create', Array)
#18 /home/yahav/www/console/app/Classes/Platforms/Processors/YoutubeProcessor.php(226): Illuminate\Database\Eloquent\Model::__callStatic('create', Array)
#19 [internal function]: App\Classes\Platforms\Processors\YoutubeProcessor->createCommentableItemRecordAndUpdateId(Array, 'GXuuVuKIEc4')
#20 /home/yahav/www/console/app/Classes/Platforms/Processors/YoutubeProcessor.php(145): array_walk(Array, Array)
#21 /home/yahav/www/console/app/Jobs/ProcessReportJob.php(165): App\Classes\Platforms\Processors\YoutubeProcessor->process()
#22 /home/yahav/www/console/app/Jobs/ProcessReportJob.php(108): App\Jobs\ProcessReportJob->processJob()
#23 [internal function]: App\Jobs\ProcessReportJob->handle()
#24 /home/yahav/www/console/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#25 /home/yahav/www/console/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#26 /home/yahav/www/console/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#27 /home/yahav/www/console/vendor/laravel/framework/src/Illuminate/Container/Container.php(564): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#28 /home/yahav/www/console/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\Container\Container->call(Array)
#29 /home/yahav/www/console/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(App\Jobs\ProcessReportJob))
#30 /home/yahav/www/console/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(App\Jobs\ProcessReportJob))
#31 /home/yahav/www/console/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#32 /home/yahav/www/console/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(49): Illuminate\Bus\Dispatcher->dispatchNow(Object(App\Jobs\ProcessReportJob), false)
#33 /home/yahav/www/console/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(83): Illuminate\Queue\CallQueuedHandler->call(Object(Illuminate\Queue\Jobs\BeanstalkdJob), Array)
#34 /home/yahav/www/console/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(322): Illuminate\Queue\Jobs\Job->fire()
#35 /home/yahav/www/console/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(272): Illuminate\Queue\Worker->process('beanstalkd', Object(Illuminate\Queue\Jobs\BeanstalkdJob), Object(Illuminate\Queue\WorkerOptions))
#36 /home/yahav/www/console/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(118): Illuminate\Queue\Worker->runJob(Object(Illuminate\Queue\Jobs\BeanstalkdJob), 'beanstalkd', Object(Illuminate\Queue\WorkerOptions))
#37 /home/yahav/www/console/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(101): Illuminate\Queue\Worker->daemon('beanstalkd', 'reportProcessin...', Object(Illuminate\Queue\WorkerOptions))
#38 /home/yahav/www/console/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(85): Illuminate\Queue\Console\WorkCommand->runWorker('beanstalkd', 'reportProcessin...')
#39 [internal function]: Illuminate\Queue\Console\WorkCommand->handle()
#40 /home/yahav/www/console/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#41 /home/yahav/www/console/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#42 /home/yahav/www/console/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#43 /home/yahav/www/console/vendor/laravel/framework/src/Illuminate/Container/Container.php(564): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#44 /home/yahav/www/console/vendor/laravel/framework/src/Illuminate/Console/Command.php(184): Illuminate\Container\Container->call(Array)
#45 /home/yahav/www/console/vendor/symfony/console/Command/Command.php(251): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#46 /home/yahav/www/console/vendor/laravel/framework/src/Illuminate/Console/Command.php(171): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#47 /home/yahav/www/console/vendor/symfony/console/Application.php(886): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#48 /home/yahav/www/console/vendor/symfony/console/Application.php(262): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Queue\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#49 /home/yahav/www/console/vendor/symfony/console/Application.php(145): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#50 /home/yahav/www/console/vendor/laravel/framework/src/Illuminate/Console/Application.php(89): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#51 /home/yahav/www/console/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#52 /home/yahav/www/console/artisan(37): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#53 {main}

Next Illuminate\Database\QueryException: Error while sending STMT_PREPARE packet. PID=291 (SQL: insert into `commentable_items` (`commentable_item_id`, `report_result_id`, `comments_count`, `url`, `title`, `published_at`, `thumbnail`, `view_count`, `like_count`, `dislike_count`, `favorite_count`, `updated_at`, `created_at`) values (GXuuVuKIEc4, 240, 40944, https://www.youtube.com/watchLOGAN PAUL WINS OVER KSI2018-07-31 17:36:17v=GXuuVuKIEc4, {"height":90,"width":120,"url":"https:\/\/i.ytimg.com\/vi\/GXuuVuKIEc4\/default.jpg"}, 4286747, 317075, 10847, 0, 2018-08-02 08:44:35, 2018-08-02 08:44:35, ?, ?)) in /home/yahav/www/console/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664
Stack trace:
#0 /home/yahav/www/console/vendor/laravel/framework/src/Illuminate/Database/Connection.php(624): Illuminate\Database\Connection->runQueryCallback('insert into `co...', Array, Object(Closure))
#1 /home/yahav/www/console/vendor/laravel/framework/src/Illuminate/Database/Connection.php(459): Illuminate\Database\Connection->run('insert into `co...', Array, Object(Closure))
#2 /home/yahav/www/console/vendor/laravel/framework/src/Illuminate/Database/Connection.php(411): Illuminate\Database\Connection->statement('insert into `co...', Array)
#3 /home/yahav/www/console/vendor/laravel/framework/src/Illuminate/Database/Query/Processors/Processor.php(32): Illuminate\Database\Connection->insert('insert into `co...', Array)
#4 /home/yahav/www/console/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2494): Illuminate\Database\Query\Processors\Processor->processInsertGetId(Object(Illuminate\Database\Query\Builder), 'insert into `co...', Array, 'id')
#5 /home/yahav/www/console/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1283): Illuminate\Database\Query\Builder->insertGetId(Array, 'id')
#6 /home/yahav/www/console/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(794): Illuminate\Database\Eloquent\Builder->__call('insertGetId', Array)
#7 /home/yahav/www/console/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(759): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(Illuminate\Database\Eloquent\Builder), Array)
#8 /home/yahav/www/console/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(622): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder))
#9 /home/yahav/www/console/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(755): Illuminate\Database\Eloquent\Model->save()
#10 /home/yahav/www/console/vendor/laravel/framework/src/Illuminate/Support/helpers.php(1041): Illuminate\Database\Eloquent\Builder->Illuminate\Database\Eloquent\{closure}(Object(App\Models\CommentableItem))
#11 /home/yahav/www/console/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(756): tap(Object(App\Models\CommentableItem), Object(Closure))
#12 /home/yahav/www/console/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1577): Illuminate\Database\Eloquent\Builder->create(Array)
#13 /home/yahav/www/console/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1589): Illuminate\Database\Eloquent\Model->__call('create', Array)
#14 /home/yahav/www/console/app/Classes/Platforms/Processors/YoutubeProcessor.php(226): Illuminate\Database\Eloquent\Model::__callStatic('create', Array)
#15 [internal function]: App\Classes\Platforms\Processors\YoutubeProcessor->createCommentableItemRecordAndUpdateId(Array, 'GXuuVuKIEc4')
#16 /home/yahav/www/console/app/Classes/Platforms/Processors/YoutubeProcessor.php(145): array_walk(Array, Array)
#17 /home/yahav/www/console/app/Jobs/ProcessReportJob.php(165): App\Classes\Platforms\Processors\YoutubeProcessor->process()
#18 /home/yahav/www/console/app/Jobs/ProcessReportJob.php(108): App\Jobs\ProcessReportJob->processJob()
#19 [internal function]: App\Jobs\ProcessReportJob->handle()
#20 /home/yahav/www/console/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#21 /home/yahav/www/console/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#22 /home/yahav/www/console/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#23 /home/yahav/www/console/vendor/laravel/framework/src/Illuminate/Container/Container.php(564): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#24 /home/yahav/www/console/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\Container\Container->call(Array)
#25 /home/yahav/www/console/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(App\Jobs\ProcessReportJob))
#26 /home/yahav/www/console/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(App\Jobs\ProcessReportJob))
#27 /home/yahav/www/console/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#28 /home/yahav/www/console/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(49): Illuminate\Bus\Dispatcher->dispatchNow(Object(App\Jobs\ProcessReportJob), false)
#29 /home/yahav/www/console/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(83): Illuminate\Queue\CallQueuedHandler->call(Object(Illuminate\Queue\Jobs\BeanstalkdJob), Array)
#30 /home/yahav/www/console/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(322): Illuminate\Queue\Jobs\Job->fire()
#31 /home/yahav/www/console/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(272): Illuminate\Queue\Worker->process('beanstalkd', Object(Illuminate\Queue\Jobs\BeanstalkdJob), Object(Illuminate\Queue\WorkerOptions))
#32 /home/yahav/www/console/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(118): Illuminate\Queue\Worker->runJob(Object(Illuminate\Queue\Jobs\BeanstalkdJob), 'beanstalkd', Object(Illuminate\Queue\WorkerOptions))
#33 /home/yahav/www/console/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(101): Illuminate\Queue\Worker->daemon('beanstalkd', 'reportProcessin...', Object(Illuminate\Queue\WorkerOptions))
#34 /home/yahav/www/console/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(85): Illuminate\Queue\Console\WorkCommand->runWorker('beanstalkd', 'reportProcessin...')
#35 [internal function]: Illuminate\Queue\Console\WorkCommand->handle()
#36 /home/yahav/www/console/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#37 /home/yahav/www/console/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#38 /home/yahav/www/console/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#39 /home/yahav/www/console/vendor/laravel/framework/src/Illuminate/Container/Container.php(564): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#40 /home/yahav/www/console/vendor/laravel/framework/src/Illuminate/Console/Command.php(184): Illuminate\Container\Container->call(Array)
#41 /home/yahav/www/console/vendor/symfony/console/Command/Command.php(251): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#42 /home/yahav/www/console/vendor/laravel/framework/src/Illuminate/Console/Command.php(171): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#43 /home/yahav/www/console/vendor/symfony/console/Application.php(886): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#44 /home/yahav/www/console/vendor/symfony/console/Application.php(262): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Queue\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#45 /home/yahav/www/console/vendor/symfony/console/Application.php(145): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#46 /home/yahav/www/console/vendor/laravel/framework/src/Illuminate/Console/Application.php(89): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#47 /home/yahav/www/console/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#48 /home/yahav/www/console/artisan(37): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#49 {main}
```

all of those queries are happening inside a 
```
DB::beginTransaction();
```

and only committed after the processing is finished.

I've read the issue is lose of connection with the DB. however i saw you've fixed this issue at:
https://github.com/laravel/framework/pull/10609/files
However, i still get this.

**Comment by tillkruss** [comment]
Are you running the latest version and have you restarted you workers?

**Comment by Yahav** [comment]
latest version of? Laravel? yes, Version: 5.6.28
of course i've restarted the workers. i've a supervisord setup, after every change in code i'll do supervisorctl restart laravel-worker:*

**Comment by tillkruss** [comment]
Could you try setting `wait_timeout` to 24 hours?

**Comment by Yahav** [comment]
This isn't really a solution, the wait_timeout is there for a reason. a solution would be implementing a mechanism that solves this situation only when required. 
Changing the global settings value is just like disabling the firewall because some software require some specific settings, don't you think?
If i have only one script that will be long running, doesn't really make sense solving it that way. its also shouldn't be solved by writing a custom solution for each project but in my opinion solving it at the framework level would be the solution.. "let your users just write their apps, you take care of the underlying requirements."
Its just my opinion though, what do you think?

**Comment by tillkruss** [comment]
If we're talking about opinions, I'd suggest using something that's better suited for long running tasks, such as Golang or even bash script. PHP isn't designed for it.

However, if you have a solution for your issue, please feel free to submit a PR.

**Comment by Yahav** [comment]
I totally agree, PHP isn't meant for long running processes. however, Laravel did address and fixed such issues before hence accepted the subject into its scope.
If i had a solution i would most definitely submit a PR, unfortunately i'm not familiar with Laravel core to be able to solve such issue. i really was hoping you guys will be able to.

**Comment by laurencei** [comment]
> If i have only one script that will be long running, doesn't really make sense solving it that way. 

There's a few other ways this could be solved;
- Are you running `queue:listen` instead of `queue:work` (so the process restarts after each job)
- Have the script run multiple transactions, or break up the processing into chunks

> I totally agree, PHP isn't meant for long running processes. 

This is an extreme edge case. Ultimately there is nothing directly wrong in the code. If you are able to show where/how a bug exists, we can do a PR and fix it. Otherwise if you need to do this, please try using the `wait_timeout` option as suggested by @tillkruss .

**Comment by ryancwalsh** [comment]
@Yahav @tillkruss I have a question that has been driving me crazy for months and now has a 500-point bounty: https://stackoverflow.com/q/53469793/470749

What should I be investigating at this point?

How can I discover whether any of my cron jobs or queued jobs are problematic? Thanks.
