### ISSUE TITLE
[5.6] Encryption-related error after update

### ISSUE THREAD

**Issue by thannaske** [laravel/framework#25396]
- Laravel Version: latest 5.6
- PHP Version: 7.2.3

### Description
After updating my Laravel app to the latest 5.6 version I got some encryption-related errors.

```
[2018-08-31 22:20:31] production.ERROR: unserialize(): Error at offset 0 of 40 bytes {"exception":"[object] (ErrorException(code: 0): unserialize(): Error at offset 0 of 40 bytes at /var/www/vhosts/example.com/releases/20180814230741/vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php:149)
[stacktrace]
#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'unserialize(): ...', '/var/www/vhosts...', 149, Array)
#1 /var/www/vhosts/example.com/releases/20180814230741/vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php(149): unserialize('1UrtPuxFSNUGW5k...')
#2 /var/www/vhosts/example.com/releases/20180814230741/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(95): Illuminate\\Encryption\\Encrypter->decrypt(Array)
#3 /var/www/vhosts/example.com/releases/20180814230741/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(76): Illuminate\\Cookie\\Middleware\\EncryptCookies->decryptCookie('eyJpdiI6Ik9mZTh...')
#4 /var/www/vhosts/example.com/releases/20180814230741/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\\Cookie\\Middleware\\EncryptCookies->decrypt(Object(Illuminate\\Http\\Request))
#5 /var/www/vhosts/example.com/releases/20180814230741/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#6 /var/www/vhosts/example.com/releases/20180814230741/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#7 /var/www/vhosts/example.com/releases/20180814230741/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#8 /var/www/vhosts/example.com/releases/20180814230741/vendor/laravel/framework/src/Illuminate/Routing/Router.php(667): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#9 /var/www/vhosts/example.com/releases/20180814230741/vendor/laravel/framework/src/Illuminate/Routing/Router.php(642): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#10 /var/www/vhosts/example.com/releases/20180814230741/vendor/laravel/framework/src/Illuminate/Routing/Router.php(608): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#11 /var/www/vhosts/example.com/releases/20180814230741/vendor/laravel/framework/src/Illuminate/Routing/Router.php(597): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#12 /var/www/vhosts/example.com/releases/20180814230741/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#13 /var/www/vhosts/example.com/releases/20180814230741/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#14 /var/www/vhosts/example.com/releases/20180814230741/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(58): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#15 /var/www/vhosts/example.com/releases/20180814230741/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#16 /var/www/vhosts/example.com/releases/20180814230741/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#17 /var/www/vhosts/example.com/releases/20180814230741/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#18 /var/www/vhosts/example.com/releases/20180814230741/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#19 /var/www/vhosts/example.com/releases/20180814230741/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#20 /var/www/vhosts/example.com/releases/20180814230741/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#21 /var/www/vhosts/example.com/releases/20180814230741/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#22 /var/www/vhosts/example.com/releases/20180814230741/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#23 /var/www/vhosts/example.com/releases/20180814230741/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#24 /var/www/vhosts/example.com/releases/20180814230741/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#25 /var/www/vhosts/example.com/releases/20180814230741/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#26 /var/www/vhosts/example.com/releases/20180814230741/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#27 /var/www/vhosts/example.com/releases/20180814230741/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#28 /var/www/vhosts/example.com/releases/20180814230741/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#29 /var/www/vhosts/example.com/releases/20180814230741/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#30 /var/www/vhosts/example.com/releases/20180814230741/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#31 /var/www/vhosts/example.com/releases/20180814230741/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#32 /var/www/vhosts/example.com/releases/20180814230741/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#33 /var/www/vhosts/example.com/releases/20180814230741/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#34 /var/www/vhosts/example.com/releases/20180814230741/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#35 /var/www/vhosts/example.com/releases/20180814230741/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#36 {main}
"}
```

Turns out that my APP_KEY made some trouble:
```
thannaske@vsc01 /var/www/vhosts/example.com/current # cat .env
[...]
APP_ENV=production
APP_KEY=base64:3Z6rtu3+bt//zKQKS1cLTLzUKMKmTk7UfUm45DAUZC0=
[...]
```

After regenerating it ...
```
thannaske@vsc01 /var/www/vhosts/example.com/current # php artisan key:generate
**************************************
*     Application In Production!     *
**************************************

 Do you really wish to run this command? (yes/no) [no]:
 > yes

Application key [base64:ewmnsOSx4jbCyS7fVfiGU9z0oLiwIpUpvs4rnb8jBWQ=] set successfully.
```

... the error was gone.
```
thannaske@vsc01 /var/www/vhosts/example.com/current # cat .env
[...]
APP_ENV=production
APP_KEY=base64:ewmnsOSx4jbCyS7fVfiGU9z0oLiwIpUpvs4rnb8jBWQ=
[...]
```

(Keys are of course invalidated and not longer used in production.)

**Comment by bonzai** [comment]
See "Cookie Serialization":
https://laravel.com/docs/5.6/upgrade#upgrade-5.6.30

**Comment by thannaske** [comment]
Thank you!
