### ISSUE TITLE
Babel-core not found

### ISSUE THREAD

**Issue by MadsN95** [laravel/framework#25779]
- Laravel Version: 5.7
- PHP Version: 7.2.9
- Database Driver & Version:

### Description:
Non-welcome pages in laravel produce this erro in console:
app.js:78 Uncaught Error: Module build failed: Error: Cannot find module 'babel-core'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\madsn\source\repos\JobNextDoor-v2.0\code\node_modules\babel-loader\lib\index.js:3:13)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at loadLoader (C:\Users\madsn\source\repos\JobNextDoor-v2.0\code\node_modules\loader-runner\lib\loadLoader.js:13:17)
    at iteratePitchingLoaders (C:\Users\madsn\source\repos\JobNextDoor-v2.0\code\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
    at runLoaders (C:\Users\madsn\source\repos\JobNextDoor-v2.0\code\node_modules\loader-runner\lib\LoaderRunner.js:362:2)
    at NormalModule.doBuild (C:\Users\madsn\source\repos\JobNextDoor-v2.0\code\node_modules\webpack\lib\NormalModule.js:182:3)
    at NormalModule.build (C:\Users\madsn\source\repos\JobNextDoor-v2.0\code\node_modules\webpack\lib\NormalModule.js:275:15)
    at Compilation.buildModule (C:\Users\madsn\source\repos\JobNextDoor-v2.0\code\node_modules\webpack\lib\Compilation.js:157:10)
    at factoryCallback (C:\Users\madsn\source\repos\JobNextDoor-v2.0\code\node_modules\webpack\lib\Compilation.js:348:12)
    at factory (C:\Users\madsn\source\repos\JobNextDoor-v2.0\code\node_modules\webpack\lib\NormalModuleFactory.js:243:5)
    at applyPluginsAsyncWaterfall (C:\Users\madsn\source\repos\JobNextDoor-v2.0\code\node_modules\webpack\lib\NormalModuleFactory.js:94:13)
    at C:\Users\madsn\source\repos\JobNextDoor-v2.0\code\node_modules\tapable\lib\Tapable.js:268:11
    at NormalModuleFactory.params.normalModuleFactory.plugin (C:\Users\madsn\source\repos\JobNextDoor-v2.0\code\node_modules\webpack\lib\CompatibilityPlugin.js:52:5)
    at NormalModuleFactory.applyPluginsAsyncWaterfall (C:\Users\madsn\source\repos\JobNextDoor-v2.0\code\node_modules\tapable\lib\Tapable.js:272:13)
    at resolver (C:\Users\madsn\source\repos\JobNextDoor-v2.0\code\node_modules\webpack\lib\NormalModuleFactory.js:69:10)
    at process.nextTick (C:\Users\madsn\source\repos\JobNextDoor-v2.0\code\node_modules\webpack\lib\NormalModuleFactory.js:196:7)
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9)
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\madsn\source\repos\JobNextDoor-v2.0\code\node_modules\babel-loader\lib\index.js:3:13)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at loadLoader (C:\Users\madsn\source\repos\JobNextDoor-v2.0\code\node_modules\loader-runner\lib\loadLoader.js:13:17)
    at iteratePitchingLoaders (C:\Users\madsn\source\repos\JobNextDoor-v2.0\code\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
    at runLoaders (C:\Users\madsn\source\repos\JobNextDoor-v2.0\code\node_modules\loader-runner\lib\LoaderRunner.js:362:2)
    at NormalModule.doBuild (C:\Users\madsn\source\repos\JobNextDoor-v2.0\code\node_modules\webpack\lib\NormalModule.js:182:3)
    at NormalModule.build (C:\Users\madsn\source\repos\JobNextDoor-v2.0\code\node_modules\webpack\lib\NormalModule.js:275:15)
    at Compilation.buildModule (C:\Users\madsn\source\repos\JobNextDoor-v2.0\code\node_modules\webpack\lib\Compilation.js:157:10)
    at factoryCallback (C:\Users\madsn\source\repos\JobNextDoor-v2.0\code\node_modules\webpack\lib\Compilation.js:348:12)
    at factory (C:\Users\madsn\source\repos\JobNextDoor-v2.0\code\node_modules\webpack\lib\NormalModuleFactory.js:243:5)
    at applyPluginsAsyncWaterfall (C:\Users\madsn\source\repos\JobNextDoor-v2.0\code\node_modules\webpack\lib\NormalModuleFactory.js:94:13)
    at C:\Users\madsn\source\repos\JobNextDoor-v2.0\code\node_modules\tapable\lib\Tapable.js:268:11
    at NormalModuleFactory.params.normalModuleFactory.plugin (C:\Users\madsn\source\repos\JobNextDoor-v2.0\code\node_modules\webpack\lib\CompatibilityPlugin.js:52:5)
    at NormalModuleFactory.applyPluginsAsyncWaterfall (C:\Users\madsn\source\repos\JobNextDoor-v2.0\code\node_modules\tapable\lib\Tapable.js:272:13)
    at resolver (C:\Users\madsn\source\repos\JobNextDoor-v2.0\code\node_modules\webpack\lib\NormalModuleFactory.js:69:10)
    at process.nextTick (C:\Users\madsn\source\repos\JobNextDoor-v2.0\code\node_modules\webpack\lib\NormalModuleFactory.js:196:7)
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9)
    at Object.<anonymous> (http://192.168.10.10/js/app.js:78:7)
    at __webpack_require__ (http://192.168.10.10/js/app.js:20:30)
    at Object.<anonymous> (http://192.168.10.10/js/app.js:70:1)
    at __webpack_require__ (http://192.168.10.10/js/app.js:20:30)
    at http://192.168.10.10/js/app.js:63:18
    at http://192.168.10.10/js/app.js:66:10

### Steps To Reproduce:
- install vagrant 2.1.5
- add box laravel/homestead
- clone homestead from github (laravel/homestead)
- fire up vagrant (the homestead.yaml config doesnt matter, set it up as you please)
- create a new laravel project through composer
- run "npm install" from windows host (as it for some reason doesnt work in the vm)
- run "php artisan make:auth"
- go to the login page (or any non-welcome page for that matter) and check console

**Comment by laurencei** [comment]
> run "npm install" from windows host (as it for some reason doesnt work in the vm)

You just need to run `npm install --no-bin-links` inside the VM as mention in the docs. Because Windows doesnt support symlinks.
