### ISSUE TITLE
Laravel sometimes fails to display the development debug screen

### ISSUE THREAD

**Issue by nekromoff** [laravel/framework#26294]
- Laravel Version: 5.6.39
- PHP Version: 7.1.0
- Database Driver & Version:
MariaDB 10.1

### Description:
Laravel sometimes fail to display the development debug screen
```
[2018-10-29 15:09:15] laravel.EMERGENCY: Unable to create configured logger. Using emergency logger. {"exception":"[object] (InvalidArgumentException(code: 0): Log [] is not defined. at /var/www/html/XXX/vendor/laravel/framework/src/Illuminate/Log/LogManager.php:181)
[stacktrace]
#0 /var/www/html/XXX/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(115): Illuminate\\Log\\LogManager->resolve(NULL)
#1 /var/www/html/XXX/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(103): Illuminate\\Log\\LogManager->get(NULL)
#2 /var/www/html/XXX/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(609): Illuminate\\Log\\LogManager->driver()
#3 /var/www/html/XXX/vendor/barryvdh/laravel-debugbar/src/LaravelDebugbar.php(270): Illuminate\\Log\\LogManager->__call('listen', Array)
#4 /var/www/html/XXX/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(61): Barryvdh\\Debugbar\\LaravelDebugbar->boot()
#5 /var/www/html/XXX/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#6 /var/www/html/XXX/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#7 /var/www/html/XXX/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#8 /var/www/html/XXX/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#9 /var/www/html/XXX/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#10 /var/www/html/XXX/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#11 /var/www/html/XXX/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#12 /var/www/html/XXX/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#13 /var/www/html/XXX/public/index.php(53): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#14 {main}
"} 
```

### Steps To Reproduce:
Unknown

**Comment by ybaruchel** [comment]
What is your default logging channel at logging.php config file and your environment LOG_CHANNEL at your .env file?

**Comment by nekromoff** [comment]
There is no `logging.php` in `config` directory and no `LOG_CHANNEL` in `.env` file.

`.env` file:
```
APP_DEBUG=true
APP_LOG_LEVEL=debug
```

app.php:
```

    /*
    |--------------------------------------------------------------------------
    | Logging Configuration
    |--------------------------------------------------------------------------
    |
    | Here you may configure the log settings for your application. Out of
    | the box, Laravel uses the Monolog PHP logging library. This gives
    | you a variety of powerful log handlers / formatters to utilize.
    |
    | Available Settings: "single", "daily", "syslog", "errorlog"
    |
     */

    'log'             => env('APP_LOG', 'single'),

    'log_level'       => env('APP_LOG_LEVEL', 'debug'),
```

**Comment by X-Coder264** [comment]
@nekromoff You obviously did not follow the [upgrade guide](https://laravel.com/docs/5.6/upgrade) for 5.6 if you don't have `logging.php` and if you have those settings in `app.php` as the entire logging component was rewritten in 5.6.

**Comment by nekromoff** [comment]
Now I am getting this in apache.log:
```
[Wed Oct 31 10:47:58.692448 2018] [php7:error] [pid 32086] [client 127.0.0.1:44814] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 32768 bytes) in /var/www/html/XXX/vendor/symfony/debug/Exception/FatalErrorException.php on line 1, referer ....
```

**Comment by nekromoff** [comment]
Actually, sometimes instead of 500 and blank page, I get regular Laravel debug screen:
```
[2018-10-31 11:14:07] local.ERROR: Allowed memory size of 134217728 bytes exhausted (tried to allocate 7336440 bytes) {"userId":XX,"email":"XXX","exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 1): Allowed memory size of 134217728 bytes exhausted (tried to allocate 7336440 bytes) at /var/www/html/XXX/vendor/league/flysystem/src/Adapter/Local.php:216)
[stacktrace]
#0 {main}
"} 
```

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs or problems. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)
