### ISSUE TITLE
[Eloquent] error with scope method

### ISSUE THREAD

**Issue by ilyachase** [laravel/framework#26989]
### Steps To Reproduce:

```
use Illuminate\Database\Eloquent\Model;

class Event extends Model
{
    public function scopeVisible($query)
    {
        return $query->where('hidden', 0);
    }
}
```

and then

`Event::visible();`

will produce

```
"debug": {
"line": 1223,
"file": "/data/projects/afisha.api/vendor/illuminate/database/Eloquent/Builder.php",
"class": "ErrorException",
"trace": [
"#0 [internal function]: Laravel\\Lumen\\Application->Laravel\\Lumen\\Concerns\\{closure}(2, 'count(): Parame...', '/data/projects/...', 1223, Array)",
"#1 /data/projects/afisha.api/vendor/illuminate/database/Eloquent/Builder.php(1223): count(NULL)",
"#2 /data/projects/afisha.api/vendor/illuminate/database/Eloquent/Builder.php(1458): Illuminate\\Database\\Eloquent\\Builder->callScope(Array, Array)",
"#3 [internal function]: Illuminate\\Database\\Eloquent\\Builder->__call('visible', Array)",
"#4 /data/projects/afisha.api/vendor/illuminate/database/Eloquent/Model.php(3551): call_user_func_array(Array, Array)",
"#5 [internal function]: Illuminate\\Database\\Eloquent\\Model->__call('visible', Array)",
"#6 /data/projects/afisha.api/vendor/illuminate/database/Eloquent/Model.php(3565): call_user_func_array(Array, Array)",
"#7 /data/projects/afisha.api/app/Http/Controllers/FilterController.php(56): Illuminate\\Database\\Eloquent\\Model::__callStatic('visible', Array)",
"#8 [internal function]: App\\Http\\Controllers\\FilterController->filter(Object(Dingo\\Api\\Http\\Request))",
"#9 /data/projects/afisha.api/vendor/illuminate/container/Container.php(508): call_user_func_array(Array, Array)",
"#10 /data/projects/afisha.api/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(743): Illuminate\\Container\\Container->call(Array, Array)",
"#11 /data/projects/afisha.api/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(709): Laravel\\Lumen\\Application->callControllerCallable(Array, Array)",
"#12 /data/projects/afisha.api/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(683): Laravel\\Lumen\\Application->callLumenController(Object(App\\Http\\Controllers\\FilterController), 'filter', Array)",
"#13 /data/projects/afisha.api/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(645): Laravel\\Lumen\\Application->callControllerAction(Array)",
"#14 /data/projects/afisha.api/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(625): Laravel\\Lumen\\Application->callActionOnArrayBasedRoute(Array)",
"#15 [internal function]: Laravel\\Lumen\\Application->Laravel\\Lumen\\Concerns\\{closure}(Object(Dingo\\Api\\Http\\Request))",
"#16 /data/projects/afisha.api/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Dingo\\Api\\Http\\Request))",
"#17 /data/projects/afisha.api/vendor/dingo/api/src/Http/Middleware/PrepareController.php(45): Laravel\\Lumen\\Routing\\Pipeline->Laravel\\Lumen\\Routing\\{closure}(Object(Dingo\\Api\\Http\\Request))",
"#18 /data/projects/afisha.api/vendor/illuminate/pipeline/Pipeline.php(137): Dingo\\Api\\Http\\Middleware\\PrepareController->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))",
"#19 [internal function]: Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
"#20 /data/projects/afisha.api/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Dingo\\Api\\Http\\Request))",
"#21 /data/projects/afisha.api/vendor/illuminate/pipeline/Pipeline.php(104): Laravel\\Lumen\\Routing\\Pipeline->Laravel\\Lumen\\Routing\\{closure}(Object(Dingo\\Api\\Http\\Request))",
"#22 /data/projects/afisha.api/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(780): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))",
"#23 /data/projects/afisha.api/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(626): Laravel\\Lumen\\Application->sendThroughPipeline(Array, Object(Closure))",
"#24 /data/projects/afisha.api/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(600): Laravel\\Lumen\\Application->handleFoundRoute(Array)",
"#25 /data/projects/afisha.api/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(533): Laravel\\Lumen\\Application->handleDispatcherResponse(Array)",
"#26 /data/projects/afisha.api/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(783): Laravel\\Lumen\\Application->Laravel\\Lumen\\Concerns\\{closure}()",
"#27 /data/projects/afisha.api/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(535): Laravel\\Lumen\\Application->sendThroughPipeline(Array, Object(Closure))",
"#28 /data/projects/afisha.api/vendor/dingo/api/src/Routing/Adapter/Lumen.php(103): Laravel\\Lumen\\Application->dispatch(Object(Dingo\\Api\\Http\\Request))",
"#29 /data/projects/afisha.api/vendor/dingo/api/src/Routing/Router.php(513): Dingo\\Api\\Routing\\Adapter\\Lumen->dispatch(Object(Dingo\\Api\\Http\\Request), 'v1')",
"#30 /data/projects/afisha.api/vendor/dingo/api/src/Http/Middleware/Request.php(126): Dingo\\Api\\Routing\\Router->dispatch(Object(Dingo\\Api\\Http\\Request))",
"#31 /data/projects/afisha.api/vendor/illuminate/pipeline/Pipeline.php(151): Dingo\\Api\\Http\\Middleware\\Request->Dingo\\Api\\Http\\Middleware\\{closure}(Object(Dingo\\Api\\Http\\Request))",
"#32 /data/projects/afisha.api/vendor/illuminate/pipeline/Pipeline.php(104): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
"#33 /data/projects/afisha.api/vendor/dingo/api/src/Http/Middleware/Request.php(127): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))",
"#34 /data/projects/afisha.api/vendor/dingo/api/src/Http/Middleware/Request.php(103): Dingo\\Api\\Http\\Middleware\\Request->sendRequestThroughRouter(Object(Dingo\\Api\\Http\\Request))",
"#35 /data/projects/afisha.api/vendor/illuminate/pipeline/Pipeline.php(137): Dingo\\Api\\Http\\Middleware\\Request->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))",
"#36 [internal function]: Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))",
"#37 /data/projects/afisha.api/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\\Http\\Request))",
"#38 /data/projects/afisha.api/vendor/illuminate/pipeline/Pipeline.php(104): Laravel\\Lumen\\Routing\\Pipeline->Laravel\\Lumen\\Routing\\{closure}(Object(Illuminate\\Http\\Request))",
"#39 /data/projects/afisha.api/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(780): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))",
"#40 /data/projects/afisha.api/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(535): Laravel\\Lumen\\Application->sendThroughPipeline(Array, Object(Closure))",
"#41 /data/projects/afisha.api/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(476): Laravel\\Lumen\\Application->dispatch(NULL)",
"#42 /data/projects/afisha.api/public/index.php(28): Laravel\\Lumen\\Application->run()",
"#43 {main}"
]
}
```

since there are no data in `$query->wheres`. `public $wheres;` must be `public $wheres = [];` instead.

**Comment by ilyachase** [comment]
Fixed in new versions...
