### ISSUE TITLE
Cloning laravel/framework and executing phpunit fails

### ISSUE THREAD

**Issue by jhm-ciberman** [laravel/framework#27690]
Hello. I want to contribute to the framework itself. I have forked and cloned the repo, run `composer install` and then `phpunit`

This is the output, I am using the latest homestead version. 

```bash
vagrant@homestead:~/code/laravel/framework$ phpunit
PHPUnit 8.0.4 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.3.1-1+ubuntu18.04.1+deb.sury.org+1
Configuration: /home/vagrant/code/laravel/framework/phpunit.xml.dist

.............................................................   61 / 4002 (  1%)
.............................................................  122 / 4002 (  3%)
.............................................................  183 / 4002 (  4%)
.............................................................  244 / 4002 (  6%)
.............................................................  305 / 4002 (  7%)
.............................................................  366 / 4002 (  9%)
.............................................................  427 / 4002 ( 10%)
.............................................................  488 / 4002 ( 12%)
.............................................................  549 / 4002 ( 13%)
.............................................................  610 / 4002 ( 15%)
.............................................................  671 / 4002 ( 16%)
....S........................................................  732 / 4002 ( 18%)
.............................................................  793 / 4002 ( 19%)
.............................................................  854 / 4002 ( 21%)
.............................................................  915 / 4002 ( 22%)
.............................................................  976 / 4002 ( 24%)
............................................................. 1037 / 4002 ( 25%)
............................................................. 1098 / 4002 ( 27%)
............................................................. 1159 / 4002 ( 28%)
............................................................. 1220 / 4002 ( 30%)
............................................................. 1281 / 4002 ( 32%)
............................................................. 1342 / 4002 ( 33%)
............................................................. 1403 / 4002 ( 35%)
............................................................. 1464 / 4002 ( 36%)
............................................................. 1525 / 4002 ( 38%)
............................................................. 1586 / 4002 ( 39%)
............................................................. 1647 / 4002 ( 41%)
............................................................. 1708 / 4002 ( 42%)
............................................................. 1769 / 4002 ( 44%)
.........................................................FFF. 1830 / 4002 ( 45%)
..........................FEEEEEEEEEEEE...................... 1891 / 4002 ( 47%)
............................................................. 1952 / 4002 ( 48%)
............................................................. 2013 / 4002 ( 50%)
............................................................. 2074 / 4002 ( 51%)
............................................................. 2135 / 4002 ( 53%)
.................SSSS........................................ 2196 / 4002 ( 54%)
............................................................. 2257 / 4002 ( 56%)
............................................................. 2318 / 4002 ( 57%)
............................................FFF.............. 2379 / 4002 ( 59%)
............................................................. 2440 / 4002 ( 60%)
.........................................PHP Fatal error:  Method Swift_Message::__toString() must not throw an excepti
on, caught ErrorException: fopen(/tmp/d6bd3a501e2644c87eb37069beb308c7/body): failed to open stream: Permission denied
in /home/vagrant/code/laravel/framework/tests/Mail/MailSesTransportTest.php on line 0
PHP Fatal error:  Uncaught Illuminate\Contracts\Container\BindingResolutionException: Target [Illuminate\Contracts\Debu
g\ExceptionHandler] is not instantiable. in /home/vagrant/code/laravel/framework/src/Illuminate/Container/Container.php
:962
Stack trace:
#0 /home/vagrant/code/laravel/framework/src/Illuminate/Container/Container.php(800): Illuminate\Container\Container->no
tInstantiable('Illuminate\\Cont...')
#1 /home/vagrant/code/laravel/framework/src/Illuminate/Container/Container.php(671): Illuminate\Container\Container->bu
ild('Illuminate\\Cont...')
#2 /home/vagrant/code/laravel/framework/src/Illuminate/Container/Container.php(619): Illuminate\Container\Container->re
solve('Illuminate\\Cont...', Array)
#3 /home/vagrant/code/laravel/framework/src/Illuminate/Foundation/Application.php(757): Illuminate\Container\Container-
>make('Illuminate\\Cont...', Array)
#4 /home/vagrant/code/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(159): Illuminate\Found
ation\Application->make('Illuminate\\Cont...')
#5 /home in /home/vagrant/code/laravel/framework/src/Illuminate/Container/Container.php on line 962

Fatal error: Method Swift_Message::__toString() must not throw an exception, caught ErrorException: fopen(/tmp/d6bd3a50
1e2644c87eb37069beb308c7/body): failed to open stream: Permission denied in /home/vagrant/code/laravel/framework/tests/
Mail/MailSesTransportTest.php on line 0

Fatal error: Uncaught Illuminate\Contracts\Container\BindingResolutionException: Target [Illuminate\Contracts\Debug\Exc
eptionHandler] is not instantiable. in /home/vagrant/code/laravel/framework/src/Illuminate/Container/Container.php:962
Stack trace:
#0 /home/vagrant/code/laravel/framework/src/Illuminate/Container/Container.php(800): Illuminate\Container\Container->no
tInstantiable('Illuminate\\Cont...')
#1 /home/vagrant/code/laravel/framework/src/Illuminate/Container/Container.php(671): Illuminate\Container\Container->bu
ild('Illuminate\\Cont...')
#2 /home/vagrant/code/laravel/framework/src/Illuminate/Container/Container.php(619): Illuminate\Container\Container->re
solve('Illuminate\\Cont...', Array)
#3 /home/vagrant/code/laravel/framework/src/Illuminate/Foundation/Application.php(757): Illuminate\Container\Container-
>make('Illuminate\\Cont...', Array)
#4 /home/vagrant/code/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(159): Illuminate\Found
ation\Application->make('Illuminate\\Cont...')
#5 /home in /home/vagrant/code/laravel/framework/src/Illuminate/Container/Container.php on line 962
```

Commit info:

```
git branch -v
* 5.8 107ee4a83 [5.8] update changelog
```
https://github.com/laravel/framework/commit/107ee4a8321b0e7a58d256143a513aa7afd3bd73

**Comment by jhm-ciberman** [comment]
@taylorotwell Sorry for bothering you. Any ideas? I want to contribute but I don't know if I am missing something.

**Comment by ahinkle** [comment]
Looks like your directories does not have read/write permissions for the user PHP runs as. There is nothing wrong with the test suite.

**Comment by jhm-ciberman** [comment]
Sorry, I ignored the template because it wasn't a bug report nor a question about the use of Laravel itself:

I feel so dumb. I tried to `sudo chmod 777 /tmp -R` and also `chmod 777 tests/ -R` and even `chmod 777 . -R`, but the tests still fail. Am I doing something wrong? 

(I know I can ask in the forums, but since this is related to `laravel/framework` itself and not about their usage I want to ask here)

**Comment by jhm-ciberman** [comment]
I restarted homestead and run `sudo chmod 777 /tmp -R` again and the Fatal error is gone. Now I got a bunch of other errors, related to line encodings. For example:

```
1) Illuminate\Tests\Integration\Mail\RenderingMailWithLocaleTest::testMailableRendersInDefaultLocale
Failed asserting that 'name\r\n
' contains "name
".
```

I think this is related to the autoclrf feature of git. I will try to disable it and re-clone the entire repo.

**Comment by jhm-ciberman** [comment]
Well... I recloned the repo with UNIX line endings and I still getting a lot of errors and I have to run `sudo chmod 777 /tmp -R` everytime I run the tests in homestead. So, I don't know what I am getting wrong. 
It would be great to add more info about in the `CONTRIBUTING.md`

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)
