### ISSUE TITLE
Fatal error: Uncaught ReflectionException: Class env does not exist

### ISSUE THREAD

**Issue by alimranahmed** [laravel/framework#28660]
- Laravel Version: 5.7.28
- PHP Version: 7.2.12
- Database Driver & Version:

### Description:
Got this error after a release. No idea why having this error. Permissions are correct. No package installed just before this break. Really frustrated. Searching for solution for last 2 hours in a very crucial time. 

### Steps To Reproduce:
Don't know the exact steps. Suddenly getting this error after running composer install. Now, getting this same error for every artisan command or composer dumpautoload. 

```
╰─$ composer dumpautoload                                                                                                                                                   255 ↵

Generating optimized autoload files> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

Fatal error: Uncaught ReflectionException: Class env does not exist in /Users/imran/Projects/Media365/bindu/vendor/laravel/framework/src/Illuminate/Container/Container.php:779
Stack trace:
#0 /Users/imran/Projects/Media365/bindu/vendor/laravel/framework/src/Illuminate/Container/Container.php(779): ReflectionClass->__construct('env')
#1 /Users/imran/Projects/Media365/bindu/vendor/laravel/framework/src/Illuminate/Container/Container.php(658): Illuminate\Container\Container->build('env')
#2 /Users/imran/Projects/Media365/bindu/vendor/laravel/framework/src/Illuminate/Container/Container.php(609): Illuminate\Container\Container->resolve('env', Array)
#3 /Users/imran/Projects/Media365/bindu/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(759): Illuminate\Container\Container->make('env', Array)
#4 /Users/imran/Projects/Media365/bindu/vendor/laravel/framework/src/Illuminate/Container/Container.php(1222): Illuminate\Foundation\Application->make('env')
#5 /Users/imran/Projects/Media365/bindu/vendor/laravel/framew in /Users/imran/Projects/Media365/bindu/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 779
```

**Comment by Tarasovych** [comment]
[Related issue](https://github.com/laravel/telescope/issues/347), maybe you find something helpful

**Comment by alimranahmed** [comment]
This was unknown to me. Solved now: 

We used `url()` method in the `service.php` config file. And that caused this issue. 

I am quite surprised to see that `env()` method works in config file but some other helper function like `url()` doesn't work. 

Peace.
