### ISSUE TITLE
Pusher can't initialize on boot (hash_algos issue)

### ISSUE THREAD

**Issue by logan-jobzmall** [laravel/framework#29691]
- Laravel Version: 5.8.32 and 5.8.33
- PHP Version: 7.2.18
- Database Driver & Version:

### Description:

We are finding on our dev environments (very recently) that Pusher can't initialize on boot due to not being able to read in `hash_algos()` array. It seems to be empty at the time that Pusher is instantiated by the BroadcastServiceProvider. For some background we are using Amazon Linux with PHP 7.2.18.

```
SHA256 appears to be unsupported - make sure you have support for it, or upgrade your version of PHP. {"exception":"[object] (Pusher\\PusherException(code: 0): SHA256 appears to be unsupported - make sure you have support for it, or upgrade your version of PHP. at /var/app/current/vendor/pusher/pusher-php-server/src/Pusher.php:243)
[stacktrace]
#0 /var/app/current/vendor/pusher/pusher-php-server/src/Pusher.php(71): Pusher\\Pusher->check_compatibility()
#1 /var/app/current/vendor/laravel/framework/src/Illuminate/Broadcasting/BroadcastManager.php(213): Pusher\\Pusher->__construct('fd80adfb3218cdb...', '35bbbcf0aa044a0...', '357719', Array)
#2 /var/app/current/vendor/laravel/framework/src/Illuminate/Broadcasting/BroadcastManager.php(189): Illuminate\\Broadcasting\\BroadcastManager->createPusherDriver(Array)
#3 /var/app/current/vendor/laravel/framework/src/Illuminate/Broadcasting/BroadcastManager.php(164): Illuminate\\Broadcasting\\BroadcastManager->resolve('pusher')
#4 /var/app/current/vendor/laravel/framework/src/Illuminate/Broadcasting/BroadcastManager.php(153): Illuminate\\Broadcasting\\BroadcastManager->get('pusher')
#5 /var/app/current/vendor/laravel/framework/src/Illuminate/Broadcasting/BroadcastManager.php(319): Illuminate\\Broadcasting\\BroadcastManager->driver()
#6 /var/app/current/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(237): Illuminate\\Broadcasting\\BroadcastManager->__call('channel', Array)
#7 /var/app/current/routes/channels.php(12): Illuminate\\Support\\Facades\\Facade::__callStatic('channel', Array)
#8 /var/app/current/app/Providers/BroadcastServiceProvider.php(19): require('/var/app/curren...')
#9 [internal function]: Framework\\Providers\\BroadcastServiceProvider->boot()
#10 /var/app/current/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array(Array, Array)
#11 /var/app/current/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#12 /var/app/current/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#13 /var/app/current/vendor/laravel/framework/src/Illuminate/Container/Container.php(576): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#14 /var/app/current/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(827): Illuminate\\Container\\Container->call(Array)
#15 /var/app/current/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(810): Illuminate\\Foundation\\Application->bootProvider(Object(Framework\\Providers\\BroadcastServiceProvider))
#16 [internal function]: Illuminate\\Foundation\\Application->Illuminate\\Foundation\\{closure}(Object(Framework\\Providers\\BroadcastServiceProvider), 43)
#17 /var/app/current/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(811): array_walk(Array, Object(Closure))
#18 /var/app/current/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\\Foundation\\Application->boot()
#19 /var/app/current/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(210): Illuminate\\Foundation\\Bootstrap\\BootProviders->bootstrap(Object(Illuminate\\Foundation\\Application))
#20 /var/app/current/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(162): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#21 /var/app/current/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(146): Illuminate\\Foundation\\Http\\Kernel->bootstrap()
#22 /var/app/current/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#23 /var/app/current/public/index.php(53): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#24 {main}
"} 
```

According to Pusher's code they check the following:

```
if (!in_array('sha256', hash_algos())) {
            throw new PusherException('SHA256 appears to be unsupported - make sure you have support for it, or upgrade your version of PHP.');
        }
```

When checking the `hash_algos()` array from `php artisan tinker`, we can see that sha256 does exist. This tends to tell me it is some sort of race condition during Laravel's boot in which it cannot read the available algorithms. Again, I am not an active contributor to Laravel so this just a symptomatic hunch.

```
     "md2",
     "md4",
     "md5",
     "sha1",
     "sha224",
     "sha256",
     "sha384",
     "sha512/224",
     "sha512/256",
     "sha512",
     "sha3-224",
     "sha3-256",
     "sha3-384",
     "sha3-512",
     "ripemd128",
     "ripemd160",
     "ripemd256",
     "ripemd320",
     "whirlpool",
     "tiger128,3",
     "tiger160,3",
     "tiger192,3",
     "tiger128,4",
     "tiger160,4",
     "tiger192,4",
     "snefru",
     "snefru256",
     "gost",
     "gost-crypto",
     "adler32",
     "crc32",
     "crc32b",
     "fnv132",
     "fnv1a32",
     "fnv164",
     "fnv1a64",
     "joaat",
     "haval128,3",
     "haval160,3",
     "haval192,3",
     "haval224,3",
     "haval256,3",
     "haval128,4",
     "haval160,4",
     "haval192,4",
     "haval224,4",
     "haval256,4",
     "haval128,5",
     "haval160,5",
     "haval192,5",
     "haval224,5",
     "haval256,5",
```
I also opened this up on Pusher's repo:

[https://github.com/pusher/pusher-http-php/issues/230](url)

**Comment by mfn** [comment]
> It seems to be empty at the time that Pusher is instantiated by the BroadcastServiceProvider

From your description, I don't think it's "empty" but rather that the message is correct and the specific algorithm is missing.

Are you by chance running the wrong PHP version?

**Comment by logan-jobzmall** [comment]
@mfn - I don't know what the "wrong" php version means. As I stated above, we are running PHP 7.2.18 through Amazon Linux (through Elastic Beanstalk). Again, when running `php artisan tinker` on the box, the `hash_algos()` comes back with the response pasted above which **does** have "sha256" (which is what is being checked by Pusher). I wouldn't expect runtime to be running a different php version than what `php artisan tinker` uses? That would be a very interesting decision on Taylor and other's parts to run a different PHP runtime just for tinker. 

Sorry if I misinterpreted what you are saying.

**Comment by driesvints** [comment]
What happens when you use `php -a` instead?

**Comment by logan-jobzmall** [comment]
@driesvints When running a `print_r(hash_algos());` in php interactive shell it returns the following:

```
Array
(
    [0] => md2
    [1] => md4
    [2] => md5
    [3] => sha1
    [4] => sha224
    [5] => sha256
    [6] => sha384
    [7] => sha512/224
    [8] => sha512/256
    [9] => sha512
    [10] => sha3-224
    [11] => sha3-256
    [12] => sha3-384
    [13] => sha3-512
    [14] => ripemd128
    [15] => ripemd160
    [16] => ripemd256
    [17] => ripemd320
    [18] => whirlpool
    [19] => tiger128,3
    [20] => tiger160,3
    [21] => tiger192,3
    [22] => tiger128,4
    [23] => tiger160,4
    [24] => tiger192,4
    [25] => snefru
    [26] => snefru256
    [27] => gost
    [28] => gost-crypto
    [29] => adler32
    [30] => crc32
    [31] => crc32b
    [32] => fnv132
    [33] => fnv1a32
    [34] => fnv164
    [35] => fnv1a64
    [36] => joaat
    [37] => haval128,3
    [38] => haval160,3
    [39] => haval192,3
    [40] => haval224,3
    [41] => haval256,3
    [42] => haval128,4
    [43] => haval160,4
    [44] => haval192,4
    [45] => haval224,4
    [46] => haval256,4
    [47] => haval128,5
    [48] => haval160,5
    [49] => haval192,5
    [50] => haval224,5
    [51] => haval256,5
)

```
You can see that at the 5th index, sha256 is existing.

**Comment by driesvints** [comment]
I really have no clue how that can happen or what's going wrong here. Welcoming any help with figuring this out.

**Comment by driesvints** [comment]
Also: does this happen as well if you initialize pusher yourself instead of using Laravel?

**Comment by logan-jobzmall** [comment]
@driesvints -- Sorry for the late return. When initializing it outside of the BootServiceProvider (whether is be `tinker` or `php -a`) it works well.

**Comment by driesvints** [comment]
That's very odd. I have no idea what could cause this. Appreciating any help with figuring this out.

**Comment by AegirLeet** [comment]
Have you tried adding some debug logging right above the `if (!in_array('sha256', hash_algos())) {` line to see what `hash_algos()` actually returns? Is it really empty?

**Comment by driesvints** [comment]
Closing this issue because it's inactive, already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue and we'll re-open this issue.

**Comment by logan-jobzmall** [comment]
@driesvints - We are still experiencing the issue, but I am spending time with Amazon to rule out environment issues. Will let you know if we confirm anything otherwise.

**Comment by jayarathinam** [comment]
> @driesvints - We are still experiencing the issue, but I am spending time with Amazon to rule out environment issues. Will let you know if we confirm anything otherwise.

we are also experiencing the issue any solution please..?

**Comment by ejlocop** [comment]
still having this issue with Laravel 7.30.3 and PHP 7.2.11
