### ISSUE TITLE
[6.1] PHPUnit can only be run from project root

### ISSUE THREAD

**Issue by jacksontong** [laravel/framework#30205]
- Laravel Version: 6.1.0
- PHP Version: 7.3.9
- Database Driver & Version:

### Description:
I have similar issue with #29862, instead the error is 
```bash
[sftp://vagrant@yogapay.test:22]:/usr/bin/php /home/vagrant/code/yoga-pay/vendor/phpunit/phpunit/phpunit --configuration /home/vagrant/code/yoga-pay/phpunit.xml --filter "/(::test_teacher_cannot_create_yoga_class)( .*)?$/" Tests\\Feature\\Api\\YogaClassTest /home/vagrant/code/yoga-pay/tests/Feature/Api/YogaClassTest.php --teamcity
PHP Fatal error:  Uncaught PHPUnit\Runner\Exception: Class 'Tests\\Feature\\Api\\YogaClassTest' could not be found in '/home/vagrant/code/yoga-pay/tests/Feature/Api/YogaClassTest.php'. in /home/vagrant/code/yoga-pay/vendor/phpunit/phpunit/src/Runner/StandardTestSuiteLoader.php:65
Stack trace:

#0 /home/vagrant/code/yoga-pay/vendor/phpunit/phpunit/src/Runner/BaseTestRunner.php(141): PHPUnit\Runner\StandardTestSuiteLoader->load('Tests\\\\Feature\\...', '/home/vagrant/c...')
Fatal error: Uncaught PHPUnit\Runner\Exception: Class 'Tests\\Feature\\Api\\YogaClassTest' could not be found in '/home/vagrant/code/yoga-pay/tests/Feature/Api/YogaClassTest.php'. in /home/vagrant/code/yoga-pay/vendor/phpunit/phpunit/src/Runner/StandardTestSuiteLoader.php:65
#1 /home/vagrant/code/yoga-pay/vendor/phpunit/phpunit/src/Runner/BaseTestRunner.php(101): PHPUnit\Runner\BaseTestRunner->loadSuiteClass('Tests\\\\Feature\\...', '/home/vagrant/c...')
Stack trace:
#2 /home/vagrant/code/yoga-pay/vendor/phpunit/phpunit/src/TextUI/Command.php(177): PHPUnit\Runner\BaseTestRunner->getTest('Tests\\\\Feature\\...', '/home/vagrant/c...', Array)
#0 /home/vagrant/code/yoga-pay/vendor/phpunit/phpunit/src/Runner/BaseTestRunner.php(141): PHPUnit\Runner\StandardTestSuiteLoader->load('Tests\\\\Feature\\...', '/home/vagrant/c...')
#3 /home/vagrant/code/yoga-pay/vendor/phpunit/phpunit/src/TextUI/Command.php(159): PHPUnit\TextUI\Command->run(Array, true)
#1 /home/vagrant/code/yoga-pay/vendor/phpunit/phpunit/src/Runner/BaseTestRunner.php(101): PHPUnit\Runner\BaseTestRunner->loadSuiteClass('Tests\\\\Feature\\...', '/home/vagrant/c...')
#4 /home/vagrant/code/yoga-pay/vendor/phpunit/phpunit/phpunit(61): PHPUnit\TextUI\C in /home/vagrant/code/yoga-pay/vendor/phpunit/phpunit/src/Runner/StandardTestSuiteLoader.php on line 65
#2 /home/vagrant/code/yoga-pay/vendor/phpunit/phpunit/src/TextUI/Command.php(177): PHPUnit\Runner\BaseTestRunner->getTest('Tests\\\\Feature\\...', '/home/vagrant/c...', Array)
#3 /home/vagrant/code/yoga-pay/vendor/phpunit/phpunit/src/TextUI/Command.php(159): PHPUnit\TextUI\Command->run(Array, true)
#4 /home/vagrant/code/yoga-pay/vendor/phpunit/phpunit/phpunit(61): PHPUnit\TextUI\C in /home/vagrant/code/yoga-pay/vendor/phpunit/phpunit/src/Runner/StandardTestSuiteLoader.php on line 65

Process finished with exit code 255
```
The terminal command is working fine 
`phpunit --filter test_authenticated_users_can_fetch_teachers`
### Steps To Reproduce:
Same with #29862

**Comment by driesvints** [comment]
The bootstrapping has been removed in the meantime so I doubt that this is broken atm: https://github.com/laravel/laravel/pull/5107

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by jacksontong** [comment]
for someone comes here with same issue, this is actually phpunit's issue https://github.com/sebastianbergmann/phpunit/issues/3904
After I downgrade to phpunit 8.3.5 it works like a charm
