### ISSUE TITLE
Unable to create configured logger

### ISSUE THREAD

**Issue by okami-chen** [laravel/framework#30491]
- Laravel Version: 6.4.1
- PHP Version: 7.3.11
- Database Driver & Version:

### Description:

`config/logging.php`
```php
'mi' => [
    'job' =>
        [
            'driver' => 'daily',
            'path' => storage_path('logs/mi.job.log'),
            'level' => 'debug',
            'days' => 5,
        ]
],
```
 通过命令行调用以及HTTP请求正常，在listener或者job中使用会出现这样的错误。

```php
[2019-10-31 20:01:37] laravel.EMERGENCY: Unable to create configured logger. Using emergency logger. {"exception":"[object] (InvalidArgumentException(code: 0): Log [mi.job] is not defined. at /Volumes/data/www/lts/vendor/laravel/framework/src/Illuminate/Log/LogManager.php:184)
[stacktrace]
#0 /Volumes/data/www/lts/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(118): Illuminate\\Log\\LogManager->resolve('mi.job')
#1 /Volumes/data/www/lts/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(98): Illuminate\\Log\\LogManager->get('mi.job')
#2 /Volumes/data/www/lts/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(87): Illuminate\\Log\\LogManager->driver('mi.job')
#3 /Volumes/data/www/lts/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(233): Illuminate\\Log\\LogManager->channel('mi.job')
#4 [internal function]: Illuminate\\Log\\LogManager->Illuminate\\Log\\{closure}('mi.job', 0)
#5 /Volumes/data/www/lts/vendor/laravel/framework/src/Illuminate/Support/Collection.php(638): array_map(Object(Closure), Array, Array)
#6 /Volumes/data/www/lts/vendor/laravel/framework/src/Illuminate/Support/Traits/EnumeratesValues.php(285): Illuminate\\Support\\Collection->map(Object(Closure))
#7 /Volumes/data/www/lts/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(234): Illuminate\\Support\\Collection->flatMap(Object(Closure))
#8 /Volumes/data/www/lts/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(74): Illuminate\\Log\\LogManager->createStackDriver(Array)
#9 /Volumes/data/www/lts/app/Listeners/Mi/Coupon/Queue/TicketListener.php(25): Illuminate\\Log\\LogManager->stack(Array)
```

### Steps To Reproduce:

```php
logger()->stack(['job.mi'])->debug(__CLASS__, $data);
```

**Comment by driesvints** [comment]
I'm very sorry but we can only offer support in English. There is https://learnku.com/laravel though which can maybe help you?
