### ISSUE TITLE
production.ERROR: The "--tries" option does not exist.

### ISSUE THREAD

**Issue by seewhy17** [laravel/framework#31372]
- Laravel Version: 6.13.x
- PHP Version: 7.3.5
- Database Driver & Version: MySQL 5.7.26

### Description:
I keep getting the following error each time my cron job runs:
```
[2020-02-05 00:00:07] production.ERROR: The "--tries" option does not exist. {"exception":"[object] (Symfony\\Component\\Console\\Exception\\RuntimeException(code: 0): The \"--tries\" option does not exist. at /home/admotadf/Admotad-Finance/vendor/symfony/console/Input/ArgvInput.php:203)
[stacktrace]
#0 /home/admotadf/Admotad-Finance/vendor/symfony/console/Input/ArgvInput.php(145): Symfony\\Component\\Console\\Input\\ArgvInput->addLongOption('tries', '3')
#1 /home/admotadf/Admotad-Finance/vendor/symfony/console/Input/ArgvInput.php(81): Symfony\\Component\\Console\\Input\\ArgvInput->parseLongOption('--tries=3')
#2 /home/admotadf/Admotad-Finance/vendor/symfony/console/Input/Input.php(55): Symfony\\Component\\Console\\Input\\ArgvInput->parse()
#3 /home/admotadf/Admotad-Finance/vendor/symfony/console/Command/Command.php(214): Symfony\\Component\\Console\\Input\\Input->bind(Object(Symfony\\Component\\Console\\Input\\InputDefinition))
#4 /home/admotadf/Admotad-Finance/vendor/laravel/framework/src/Illuminate/Console/Command.php(188): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#5 /home/admotadf/Admotad-Finance/vendor/symfony/console/Application.php(1012): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#6 /home/admotadf/Admotad-Finance/vendor/symfony/console/Application.php(272): Symfony\\Component\\Console\\Application->doRunCommand(Object(Illuminate\\Queue\\Console\\RetryCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#7 /home/admotadf/Admotad-Finance/vendor/symfony/console/Application.php(148): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#8 /home/admotadf/Admotad-Finance/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#9 /home/admotadf/Admotad-Finance/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(131): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#10 /home/admotadf/Admotad-Finance/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#11 {main}
"} 
```

### Steps To Reproduce:
I have the following in the schedule method my Kernel.php file that is ran by the cron every minute

```
    protected function schedule(Schedule $schedule)
    {
        $schedule->command('ScheduleLoanRetrieval')->dailyAt('23:00');
        $schedule->command('CalculateTithe')->dailyAt('22:00')->when(function () {
            return Carbon::now()->endOfMonth()->isToday();
        });
        $schedule->command('queue:work --timeout=60 --tries=3 --delay=3')->everyMinute()->withoutOverlapping();
        $schedule->command('queue:retry all --tries=3')->everyThirtyMinutes(10)->withoutOverlapping();

    }
```

**Comment by crynobone** [comment]
`queue:retry` artisan command doesn't have `--tries` options.

**Comment by seewhy17** [comment]
@crynobone thanks 👍
