### ISSUE TITLE
Validation methods not populating error bag

### ISSUE THREAD

**Issue by casperwilkes** [laravel/framework#31491]
- Laravel Version: 6.2
- PHP Version: 7.3
- Database Driver & Version: unrelated

### Description:
For about a week, I've been dealing with the same issue as #27729 , just chasing my tail.

I'm just starting a new application, using laravel v6.2. I used the auth scaffolding from laravel ui. That is all working. I decided to build out a
resource controller, and use FormRequest validation. At first it seemed to work, but then i noticed that it wasn't working for 2 particular fields,
it's probably unrelated, but they're both `text` inputs. one is `image_id` (i'm just work-shopping at the moment, so it's a text input just to capture
a number, no relations yet), and the other is `title`.

For this particular model, at the moment, I have 4 fields i'm trying to populate:
- image_id (text)
- title (text)
- abstract (textarea)
- body (textarea)

See visuals below, very basic.

So, through *A LOT* of testing, i've discovered some weird inconsistencies. And like reported in #27729, it kind of _seems_ that it's random. I'm
experiencing everything else @Daniel Malmgren is experiencing.

From what i've witnessed, it has _something_ to do with the validator class structure, somewhere. From what I can tell, if the validation fails, it
throws an exception, as is expected in laravel, but for some reason, the exception isn't caught and put into the session "_error bag_". And because it
doesn't populate the error bag, it doesn't show.

*BUT* here's the rub. It *only* happens on the "text" inputs, `image_id` & `title`. With a little testing, if I purposely send invalid data with the
text inputs, it doesn't matter what rule i've violated, it will populate and display the errors.

#### Test running

"text" = `user_id`, `title`

"textarea" = `abstract`, `body`

The create and edit forms are identical with one difference, setting default on the `old` function.

* If I "invalidate" either text input, by themselves, the errors aren't captured.
* If I "invalidate" the text inputs *&* the text areas, the errors are captured.

On the Create page:

* If I populate the textareas, but leave either or both the text inputs empty, I lose all data for all fields
* If I populate the text fields, but with invalid, or valid data, and invalidate the textareas, the data is persisted, and the errors for the text areas populate
* Errors for the text fields *only* populate if a textarea is invalid first, or at the same time

On the Edit page:
* If I populate the textareas, but leave either or both the text inputs empty, or invalidated, I lose all changes

It basically boils down to 2 fields always validate without issue, and 2 cause something to break somewhere in the chain.

I've tried using `FormRequest`, `validator()`, `Validator::make()`. All the same

I've tried messing with the rules a bit, `'required|bail|string|between:1,250'`. All the same.

#### ANOTHER CATCH

What makes this interesting, and seem "random" is that the errors are only caught and displayed if the textareas are invalidated *first*, or *at the same time as*
the text fields. If the text fields invalidate first, all data (changes) are lost.

#### My thoughts
Originally, I thought it had something to do with the required field, but now i'm not too sure. I'm starting to think it has something to do with either the
array processing that occurs within the validation, or the exception handling has changed.

This isn't my first laravel application, I've used `FormRequest` in the past, and prior validation methods, and have never experienced an issue. I even went
and tested with an old 5.4 app with no problem.

#### Edit

I just realized that this is happening on the Login form as well. And that is vanilla `auth` from the laravel ui package.

### Code snippets
Story Edit form:
```php
@csrf
<div class="form-group">
    <label for="Image">Image</label>
    <input type="number" class="form-control @error('image_id') is-invalid @enderror" id="image_id" name="image_id"
           aria-describedby="imageHelp" value="{{old('image_id') ?: $story->image_id}}">
    <small id="imageHelp" class="form-text text-muted">Image associated with your story</small>
    @error('image_id')
        <span class="invalid-feedback" role="alert"><strong>{{ $message }}</strong></span>
    @enderror
</div>
<div class="form-group">
    <label for="title">Title</label>
    <input type="text" class="form-control @error('title') is-invalid @enderror" id="title" name="title"
           aria-describedby="titleHelp" value="{{old('title', $story->title)}}">
    <small id="titleHelp" class="form-text text-muted">Title of your story</small>
    @error('title')
        <span class="invalid-feedback" role="alert"><strong>{{ $message }}</strong></span>
    @enderror
</div>
<div class="form-group">
    <label for="abstract">Abstract</label>
    <textarea class="form-control @error('abstract') is-invalid @enderror" id="abstract"
              name="abstract" aria-describedby="abstractHelp">{{old('abstract', $story->abstract)}}</textarea>
    <small id="abstractHelp" class="form-text text-muted">Small blurb about your story to interest readers.</small>
    @error('abstract')
        <span class="invalid-feedback" role="alert"><strong>{{ $message }}</strong></span>
    @enderror
</div>
<div class="form-group">
    <label for="body">Story</label>
    <textarea class="form-control @error('body') is-invalid @enderror" id="body" name="body"
              aria-describedby="bodyHelp">{{old('body', $story->body)}}</textarea>
    <small id="bodyHelp" class="form-text text-muted">The main story</small>
    @error('body')
        <span class="invalid-feedback" role="alert"><strong>{{ $message }}</strong></span>
    @enderror
</div>
```

Story model:
```php
class Story extends Model {

    use SoftDeletes;

    protected $guarded = [];
}
```

Story Controller update method:
```php
    /**
     * Update the specified resource in storage.
     *
     * @param Request $request
     * @param Story $story
     * @return StoryPostRequest
     */
    public function update(StoryPostRequest $request, Story $story) {
    }
```

StoryPostRequest FormRequest validation:
```php
class StoryPostRequest extends FormRequest {

    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize() {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules() {
        return [
            'image_id' => 'required|numeric',
            'title' => 'required|string|max:250',
            'abstract' => 'required|string|min:50',
            'body' => 'required|string|min:50',
        ];
    }

    public function attributes() {
        return [
            'body' => 'story',
        ];
    }
}
```

Validation Exception:
```log
The given data was invalid.
Illuminate\Validation\ValidationException
     */
    protected function failedValidation(Validator $validator)
    {
        throw (new ValidationException($validator))
                    ->errorBag($this->errorBag)
                    ->redirectTo($this->getRedirectUrl());
    }
/var/www/dummy_site/vendor/laravel/framework/src/Illuminate/Foundation/Http/FormRequest.php#130
#0 /var/www/dummy_site/vendor/laravel/framework/src/Illuminate/Validation/ValidatesWhenResolvedTrait.php(26): Illuminate\Foundation\Http\FormRequest->failedValidation(Object(Illuminate\Validation\Validator))
#1 /var/www/dummy_site/vendor/laravel/framework/src/Illuminate/Foundation/Providers/FormRequestServiceProvider.php(30): Illuminate\Foundation\Http\FormRequest->validateResolved()
#2 /var/www/dummy_site/vendor/laravel/framework/src/Illuminate/Container/Container.php(1102): Illuminate\Foundation\Providers\FormRequestServiceProvider->Illuminate\Foundation\Providers\{closure}(Object(App\Http\Requests\StoryPostRequest), Object(Illuminate\Foundation\Application))
#3 /var/www/dummy_site/vendor/laravel/framework/src/Illuminate/Container/Container.php(1066): Illuminate\Container\Container->fireCallbackArray(Object(App\Http\Requests\StoryPostRequest), Array)
#4 /var/www/dummy_site/vendor/laravel/framework/src/Illuminate/Container/Container.php(1051): Illuminate\Container\Container->fireAfterResolvingCallbacks('App\\Http\\Reques...', Object(App\Http\Requests\StoryPostRequest))
#5 /var/www/dummy_site/vendor/laravel/framework/src/Illuminate/Container/Container.php(701): Illuminate\Container\Container->fireResolvingCallbacks('App\\Http\\Reques...', Object(App\Http\Requests\StoryPostRequest))
#6 /var/www/dummy_site/vendor/laravel/framework/src/Illuminate/Container/Container.php(629): Illuminate\Container\Container->resolve('App\\Http\\Reques...', Array)
#7 /var/www/dummy_site/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(776): Illuminate\Container\Container->make('App\\Http\\Reques...', Array)
#8 /var/www/dummy_site/vendor/laravel/framework/src/Illuminate/Routing/RouteDependencyResolverTrait.php(79): Illuminate\Foundation\Application->make('App\\Http\\Reques...')
#9 /var/www/dummy_site/vendor/laravel/framework/src/Illuminate/Routing/RouteDependencyResolverTrait.php(46): Illuminate\Routing\ControllerDispatcher->transformDependency(Object(ReflectionParameter), Array)
#10 /var/www/dummy_site/vendor/laravel/framework/src/Illuminate/Routing/RouteDependencyResolverTrait.php(27): Illuminate\Routing\ControllerDispatcher->resolveMethodDependencies(Array, Object(ReflectionMethod))
#11 /var/www/dummy_site/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(41): Illuminate\Routing\ControllerDispatcher->resolveClassMethodDependencies(Array, Object(App\Http\Controllers\StoryController), 'store')
#12 /var/www/dummy_site/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(App\Http\Controllers\StoryController), 'store')
#13 /var/www/dummy_site/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\Routing\Route->runController()
#14 /var/www/dummy_site/vendor/laravel/framework/src/Illuminate/Routing/Router.php(681): Illuminate\Routing\Route->run()
#15 /var/www/dummy_site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#16 /var/www/dummy_site/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#17 /var/www/dummy_site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#18 /var/www/dummy_site/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(43): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#19 /var/www/dummy_site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Auth\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#20 /var/www/dummy_site/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(76): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#21 /var/www/dummy_site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#22 /var/www/dummy_site/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#23 /var/www/dummy_site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#24 /var/www/dummy_site/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(56): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#25 /var/www/dummy_site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#26 /var/www/dummy_site/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#27 /var/www/dummy_site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#28 /var/www/dummy_site/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#29 /var/www/dummy_site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#30 /var/www/dummy_site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#31 /var/www/dummy_site/vendor/laravel/framework/src/Illuminate/Routing/Router.php(683): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#32 /var/www/dummy_site/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#33 /var/www/dummy_site/vendor/laravel/framework/src/Illuminate/Routing/Router.php(624): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#34 /var/www/dummy_site/vendor/laravel/framework/src/Illuminate/Routing/Router.php(613): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#35 /var/www/dummy_site/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(170): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#36 /var/www/dummy_site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#37 /var/www/dummy_site/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(65): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#38 /var/www/dummy_site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Barryvdh\Debugbar\Middleware\InjectDebugbar->handle(Object(Illuminate\Http\Request), Object(Closure))
#39 /var/www/dummy_site/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#40 /var/www/dummy_site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#41 /var/www/dummy_site/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#42 /var/www/dummy_site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#43 /var/www/dummy_site/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#44 /var/www/dummy_site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(Illuminate\Http\Request), Object(Closure))
#45 /var/www/dummy_site/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#46 /var/www/dummy_site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#47 /var/www/dummy_site/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#48 /var/www/dummy_site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#49 /var/www/dummy_site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#50 /var/www/dummy_site/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#51 /var/www/dummy_site/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#52 /var/www/dummy_site/public/index.php(55): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#53 {main}
```

### Steps To Reproduce:
see [#test_running]

**Comment by driesvints** [comment]
Heya, thanks for reporting. Is there any chance we can boil all of this down to a single input and one simple validation line?

**Comment by casperwilkes** [comment]
Hey @driesvints Thanks for responding. I included all the information to make sure I didn't under-report. I don't know what exactly you want me to boil down further. It's happening in all forms that include simple text fields; this includes the login fields. 

Would that be a good place to start?

**Comment by driesvints** [comment]
@casperwilkes try to upload a sample app that reproduces the error. Preferable with just one field. Try to commit your custom changes separately from the laravel skeleton.

**Comment by buismaarten** [comment]
Experiencing this problem too, luckily I'm not the only one.

- Laravel Version: v6.16.0
- PHP Version: 7.4.1

**Comment by buismaarten** [comment]
Tried a new Laravel project with authentication en Laravel Telescope only, the problem only encounters after a Laravel Telescope installation.

**Comment by driesvints** [comment]
@buismaarten please open an issue on Telescope.

**Comment by casperwilkes** [comment]
Hello, Wanted to follow up. I kinda figured out what the issue was. It had something to do with my session. I'm not sure if there was a time out or what, but the issue always seemed intermittent. I found that if I logged out, and back in, it would resolve itself. 

So, for anyone else experiencing the same issue, try logging out and back in again.
