### ISSUE TITLE
Job middleware revives retry_after bug after job fails

### ISSUE THREAD

**Issue by davi5e** [laravel/framework#32266]
- Laravel Version: v7.4.0
- PHP Version: 7.3.16
- Redis Driver 5.0 & Version: predis v1.1.1

### Description:

The old issue https://github.com/laravel/horizon/issues/567 and its fix https://github.com/laravel/framework/pull/29024 stopped working when a `middleware()` method is placed inside the job class.

I found this behavior after failing a job manually using a custom message so I'd see said message on Horizon's dashboard. Nevertheless, once I figured out how to do this, I noticed the custom error persisted for the time it took the queue to re-run the job (param `retry_after`) and overwrite the failed cause with `MaxAttemptsExceededException`.

In other words, the nice error message that tells me why the job failed gets replaced, even after I've called `fail()` intentionally. In the tests I did to reproduce the issue, removing the `middleware()` method makes it work, so I think I've found the culprit...

Anyway, I may have forced my way into failing the job. If anyone knows a better way to accomplish this, it would be really helpful!

### Steps To Reproduce:

**1. Configure the queue connection**

```php
<?php

return [

    // config/queue.php redacted

    'connections' => [
        'redis' => [
            'driver' => 'redis',
            'connection' => 'default',
            'queue' => 'default',
            'retry_after' => 90,
            'block_for' => null,
        ],
    ],

    'failed' => [
        'driver' => env('QUEUE_FAILED_DRIVER', 'database'),
        'database' => env('DB_CONNECTION', 'mysql'),
        'table' => 'failed_jobs',
    ],
```

**2. Create a job**

```php
<?php

namespace App\Jobs;

use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Queue\SerializesModels;
use RuntimeException;

class TestJob implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    /**
     * The number of times the job may be attempted.
     *
     * @var int
     */
    public $tries = 1;

    public function __construct()
    {
        //
    }

    public function middleware()
    {
        return [
            new Middleware\IntegrityCheck,
        ];
    }

    public function handle()
    {
        $this->job->fail($e = new RuntimeException('some meaningful message here'));
        throw $e;
    }
}
```

**3. Create a middleware**: for example, one that assures the failed job gets saved...

```php
<?php

namespace App\Jobs\Middleware;

use Illuminate\Support\Facades\DB;

class IntegrityCheck
{
    /**
     * Check if database is online before attempting to run the job.
     *
     * @param  mixed  $command
     * @param  callable  $next
     *
     * @return mixed
     */
    public function handle($command, callable $next)
    {
        try {
            // Check to see if the database is online
            DB::connection()->getPdo();
            $next($command);
        }
        catch (\Exception $error) {
            if ($command->attempts() <= 3) {
                // Wait 1 minute before retry
                $command->release(60);
            } else {
                // Wait 20 minutes before retry
                $command->release(1200);
            }
        }
    }
}
```

**4. Start the queue worker** and see the job failing **twice**, the second time being flagged as exceeding the max attempts...

```bash
php artisan queue:work --verbose --tries=5 --timeout=60
```

If you comment out the middleware, the command behave as expected.

### Logs WITH job middleware (problematic)

```
[2020-04-07 01:37:46][15] Processing: App\Jobs\TestJob
[2020-04-07 01:37:46][15] Failed:     App\Jobs\TestJob
[2020-04-07 01:37:46][15] Processed:  App\Jobs\TestJob
[2020-04-07 01:38:46][15] Processing: App\Jobs\TestJob
[2020-04-07 01:38:46][15] Failed:     App\Jobs\TestJob
[2020-04-07 01:38:46] local.ERROR: App\Jobs\TestJob has been attempted too many times or run too long. The job may have previously timed out. {"exception":"[object] (Illuminate\\Queue\\MaxAttemptsExceededException(code: 0): App\\Jobs\\TestJob has been attempted too many times or run too long. The job may have previously timed out. at /srv/vendor/laravel/framework/src/Illuminate/Queue/Worker.php:647)
[stacktrace]
#0 /srv/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(434): Illuminate\\Queue\\Worker->maxAttemptsExceededException(Object(Illuminate\\Queue\\Jobs\\RedisJob))
#1 /srv/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(346): Illuminate\\Queue\\Worker->markJobAsFailedIfAlreadyExceedsMaxAttempts('redis', Object(Illuminate\\Queue\\Jobs\\RedisJob), 1)
#2 /srv/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(306): Illuminate\\Queue\\Worker->process('redis', Object(Illuminate\\Queue\\Jobs\\RedisJob), Object(Illuminate\\Queue\\WorkerOptions))
#3 /srv/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(132): Illuminate\\Queue\\Worker->runJob(Object(Illuminate\\Queue\\Jobs\\RedisJob), 'redis', Object(Illuminate\\Queue\\WorkerOptions))
#4 /srv/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(112): Illuminate\\Queue\\Worker->daemon('redis', 'default', Object(Illuminate\\Queue\\WorkerOptions))
#5 /srv/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(96): Illuminate\\Queue\\Console\\WorkCommand->runWorker('redis', 'default')
#6 [internal function]: Illuminate\\Queue\\Console\\WorkCommand->handle()
#7 /srv/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array(Array, Array)
#8 /srv/vendor/laravel/framework/src/Illuminate/Container/Util.php(36): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#9 /srv/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#10 /srv/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#11 /srv/vendor/laravel/framework/src/Illuminate/Container/Container.php(592): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#12 /srv/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\\Container\\Container->call(Array)
#13 /srv/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#14 /srv/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#15 /srv/vendor/symfony/console/Application.php(912): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#16 /srv/vendor/symfony/console/Application.php(264): Symfony\\Component\\Console\\Application->doRunCommand(Object(Illuminate\\Queue\\Console\\WorkCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#17 /srv/vendor/symfony/console/Application.php(140): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#18 /srv/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#19 /srv/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#20 /srv/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#21 {main}
"}
```

### Logs WITHOUT job middleware (working fine):

```
[2020-04-07 01:47:37][16] Processing: App\Jobs\TestJob
[2020-04-07 01:47:37][16] Failed:     App\Jobs\TestJob
[2020-04-07 01:47:37] local.ERROR: some meaningful message here {"exception":"[object] (RuntimeException(code: 0): some meaningful message here at /srv/app/Jobs/TestJob.php:37)
[stacktrace]
#0 [internal function]: App\\Jobs\\TestJob->handle()
#1 /srv/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array(Array, Array)
#2 /srv/vendor/laravel/framework/src/Illuminate/Container/Util.php(36): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#3 /srv/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#4 /srv/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#5 /srv/vendor/laravel/framework/src/Illuminate/Container/Container.php(592): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#6 /srv/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\\Container\\Container->call(Array)
#7 /srv/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}(Object(App\\Jobs\\TestJob))
#8 /srv/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(App\\Jobs\\TestJob))
#9 /srv/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#10 /srv/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(83): Illuminate\\Bus\\Dispatcher->dispatchNow(Object(App\\Jobs\\TestJob), false)
#11 /srv/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Queue\\CallQueuedHandler->Illuminate\\Queue\\{closure}(Object(App\\Jobs\\TestJob))
#12 /srv/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(App\\Jobs\\TestJob))
#13 /srv/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(85): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#14 /srv/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(59): Illuminate\\Queue\\CallQueuedHandler->dispatchThroughMiddleware(Object(Illuminate\\Queue\\Jobs\\RedisJob), Object(App\\Jobs\\TestJob))
#15 /srv/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(98): Illuminate\\Queue\\CallQueuedHandler->call(Object(Illuminate\\Queue\\Jobs\\RedisJob), Array)
#16 /srv/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(356): Illuminate\\Queue\\Jobs\\Job->fire()
#17 /srv/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(306): Illuminate\\Queue\\Worker->process('redis', Object(Illuminate\\Queue\\Jobs\\RedisJob), Object(Illuminate\\Queue\\WorkerOptions))
#18 /srv/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(132): Illuminate\\Queue\\Worker->runJob(Object(Illuminate\\Queue\\Jobs\\RedisJob), 'redis', Object(Illuminate\\Queue\\WorkerOptions))
#19 /srv/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(112): Illuminate\\Queue\\Worker->daemon('redis', 'default', Object(Illuminate\\Queue\\WorkerOptions))
#20 /srv/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(96): Illuminate\\Queue\\Console\\WorkCommand->runWorker('redis', 'default')
#21 [internal function]: Illuminate\\Queue\\Console\\WorkCommand->handle()
#22 /srv/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array(Array, Array)
#23 /srv/vendor/laravel/framework/src/Illuminate/Container/Util.php(36): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#24 /srv/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#25 /srv/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#26 /srv/vendor/laravel/framework/src/Illuminate/Container/Container.php(592): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#27 /srv/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\\Container\\Container->call(Array)
#28 /srv/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#29 /srv/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#30 /srv/vendor/symfony/console/Application.php(912): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#31 /srv/vendor/symfony/console/Application.php(264): Symfony\\Component\\Console\\Application->doRunCommand(Object(Illuminate\\Queue\\Console\\WorkCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#32 /srv/vendor/symfony/console/Application.php(140): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#33 /srv/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#34 /srv/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#35 /srv/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#36 {main}
"}
```

**Comment by driesvints** [comment]
I'll take a look at this at a later time. Appreciating any help in the meantime.

**Comment by taylorotwell** [comment]
I suspect it's something to with the middleware swallowing your failed exception you throw in the job and retrying. In your middleware catch why not check `if ($command->job->hasFailed())`?

**Comment by davi5e** [comment]
Hi @taylorotwell!

To your point of the implementation being odd, I really didn't know how to to achieve a custom error message and ended up with the above example. Also, I didn't understand exactly how to proceed based in your comment...

Assuming all middleware run before `handle()` is called, the idea is to have a new middleware to check if this is the second run and if so check if the previous failed?

Anyhow, in this scenario, I'd also think about registering `Queue::before()` over in `JobsServiceProvider::boot() (or `Queue::exceptionOccurred()` depending on how to stop the queue worker), but nonetheless I still don't know how to just keep the custom exception in place and do not retry...

**Comment by taylorotwell** [comment]
I don't know what you mean. In your middleware catch why can you not just do `if ($this->job->hasFailed()) throw $e`.

**Comment by davi5e** [comment]
It gave an error...

```
local.ERROR: Call to undefined method App\Jobs\TestJob::hasFailed() {"exception":"[object] (Error(code: 0): Call to undefined method App\\Jobs\\TestJob::hasFailed() at /srv/app/Jobs/Middleware/IntegrityCheck.php:19)
```

I had to change `$this->job->hasFailed()` to `$job->hasFailed()` but in the end the property `$job` is protected, so the middleware can't call `hasFailed()`.

**Comment by taylorotwell** [comment]
Ah. We may need to add a method that allows that job instance to be accessed publicly.

**Comment by davi5e** [comment]
Anyway, as an outsider, seems to me that calling `$this->job->fail()` should halt any further attempts to re-run it, and it does so in the absence of a Middleware.

The fact that using one changes this isn't also odd?

**Comment by driesvints** [comment]
I sent in a PR to retrieve the job: https://github.com/laravel/framework/pull/32414

**Comment by driesvints** [comment]
The job property will be public in the next release so you can reference it then.
