### ISSUE TITLE
Class 'Doctrine\Common\Inflector\Inflector' not found

### ISSUE THREAD

**Issue by kenwilliams5** [laravel/framework#33043]
- Laravel Version: 7.13.0
- PHP Version: 7.4.6

### Description:
I know this issue has been reported and closed, but I'm still having this problem. When I try to dispatch a job, I get this error in the failed_jobs table:

```
Error: Class 'Doctrine\Inflector\Inflector' not found in /var/www/html/dev.test/public_html/vendor/laravel/framework/src/Illuminate/Support/Pluralizer.php:135
Stack trace:
#0 /var/www/html/dev.test/public_html/vendor/laravel/framework/src/Illuminate/Support/Pluralizer.php(76): Illuminate\Support\Pluralizer::inflector()
#1 /var/www/html/dev.test/public_html/vendor/laravel/framework/src/Illuminate/Support/Str.php(394): Illuminate\Support\Pluralizer::plural()
#2 /var/www/html/dev.test/public_html/vendor/laravel/framework/src/Illuminate/Support/Str.php(410): Illuminate\Support\Str::plural()
#3 /var/www/html/dev.test/public_html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1326): Illuminate\Support\Str::pluralStudly()
#4 /var/www/html/dev.test/public_html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1292): Illuminate\Database\Eloquent\Model->getTable()
#5 /var/www/html/dev.test/public_html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(998): Illuminate\Database\Eloquent\Builder->setModel()
#6 /var/www/html/dev.test/public_html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1033): Illuminate\Database\Eloquent\Model->newModelQuery()
#7 /var/www/html/dev.test/public_html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1059): Illuminate\Database\Eloquent\Model->newQueryWithoutScopes()
#8 /var/www/html/dev.test/public_html/vendor/laravel/framework/src/Illuminate/Queue/SerializesAndRestoresModelIdentifiers.php(114): Illuminate\Database\Eloquent\Model->newQueryForRestoration()
#9 /var/www/html/dev.test/public_html/vendor/laravel/framework/src/Illuminate/Queue/SerializesAndRestoresModelIdentifiers.php(101): App\Events\NewUserAdded->getQueryForModelRestoration()
#10 /var/www/html/dev.test/public_html/vendor/laravel/framework/src/Illuminate/Queue/SerializesAndRestoresModelIdentifiers.php(57): App\Events\NewUserAdded->restoreModel()
#11 /var/www/html/dev.test/public_html/vendor/laravel/framework/src/Illuminate/Queue/SerializesModels.php(116): App\Events\NewUserAdded->getRestoredPropertyValue()
#12 [internal function]: App\Events\NewUserAdded->__unserialize()
#13 /var/www/html/dev.test/public_html/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(53): unserialize()
#14 /var/www/html/dev.test/public_html/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(98): Illuminate\Queue\CallQueuedHandler->call()
#15 /var/www/html/dev.test/public_html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(356): Illuminate\Queue\Jobs\Job->fire()
#16 /var/www/html/dev.test/public_html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(306): Illuminate\Queue\Worker->process()
#17 /var/www/html/dev.test/public_html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(132): Illuminate\Queue\Worker->runJob()
#18 /var/www/html/dev.test/public_html/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(112): Illuminate\Queue\Worker->daemon()
#19 /var/www/html/dev.test/public_html/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(96): Illuminate\Queue\Console\WorkCommand->runWorker()
#20 [internal function]: Illuminate\Queue\Console\WorkCommand->handle()
#21 /var/www/html/dev.test/public_html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(33): call_user_func_array()
#22 /var/www/html/dev.test/public_html/vendor/laravel/framework/src/Illuminate/Container/Util.php(36): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#23 /var/www/html/dev.test/public_html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(91): Illuminate\Container\Util::unwrapIfClosure()
#24 /var/www/html/dev.test/public_html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\Container\BoundMethod::callBoundMethod()
#25 /var/www/html/dev.test/public_html/vendor/laravel/framework/src/Illuminate/Container/Container.php(592): Illuminate\Container\BoundMethod::call()
#26 /var/www/html/dev.test/public_html/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\Container\Container->call()
#27 /var/www/html/dev.test/public_html/vendor/symfony/console/Command/Command.php(255): Illuminate\Console\Command->execute()
#28 /var/www/html/dev.test/public_html/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\Component\Console\Command\Command->run()
#29 /var/www/html/dev.test/public_html/vendor/symfony/console/Application.php(912): Illuminate\Console\Command->run()
#30 /var/www/html/dev.test/public_html/vendor/symfony/console/Application.php(264): Symfony\Component\Console\Application->doRunCommand()
#31 /var/www/html/dev.test/public_html/vendor/symfony/console/Application.php(140): Symfony\Component\Console\Application->doRun()
#32 /var/www/html/dev.test/public_html/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\Component\Console\Application->run()
#33 /var/www/html/dev.test/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\Console\Application->run()
#34 /var/www/html/dev.test/public_html/artisan(37): Illuminate\Foundation\Console\Kernel->handle()
#35 {main}

```

I have tried to update everything to the latest version, required doctrine/common v3.0.1 and doctrine/inflector v2.0.3 with no change. This was a fresh install of Laravel v7 and upgraded to the latest versions as I work.

I have tried to do as suggested before: delete /bootstrap/cache files and run composer update. This made no change.

I am at a loss as to what to do.

### Steps To Reproduce:

Fire an event and have the listener implement ShouldQueue with a User model passed in to the event.

**Comment by thisismhp** [comment]
https://github.com/laravel/framework/issues/32814#issuecomment-628411610

**Comment by kenwilliams5** [comment]
So it's closed? This doesn't work...Can you even tell me that you think it's fixed?
