### ISSUE TITLE
Laravel 7.x not working on shared hosting

### ISSUE THREAD

**Issue by sunilFullStack** [laravel/framework#33646]
i created a fresh laravel project on my computer and its working fine but when i upload its on server its giving me HTTP ERROR 500 and i found thiis error in error.log

```
[25-Jul-2020 06:17:15 UTC] PHP Fatal error:  Declaration of Carbon\Translator::setLocale($locale) must be compatible with Symfony\Contracts\Translation\LocaleAwareInterface::setLocale(string $locale) in /home1/comdotndash/public_html/demo/marble/vendor/nesbot/carbon/src/Carbon/Translator.php on line 18
[25-Jul-2020 06:17:15 UTC] PHP Fatal error:  Uncaught TypeError: Return value of Symfony\Component\HttpFoundation\Response::setStatusCode() must be an instance of Symfony\Component\HttpFoundation\object, instance of Symfony\Component\HttpFoundation\Response returned in /home1/comdotndash/public_html/demo/marble/vendor/symfony/http-foundation/Response.php:475
Stack trace:
#0 /home1/comdotndash/public_html/demo/marble/vendor/symfony/http-foundation/Response.php(219): Symfony\Component\HttpFoundation\Response->setStatusCode(500)
#1 /home1/comdotndash/public_html/demo/marble/vendor/symfony/http-foundation/Response.php(239): Symfony\Component\HttpFoundation\Response->__construct('<!doctype html>...', 500, Array)
#2 /home1/comdotndash/public_html/demo/marble/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(328): Symfony\Component\HttpFoundation\Response::create('<!doctype html>...', 500, Array)
#3 /home1/comdotndash/public_html/demo/marble/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(305): Illuminate\Found in /home1/comdotndash/public_html/demo/marble/vendor/symfony/http-foundation/Response.php on line 475
 
```

**Comment by oceanapplications** [comment]
Check the PHP version installed on that server. 

https://github.com/laravel/framework/issues/31907

**Comment by sunilFullStack** [comment]
i tried  all php versions 7.0 to 7.4

**Comment by GrahamCampbell** [comment]
> [25-Jul-2020 06:17:15 UTC] PHP Fatal error:  Uncaught TypeError: Return value of Symfony\Component\HttpFoundation\Response::setStatusCode() must be an instance of Symfony\Component\HttpFoundation\object, instance of Symfony\Component\HttpFoundation\Response returned in /home1/comdotndash/public_html/demo/marble/vendor/symfony/http-foundation/Response.php:475

That error happens when your PHP version is less than 7.2.0. Laravel 7 requires PHP 7.2.5 or higher.
