### ISSUE TITLE
ReflectionException error in router 

### ISSUE THREAD

**Issue by niteen1593** [laravel/framework#33893]
- Laravel Version: 7.25.0
- PHP Version:7.4.7
- Database Driver & Version: Mysql 8.0.20

### Description:
If I define route like below 
```php
Route::middleware('auth:sanctum')->get('affairs/list', [AffairsController::class, 'getAffairs']);
```
I am getting error

```
ReflectionException: Function () does not exist in file /home/ubuntu/projects/study/saralseva/vendor/laravel/framework/src/Illuminate/Routing/RouteSignatureParameters.php on line 23

#0 /home/ubuntu/projects/study/saralseva/vendor/laravel/framework/src/Illuminate/Routing/RouteSignatureParameters.php(23): ReflectionFunction->__construct()
#1 /home/ubuntu/projects/study/saralseva/vendor/laravel/framework/src/Illuminate/Routing/Route.php(491): Illuminate\Routing\RouteSignatureParameters::fromAction()
#2 /home/ubuntu/projects/study/saralseva/vendor/laravel/framework/src/Illuminate/Routing/ImplicitRouteBinding.php(25): Illuminate\Routing\Route->signatureParameters()
#3 /home/ubuntu/projects/study/saralseva/vendor/laravel/framework/src/Illuminate/Routing/Router.php(798): Illuminate\Routing\ImplicitRouteBinding::resolveForRoute()
#4 /home/ubuntu/projects/study/saralseva/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(39): Illuminate\Routing\Router->substituteImplicitBindings()
#5 /home/ubuntu/projects/study/saralseva/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Routing\Middleware\SubstituteBindings->handle()
#6 /home/ubuntu/projects/study/saralseva/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(44): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#7 /home/ubuntu/projects/study/saralseva/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Auth\Middleware\Authenticate->handle()
#8 /home/ubuntu/projects/study/saralseva/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(77): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#9 /home/ubuntu/projects/study/saralseva/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle()
#10 /home/ubuntu/projects/study/saralseva/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#11 /home/ubuntu/projects/study/saralseva/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\View\Middleware\ShareErrorsFromSession->handle()
#12 /home/ubuntu/projects/study/saralseva/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#13 /home/ubuntu/projects/study/saralseva/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(62): Illuminate\Session\Middleware\StartSession->handleStatefulRequest()
#14 /home/ubuntu/projects/study/saralseva/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Session\Middleware\StartSession->handle()
#15 /home/ubuntu/projects/study/saralseva/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#16 /home/ubuntu/projects/study/saralseva/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle()
#17 /home/ubuntu/projects/study/saralseva/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#18 /home/ubuntu/projects/study/saralseva/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Cookie\Middleware\EncryptCookies->handle()
#19 /home/ubuntu/projects/study/saralseva/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#20 /home/ubuntu/projects/study/saralseva/vendor/laravel/framework/src/Illuminate/Routing/Router.php(687): Illuminate\Pipeline\Pipeline->then()
#21 /home/ubuntu/projects/study/saralseva/vendor/laravel/framework/src/Illuminate/Routing/Router.php(662): Illuminate\Routing\Router->runRouteWithinStack()
#22 /home/ubuntu/projects/study/saralseva/vendor/laravel/framework/src/Illuminate/Routing/Router.php(628): Illuminate\Routing\Router->runRoute()
#23 /home/ubuntu/projects/study/saralseva/vendor/laravel/framework/src/Illuminate/Routing/Router.php(617): Illuminate\Routing\Router->dispatchToRoute()
#24 /home/ubuntu/projects/study/saralseva/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\Routing\Router->dispatch()
#25 /home/ubuntu/projects/study/saralseva/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}()
#26 /home/ubuntu/projects/study/saralseva/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#27 /home/ubuntu/projects/study/saralseva/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
#28 /home/ubuntu/projects/study/saralseva/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#29 /home/ubuntu/projects/study/saralseva/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
#30 /home/ubuntu/projects/study/saralseva/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#31 /home/ubuntu/projects/study/saralseva/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle()
#32 /home/ubuntu/projects/study/saralseva/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#33 /home/ubuntu/projects/study/saralseva/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle()
#34 /home/ubuntu/projects/study/saralseva/vendor/fruitcake/laravel-cors/src/HandleCors.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#35 /home/ubuntu/projects/study/saralseva/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\Cors\HandleCors->handle()
#36 /home/ubuntu/projects/study/saralseva/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#37 /home/ubuntu/projects/study/saralseva/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\Proxy\TrustProxies->handle()
#38 /home/ubuntu/projects/study/saralseva/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#39 /home/ubuntu/projects/study/saralseva/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(140): Illuminate\Pipeline\Pipeline->then()
#40 /home/ubuntu/projects/study/saralseva/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(109): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
#41 /home/ubuntu/projects/study/saralseva/public/index.php(55): Illuminate\Foundation\Http\Kernel->handle()
#42 /home/ubuntu/projects/study/saralseva/server.php(21): require_once('/home/ubuntu/pr...')
#43 {main}
```

If I change this to following it works
```php
Route::get('affairs/list', [AffairsController::class, 'getAffairs'])->middleware('auth:sanctum');
```
and following also it works
```php
Route::middleware('auth:sanctum')->get('affairs/list', 'AffairsController@getAffairs');
```

so only for 
```php
Route::middleware('auth:sanctum')->get('affairs/list', [AffairsController::class, 'getAffairs']);
```
above it is not working.

**Comment by GrahamCampbell** [comment]
Yep, that syntax is not supported. You must use a Closure, laravel class@method syntax, or a name. If you look at the phpdoc, it will tell you that you cannot pass a callable. :)

**Comment by GrahamCampbell** [comment]
It's odd that it works for that other case though. Maybe someone added callable support in a PR, but didn't cover all the places properly?

**Comment by taylorotwell** [comment]
Fixed in next patch release.
