### ISSUE TITLE
upsert() fails for models using Attribute Casting

### ISSUE THREAD

**Issue by sunaoka** [laravel/framework#34967]
- Laravel Version: 8.11.2
- PHP Version: 7.4.7
- Database Driver & Version: sqlite 3.28.0

### Description:

The upsert() method, supported since 8.10, throws an error when used with Attribute Casting.

### Steps To Reproduce:

Migration:

```php
<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateFlightsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('flights', function (Blueprint $table) {
            $table->id();
            $table->jsonb('movies');
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('flights');
    }
}
```

Model:

```php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Flight extends Model
{
    use HasFactory;

    protected $casts = [
        'movies' => 'array',
    ];
}
```

Code:

```php
<?php

$flight = new Flight;
$flight->movies = ['movie 1', 'movie 2'];
$flight->save();

// OK
// insert into "flights" ("movies", "updated_at", "created_at") values ('["movie 1","movie 2"]', '2020-10-26 06:18:36', '2020-10-26 06:18:36');

Flight::where('id', 1)
    ->update([
        'movies' => ['movie 3', 'movie 4'],
    ]);

// OK
// update "flights" set "movies" = '["movie 3","movie 4"]', "updated_at" = '2020-10-26 06:18:36' where "id" = 1;

Flight::upsert([
    'id'     => 1,
    'movies' => ['movie 5', 'movie 6'],
], ['id']);

// Error...

Flight::upsert([
    'id'     => 1,
    'movies' => json_encode(['movie 5', 'movie 6']),
], ['id']);

// But, json_encode() and OK.
// insert into "flights" ("created_at", "id", "movies", "updated_at") values ('2020-10-26 06:18:36', 1, '["movie 5","movie 6"]', '2020-10-26 06:18:36') on conflict ("id") do update set "id" = "excluded"."id", "movies" = "excluded"."movies", "updated_at" = "excluded"."updated_at"; 
```

Error:

```
[2020-10-26 06:06:07] local.ERROR: Array to string conversion {"exception":"[object] (ErrorException(code: 0): Array to string conversion at /tmp/8.11.2/vendor/laravel/framework/src/Illuminate/Support/Str.php:494)
[stacktrace]
#0 /tmp/8.11.2/vendor/laravel/framework/src/Illuminate/Support/Str.php(494): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /tmp/8.11.2/vendor/laravel/framework/src/Illuminate/Database/QueryException.php(57): Illuminate\\Support\\Str::replaceArray()
#2 /tmp/8.11.2/vendor/laravel/framework/src/Illuminate/Database/QueryException.php(40): Illuminate\\Database\\QueryException->formatMessage()
#3 /tmp/8.11.2/vendor/laravel/framework/src/Illuminate/Database/Connection.php(672): Illuminate\\Database\\QueryException->__construct()
#4 /tmp/8.11.2/vendor/laravel/framework/src/Illuminate/Database/Connection.php(631): Illuminate\\Database\\Connection->runQueryCallback()
#5 /tmp/8.11.2/vendor/laravel/framework/src/Illuminate/Database/Connection.php(496): Illuminate\\Database\\Connection->run()
#6 /tmp/8.11.2/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2964): Illuminate\\Database\\Connection->affectingStatement()
#7 /tmp/8.11.2/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(828): Illuminate\\Database\\Query\\Builder->upsert()
#8 /tmp/8.11.2/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php(23): Illuminate\\Database\\Eloquent\\Builder->upsert()
#9 /tmp/8.11.2/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1724): Illuminate\\Database\\Eloquent\\Model->forwardCallTo()
#10 /tmp/8.11.2/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1736): Illuminate\\Database\\Eloquent\\Model->__call()
#11 /tmp/8.11.2/app/Console/Commands/UpsertCommand.php(57): Illuminate\\Database\\Eloquent\\Model::__callStatic()
#12 /tmp/8.11.2/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Console\\Commands\\UpsertCommand->handle()
#13 /tmp/8.11.2/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#14 /tmp/8.11.2/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#15 /tmp/8.11.2/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#16 /tmp/8.11.2/vendor/laravel/framework/src/Illuminate/Container/Container.php(596): Illuminate\\Container\\BoundMethod::call()
#17 /tmp/8.11.2/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\\Container\\Container->call()
#18 /tmp/8.11.2/vendor/symfony/console/Command/Command.php(258): Illuminate\\Console\\Command->execute()
#19 /tmp/8.11.2/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
#20 /tmp/8.11.2/vendor/symfony/console/Application.php(920): Illuminate\\Console\\Command->run()
#21 /tmp/8.11.2/vendor/symfony/console/Application.php(266): Symfony\\Component\\Console\\Application->doRunCommand()
#22 /tmp/8.11.2/vendor/symfony/console/Application.php(142): Symfony\\Component\\Console\\Application->doRun()
#23 /tmp/8.11.2/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\\Component\\Console\\Application->run()
#24 /tmp/8.11.2/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run()
#25 /tmp/8.11.2/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#26 {main}
"} 
```

**Comment by driesvints** [comment]
Ping @paras-malhotra.

**Comment by paras-malhotra** [comment]
This is similar behaviour to `insert` and `insertOrIgnore`. You'll just have to use `json_encode`, don't think this is a bug.

**Comment by driesvints** [comment]
@paras-malhotra I agree here. Thanks
