### ISSUE TITLE
`schema:dump` will fail if `migrations` table was renamed

### ISSUE THREAD

**Issue by LastDragon-ru** [laravel/framework#35108]
- Laravel Version: 8.13.0
- PHP Version: 7.4.x
- Database Driver & Version: MySQL 8.x

### Description:

The `migrations` table can be renamed in `config/database.php`, but `src/Illuminate/Database/Schema/*SchemaState.php` always use the hardcoded `migrations` string.

https://github.com/laravel/framework/blob/9561987ebf570befc346e63ec45b9ecd1c161048/src/Illuminate/Database/Schema/MySqlSchemaState.php#L56

https://github.com/laravel/framework/blob/9561987ebf570befc346e63ec45b9ecd1c161048/src/Illuminate/Database/Schema/PostgresSchemaState.php#L22

https://github.com/laravel/framework/blob/9561987ebf570befc346e63ec45b9ecd1c161048/src/Illuminate/Database/Schema/SqliteSchemaState.php#L42

### Steps To Reproduce:

1. Rename `migrations` table in `config/database.php`
2. `php artisan schema:dump`

### Logs

<details>
  <summary>laravel.log</summary>

```
[2020-11-05 13:09:11] local.ERROR: The command "mysqldump --set-gtid-purged=OFF --skip-add-drop-table --skip-add-locks --skip-comments --skip-set-charset --tz-utc --host="${:LARAVEL_LOAD_HOST}" --port="${:LARAVEL_LOAD_PORT}" --user="${:LARAVEL_LOAD_USER}" --password="${:LARAVEL_LOAD_PASSWORD}" "${:LARAVEL_LOAD_DATABASE}" migrations --no-create-info --skip-extended-insert --skip-routines --compact" failed.

Exit Code: 6(Unknown error)

Working directory: /project

Output:
================


Error Output:
================
mysqldump: [Warning] Using a password on the command line interface can be insecure.
mysqldump: Couldn't find table: "migrations"
 {"exception":"[object] (Symfony\\Component\\Process\\Exception\\ProcessFailedException(code: 0): The command \"mysqldump --set-gtid-purged=OFF --skip-add-drop-table --skip-add-locks --skip-comments --skip-set-charset --tz-utc --host=\"${:LARAVEL_LOAD_HOST}\" --port=\"${:LARAVEL_LOAD_PORT}\" --user=\"${:LARAVEL_LOAD_USER}\" --password=\"${:LARAVEL_LOAD_PASSWORD}\" \"${:LARAVEL_LOAD_DATABASE}\" migrations --no-create-info --skip-extended-insert --skip-routines --compact\" failed.

Exit Code: 6(Unknown error)

Working directory: /project

Output:
================


Error Output:
================
mysqldump: [Warning] Using a password on the command line interface can be insecure.
mysqldump: Couldn't find table: \"migrations\"
 at /project/vendor/symfony/process/Process.php:252)
[stacktrace]
#0 /project/vendor/laravel/framework/src/Illuminate/Database/Schema/MySqlSchemaState.php(121): Symfony\\Component\\Process\\Process->mustRun()
#1 /project/vendor/laravel/framework/src/Illuminate/Database/Schema/MySqlSchemaState.php(124): Illuminate\\Database\\Schema\\MySqlSchemaState->executeDumpProcess()
#2 /project/vendor/laravel/framework/src/Illuminate/Database/Schema/MySqlSchemaState.php(59): Illuminate\\Database\\Schema\\MySqlSchemaState->executeDumpProcess()
#3 /project/vendor/laravel/framework/src/Illuminate/Database/Schema/MySqlSchemaState.php(29): Illuminate\\Database\\Schema\\MySqlSchemaState->appendMigrationData()
#4 /project/vendor/laravel/framework/src/Illuminate/Database/Console/DumpCommand.php(41): Illuminate\\Database\\Schema\\MySqlSchemaState->dump()
#5 /project/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Database\\Console\\DumpCommand->handle()
#6 /project/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#7 /project/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#8 /project/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#9 /project/vendor/laravel/framework/src/Illuminate/Container/Container.php(596): Illuminate\\Container\\BoundMethod::call()
#10 /project/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\\Container\\Container->call()
#11 /project/vendor/symfony/console/Command/Command.php(258): Illuminate\\Console\\Command->execute()
#12 /project/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
#13 /project/vendor/symfony/console/Application.php(920): Illuminate\\Console\\Command->run()
#14 /project/vendor/symfony/console/Application.php(266): Symfony\\Component\\Console\\Application->doRunCommand()
#15 /project/vendor/symfony/console/Application.php(142): Symfony\\Component\\Console\\Application->doRun()
#16 /project/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\\Component\\Console\\Application->run()
#17 /project/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run()
#18 /project/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#19 {main}
"} 
```
</details>

**Comment by driesvints** [comment]
I get that his is causing issues. But then again, what are you going to do if you do it the other way around when the schema is already dumped? I think this might be a limitation which we can't overcome.

**Comment by LastDragon-ru** [comment]
> But then again, what are you going to do if you do it the other way around when the schema is already dumped?

@driesvints, nothing, because if you want to rename any table in the project, this is a big change and you must update all code/sqls/add migration/etc... So this is a developer problem, not Laravel. Much worse when you cannot use one of the standard settings in a big* old project where `scheme:dump` may be really useful :(

_* a few hundred migrations, and ~ hundred tables... ability to rename laravel's tables is really needed to keep things organized here._

**Comment by taylorotwell** [comment]
Will get a fix in the upcoming patch release.

**Comment by LastDragon-ru** [comment]
> Will get a fix in the upcoming patch release.

Thanks!
