### ISSUE TITLE
Uncaught exception handler - Symfony\Component\HttpFoundation\Response::create() is deprecated in Illuminate\Foundation\Exceptions\Handler::convertExceptionToResponse()

### ISSUE THREAD

**Issue by arruor** [laravel/framework#35288]
- Laravel Version: 8.15.0
- PHP Version: 7.4.12
- Database Driver & Version:

### Description:
Update to `symphony/http-foundation` to 5.1.x causes uncaught exception when trying to convert previous exception to response. Since 5.1 using `\Symfony\Component\HttpFoundation\Response::create()` is deprecated and constructor should be used instead.

### Steps To Reproduce:
1. Create a new or update existing project to 8.x (which will trigger `symphony/http-foundation` to be updated to 5.1.x).
2. Force uncaught exception - wrong syntax, call to missing method, etc.
3. Server responds with 500 instead of displaying exception.

```
[2020-11-19 12:45:04] development.ERROR: Since symfony/http-foundation 5.1: The "Symfony\Component\HttpFoundation\Response::create()" method is deprecated, use "new Symfony\Component\HttpFoundation\Response()" instead. {"exception":"[object] (ErrorException(code: 0): Since symfony/http-foundation 5.1: The \"Symfony\\Component\\HttpFoundation\\Response::create()\" method is deprecated, use \"new Symfony\\Component\\HttpFoundation\\Response()\" instead. at /data/mind/Projects/SampleProject/src/vendor/symfony/deprecation-contracts/function.php:25)
[stacktrace]
#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /data/mind/Projects/SampleProject/src/vendor/symfony/deprecation-contracts/function.php(25): trigger_error()
#2 /data/mind/Projects/SampleProject/src/vendor/symfony/http-foundation/Response.php(237): trigger_deprecation()
#3 /data/mind/Projects/SampleProject/src/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(471): Symfony\\Component\\HttpFoundation\\Response::create()
#4 /data/mind/Projects/SampleProject/src/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(448): Illuminate\\Foundation\\Exceptions\\Handler->convertExceptionToResponse()
#5 /data/mind/Projects/SampleProject/src/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(336): Illuminate\\Foundation\\Exceptions\\Handler->prepareResponse()
#6 /data/mind/Projects/SampleProject/src/app/Exceptions/Handler.php(53): Illuminate\\Foundation\\Exceptions\\Handler->render()
#7 /data/mind/Projects/SampleProject/src/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(416): App\\Exceptions\\Handler->render()
#8 /data/mind/Projects/SampleProject/src/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(114): Illuminate\\Foundation\\Http\\Kernel->renderException()
#9 /data/mind/Projects/SampleProject/src/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle()
#10 {main}
"}
```

**Comment by driesvints** [comment]
This is a deprecation notice which should be turned off in production.

**Comment by arruor** [comment]
Do you suggest all development to happen in production environment? 
I think using Laravel's debug mode is still a valid scenario.

**Comment by driesvints** [comment]
There's nothing broken here. It's just a warning that's thrown. Also, that PR seems unrelated?
