### ISSUE TITLE
Exception when testing with @runInSeparateProcess

### ISSUE THREAD

**Issue by LocalHeroPro** [laravel/framework#35307]
- Laravel Version: 8.15.0
- PHP Version: 7.3.12
- Database Driver & Version:

### Steps To Reproduce:
```php
/**
* @runInSeparateProcess
*/
public function testExample(): void
{
    self::assertTrue(true);
}
```
gives error
```bash
PHPUnit\Framework\Exception: PHP Fatal error:  Uncaught ReflectionException: Class config does not exist in /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:830
Stack trace:
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(830): ReflectionClass->__construct('config')
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(712): Illuminate\Container\Container->build('config')
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(796): Illuminate\Container\Container->resolve('config', Array, true)
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(651): Illuminate\Foundation\Application->resolve('config', Array)
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(781): Illuminate\Container\Container->make('config', Array)
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(119): Illuminate\Foundation\Applic in /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 832

Fatal error: Uncaught ReflectionException: Class config does not exist in /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 832

Illuminate\Contracts\Container\BindingResolutionException: Target class [config] does not exist. in /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 832

Call Stack:
    0.0023    1273264   1. {main}() Standard input code:0
    0.0532   14604680   2. require_once('/var/www/html/config/horizon.php') Standard input code:668
    0.0533   14605432   3. config() /var/www/html/config/horizon.php:119
    0.0533   14605432   4. app() /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php:275
    0.0533   14605432   5. Illuminate\Foundation\Application->make() /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php:119
    0.0533   14605432   6. Illuminate\Foundation\Application->make() /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:781
    0.0533   14605432   7. Illuminate\Foundation\Application->resolve() /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:651
    0.0533   14605432   8. Illuminate\Foundation\Application->resolve() /var/wwwhtml/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:796
    0.0533   14605808   9. Illuminate\Foundation\Application->build() /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:712

 at vendor/phpunit/phpunit/phpunit:61
     57▕ unset($options);
     58▕ 
     59▕ require PHPUNIT_COMPOSER_INSTALL;
     60▕ 
  ➜  61▕ PHPUnit\TextUI\Command::main();
     62▕ 

--
```

**Comment by driesvints** [comment]
This isn't a Laravel issue.

**Comment by LocalHeroPro** [comment]
True. This is the easiest way, as always.
