### ISSUE TITLE
SerializesModels trait doesn't work in SerializableClosure

### ISSUE THREAD

**Issue by Vinimaks** [laravel/framework#35336]
- Laravel Version: 6.18.35
- PHP Version: 7.4.11
- Database Driver & Version: MySQL 5.8

### Description:
For some reason, if we try to dispatch closure with `use` some class that uses `SerializableClosure` trait after unserialization `ModelIdentifier` properties will just disappear.

### Steps To Reproduce:

1. Create some `Mailable` class

```php

<?php

namespace App\Mail;

use App\Http\Models\User;
use Illuminate\Bus\Queueable;
use Illuminate\Mail\Mailable;
use Illuminate\Queue\SerializesModels;

class SomeMail extends Mailable
{
    use Queueable, SerializesModels;

    public User $user;

    public function __construct(User $user)
    {
        $this->user = $user;
    }

    public function validate(): bool
    {
        // do smth here
        return $this->user->exists();
    }

    public function build()
    {
        return $this->view('');
    }
}

```

2. Dispatch sending with delayed validation

```php

$mail = new SomeMail(User::find(32)); 

dispatch(function () use ($mail) {
    if ($mail->validate()) {
        return;
    }
    
    \Mail::send($mail);
});
```
3. Queued job will be failed with error: 

```bash
Symfony\Component\Debug\Exception\FatalThrowableError: Typed property App\Mail\SomeMail::$user must not be accessed before initialization in /var/www/test/vendor/opis/closure/src/SerializableClosure.php:564
Stack trace:
#0 /var/www/site/vendor/opis/closure/src/SerializableClosure.php(564): ReflectionProperty->getValue()
#1 /var/www/site/vendor/opis/closure/src/SerializableClosure.php(531): Opis\Closure\SerializableClosure->mapPointers()
#2 /var/www/site/vendor/opis/closure/src/SerializableClosure.php(252): Opis\Closure\SerializableClosure->mapPointers()
#3 [internal function]: Opis\Closure\SerializableClosure->unserialize()
#4 /var/www/site/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(53): unserialize()
#5 /var/www/site/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(88): Illuminate\Queue\CallQueuedHandler->call()
#6 /var/www/site/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(368): Illuminate\Queue\Jobs\Job->fire()
#7 /var/www/site/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(314): Illuminate\Queue\Worker->process()
#8 /var/www/site/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(267): Illuminate\Queue\Worker->runJob()
#9 /var/www/site/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(112): Illuminate\Queue\Worker->runNextJob()
#10 /var/www/site/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(96): Illuminate\Queue\Console\WorkCommand->runWorker()
#11 [internal function]: Illuminate\Queue\Console\WorkCommand->handle()
#12 /var/www/site/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array()
#13 /var/www/site/vendor/laravel/framework/src/Illuminate/Container/Util.php(37): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#14 /var/www/site/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\Container\Util::unwrapIfClosure()
#15 /var/www/site/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\Container\BoundMethod::callBoundMethod()
#16 /var/www/site/vendor/laravel/framework/src/Illuminate/Container/Container.php(590): Illuminate\Container\BoundMethod::call()
#17 /var/www/site/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\Container\Container->call()
#18 /var/www/site/vendor/symfony/console/Command/Command.php(255): Illuminate\Console\Command->execute()
#19 /var/www/site/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\Component\Console\Command\Command->run()
#20 /var/www/site/vendor/symfony/console/Application.php(1000): Illuminate\Console\Command->run()
#21 /var/www/site/vendor/symfony/console/Application.php(271): Symfony\Component\Console\Application->doRunCommand()
#22 /var/www/site/vendor/symfony/console/Application.php(147): Symfony\Component\Console\Application->doRun()
#23 /var/www/site/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\Component\Console\Application->run()
#24 /var/www/site/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(131): Illuminate\Console\Application->run()
#25 /var/www/site/artisan(35): Illuminate\Foundation\Console\Kernel->handle()
#26 {main}

```

**Comment by taylorotwell** [comment]
I am unable to recreate on Laravel 8.

**Comment by Vinimaks** [comment]
@taylorotwell Forgot to add, that `QUEUE_DRIVER=redis`

**Comment by taylorotwell** [comment]
Hmm, I don't think queue driver would affect things here really. Are you able to try to simple recreation on Laravel 8?

**Comment by Vinimaks** [comment]
@taylorotwell I can reproduce the issue only on Larave 6.x. On Laravel 7.x and 8.x, it's working

**Comment by Vinimaks** [comment]
The issue related to the old version of `opis/closure`, in the new version they just added a check for PHP version :D

![image](https://user-images.githubusercontent.com/17598095/100018914-e3f24c00-2de5-11eb-814b-4b543afece75.png)

Excuse me for troubling you @taylorotwell @driesvints
