### ISSUE TITLE
Job batching does not work inside of chain

### ISSUE THREAD

**Issue by godismyjudge95** [laravel/framework#35572]
- Laravel Version: 8.18.1
- PHP Version: 7.4.13
- Database Driver & Version:  mysql  Ver 14.14 Distrib 5.7.32

### Description:
Although running a batch of chains works, it does not work the other way around.
For some reason trying to chain batches will cause an error.

### Steps To Reproduce:
```
Bus::chain([
    new ImportAuthors,
    new ImportCategories,
    Bus::batch([
        new BatchImportPodcasts(1, 100),
        new BatchImportPodcasts(101, 200),
        new BatchImportPodcasts(201, 300),
        new BatchImportPodcasts(301, 400),
        new BatchImportPodcasts(401, 500),
    ])->catch(function (Throwable $e) {
        // A job within the batch has failed
    }),
])->catch(function (Throwable $e) {
    // A job within the chain has failed
})->dispatch();
```

Result:
```
Serialization of 'Closure' is not allowed {"exception":"[object] (Exception(code: 0): Serialization of 'Closure' is not allowed at /marketing/jjkane/api/vendor/laravel/framework/src/Illuminate/Bus/Queueable.php:183)
[stacktrace]
#0 /marketing/jjkane/api/vendor/laravel/framework/src/Illuminate/Bus/Queueable.php(183): serialize()
#1 /marketing/jjkane/api/vendor/laravel/framework/src/Illuminate/Bus/Queueable.php(158): Illuminate\\Queue\\CallQueuedClosure->serializeJob()
#2 [internal function]: Illuminate\\Queue\\CallQueuedClosure->Illuminate\\Bus\\{closure}()
#3 /marketing/jjkane/api/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(630): array_map()
#4 /marketing/jjkane/api/vendor/laravel/framework/src/Illuminate/Bus/Queueable.php(159): Illuminate\\Support\\Collection->map()
#5 /marketing/jjkane/api/vendor/laravel/framework/src/Illuminate/Foundation/Bus/PendingChain.php(160): Illuminate\\Queue\\CallQueuedClosure->chain()
#6 /marketing/jjkane/api/app/Jobs/StartSync.php(125): Illuminate\\Foundation\\Bus\\PendingChain->dispatch()
#7 /marketing/jjkane/api/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Jobs\\StartSync->handle()
#8 /marketing/jjkane/api/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#9 /marketing/jjkane/api/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#10 /marketing/jjkane/api/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#11 /marketing/jjkane/api/vendor/laravel/framework/src/Illuminate/Container/Container.php(610): Illuminate\\Container\\BoundMethod::call()
#12 /marketing/jjkane/api/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(128): Illuminate\\Container\\Container->call()
...
```

Function where it is failing:
```
    protected function serializeJob($job)
    {
        if ($job instanceof Closure) {
            if (! class_exists(CallQueuedClosure::class)) {
                throw new RuntimeException(
                    'To enable support for closure jobs, please install the illuminate/queue package.'
                );
            }

            $job = CallQueuedClosure::create($job);
        }

        return serialize($job);
    }
```

I tried fiddling around with the source code to see if I could resolve this and submit a pull request, but I am having no luck.
Any ideas?  As shown in my use case above it is crucial to be able to import authors, then categories, and finally podcasts because of foreign key relations.

Also some background, I am using a redis queue with 4 workers kept online via supervisor.

**Comment by themsaid** [comment]
Yes it's not supported, do this instead:

```
Bus::chain([
    new ImportAuthors,
    new ImportCategories,
    function(){
        Bus::batch([
        new BatchImportPodcasts(1, 100),
        new BatchImportPodcasts(101, 200),
        new BatchImportPodcasts(201, 300),
        new BatchImportPodcasts(301, 400),
        new BatchImportPodcasts(401, 500),
    ])->catch(function (Throwable $e) {
        // A job within the batch has failed
    })
    },
])->catch(function (Throwable $e) {
    // A job withi the chain has failed
})->dispatch();
```

**Comment by cerw** [comment]
How do i test this? Do Bach/Chain run in sync mode?
