### ISSUE TITLE
Query builder pagination is broken

### ISSUE THREAD

**Issue by EM-LilianaIturribarria** [laravel/framework#35791]
- Laravel Version: 8.21
- PHP Version: 7.3
- Database Driver & Version: mysql 8.0

### Description:
I did a big upgrade from laravel 5.8 to laravel 8.0
I have a Collection and Resource that were working fine on 5.8

my controller:
```
$data = $this->ad->getAll();
return new AdCollection($data);
```

where $this->ad is a repository that does a BIG query using the query builder.
at the end of the query builder i'm doing this:
```
->orderBy('updated_at')
->paginate(10);
```

and if i dd the result, it's a LenghtAwarePagination with items

if i dd a single element from my Resource it gives me the correct information
IF i instead do this:

```
->orderBy('updated_at')
->get()
```
it shows me the correct response but WITHOUT the pagination

so that's why it appears that the pagination is not working... or something regarding the Resource?

the error at the end is this: "Undefined property: stdClass::$resource""

i don't even have a $resource variable anywhere...

The logs are showing this:
```
[2021-01-05 16:14:25] local.ERROR: Undefined property: stdClass::$resource {"userId":1,"exception":"[object] (ErrorException(code: 0): Undefined property: stdClass::$resource at /var/www/og_platform-originplatform/vendor/laravel/framework/src/Illuminate/Http/Resources/Json/PaginatedResourceResponse.php:29)
[stacktrace]
#0 /var/www/og_platform-originplatform/vendor/laravel/framework/src/Illuminate/Http/Resources/Json/PaginatedResourceResponse.php(29): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'Undefined prope...', '/var/www/og_pla...', 29, Array)
#1 [internal function]: Illuminate\\Http\\Resources\\Json\\PaginatedResourceResponse->Illuminate\\Http\\Resources\\Json\\{closure}(Object(stdClass), 0)
#2 /var/www/og_platform-originplatform/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(630): array_map(Object(Closure), Array, Array)
#3 /var/www/og_platform-originplatform/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php(23): Illuminate\\Support\\Collection->map(Object(Closure))
#4 /var/www/og_platform-originplatform/vendor/laravel/framework/src/Illuminate/Pagination/AbstractPaginator.php(738): Illuminate\\Pagination\\AbstractPaginator->forwardCallTo(Object(Illuminate\\Support\\Collection), 'map', Array)
#5 /var/www/og_platform-originplatform/vendor/laravel/framework/src/Illuminate/Http/Resources/Json/PaginatedResourceResponse.php(30): Illuminate\\Pagination\\AbstractPaginator->__call('map', Array)
#6 /var/www/og_platform-originplatform/vendor/laravel/framework/src/Illuminate/Support/helpers.php(263): Illuminate\\Http\\Resources\\Json\\PaginatedResourceResponse->Illuminate\\Http\\Resources\\Json\\{closure}(Object(Illuminate\\Http\\JsonResponse))
#7 /var/www/og_platform-originplatform/vendor/laravel/framework/src/Illuminate/Http/Resources/Json/PaginatedResourceResponse.php(33): tap(Object(Illuminate\\Http\\JsonResponse), Object(Closure))
#8 /var/www/og_platform-originplatform/vendor/laravel/framework/src/Illuminate/Http/Resources/Json/ResourceCollection.php(132): Illuminate\\Http\\Resources\\Json\\PaginatedResourceResponse->toResponse(Object(Illuminate\\Http\\Request))
#9 /var/www/og_platform-originplatform/vendor/laravel/framework/src/Illuminate/Http/Resources/Json/ResourceCollection.php(112): Illuminate\\Http\\Resources\\Json\\ResourceCollection->preparePaginatedResponse(Object(Illuminate\\Http\\Request))
#10 /var/www/og_platform-originplatform/vendor/laravel/framework/src/Illuminate/Routing/Router.php(765): Illuminate\\Http\\Resources\\Json\\ResourceCollection->toResponse(Object(Illuminate\\Http\\Request))
#11 /var/www/og_platform-originplatform/vendor/laravel/framework/src/Illuminate/Routing/Router.php(752): Illuminate\\Routing\\Router::toResponse(Object(Illuminate\\Http\\Request), Object(Origin\\Http\\Resources\\Ad\\AdCollection))
#12 /var/www/og_platform-originplatform/vendor/laravel/framework/src/Illuminate/Routing/Router.php(692): Illuminate\\Routing\\Router->prepareResponse(Object(Illuminate\\Http\\Request), Object(Origin\\Http\\Resources\\Ad\\AdCollection))
#13 /var/www/og_platform-originplatform/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#14 /var/www/og_platform-originplatform/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#15 /var/www/og_platform-originplatform/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#16 /var/www/og_platform-originplatform/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(127): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#17 /var/www/og_platform-originplatform/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(63): Illuminate\\Routing\\Middleware\\ThrottleRequests->handleRequest(Object(Illuminate\\Http\\Request), Object(Closure), Array)
#18 /var/www/og_platform-originplatform/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\ThrottleRequests->handle(Object(Illuminate\\Http\\Request), Object(Closure), '60', '1')
#19 /var/www/og_platform-originplatform/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(44): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#20 /var/www/og_platform-originplatform/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Auth\\Middleware\\Authenticate->handle(Object(Illuminate\\Http\\Request), Object(Closure), 'api')
#21 /var/www/og_platform-originplatform/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#22 /var/www/og_platform-originplatform/vendor/laravel/framework/src/Illuminate/Routing/Router.php(694): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#23 /var/www/og_platform-originplatform/vendor/laravel/framework/src/Illuminate/Routing/Router.php(669): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#24 /var/www/og_platform-originplatform/vendor/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#25 /var/www/og_platform-originplatform/vendor/laravel/framework/src/Illuminate/Routing/Router.php(624): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#26 /var/www/og_platform-originplatform/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(166): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#27 /var/www/og_platform-originplatform/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#28 /var/www/og_platform-originplatform/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#29 /var/www/og_platform-originplatform/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#30 /var/www/og_platform-originplatform/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#31 /var/www/og_platform-originplatform/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest(Object(Illuminate\\Http\\Request), Object(Illuminate\\Session\\Store), Object(Closure))
#32 /var/www/og_platform-originplatform/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#33 /var/www/og_platform-originplatform/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#34 /var/www/og_platform-originplatform/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#35 /var/www/og_platform-originplatform/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#36 /var/www/og_platform-originplatform/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#37 /var/www/og_platform-originplatform/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#38 /var/www/og_platform-originplatform/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#39 /var/www/og_platform-originplatform/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#40 /var/www/og_platform-originplatform/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#41 /var/www/og_platform-originplatform/vendor/fruitcake/laravel-cors/src/HandleCors.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#42 /var/www/og_platform-originplatform/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#43 /var/www/og_platform-originplatform/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#44 /var/www/og_platform-originplatform/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#45 /var/www/og_platform-originplatform/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#46 /var/www/og_platform-originplatform/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(141): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#47 /var/www/og_platform-originplatform/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#48 /var/www/og_platform-originplatform/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#49 {main}
"} 
[2021-01-05 16:14:25] local.ERROR: Undefined property: stdClass::$resource  
```

### Steps To Reproduce:
1. Return a query builder result collection on a ResourceCollection from your controller

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by EM-LilianaIturribarria** [comment]
just FYI someone also opened a ticket for doctrine

https://github.com/laravel-doctrine/orm/issues/444

**Comment by projct1** [comment]
Same problem. I just using QueryBuilder as `$resource` and paginate this:
```php
class BarCollectionSearchResource extends ResourceCollection
{
    protected YandexSearchDTO $dto;

    public function __construct(YandexSearchDTO $dto)
    {
        $this->dto = $dto;

        parent::__construct($this->getResource());
    }

    public function toArray($request)
    {
        return $this->resource->map(function(stdClass $bar) {
            $bar = (array) $bar;

            return [
                'url' => \Base_Url::toBarCard($bar),
                'name' => $this->setHighlight($bar['name']),
                'address' => $this->setHighlight($bar['address']),
                'vip' => \Bar_Service_Tariff::isActive($bar['id']),
                'renamed_to' => $this->setHighlight($bar['renamed_to']),
                'partner' => \Partner_Service_Main::normalizePartnerName(\Bar_Helper_Bron::getPartnerForButton($bar))
                //etc transformations
            ];
        });
    }

    protected function getResource(): AbstractPaginator
    {
        $builder = DB::table('bar_struct as s')
            //some of joins
            ->select() //some of selects
            ->where() //some of where
            ->groupBy('s.id');

        return $builder->paginate($this->dto->perPage, ['*'], 'page', $this->dto->page);
    }

    protected function setHighlight(string $where = null):? string
    {
 	return preg_replace('~(' . $this->dto->query . ')~iu', "<em>$1</em>", $where);
    }
}
```
But got error `Undefined property: stdClass::$resource` in controller:
```php
class YandexSearchController extends Controller
{
    public function indexAction(Request $request)
    {
        return new BarCollectionSearchResource(
            new YandexSearchDTO($request)
        );
    }
}
```
