### ISSUE TITLE
Issue creating app with Jetstream/Inertia

### ISSUE THREAD

**Issue by flacerte** [laravel/framework#35830]
- Laravel Version: 8.5.7
- PHP Version: 7.4.9
- Database Driver & Version: N/A
 
### Description:
There's an issue installing a new Laravel wit jetstream and Inertia at the npm run dev step:

    [webpack-cli] C:\Dev\OW2\ow2\node_modules\laravel-mix\src\Mix.js:18
    static _primary = null;
                    ^

SyntaxError: Unexpected token =
    at new Script (vm.js:83:7)
    at NativeCompileCache._moduleCompile (C:\Dev\OW2\ow2\node_modules\v8-compile-cache\v8-compile-cache.js:240:18)
    at Module._compile (C:\Dev\OW2\ow2\node_modules\v8-compile-cache\v8-compile-cache.js:184:36)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (C:\Dev\OW2\ow2\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at module.exports (C:\Dev\OW2\ow2\node_modules\laravel-mix\setup\webpack.config.js:2:17)

### Steps To Reproduce:
Laralvel new app --jet (select Inertia as stack)

**Comment by driesvints** [comment]
I can't reproduce this.

**Comment by flacerte** [comment]
A node update seems to have resolved the issue

**Comment by pgrimaud** [comment]
If someone has the same error, you need node >= 12

**Comment by langy** [comment]
Can also confirm updating node resolves the issue.

**Comment by camohub** [comment]
I have node 15 and still the same error.
