### ISSUE TITLE
npm run dev throws error Laravel 8

### ISSUE THREAD

**Issue by LuanHimmlisch** [laravel/framework#35856]
- Laravel Version: 8.12
- PHP Version: 8.0.1
- NodeJS Version: 15.5.1
- npm Version: 6.14.11

### Description:
Found this problem when doing `npm run dev`:
```> @ dev F:\Himmlisch\Desarrollo Indie\HTML\Webpages\Mine\freeCodeGram
> node run development

node:internal/modules/cjs/loader:928
  throw err;
  ^

Error: Cannot find module 'F:\Himmlisch\Desarrollo Indie\HTML\Webpages\Mine\freeCodeGram\run'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:925:15)
    at Function.Module._load (node:internal/modules/cjs/loader:769:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ dev: `node run development`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Luan\AppData\Roaming\npm-cache\_logs\2021-01-12T07_14_12_407Z-debug.log
```

I just want to follow a course, I'm new at Laravel and really this lowers my excitement on trying it.

I removed node_modules like 5 times at this time so, no, that ain't it. Also installed weird packages that people recommended to solve this problem and also nothing.

Here's the .log:

```0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Luan\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'dev'
1 verbose cli ]
2 info using npm@6.14.11
3 info using node@v15.5.1
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle @~predev: @
6 info lifecycle @~dev: @
7 verbose lifecycle @~dev: unsafe-perm in lifecycle true
8 verbose lifecycle @~dev: PATH: C:\Users\Luan\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;F:\Himmlisch\Desarrollo Indie\HTML\Webpages\Mine\freeCodeGram\node_modules\.bin;F:\Himmlisch\Desarrollo Indie\HTML\Webpages\Mine\freeCodeGram\node_modules\.bin;C:\Python27\;C:\Python27\Scripts;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\Microsoft VS Code\bin;C:\Program Files\dotnet\;C:\Program Files (x86)\Brackets\command;C:\Program Files (x86)\ZeroTier\One\;F:\Himmlisch\Desarrollo Indie\HTML\$PHP;C:\Program Files\nodejs\;C:\Gradle\gradle-6.2.2\bin;C:\Program Files\Redis\;C:\Users\Luan\AppData\Local\Programs\Python\Python38\Scripts\;C:\Users\Luan\AppData\Local\Programs\Python\Python38\;C:\Program Files\Git\cmd;C:\composer;C:\Users\Luan\AppData\Local\Programs\Python\Python38\Scripts\;C:\Users\Luan\AppData\Local\Programs\Python\Python38\;C:\Users\Luan\AppData\Local\Microsoft\WindowsApps;C:\Users\Luan\AppData\Roaming\npm;C:\Gradle\gradle-6.2.2\bin;C:\xampp\php;C:\Program Files\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\mingw64\bin;C:\xampp\mysql\bin;C:\xampp\mysql\bin\mysqld.exe;C:\Users\Luan\AppData\Roaming\Composer\vendor\bin;C:\xampp\apache\bin;
9 verbose lifecycle @~dev: CWD: F:\Himmlisch\Desarrollo Indie\HTML\Webpages\Mine\freeCodeGram
10 silly lifecycle @~dev: Args: [ '/d /s /c', 'node run development' ]
11 silly lifecycle @~dev: Returned: code: 1  signal: null
12 info lifecycle @~dev: Failed to exec dev script
13 verbose stack Error: @ dev: `node run development`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\Luan\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (node:events:376:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\Luan\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (node:events:376:20)
13 verbose stack     at maybeClose (node:internal/child_process:1063:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:295:5)
14 verbose pkgid @
15 verbose cwd F:\Himmlisch\Desarrollo Indie\HTML\Webpages\Mine\freeCodeGram
16 verbose Windows_NT 10.0.18363
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Luan\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
18 verbose node v15.5.1
19 verbose npm  v6.14.11
20 error code ELIFECYCLE
21 error errno 1
22 error @ dev: `node run development`
22 error Exit status 1
23 error Failed at the @ dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

### Steps To Reproduce:
Simply run `npm run dev` on a freshly created Laravel project

**Comment by Krisell** [comment]
Looks like you are running `node run development` and not `npm run development` ?

**Comment by LuanHimmlisch** [comment]
Sorry about that @Krisell , I replaced npm with one of the packages someone suggest and in my desesperation I didn't realize I write "node" back.

This is the error when running `npm run dev`:
```
node:internal/modules/cjs/loader:928
  throw err;
  ^

Error: Cannot find module 'F:\Himmlisch\Desarrollo'
Require stack:
- F:\Himmlisch\Desarrollo Indie\HTML\Webpages\Mine\freeCodeGram\node_modules\webpack\bin\convert-argv.js
- F:\Himmlisch\Desarrollo Indie\HTML\Webpages\Mine\freeCodeGram\node_modules\webpack\bin\webpack.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:925:15)
    at Function.Module._load (node:internal/modules/cjs/loader:769:27)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at requireConfig (F:\Himmlisch\Desarrollo Indie\HTML\Webpages\Mine\freeCodeGram\node_modules\webpack\bin\convert-argv.js:97:18)
    at F:\Himmlisch\Desarrollo Indie\HTML\Webpages\Mine\freeCodeGram\node_modules\webpack\bin\convert-argv.js:104:17
    at Array.forEach (<anonymous>)
    at module.exports (F:\Himmlisch\Desarrollo Indie\HTML\Webpages\Mine\freeCodeGram\node_modules\webpack\bin\convert-argv.js:102:15)
    at Object.<anonymous> (F:\Himmlisch\Desarrollo Indie\HTML\Webpages\Mine\freeCodeGram\node_modules\webpack\bin\webpack.js:155:40)
    at Module._compile (node:internal/modules/cjs/loader:1108:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'F:\\Himmlisch\\Desarrollo Indie\\HTML\\Webpages\\Mine\\freeCodeGram\\node_modules\\webpack\\bin\\convert-argv.js',
    'F:\\Himmlisch\\Desarrollo Indie\\HTML\\Webpages\\Mine\\freeCodeGram\\node_modules\\webpack\\bin\\webpack.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ development: `mix`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ development script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Luan\AppData\Local\npm-cache\_logs\2021-01-12T18_28_52_032Z-debug.log
npm ERR! code 1
npm ERR! path F:\Himmlisch\Desarrollo Indie\HTML\Webpages\Mine\freeCodeGram
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c npm run development

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Luan\AppData\Local\npm-cache\_logs\2021-01-12T18_28_52_490Z-debug.log

Process finished with exit code 1
```
It looks like an error related to a relative path or something like that.

The log:

```
0 verbose cli [
0 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
0 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
0 verbose cli   'run',
0 verbose cli   'dev',
0 verbose cli   '--scripts-prepend-node-path=auto'
0 verbose cli ]
1 info using npm@7.3.0
2 info using node@v15.5.1
3 timing config:load:defaults Completed in 8ms
4 timing config:load:file:C:\Program Files\nodejs\node_modules\npm\npmrc Completed in 222ms
5 timing config:load:builtin Completed in 222ms
6 timing config:load:cli Completed in 40ms
7 timing config:load:env Completed in 5ms
8 timing config:load:file:F:\Himmlisch\Desarrollo Indie\HTML\Webpages\Mine\freeCodeGram\.npmrc Completed in 57ms
9 timing config:load:project Completed in 264ms
10 timing config:load:file:C:\Users\Luan\.npmrc Completed in 95ms
11 timing config:load:user Completed in 96ms
12 timing config:load:file:C:\Users\Luan\AppData\Roaming\npm\etc\npmrc Completed in 64ms
13 timing config:load:global Completed in 65ms
14 timing config:load:cafile Completed in 1ms
15 timing config:load:validate Completed in 9ms
16 timing config:load:setUserAgent Completed in 2ms
17 timing config:load:setEnvs Completed in 3ms
18 timing config:load Completed in 716ms
19 verbose npm-session 455f228c72b5e6a2
20 timing npm:load Completed in 1262ms
21 timing command:run-script Completed in 132652ms
22 verbose stack Error: command failed
22 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\promise-spawn\index.js:64:27)
22 verbose stack     at ChildProcess.emit (node:events:376:20)
22 verbose stack     at maybeClose (node:internal/child_process:1063:16)
22 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:295:5)
23 verbose cwd F:\Himmlisch\Desarrollo Indie\HTML\Webpages\Mine\freeCodeGram
24 verbose Windows_NT 10.0.18363
25 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev" "--scripts-prepend-node-path=auto"
26 verbose node v15.5.1
27 verbose npm  v7.3.0
28 error code 1
29 error path F:\Himmlisch\Desarrollo Indie\HTML\Webpages\Mine\freeCodeGram
30 error command failed
31 error command C:\Windows\system32\cmd.exe /d /s /c npm run development
32 verbose exit 1

```
