### ISSUE TITLE
 Uncaught TypeError: mb_strpos(): Argument #1 ($haystack) must be of type string, null given

### ISSUE THREAD

**Issue by AEK-BKF** [laravel/framework#35948]
- Laravel Version: 8.22.1
- PHP Version: 8.0.1
- Database Driver & Version: Postgres 13

### Description:
Updated php to last version 8.0.1 on Ubuntu 18

### Steps To Reproduce:
Just run php artisan serve

```
Starting Laravel development server: http://127.0.0.1:8000
[Tue Jan 19 23:40:37 2021] PHP 8.0.1 Development Server (http://127.0.0.1:8000) started
[Tue Jan 19 23:40:43 2021] 127.0.0.1:60006 Accepted
[Tue Jan 19 23:40:43 2021] 127.0.0.1:60008 Accepted
[Tue Jan 19 23:40:43 2021] PHP Fatal error:  Uncaught TypeError: mb_strpos(): Argument #1 ($haystack) must be of type string, null given, called in /home/akaderb/Projects/Menu/server/vendor/laravel/framework/src/Illuminate/Support/Str.php on line 183 and defined in /home/akaderb/Projects/Menu/server/vendor/symfony/polyfill-mbstring/bootstrap80.php:60
Stack trace:
#0 /home/akaderb/Projects/Menu/server/vendor/laravel/framework/src/Illuminate/Support/Str.php(183): mb_strpos()
#1 /home/akaderb/Projects/Menu/server/vendor/laravel/framework/src/Illuminate/Http/Concerns/InteractsWithContentTypes.php(16): Illuminate\Support\Str::contains()
#2 /home/akaderb/Projects/Menu/server/vendor/laravel/framework/src/Illuminate/Http/Request.php(371): Illuminate\Http\Request->isJson()
#3 /home/akaderb/Projects/Menu/server/vendor/laravel/framework/src/Illuminate/Http/Request.php(435): Illuminate\Http\Request->getInputSource()
#4 /home/akaderb/Projects/Menu/server/vendor/laravel/framework/src/Illuminate/Http/Request.php(64): Illuminate\Http\Request::createFromBase()
#5 /home/akaderb/Projects/Menu/server/public/index.php(52): Illuminate\Http\Request::capture()
#6 /home/akaderb/Projects/Menu/server/server.php(21): require_once('...')
#7 {main}
  thrown in /home/akaderb/Projects/Menu/server/vendor/symfony/polyfill-mbstring/bootstrap80.php on line 60
[Tue Jan 19 23:40:43 2021] 127.0.0.1:60008 Closing
```

**Comment by driesvints** [comment]
> Argument #1 ($haystack) must be of type string, null given

Here's your error. You're passing null but should be passing a string.

**Comment by AEK-BKF** [comment]
@driesvints 
But I didn't change any thing, just upgrade php to latest version !
It was working fine before !!!

**Comment by driesvints** [comment]
@AEK-BKF PHP 8 is more strict here.

**Comment by AEK-BKF** [comment]
Thank you, I found the issue.

**Comment by ingoldsby** [comment]
> Thank you, I found the issue.

for those wondering, what was the issue and your solution?
