### ISSUE TITLE
New installation: Undefined index: argv - Error in IgnitionServiceProvider - runningInConsole?

### ISSUE THREAD

**Issue by camya** [laravel/framework#36275]
If I install a new installation of Laravel via composer or direct download of the latest version from Github, I get an error in the browser window.

**ErrorException
Undefined index: argv**

Illuminate\Foundation\Bootstrap\HandleExceptions::handleError
C:\projec-name\app\vendor\facade\ignition\src\IgnitionServiceProvider.php:83

The IgnitionServiceProvider thinks, that I run the app from the console.
If I comment out the runningInConsole() condition, the site works again.

 I'm really not sure why Laravel thinks, that it runs from console here. I have installed another older Laravel project (Laravel Jetstream) installed on the same server which works without this problem. Also I installed the dev-master version which also don't outhput this error.

\PHP_SAPI returns `cgi-fcgi`

The problem is this part of the IgnitionServiceProvider.php

```
        if ($this->app->runningInConsole()) {
            ...
            if (['artisan', 'tinker'] === $_SERVER['argv']) {
                Api::sendReportsInBatches(false);
            }
        }
```

- Laravel Version: 8.x (Latest)
- PHP Version: 7.4.1

```
[2021-02-15 19:27:21] local.ERROR: Undefined index: argv {"exception":"[object] (ErrorException(code: 0): Undefined index: argv at C:\\project-name\\app\\vendor\\facade\\ignition\\src\\IgnitionServiceProvider.php:83)
[stacktrace]
#0 C:\\project-name\\app\\vendor\\facade\\ignition\\src\\IgnitionServiceProvider.php(83): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'Undefined index...', 'C:\\\\project-name...', 83, Array)
#1 C:\\project-name\\app\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(36): Facade\\Ignition\\IgnitionServiceProvider->boot()
#2 C:\\project-name\\app\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#3 C:\\project-name\\app\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#4 C:\\project-name\\app\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#5 C:\\project-name\\app\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(596): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#6 C:\\project-name\\app\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(869): Illuminate\\Container\\Container->call(Array)
#7 C:\\project-name\\app\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(850): Illuminate\\Foundation\\Application->bootProvider(Object(Facade\\Ignition\\IgnitionServiceProvider))
#8 [internal function]: Illuminate\\Foundation\\Application->Illuminate\\Foundation\\{closure}(Object(Facade\\Ignition\\IgnitionServiceProvider), 14)
#9 C:\\project-name\\app\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(851): array_walk(Array, Object(Closure))
#10 C:\\project-name\\app\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\BootProviders.php(17): Illuminate\\Foundation\\Application->boot()
#11 C:\\project-name\\app\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(230): Illuminate\\Foundation\\Bootstrap\\BootProviders->bootstrap(Object(Illuminate\\Foundation\\Application))
#12 C:\\project-name\\app\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(152): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#13 C:\\project-name\\app\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(136): Illuminate\\Foundation\\Http\\Kernel->bootstrap()
#14 C:\\project-name\\app\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#15 C:\\project-name\\app\\public\\index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#16 {main}
"}
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
