### ISSUE TITLE
PHP Fatal error:  Uncaught ErrorException: class_parents on Job Dispatch

### ISSUE THREAD

**Issue by eusonlito** [laravel/framework#36431]
- Laravel Version: v8.29.0 and v8.30.0
- PHP Version: 7.4.15
- Database Driver & Version: Not Used

### Description:

I have multiple commands with jobs related but I can't get to work one of them, only one. Is easy to reproduce with a default Laravel installation.

After launch `SyncJob::dispatch()` form a command, I get:

```
$> php artisan provider:sync

App\Domains\Provider\Job\Sync::__construct::17

PHP Fatal error:  Uncaught ErrorException: class_parents(): object or string expected in /www/example-app/vendor/laravel/framework/src/Illuminate/Support/helpers.php:92
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#1 /www/example-app/vendor/laravel/framework/src/Illuminate/Support/helpers.php(92): class_parents()
#2 /www/example-app/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(110): class_uses_recursive()
#3 /www/example-app/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(78): Illuminate\Bus\Dispatcher->dispatchNow()
#4 /www/example-app/vendor/laravel/framework/src/Illuminate/Foundation/Bus/PendingDispatch.php(202): Illuminate\Bus\Dispatcher->dispatch()
#5 [internal function]: Illuminate\Foundation\Bus\PendingDispatch->__destruct()
#6 {main}
  thrown in /www/example-app/vendor/laravel/framework/src/Illuminate/Support/helpers.php on line 92
```

### Steps To Reproduce:

1. Setup a new laravel installation:

```
composer create-project laravel/laravel example-app
cd example-app
composer update
```

2. Create the domain folders:

```
install -d app/Domains/Provider/Command
install -d app/Domains/Provider/Job
```

3. Add command to Console Kernel:

```
vi app/Console/Kernel.php

    protected function commands()
    {
        $this->load(base_path('app/Domains/Provider/Command'));

        require base_path('routes/console.php');
    }
```

4. Create the command:

```
vi app/Domains/Provider/Command/Sync.php

<?php declare(strict_types=1);

namespace App\Domains\Provider\Command;

use Illuminate\Console\Command;
use App\Domains\Provider\Job\Sync as SyncJob;

class Sync extends Command
{
    protected $signature = 'provider:sync';
    protected $description = 'Sync Provider Stats';

    public function handle()
    {
        SyncJob::dispatch();
    }
}
```

5. Create the Job:

```
vi app/Domains/Provider/Job/Sync.php

<?php declare(strict_types=1);

namespace App\Domains\Provider\Job;

use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Queue\SerializesModels;

class Sync implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    public function __construct()
    {
        die(__METHOD__.'::'.__LINE__."\n\n");
    }

    public function handle()
    {
        die(__METHOD__.'::'.__LINE__."\n\n");
    }
}
```

6. Execute:

```
php artisan provider:sync

App\Domains\Provider\Job\Sync::__construct::17

PHP Fatal error:  Uncaught ErrorException: class_parents(): object or string expected in /www/example-app/vendor/laravel/framework/src/Illuminate/Support/helpers.php:92
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#1 /www/example-app/vendor/laravel/framework/src/Illuminate/Support/helpers.php(92): class_parents()
#2 /www/example-app/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(110): class_uses_recursive()
#3 /www/example-app/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(78): Illuminate\Bus\Dispatcher->dispatchNow()
#4 /www/example-app/vendor/laravel/framework/src/Illuminate/Foundation/Bus/PendingDispatch.php(202): Illuminate\Bus\Dispatcher->dispatch()
#5 [internal function]: Illuminate\Foundation\Bus\PendingDispatch->__destruct()
#6 {main}
  thrown in /www/example-app/vendor/laravel/framework/src/Illuminate/Support/helpers.php on line 92
```

Thanks!

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by eusonlito** [comment]
Thanks @driesvints, but is not a support needed, is a bug, not? You can reproduce easy with this steps, there aren't any code error on my example. Thanks!

**Comment by driesvints** [comment]
I see you're using `php artisan provider:sync`. That doesn't exist in Laravel. Please try a support channel first?

**Comment by eusonlito** [comment]
> I see you're using `php artisan provider:sync`. That doesn't exist in Laravel. Please try a support channel first?

mmm, it's defined on my custom command (`app/Domains/Provider/Command/Sync.php`):

```php
    protected $signature = 'provider:sync';
```

and loaded from Console Kernel.php:

```
    protected function commands()
    {
        $this->load(base_path('app/Domains/Provider/Command'));

        require base_path('routes/console.php');
    }
```

The Job is executed, but with error on destruct from `Illuminate\Foundation\Bus\PendingDispatch`.

**Comment by driesvints** [comment]
Please try some of the support channels first and then report back 👍

**Comment by eusonlito** [comment]
🤷🏻‍♂️
