### ISSUE TITLE
[8.x] schema:dump causes error when using read and write connections in pgsql driver

### ISSUE THREAD

**Issue by ddzobov** [laravel/framework#36875]
- Laravel Version: 8.35.1
- PHP Version: 7.4.16
- Database Driver & Version: pgsql

### Description:
```
'pgsql' => [
            'read' => [
                'host' => explode(',', env('DB_HOST_READ', '127.0.0.1')),
            ],
            'write' => [
                'host' => explode(',', env('DB_HOST_WRITE', '127.0.0.1')),
            ],
```

php artisan schema:dump causes error:
`[2021-04-05 14:02:09] local.ERROR: Array to string conversion {"exception":"[object] (ErrorException(code: 0): Array to string conversion at /var/www/vendor/symfony/process/Process.php:339)`

Process.php:339
```
        $envPairs = [];
        foreach ($env as $k => $v) {
            if (false !== $v) {
                $envPairs[] = $k.'='.$v; // 339
            }
        }
```

Trying to dump $env inside Process.php
```
dd($env);
array:74 [
  "LARAVEL_LOAD_HOST" => array:1 [
    0 => "host.docker.internal"
  ]

```

### Steps To Reproduce:
1. Set read and write connections in database.php
2. Run php artisan schema:dump
3. Get error

**Comment by driesvints** [comment]
Can you share the full stack trace?

**Comment by ddzobov** [comment]
```
www-data@f4a3fbed230d:~$ php artisan schema:dump
[2021-04-05 14:39:12] local.ERROR: Array to string conversion {"exception":"[object] (ErrorException(code: 0): Array to string conversion at /var/www/vendor/symfony/process/Process.php:339)
[stacktrace]
#0 /var/www/vendor/symfony/process/Process.php(339): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'Array to string...', '/var/www/vendor...', 339, Array)
#1 /var/www/vendor/symfony/process/Process.php(247): Symfony\\Component\\Process\\Process->start(Object(Closure), Array)
#2 /var/www/vendor/symfony/process/Process.php(266): Symfony\\Component\\Process\\Process->run(Object(Closure), Array)
#3 /var/www/vendor/laravel/framework/src/Illuminate/Database/Schema/PostgresSchemaState.php(30): Symfony\\Component\\Process\\Process->mustRun(Object(Closure), Array)
#4 /var/www/vendor/laravel/framework/src/Illuminate/Database/Console/DumpCommand.php(44): Illuminate\\Database\\Schema\\PostgresSchemaState->dump(Object(Staudenmeir\\LaravelCte\\Connections\\PostgresConnection), '/var/www/databa...')
#5 /var/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Database\\Console\\DumpCommand->handle(Object(Illuminate\\Database\\DatabaseManager), Object(Illuminate\\Events\\Dispatcher))
#6 /var/www/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#7 /var/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#8 /var/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#9 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(611): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#10 /var/www/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\\Container\\Container->call(Array)
#11 /var/www/vendor/symfony/console/Command/Command.php(256): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#12 /var/www/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#13 /var/www/vendor/symfony/console/Application.php(971): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#14 /var/www/vendor/symfony/console/Application.php(290): Symfony\\Component\\Console\\Application->doRunCommand(Object(Illuminate\\Database\\Console\\DumpCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#15 /var/www/vendor/symfony/console/Application.php(166): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#16 /var/www/vendor/laravel/framework/src/Illuminate/Console/Application.php(92): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#17 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#18 /var/www/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#19 {main}
"} 

   ErrorException 

  Array to string conversion

  at vendor/symfony/process/Process.php:339
    335▕ 
    336▕         $envPairs = [];
    337▕         foreach ($env as $k => $v) {
    338▕             if (false !== $v) {
  ➜ 339▕                 $envPairs[] = $k.'='.$v;
    340▕             }
    341▕         }
    342▕ 
    343▕         if (!is_dir($this->cwd)) {

      +18 vendor frames 
  19  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

```

**Comment by driesvints** [comment]
Can you paste your `database.php` config file?

**Comment by ddzobov** [comment]
```
<?php

use Illuminate\Support\Str;

return [

    /*
    |--------------------------------------------------------------------------
    | Default Database Connection Name
    |--------------------------------------------------------------------------
    |
    | Here you may specify which of the database connections below you wish
    | to use as your default connection for all database work. Of course
    | you may use many connections at once using the Database library.
    |
    */

    'default' => env('DB_CONNECTION', 'mysql'),

    /*
    |--------------------------------------------------------------------------
    | Database Connections
    |--------------------------------------------------------------------------
    |
    | Here are each of the database connections setup for your application.
    | Of course, examples of configuring each database platform that is
    | supported by Laravel is shown below to make development simple.
    |
    |
    | All database work in Laravel is done through the PHP PDO facilities
    | so make sure you have the driver for your particular database of
    | choice installed on your machine before you begin development.
    |
    */

    'connections' => [

        'sqlite' => [
            'driver' => 'sqlite',
            'url' => env('DATABASE_URL'),
            'database' => env('DB_DATABASE', database_path('database.sqlite')),
            'prefix' => '',
            'foreign_key_constraints' => env('DB_FOREIGN_KEYS', true),
        ],

        'mysql' => [
            'driver' => 'mysql',
            'url' => env('DATABASE_URL'),
            'host' => env('DB_HOST', '127.0.0.1'),
            'port' => env('DB_PORT', '3306'),
            'database' => env('DB_DATABASE', 'forge'),
            'username' => env('DB_USERNAME', 'forge'),
            'password' => env('DB_PASSWORD', ''),
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'prefix_indexes' => true,
            'strict' => true,
            'engine' => null,
            'options' => extension_loaded('pdo_mysql') ? array_filter([
                PDO::MYSQL_ATTR_SSL_CA => env('MYSQL_ATTR_SSL_CA'),
            ]) : [],
        ],

        'pgsql' => [
            'read' => [
                'host' => explode(',', env('DB_HOST_READ', '127.0.0.1')),
            ],
            'write' => [
                'host' => explode(',', env('DB_HOST_WRITE', '127.0.0.1')),
            ],
            'driver' => 'pgsql',
            'sticky' => true,
            'url' => env('DATABASE_URL'),
            'port' => env('DB_PORT', '5432'),
            'database' => env('DB_DATABASE', 'forge'),
            'username' => env('DB_USERNAME', 'forge'),
            'password' => env('DB_PASSWORD', ''),
            'charset' => 'utf8',
            'prefix' => '',
            'prefix_indexes' => true,
            'schema' => 'public',
            'sslmode' => 'prefer',
        ],

        'sqlsrv' => [
            'driver' => 'sqlsrv',
            'url' => env('DATABASE_URL'),
            'host' => env('DB_HOST', 'localhost'),
            'port' => env('DB_PORT', '1433'),
            'database' => env('DB_DATABASE', 'forge'),
            'username' => env('DB_USERNAME', 'forge'),
            'password' => env('DB_PASSWORD', ''),
            'charset' => 'utf8',
            'prefix' => '',
            'prefix_indexes' => true,
        ],

    ],

    /*
    |--------------------------------------------------------------------------
    | Migration Repository Table
    |--------------------------------------------------------------------------
    |
    | This table keeps track of all the migrations that have already run for
    | your application. Using this information, we can determine which of
    | the migrations on disk haven't actually been run in the database.
    |
    */

    'migrations' => 'migrations',

    /*
    |--------------------------------------------------------------------------
    | Redis Databases
    |--------------------------------------------------------------------------
    |
    | Redis is an open source, fast, and advanced key-value store that also
    | provides a richer body of commands than a typical key-value system
    | such as APC or Memcached. Laravel makes it easy to dig right in.
    |
    */

    'redis' => [

        'client' => env('REDIS_CLIENT', 'phpredis'),

        'options' => [
            'cluster' => env('REDIS_CLUSTER', 'redis'),
            'prefix' => env('REDIS_PREFIX', Str::slug(env('APP_NAME', 'laravel'), '_').'_database_'),
        ],

        'default' => [
            'url' => env('REDIS_URL'),
            'host' => env('REDIS_HOST', '127.0.0.1'),
            'password' => env('REDIS_PASSWORD', null),
            'port' => env('REDIS_PORT', '6379'),
            'database' => env('REDIS_DB', '0'),
        ],

        'cache' => [
            'url' => env('REDIS_URL'),
            'host' => env('REDIS_HOST', '127.0.0.1'),
            'password' => env('REDIS_PASSWORD', null),
            'port' => env('REDIS_PORT', '6379'),
            'database' => env('REDIS_CACHE_DB', '1'),
        ],

    ],

];

```

**Comment by driesvints** [comment]
For some reason the `array_merge` here is returning the "read"/"write" options I think from your config. It normally shouldn't as it's filtered by `baseVariables`. You're not overwriting this method right? Can you verify the results from the `array_merge` with a die/dump? If you paste that here please obfuscate your sensitive data.

https://github.com/laravel/framework/blob/4f289b0b3f6c5ad7818bc81b230c8b0c497d2348/src/Illuminate/Database/Schema/PostgresSchemaState.php#L29

**Comment by ddzobov** [comment]
```
www-data@f4a3fbed230d:~$ php artisan schema:dump
array:5 [
  "LARAVEL_LOAD_HOST" => array:1 [
    0 => "host.docker.internal"
  ]
  "LARAVEL_LOAD_PORT" => "5432"
  "LARAVEL_LOAD_USER" => "my-pg-user"
  "LARAVEL_LOAD_PASSWORD" => "my-pg-password"
  "LARAVEL_LOAD_DATABASE" => "my-pg-database"
]
www-data@f4a3fbed230d:~$ 
```

**Comment by driesvints** [comment]
Okay that's what I suspected. Can you apply the same changes from the MySqlSchemaState to the postgres one and see if that does the trick?

This line: https://github.com/laravel/framework/blob/d786e741e15ad1afa723cef19f05dabc040be912/src/Illuminate/Database/Schema/MySqlSchemaState.php#L121
And this line: https://github.com/laravel/framework/blob/d786e741e15ad1afa723cef19f05dabc040be912/src/Illuminate/Database/Schema/MySqlSchemaState.php#L125

**Comment by ddzobov** [comment]
Yes problem was solved:

https://github.com/laravel/framework/blob/d786e741e15ad1afa723cef19f05dabc040be912/src/Illuminate/Database/Schema/PostgresSchemaState.php#L71-L80

Changed to:
```
protected function baseVariables(array $config)
    {
        $config['host'] = $config['host'] ?? '';

        return [
            'LARAVEL_LOAD_HOST' => is_array($config['host']) ? $config['host'][0] : $config['host'],
            'LARAVEL_LOAD_PORT' => $config['port'],
            'LARAVEL_LOAD_USER' => $config['username'],
            'LARAVEL_LOAD_PASSWORD' => $config['password'],
            'LARAVEL_LOAD_DATABASE' => $config['database'],
        ];
    }
```

**Comment by driesvints** [comment]
Can you maybe pr those changes? Thanks for verifying.
