### ISSUE TITLE
queue:work and queue:listen doenst work correctly

### ISSUE THREAD

**Issue by viniciusstroff** [laravel/framework#37469]
- Laravel Version: 8.41.0
- PHP Version: 7.4.18
- Database Driver & Version:  10.1.37-MariaDB

### Description:
when the command 'php artisan queue:work' is executed, just nothing happens at the terminal, my queue name is default.

when the command  'php artisan queue:listen' is executed the output is:

  The "--name" option does not exist.

[2021-05-24 22:53:37] local.ERROR: Symfony\Component\Console\Exception\RuntimeException: The "--name" option does not exist. in D:\Vinicius\TCC\vendor\symfony\console\Input\ArgvInput.php:212
Stack trace:
#0 D:\Vinicius\TCC\vendor\symfony\console\Input\ArgvInput.php(140): Symfony\Component\Console\Input\ArgvInput->addLongOption()
#1 D:\Vinicius\TCC\vendor\symfony\console\Input\ArgvInput.php(76): Symfony\Component\Console\Input\ArgvInput->parseLongOption()
#2 D:\Vinicius\TCC\vendor\symfony\console\Input\Input.php(55): Symfony\Component\Console\Input\ArgvInput->parse()
#3 D:\Vinicius\TCC\vendor\symfony\console\Command\Command.php(215): Symfony\Component\Console\Input\Input->bind()
#4 D:\Vinicius\TCC\vendor\laravel\framework\src\Illuminate\Console\Command.php(121): Symfony\Component\Console\Command\Command->run()
#5 D:\Vinicius\TCC\vendor\symfony\console\Application.php(971): Illuminate\Console\Command->run()
#6 D:\Vinicius\TCC\vendor\symfony\console\Application.php(290): Symfony\Component\Console\Application->doRunCommand()
#7 D:\Vinicius\TCC\vendor\symfony\console\Application.php(166): Symfony\Component\Console\Application->doRun()
#8 D:\Vinicius\TCC\vendor\laravel\framework\src\Illuminate\Console\Application.php(92): Symfony\Component\Console\Application->run()
#9 D:\Vinicius\TCC\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(129): Illuminate\Console\Application->run()
#10 D:\Vinicius\TCC\artisan(37): Illuminate\Foundation\Console\Kernel->handle()
#11 {main}

### Steps To Reproduce:

obs:
In my env queue connection is database

i tried restart queue with php artisan queue:restart,  queue:clear, queue:forget.....

i tried restar pc, but did not work

similar at: 
https://github.com/laravel/framework/issues/17487

but i trying execute manually

in App\Console\Kenel has nothing executed in schedule

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
