### ISSUE TITLE
Use `Artisan::call('route:list')` in controllers will cause errors

### ISSUE THREAD

**Issue by mydansun** [laravel/framework#38072]
- Laravel Version: 8.50.0
- PHP Version: 8.0
- Database Driver & Version: mysql

### Description:

using `Artisan::call('route:list')` in controllers will cause errors.

#### One of the possible reasons
Check `vendor/laravel/framework/src/Illuminate/Routing/Router.php:706`
`$this->middlewareGroups` was unexpectedly empty, thus `web` is unsolvable.

### Steps To Reproduce:

1\. create a new project
```
composer create-project laravel/laravel example-app
cd example-app
```

2\. edit `routes/web.php` and append
```
Route::get('routes', function () {
    Artisan::call('route:list');
    $output = Artisan::output();
    return response("<pre>{$output}");
});
```

3\. run server
```
php artisan serve
```

3\. visit `http://127.0.0.1:8000/routes`
This following error will be displayed.

```
[2021-07-19 17:08:03] local.ERROR: Target class [web] does not exist. {"exception":"[object] (Illuminate\\Contracts\\Container\\BindingResolutionException(code: 0): Target class [web] does not exist. at /Users/sun/www-data/laravel-test/vendor/laravel/framework/src/Illuminate/Container/Container.php:875)
[stacktrace]
#0 /Users/sun/www-data/laravel-test/vendor/laravel/framework/src/Illuminate/Container/Container.php(754): Illuminate\\Container\\Container->build('web')
#1 /Users/sun/www-data/laravel-test/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(841): Illuminate\\Container\\Container->resolve('web', Array, true)
#2 /Users/sun/www-data/laravel-test/vendor/laravel/framework/src/Illuminate/Container/Container.php(692): Illuminate\\Foundation\\Application->resolve('web', Array)
#3 /Users/sun/www-data/laravel-test/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(826): Illuminate\\Container\\Container->make('web', Array)
#4 /Users/sun/www-data/laravel-test/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(205): Illuminate\\Foundation\\Application->make('web')
#5 /Users/sun/www-data/laravel-test/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(179): Illuminate\\Foundation\\Http\\Kernel->terminateMiddleware(Object(Illuminate\\Http\\Request), Object(Illuminate\\Http\\Response))
#6 /Users/sun/www-data/laravel-test/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->terminate(Object(Illuminate\\Http\\Request), Object(Illuminate\\Http\\Response))
#7 /Users/sun/www-data/laravel-test/server.php(21): require_once('/Users/sun/www-...')
#8 {main}

[previous exception] [object] (ReflectionException(code: -1): Class \"web\" does not exist at /Users/sun/www-data/laravel-test/vendor/laravel/framework/src/Illuminate/Container/Container.php:873)
[stacktrace]
#0 /Users/sun/www-data/laravel-test/vendor/laravel/framework/src/Illuminate/Container/Container.php(873): ReflectionClass->__construct('web')
#1 /Users/sun/www-data/laravel-test/vendor/laravel/framework/src/Illuminate/Container/Container.php(754): Illuminate\\Container\\Container->build('web')
#2 /Users/sun/www-data/laravel-test/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(841): Illuminate\\Container\\Container->resolve('web', Array, true)
#3 /Users/sun/www-data/laravel-test/vendor/laravel/framework/src/Illuminate/Container/Container.php(692): Illuminate\\Foundation\\Application->resolve('web', Array)
#4 /Users/sun/www-data/laravel-test/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(826): Illuminate\\Container\\Container->make('web', Array)
#5 /Users/sun/www-data/laravel-test/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(205): Illuminate\\Foundation\\Application->make('web')
#6 /Users/sun/www-data/laravel-test/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(179): Illuminate\\Foundation\\Http\\Kernel->terminateMiddleware(Object(Illuminate\\Http\\Request), Object(Illuminate\\Http\\Response))
#7 /Users/sun/www-data/laravel-test/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->terminate(Object(Illuminate\\Http\\Request), Object(Illuminate\\Http\\Response))
#8 /Users/sun/www-data/laravel-test/server.php(21): require_once('/Users/sun/www-...')
#9 {main}
"} 
```

![image](https://user-images.githubusercontent.com/8871143/126199622-481e7021-d83d-4f8e-9cd2-cd7d2b7ac17a.png)

**Comment by driesvints** [comment]
> `using Artisan::call('route:list') in controllers will cause errors.`

Don't call that. There's no use case for that imo.

**Comment by mydansun** [comment]
for anyone who want to display the output of `route:list` command in browser, as the `middlewareGroups` has been cleared in `vendor/laravel/framework/src/Illuminate/Foundation/Console/RouteListCommand.php:70`. you can try this.

```php
Route::get('routes', function () {
    Artisan::call('route:list');
    exit('<pre>'.Artisan::output());
});
```
