### ISSUE TITLE
Job batches cannot store more than 1600 failed job IDs

### ISSUE THREAD

**Issue by sebdesign** [laravel/framework#38173]
- Laravel Version: 8.52.0
- PHP Version: 8.0.8
- Database Driver & Version: MySQL 5.7.34

### Description:

The `failed_job_ids` column on the `job_batches` table has a `text` type, which can store 65535 bytes.
The UUID of each failed job takes about 41 bytes when encoded to JSON, so when a batch has 65535/41~=1600 failed jobs, the following error occurs:

```
SQLSTATE[22001]: String data, right truncated: 
1406 Data too long for column 'failed_job_ids' at row ...
(SQL: update `job_batches` set `pending_jobs` = ..., `failed_jobs` = ..., `failed_job_ids` = [...] where `id` = ...)
at vendor/laravel/framework/src/Illuminate/Database/Connection.php:692)
[stacktrace]
#0 vendor/laravel/framework/src/Illuminate/Database/Connection.php(652): Illuminate\\Database\\Connection->runQueryCallback()
#1 vendor/laravel/framework/src/Illuminate/Database/Connection.php(517): Illuminate\\Database\\Connection->run()
#2 vendor/laravel/framework/src/Illuminate/Database/Connection.php(450): Illuminate\\Database\\Connection->affectingStatement()
#3 vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2999): Illuminate\\Database\\Connection->update()
#4 vendor/laravel/framework/src/Illuminate/Bus/DatabaseBatchRepository.php(192): Illuminate\\Database\\Query\\Builder->update()
#5 vendor/laravel/framework/src/Illuminate/Support/helpers.php(263): Illuminate\\Bus\\DatabaseBatchRepository->Illuminate\\Bus\\{closure}()
#6 vendor/laravel/framework/src/Illuminate/Bus/DatabaseBatchRepository.php(193): tap()
#7 vendor/laravel/framework/src/Illuminate/Database/Concerns/ManagesTransactions.php(29): Illuminate\\Bus\\DatabaseBatchRepository->Illuminate\\Bus\\{closure}()
#8 vendor/laravel/framework/src/Illuminate/Bus/DatabaseBatchRepository.php(194): Illuminate\\Database\\Connection->transaction()
#9 vendor/laravel/framework/src/Illuminate/Bus/DatabaseBatchRepository.php(169): Illuminate\\Bus\\DatabaseBatchRepository->updateAtomicValues()
#10 vendor/laravel/framework/src/Illuminate/Bus/Batch.php(358): Illuminate\\Bus\\DatabaseBatchRepository->incrementFailedJobs()
#11 vendor/laravel/framework/src/Illuminate/Bus/Batch.php(327): Illuminate\\Bus\\Batch->incrementFailedJobs()
#12 vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(282): Illuminate\\Bus\\Batch->recordFailedJob()
#13 vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(259): Illuminate\\Queue\\CallQueuedHandler->ensureFailedBatchJobIsRecorded()
#14 vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(213): Illuminate\\Queue\\CallQueuedHandler->failed()
#15 vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(192): Illuminate\\Queue\\Jobs\\Job->failed()
#16 vendor/laravel/framework/src/Illuminate/Queue/Worker.php(581): Illuminate\\Queue\\Jobs\\Job->fail()
#17 vendor/laravel/framework/src/Illuminate/Queue/Worker.php(527): Illuminate\\Queue\\Worker->failJob()
#18 vendor/laravel/framework/src/Illuminate/Queue/Worker.php(455): Illuminate\\Queue\\Worker->markJobAsFailedIfWillExceedMaxAttempts()
#19 vendor/laravel/framework/src/Illuminate/Queue/Worker.php(432): Illuminate\\Queue\\Worker->handleJobException()
#20 vendor/laravel/framework/src/Illuminate/Queue/Worker.php(378): Illuminate\\Queue\\Worker->process()
#21 vendor/laravel/framework/src/Illuminate/Queue/Worker.php(172): Illuminate\\Queue\\Worker->runJob()
#22 vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(117): Illuminate\\Queue\\Worker->daemon()
#23 vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(101): Illuminate\\Queue\\Console\\WorkCommand->runWorker()
#24 vendor/laravel/horizon/src/Console/WorkCommand.php(51): Illuminate\\Queue\\Console\\WorkCommand->handle()
#25 vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Laravel\\Horizon\\Console\\WorkCommand->handle()
#26 vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#27 vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#28 vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#29 vendor/laravel/framework/src/Illuminate/Container/Container.php(651): Illuminate\\Container\\BoundMethod::call()
#30 vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\\Container\\Container->call()
#31 vendor/symfony/console/Command/Command.php(299): Illuminate\\Console\\Command->execute()
#32 vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
#33 vendor/symfony/console/Application.php(978): Illuminate\\Console\\Command->run()
#34 vendor/symfony/console/Application.php(295): Symfony\\Component\\Console\\Application->doRunCommand()
#35 vendor/symfony/console/Application.php(167): Symfony\\Component\\Console\\Application->doRun()
#36 vendor/laravel/framework/src/Illuminate/Console/Application.php(92): Symfony\\Component\\Console\\Application->run()
#37 vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run()
#38 artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#39 {main}

[previous exception] [object] (PDOException(code: 22001): SQLSTATE[22001]: String data, right truncated: 
1406 Data too long for column 'failed_job_ids' at row ... 
at vendor/laravel/framework/src/Illuminate/Database/Connection.php:510)
[stacktrace]
#0 vendor/laravel/framework/src/Illuminate/Database/Connection.php(510): PDOStatement->execute()
#1 vendor/laravel/framework/src/Illuminate/Database/Connection.php(685): Illuminate\\Database\\Connection->Illuminate\\Database\\{closure}()
#2 vendor/laravel/framework/src/Illuminate/Database/Connection.php(652): Illuminate\\Database\\Connection->runQueryCallback()
#3 vendor/laravel/framework/src/Illuminate/Database/Connection.php(517): Illuminate\\Database\\Connection->run()
#4 vendor/laravel/framework/src/Illuminate/Database/Connection.php(450): Illuminate\\Database\\Connection->affectingStatement()
#5 vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2999): Illuminate\\Database\\Connection->update()
#6 vendor/laravel/framework/src/Illuminate/Bus/DatabaseBatchRepository.php(192): Illuminate\\Database\\Query\\Builder->update()
#7 vendor/laravel/framework/src/Illuminate/Support/helpers.php(263): Illuminate\\Bus\\DatabaseBatchRepository->Illuminate\\Bus\\{closure}()
#8 vendor/laravel/framework/src/Illuminate/Bus/DatabaseBatchRepository.php(193): tap()
#9 vendor/laravel/framework/src/Illuminate/Database/Concerns/ManagesTransactions.php(29): Illuminate\\Bus\\DatabaseBatchRepository->Illuminate\\Bus\\{closure}()
#10 vendor/laravel/framework/src/Illuminate/Bus/DatabaseBatchRepository.php(194): Illuminate\\Database\\Connection->transaction()
#11 vendor/laravel/framework/src/Illuminate/Bus/DatabaseBatchRepository.php(169): Illuminate\\Bus\\DatabaseBatchRepository->updateAtomicValues()
#12 vendor/laravel/framework/src/Illuminate/Bus/Batch.php(358): Illuminate\\Bus\\DatabaseBatchRepository->incrementFailedJobs()
#13 vendor/laravel/framework/src/Illuminate/Bus/Batch.php(327): Illuminate\\Bus\\Batch->incrementFailedJobs()
#14 vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(282): Illuminate\\Bus\\Batch->recordFailedJob()
#15 vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(259): Illuminate\\Queue\\CallQueuedHandler->ensureFailedBatchJobIsRecorded()
#16 vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(213): Illuminate\\Queue\\CallQueuedHandler->failed()
#17 vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(192): Illuminate\\Queue\\Jobs\\Job->failed()
#18 vendor/laravel/framework/src/Illuminate/Queue/Worker.php(581): Illuminate\\Queue\\Jobs\\Job->fail()
#19 vendor/laravel/framework/src/Illuminate/Queue/Worker.php(527): Illuminate\\Queue\\Worker->failJob()
#20 vendor/laravel/framework/src/Illuminate/Queue/Worker.php(455): Illuminate\\Queue\\Worker->markJobAsFailedIfWillExceedMaxAttempts()
#21 vendor/laravel/framework/src/Illuminate/Queue/Worker.php(432): Illuminate\\Queue\\Worker->handleJobException()
#22 vendor/laravel/framework/src/Illuminate/Queue/Worker.php(378): Illuminate\\Queue\\Worker->process()
#23 vendor/laravel/framework/src/Illuminate/Queue/Worker.php(172): Illuminate\\Queue\\Worker->runJob()
#24 vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(117): Illuminate\\Queue\\Worker->daemon()
#25 vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(101): Illuminate\\Queue\\Console\\WorkCommand->runWorker()
#26 vendor/laravel/horizon/src/Console/WorkCommand.php(51): Illuminate\\Queue\\Console\\WorkCommand->handle()
#27 vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Laravel\\Horizon\\Console\\WorkCommand->handle()
#28 vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#29 vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#30 vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#31 vendor/laravel/framework/src/Illuminate/Container/Container.php(651): Illuminate\\Container\\BoundMethod::call()
#32 vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\\Container\\Container->call()
#33 vendor/symfony/console/Command/Command.php(299): Illuminate\\Console\\Command->execute()
#34 vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
#35 vendor/symfony/console/Application.php(978): Illuminate\\Console\\Command->run()
#36 vendor/symfony/console/Application.php(295): Symfony\\Component\\Console\\Application->doRunCommand()
#37 vendor/symfony/console/Application.php(167): Symfony\\Component\\Console\\Application->doRun()
#38 vendor/laravel/framework/src/Illuminate/Console/Application.php(92): Symfony\\Component\\Console\\Application->run()
#39 vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run()
#40 artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#41 {main}
"}
```

### Steps To Reproduce:

```php
class FailJob implements ShouldQueue
{
    use Batchable, Dispatchable, Queueable;

    public __construct(public int $code) {}

    public function handle()
    {
        abort($this->code);
    }
}

$jobs = Collection::times(2000)->map(fn () => new FailJob(500)));

Bus::batch($jobs)->allowFailures()->dispatch();
```

**Comment by themsaid** [comment]
You may update the field type in your app if you expect to store larger values.
