### ISSUE TITLE
HTTP Client "withBody" throw an exception when a resource is passed as the body content

### ISSUE THREAD

**Issue by Tchanove** [laravel/framework#38209]
- Laravel Version: 8.52.0
- PHP Version: 7.4.20
- Database Driver & Version: Irrelevant

### Description:

I need to send a file to an endpoint with the file content as the body of the request.
So I used `Http::withBody` as it seems to perfectly match what I need.

I wrote this code firstly and it was working perfectly:
```
$response = Http::withBody(
    $file->getContent(),
    $file->getMimeType()
)->put($api['putEndpoint']);
```

I now need to send much bigger files (250Mo+) and this code is now failing because `$file->getContent()` (obviously) fills up the memory and an out of memory exception is throw.

So I looked at the definition of `Http::withBody` and noticed that it accepts a `resource` for the body content so I updated my code to this:

```
$response = Http::withBody(
    fopen($file->path(), 'r'),
    $file->getMimeType()
)->put($api['putEndpoint']);
```

The file should now be streamed and not fully loaded in memory which solve my problem.

However, passing a `resource` to the `withBody` throw this exception:

<details>
  <summary>(click for full exception) Argument 1 passed to Illuminate\Http\Client\Request::withData() must be of the type array, resource given</summary>
  
```
[2021-08-02 16:05:19] local.ERROR: Argument 1 passed to Illuminate\Http\Client\Request::withData() must be of the type array, resource given, called in /var/www/site/vendor/laravel/framework/src/Illuminate/Http/Client/PendingRequest.php on line 919 {"exception":"[object] (TypeError(code: 0): Argument 1 passed to Illuminate\\Http\\Client\\Request::withData() must be of the type array, resource given, called in /var/www/site/vendor/laravel/framework/src/Illuminate/Http/Client/PendingRequest.php on line 919 at /var/www/site/vendor/laravel/framework/src/Illuminate/Http/Client/Request.php:243)
[stacktrace]
#0 /var/www/site/vendor/laravel/framework/src/Illuminate/Http/Client/PendingRequest.php(919): Illuminate\\Http\\Client\\Request->withData(Resource id #650)
#1 /var/www/site/vendor/laravel/framework/src/Illuminate/Support/helpers.php(263): Illuminate\\Http\\Client\\PendingRequest->Illuminate\\Http\\Client\\{closure}(Object(GuzzleHttp\\Psr7\\Request))
#2 /var/www/site/vendor/laravel/framework/src/Illuminate/Http/Client/PendingRequest.php(923): tap(Object(GuzzleHttp\\Psr7\\Request), Object(Closure))
#3 /var/www/site/vendor/laravel/framework/src/Illuminate/Http/Client/PendingRequest.php(826): Illuminate\\Http\\Client\\PendingRequest->runBeforeSendingCallbacks(Object(GuzzleHttp\\Psr7\\Request), Array)
#4 /var/www/site/vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php(64): Illuminate\\Http\\Client\\PendingRequest->Illuminate\\Http\\Client\\{closure}(Object(GuzzleHttp\\Psr7\\Request), Array)
#5 /var/www/site/vendor/guzzlehttp/guzzle/src/Middleware.php(37): GuzzleHttp\\PrepareBodyMiddleware->__invoke(Object(GuzzleHttp\\Psr7\\Request), Array)
#6 /var/www/site/vendor/guzzlehttp/guzzle/src/RedirectMiddleware.php(71): GuzzleHttp\\Middleware::GuzzleHttp\\{closure}(Object(GuzzleHttp\\Psr7\\Request), Array)
#7 /var/www/site/vendor/guzzlehttp/guzzle/src/Middleware.php(61): GuzzleHttp\\RedirectMiddleware->__invoke(Object(GuzzleHttp\\Psr7\\Request), Array)
#8 /var/www/site/vendor/guzzlehttp/guzzle/src/HandlerStack.php(75): GuzzleHttp\\Middleware::GuzzleHttp\\{closure}(Object(GuzzleHttp\\Psr7\\Request), Array)
#9 /var/www/site/vendor/guzzlehttp/guzzle/src/Client.php(331): GuzzleHttp\\HandlerStack->__invoke(Object(GuzzleHttp\\Psr7\\Request), Array)
#10 /var/www/site/vendor/guzzlehttp/guzzle/src/Client.php(168): GuzzleHttp\\Client->transfer(Object(GuzzleHttp\\Psr7\\Request), Array)
#11 /var/www/site/vendor/guzzlehttp/guzzle/src/Client.php(187): GuzzleHttp\\Client->requestAsync('PUT', Object(GuzzleHttp\\Psr7\\Uri), Array)
#12 /var/www/site/vendor/laravel/framework/src/Illuminate/Http/Client/PendingRequest.php(737): GuzzleHttp\\Client->request('PUT', 'https://storage...', Array)
#13 /var/www/site/vendor/laravel/framework/src/Illuminate/Http/Client/PendingRequest.php(668): Illuminate\\Http\\Client\\PendingRequest->sendRequest('PUT', 'https://storage...', Array)
#14 /var/www/site/vendor/laravel/framework/src/Illuminate/Support/helpers.php(234): Illuminate\\Http\\Client\\PendingRequest->Illuminate\\Http\\Client\\{closure}(1)
#15 /var/www/site/vendor/laravel/framework/src/Illuminate/Http/Client/PendingRequest.php(682): retry(0, Object(Closure), 100)
#16 /var/www/site/vendor/laravel/framework/src/Illuminate/Http/Client/PendingRequest.php(593): Illuminate\\Http\\Client\\PendingRequest->send('PUT', 'https://storage...', Array)
#17 /var/www/site/app/Business/OvhApi.php(313): Illuminate\\Http\\Client\\PendingRequest->put('https://storage...')
#18 /var/www/site/app/Http/Controllers/DocumentController.php(59): App\\Business\\OvhApi->createDocument(Object(Illuminate\\Http\\UploadedFile))
#19 /var/www/site/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\\Http\\Controllers\\DocumentController->store(Object(Illuminate\\Http\\Request), 'efc', 'privateDatabase', 'dl763-001', 'efcformation_de...')
#20 /var/www/site/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('store', Array)
#21 /var/www/site/vendor/laravel/framework/src/Illuminate/Routing/Route.php(254): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Http\\Controllers\\DocumentController), 'store')
#22 /var/www/site/vendor/laravel/framework/src/Illuminate/Routing/Route.php(197): Illuminate\\Routing\\Route->runController()
#23 /var/www/site/vendor/laravel/framework/src/Illuminate/Routing/Router.php(695): Illuminate\\Routing\\Route->run()
#24 /var/www/site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#25 /var/www/site/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#26 /var/www/site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#27 /var/www/site/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#28 /var/www/site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#29 /var/www/site/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#30 /var/www/site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#31 /var/www/site/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#32 /var/www/site/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest(Object(Illuminate\\Http\\Request), Object(Illuminate\\Session\\Store), Object(Closure))
#33 /var/www/site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#34 /var/www/site/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#35 /var/www/site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#36 /var/www/site/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#37 /var/www/site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#38 /var/www/site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#39 /var/www/site/vendor/laravel/framework/src/Illuminate/Routing/Router.php(697): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#40 /var/www/site/vendor/laravel/framework/src/Illuminate/Routing/Router.php(672): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#41 /var/www/site/vendor/laravel/framework/src/Illuminate/Routing/Router.php(636): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#42 /var/www/site/vendor/laravel/framework/src/Illuminate/Routing/Router.php(625): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#43 /var/www/site/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(166): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#44 /var/www/site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#45 /var/www/site/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#46 /var/www/site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#47 /var/www/site/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#48 /var/www/site/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#49 /var/www/site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#50 /var/www/site/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#51 /var/www/site/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#52 /var/www/site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#53 /var/www/site/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#54 /var/www/site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#55 /var/www/site/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#56 /var/www/site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#57 /var/www/site/vendor/fruitcake/laravel-cors/src/HandleCors.php(38): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#58 /var/www/site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#59 /var/www/site/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#60 /var/www/site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#61 /var/www/site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#62 /var/www/site/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(141): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#63 /var/www/site/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#64 /var/www/site/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#65 {main}
"}

```
  
</details>

From what I see, the problem seems to be in the file `src/Illuminate/Http/Client/PendingRequest.php` in the `parseRequestData` function which (as specified in the PHPDoc) should return an `array`.

However, if `$options[$this->bodyFormat]` is not an array nor a string, `parseRequestData` return it as-is (a resource in my case).
It should either throw an exception when the return value is not an array or wrap the return value in an array:

```
        if (!is_array($laravelData)) {
            $laravelData = [$laravelData];
        }
```

This fix the use of resource as body param but I don't know if it's the correct way to do it and if there is any impact, any idea ?

Btw, the PHPDoc of the `pendingBody` property should be updated to:

```
    /**
     * The raw body for the request.
     *
     * @var resource|string
     */
    protected $pendingBody;
```

I hope this is at least understandable, have a great day :)

**Comment by driesvints** [comment]
Heya, thanks for the thorough issue. I believe the type on `withBody` is wrong. I've sent in a PR to adjust it: https://github.com/laravel/framework/pull/38218

What you're looking for is `attach`. See: https://laravel.com/docs/8.x/http-client#multi-part-requests

```php
$photo = fopen('photo.jpg', 'r');

$response = Http::attach(
    'attachment', $photo, 'photo.jpg'
)->post('http://example.com/attachments');
```
