### ISSUE TITLE
Illuminate\Http\Client\Request::withData(): Argument #1 ($data) must be of type array, null given

### ISSUE THREAD

**Issue by dwightwatson** [laravel/framework#38674]
- Laravel Version: 8.58.0
- PHP Version: 8.0.10
- Database Driver & Version: Postgres 13.4

### Description:

I started receiving a strange intermittent issue in two separate queued jobs that use the HTTP client to make an external request. 

```
Illuminate\Http\Client\Request::withData(): Argument #1 ($data) must be of type array, null given, called in /app/vendor/laravel/framework/src/Illuminate/Http/Client/PendingRequest.php on line 941
```

It came out of nowhere, and it doesn't happen consistently. Most of the time these jobs run without issue and I haven't yet nailed down what triggers the failure. The calling code in both these jobs is pretty trivial too - a GET request with some parameters.

```php
$response = Http::get($url, [
    'limit' => 1,
    'locale' => 'en',
    'types' => 'district,place,locality,neighborhood',
    'access_token' => config('services.mapbox.key'),
]);
```

Going back through my deploy log it appears as though this error only started appearing after upgrading to Laravel 8.55.0. [Though I'm not sure there is anything in the changelog that could be directly responsible](https://github.com/laravel/framework/compare/v8.54.0...v8.55.0). I am using Horizon as a queue driver.

I'm still digging to get to the bottom of this and happy to provide more information as possible. I wanted to open an issue in case others are running into the same problem and this isn't isolated to my setup.

Here is the full stacktrace if helpful:

```
TypeError: Illuminate\Http\Client\Request::withData(): Argument #1 ($data) must be of type array, null given, called in /app/vendor/laravel/framework/src/Illuminate/Http/Client/PendingRequest.php on line 950
#59 /vendor/laravel/framework/src/Illuminate/Http/Client/Request.php(243): Illuminate\Http\Client\Request::withData
#58 /vendor/laravel/framework/src/Illuminate/Http/Client/PendingRequest.php(950): Illuminate\Http\Client\PendingRequest::Illuminate\Http\Client\{closure}
#57 /vendor/laravel/framework/src/Illuminate/Support/helpers.php(263): tap
#56 /vendor/laravel/framework/src/Illuminate/Http/Client/PendingRequest.php(954): Illuminate\Http\Client\PendingRequest::runBeforeSendingCallbacks
#55 /vendor/laravel/framework/src/Illuminate/Http/Client/PendingRequest.php(857): Illuminate\Http\Client\PendingRequest::Illuminate\Http\Client\{closure}
#54 /vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php(35): GuzzleHttp\PrepareBodyMiddleware::__invoke
#53 /vendor/guzzlehttp/guzzle/src/Middleware.php(37): GuzzleHttp\Middleware::GuzzleHttp\{closure}
#52 /vendor/guzzlehttp/guzzle/src/RedirectMiddleware.php(71): GuzzleHttp\RedirectMiddleware::__invoke
#51 /vendor/guzzlehttp/guzzle/src/Middleware.php(63): GuzzleHttp\Middleware::GuzzleHttp\{closure}
#50 /vendor/guzzlehttp/guzzle/src/HandlerStack.php(75): GuzzleHttp\HandlerStack::__invoke
#49 /vendor/guzzlehttp/guzzle/src/Client.php(331): GuzzleHttp\Client::transfer
#48 /vendor/guzzlehttp/guzzle/src/Client.php(168): GuzzleHttp\Client::requestAsync
#47 /vendor/guzzlehttp/guzzle/src/Client.php(187): GuzzleHttp\Client::request
#46 /vendor/guzzlehttp/guzzle/src/Client.php(92): GuzzleHttp\Client::__call
#45 /vendor/laravel/framework/src/Illuminate/Http/Client/PendingRequest.php(814): Illuminate\Http\Client\PendingRequest::createClient
#44 /vendor/laravel/framework/src/Illuminate/Http/Client/PendingRequest.php(802): Illuminate\Http\Client\PendingRequest::buildClient
#43 /vendor/laravel/framework/src/Illuminate/Http/Client/PendingRequest.php(745): Illuminate\Http\Client\PendingRequest::sendRequest
#42 /vendor/laravel/framework/src/Illuminate/Http/Client/PendingRequest.php(677): Illuminate\Http\Client\PendingRequest::Illuminate\Http\Client\{closure}
#41 /vendor/laravel/framework/src/Illuminate/Support/helpers.php(234): retry
#40 /vendor/laravel/framework/src/Illuminate/Http/Client/PendingRequest.php(691): Illuminate\Http\Client\PendingRequest::send
#39 /vendor/laravel/framework/src/Illuminate/Http/Client/PendingRequest.php(546): Illuminate\Http\Client\PendingRequest::get
#38 /vendor/laravel/framework/src/Illuminate/Http/Client/Factory.php(390): Illuminate\Http\Client\Factory::__call
#37 /vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Illuminate\Support\Facades\Facade::__callStatic
#36 /app/Support/Geocoder.php(24): App\Support\Geocoder::getCoordinates
#35 /app/Jobs/Locations/GeocodeJob.php(29): App\Jobs\Locations\GeocodeJob::handle
#34 /vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}
#33 /vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\Container\Util::unwrapIfClosure
#32 /vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\BoundMethod::callBoundMethod
#31 /vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::call
#30 /vendor/laravel/framework/src/Illuminate/Container/Container.php(651): Illuminate\Container\Container::call
#29 /vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(128): Illuminate\Bus\Dispatcher::Illuminate\Bus\{closure}
#28 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#27 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline::then
#26 /vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(132): Illuminate\Bus\Dispatcher::dispatchNow
#25 /vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(120): Illuminate\Queue\CallQueuedHandler::Illuminate\Queue\{closure}
#24 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#23 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline::then
#22 /vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(122): Illuminate\Queue\CallQueuedHandler::dispatchThroughMiddleware
#21 /vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(70): Illuminate\Queue\CallQueuedHandler::call
#20 /vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(98): Illuminate\Queue\Jobs\Job::fire
#19 /vendor/laravel/framework/src/Illuminate/Queue/Worker.php(428): Illuminate\Queue\Worker::process
#18 /vendor/laravel/framework/src/Illuminate/Queue/Worker.php(378): Illuminate\Queue\Worker::runJob
#17 /vendor/laravel/framework/src/Illuminate/Queue/Worker.php(172): Illuminate\Queue\Worker::daemon
#16 /vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(117): Illuminate\Queue\Console\WorkCommand::runWorker
#15 /vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(101): Illuminate\Queue\Console\WorkCommand::handle
#14 /vendor/laravel/horizon/src/Console/WorkCommand.php(51): Laravel\Horizon\Console\WorkCommand::handle
#13 /vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}
#12 /vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\Container\Util::unwrapIfClosure
#11 /vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\BoundMethod::callBoundMethod
#10 /vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::call
#9 /vendor/laravel/framework/src/Illuminate/Container/Container.php(651): Illuminate\Container\Container::call
#8 /vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\Console\Command::execute
#7 /vendor/symfony/console/Command/Command.php(299): Symfony\Component\Console\Command\Command::run
#6 /vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Illuminate\Console\Command::run
#5 /vendor/symfony/console/Application.php(978): Symfony\Component\Console\Application::doRunCommand
#4 /vendor/symfony/console/Application.php(295): Symfony\Component\Console\Application::doRun
#3 /vendor/symfony/console/Application.php(167): Symfony\Component\Console\Application::run
#2 /vendor/laravel/framework/src/Illuminate/Console/Application.php(92): Illuminate\Console\Application::run
#1 /vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\Foundation\Console\Kernel::handle
#0 /artisan(37): null
```

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
