### ISSUE TITLE
Resolving env service before binding if class not found in configuration files.

### ISSUE THREAD

**Issue by oanhnn** [laravel/framework#39347]
- Laravel Version: 8.67.0
- PHP Version: 8.0.11

### Description:

Resolving env service before binding if class not found in configuration files.

### Steps To Reproduce:

In one config file (Eg. `config/logging.php` ), using a class, that isn't existed.

```php
<?php

use Monolog\Handler\NullHandler;
use Monolog\Handler\StreamHandler;
use Monolog\Handler\SyslogUdpHandler;

return [

    /*
    |--------------------------------------------------------------------------
    | Default Log Channel
    |--------------------------------------------------------------------------
    |
    | This option defines the default log channel that gets used when writing
    | messages to the logs. The name specified in this option should match
    | one of the channels defined in the "channels" configuration array.
    |
    */

    'default' => env('LOG_CHANNEL', ClassNotExisted::CONST_A),

```

Run: `php artisan`

**Expected**

Throw class `ClassNotExisted` not found exception

**Actual**

Throw ReflectionException and BindingResolutionException

```
Uncaught ReflectionException: Class "env" does not exist in project/vendor/laravel/framework/src/Illuminate/Container/Container.php:877
```
```
Next Illuminate\Contracts\Container\BindingResolutionException: Target class [env] does not exist. in project/vendor/laravel/framework/src/Illuminate/Container/Container.php:879
```

**Reason**

Try resolving `env` service before binding  
https://github.com/laravel/framework/blob/8.x/src/Illuminate/Log/LogManager.php#L523..L525

**Comment by oanhnn** [comment]
@jstephancc 
Your code maybe throw an exception in config files.
Laravel have issue when try handler this exception (logging it).
It shows error as your report instead of show this exception.
You can find this exception by commend https://github.com/laravel/framework/blob/8.x/src/Illuminate/Log/LogManager.php#L523..L525 in `vendor`

**Comment by oanhnn** [comment]
@driesvints 

You can try

### reproduce

```bash
composer create-project laravel/laravel project-test
cd project-test
php artisan
sed -i -e "s#<?php#<?php throw new \\\Exception('test');#" config/database.php
php artisan
```

### Actual

Error like @jstephancc and me reported

```
Next Illuminate\Contracts\Container\BindingResolutionException: Target class [env] does not exist. in /path/to/project-test/vendor/laravel/framework/src/Illuminate/Container/Container.php:879
Stack trace:
#0 /path/to/project-test/vendor/laravel/framework/src/Illuminate/Container/Container.php(758): Illuminate\Container\Container->build('env')
#1 /path/to/project-test/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(841): Illuminate\Container\Container->resolve('env', Array, true)
#2 /path/to/project-test/vendor/laravel/framework/src/Illuminate/Container/Container.php(694): Illuminate\Foundation\Application->resolve('env', Array)
#3 /path/to/project-test/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(826): Illuminate\Container\Container->make('env', Array)
#4 /path/to/project-test/vendor/laravel/framework/src/Illuminate/Container/Container.php(1423): Illuminate\Foundation\Application->make('env')
#5 /path/to/project-test/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(631): Illuminate\Container\Container->offsetGet('env')
#6 /path/to/project-test/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(523): Illuminate\Foundation\Application->runningUnitTests()
#7 /path/to/project-test/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(109): Illuminate\Log\LogManager->parseDriver(NULL)
#8 /path/to/project-test/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(581): Illuminate\Log\LogManager->driver()
#9 /path/to/project-test/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(252): Illuminate\Log\LogManager->error('syntax error, u...', Array)
#10 /path/to/project-test/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(366): Illuminate\Foundation\Exceptions\Handler->report(Object(ParseError))
#11 /path/to/project-test/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(131): Illuminate\Foundation\Console\Kernel->reportException(Object(ParseError))
#12 /path/to/project-test/artisan(37): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 {main}
  thrown in /path/to/project-test/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 879

Fatal error: Uncaught ReflectionException: Class "env" does not exist in /path/to/project-test/vendor/laravel/framework/src/Illuminate/Container/Container.php:877
Stack trace:
#0 /path/to/project-test/vendor/laravel/framework/src/Illuminate/Container/Container.php(877): ReflectionClass->__construct('env')
#1 /path/to/project-test/vendor/laravel/framework/src/Illuminate/Container/Container.php(758): Illuminate\Container\Container->build('env')
#2 /path/to/project-test/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(841): Illuminate\Container\Container->resolve('env', Array, true)
#3 /path/to/project-test/vendor/laravel/framework/src/Illuminate/Container/Container.php(694): Illuminate\Foundation\Application->resolve('env', Array)
#4 /path/to/project-test/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(826): Illuminate\Container\Container->make('env', Array)
#5 /path/to/project-test/vendor/laravel/framework/src/Illuminate/Container/Container.php(1423): Illuminate\Foundation\Application->make('env')
#6 /path/to/project-test/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(631): Illuminate\Container\Container->offsetGet('env')
#7 /path/to/project-test/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(523): Illuminate\Foundation\Application->runningUnitTests()
#8 /path/to/project-test/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(109): Illuminate\Log\LogManager->parseDriver(NULL)
#9 /path/to/project-test/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(581): Illuminate\Log\LogManager->driver()
#10 /path/to/project-test/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(252): Illuminate\Log\LogManager->error('syntax error, u...', Array)
#11 /path/to/project-test/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(366): Illuminate\Foundation\Exceptions\Handler->report(Object(ParseError))
#12 /path/to/project-test/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(131): Illuminate\Foundation\Console\Kernel->reportException(Object(ParseError))
#13 /path/to/project-test/artisan(37): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 {main}
```

### Expected

![image](https://user-images.githubusercontent.com/1757120/139623404-3fb7924d-e6fb-4131-88cd-8507bc765ad8.png)

Result after comment https://github.com/laravel/framework/blob/8.x/src/Illuminate/Log/LogManager.php#L523..L525

**Comment by driesvints** [comment]
@oanhnn I finally see what you're saying. Checking into this.

**Comment by driesvints** [comment]
Sent in a PR here: https://github.com/laravel/framework/pull/39434

**Comment by oanhnn** [comment]
Sorry, my English is not good.
