### ISSUE TITLE
Update to Laravel 8.70 breaks postAutoloadDump

### ISSUE THREAD

**Issue by edwinvdpol** [laravel/framework#39548]
- Laravel Version: 8.70.0
- PHP Version: 8.0.10
- Database Driver & Version: MySQL 8.0.26

### Description:

The artisan package discovery command throws an `UnexpectedValueException` when running `postAutoloadDump`

`Invalid route action: [1\App\Actions\Calendar\CalendarEvents]`.

I noticed a `1` in front of the class name.

When I specifically set the Laravel framework to `v8.69.0` in `composer.json` and run it again, all works as it should.

### Steps To Reproduce:

* Upgrade from Laravel framework v8.69 to v8.70.
* `sail composer update`

<details>
  <summary>Output</summary>

```
Loading composer repositories with package information
Updating dependencies
Lock file operations: 0 installs, 1 update, 0 removals
  - Upgrading laravel/framework (v8.69.0 => v8.70.0)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 0 installs, 1 update, 0 removals
  - Downloading laravel/framework (v8.70.0)
  - Upgrading laravel/framework (v8.69.0 => v8.70.0): Extracting archive
Generating optimized autoload files
composer/package-versions-deprecated: Generating version class...
composer/package-versions-deprecated: ...done generating version class
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

   UnexpectedValueException 

  Invalid route action: [1\App\Actions\Calendar\CalendarEvents].

  at vendor/laravel/framework/src/Illuminate/Routing/RouteAction.php:92
     88▕      */
     89▕     protected static function makeInvokable($action)
     90▕     {
     91▕         if (! method_exists($action, '__invoke')) {
  ➜  92▕             throw new UnexpectedValueException("Invalid route action: [{$action}].");
     93▕         }
     94▕ 
     95▕         return $action.'@__invoke';
     96▕     }

      +8 vendor frames 
  9   routes/web.php:38
      Illuminate\Support\Facades\Facade::__callStatic()

      +3 vendor frames 
  13  routes/web.php:57
      Illuminate\Routing\RouteRegistrar::group()
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1
```
</details>

**Comment by victorybiz** [comment]
Current having the same issue with Laravel v8.70.0

**Comment by taylorotwell** [comment]
Please share your routes file

**Comment by Faks** [comment]
Our development server went down after the update hmm.

**Comment by taylorotwell** [comment]
I can't help anyone until you share more information - thanks.

**Comment by Faks** [comment]
Stack Trace:
[2021-11-09T18:21:04.183951+02:00] RROR: Target class [1\App\Http\Controllers\Api\GameApiController] does not exist. ["ReflectionException: Class \"1\\App\\Http\\Controllers\\Api\\GameApiController\" does not exist in /home/faks_api_noker/public_html/vendor/laravel/framework/src/Illuminate/Container/Container.php:877","Stack trace:","#0 /home/faks_api_noker/public_html/vendor/laravel/framework/src/Illuminate/Container/Container.php(877): ReflectionClass->__construct()","#1 /home/faks_api_noker/public_html/vendor/laravel/framework/src/Illuminate/Container/Container.php(758): Illuminate\\Container\\Container->build()","#2 /home/faks_api_noker/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(841): Illuminate\\Container\\Container->resolve()","#3 /home/faks_api_noker/public_html/vendor/laravel/framework/src/Illuminate/Container/Container.php(694): Illuminate\\Foundation\\Application->resolve()","#4 /home/faks_api_noker/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(826): Illuminate\\Container\\Container->make()","#5 /home/faks_api_noker/public_html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(276): Illuminate\\Foundation\\Application->make()","#6 /home/faks_api_noker/public_html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(1069): Illuminate\\Routing\\Route->getController()","#7 /home/faks_api_noker/public_html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(1012): Illuminate\\Routing\\Route->controllerMiddleware()","#8 /home/faks_api_noker/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(708): Illuminate\\Routing\\Route->gatherMiddleware()","#9 /home/faks_api_noker/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(688): Illuminate\\Routing\\Router->gatherRouteMiddleware()","#10 /home/faks_api_noker/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(672): Illuminate\\Routing\\Router->runRouteWithinStack()","#11 /home/faks_api_noker/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(636): Illuminate\\Routing\\Router->runRoute()","#12 /home/faks_api_noker/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(625): Illuminate\\Routing\\Router->dispatchToRoute()","#13 /home/faks_api_noker/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(167): Illuminate\\Routing\\Router->dispatch()","#14 /home/faks_api_noker/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()","#15 /home/faks_api_noker/public_html/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()","#16 /home/faks_api_noker/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle()","#17 /home/faks_api_noker/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()","#18 /home/faks_api_noker/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()","#19 /home/faks_api_noker/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()","#20 /home/faks_api_noker/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()","#21 /home/faks_api_noker/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()","#22 /home/faks_api_noker/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()","#23 /home/faks_api_noker/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()","#24 /home/faks_api_noker/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()","#25 /home/faks_api_noker/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()","#26 /home/faks_api_noker/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()","#27 /home/faks_api_noker/public_html/vendor/fruitcake/laravel-cors/src/HandleCors.php(52): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()","#28 /home/faks_api_noker/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle()","#29 /home/faks_api_noker/public_html/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()","#30 /home/faks_api_noker/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle()","#31 /home/faks_api_noker/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()","#32 /home/faks_api_noker/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\\Pipeline\\Pipeline->then()","#33 /home/faks_api_noker/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()","#34 /home/faks_api_noker/public_html/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle()","#35 {main}","","Next Illuminate\\Contracts\\Container\\BindingResolutionException: Target class [1\\App\\Http\\Controllers\\Api\\GameApiController] does not exist. in /home/faks_api_noker/public_html/vendor/laravel/framework/src/Illuminate/Container/Container.php:879","Stack trace:","#0 /home/faks_api_noker/public_html/vendor/laravel/framework/src/Illuminate/Container/Container.php(758): Illuminate\\Container\\Container->build()","#1 /home/faks_api_noker/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(841): Illuminate\\Container\\Container->resolve()","#2 /home/faks_api_noker/public_html/vendor/laravel/framework/src/Illuminate/Container/Container.php(694): Illuminate\\Foundation\\Application->resolve()","#3 /home/faks_api_noker/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(826): Illuminate\\Container\\Container->make()","#4 /home/faks_api_noker/public_html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(276): Illuminate\\Foundation\\Application->make()","#5 /home/faks_api_noker/public_html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(1069): Illuminate\\Routing\\Route->getController()","#6 /home/faks_api_noker/public_html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(1012): Illuminate\\Routing\\Route->controllerMiddleware()","#7 /home/faks_api_noker/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(708): Illuminate\\Routing\\Route->gatherMiddleware()","#8 /home/faks_api_noker/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(688): Illuminate\\Routing\\Router->gatherRouteMiddleware()","#9 /home/faks_api_noker/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(672): Illuminate\\Routing\\Router->runRouteWithinStack()","#10 /home/faks_api_noker/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(636): Illuminate\\Routing\\Router->runRoute()","#11 /home/faks_api_noker/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(625): Illuminate\\Routing\\Router->dispatchToRoute()","#12 /home/faks_api_noker/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(167): Illuminate\\Routing\\Router->dispatch()","#13 /home/faks_api_noker/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()","#14 /home/faks_api_noker/public_html/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()","#15 /home/faks_api_noker/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle()","#16 /home/faks_api_noker/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()","#17 /home/faks_api_noker/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()","#18 /home/faks_api_noker/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()","#19 /home/faks_api_noker/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()","#20 /home/faks_api_noker/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()","#21 /home/faks_api_noker/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()","#22 /home/faks_api_noker/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()","#23 /home/faks_api_noker/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()","#24 /home/faks_api_noker/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()","#25 /home/faks_api_noker/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()","#26 /home/faks_api_noker/public_html/vendor/fruitcake/laravel-cors/src/HandleCors.php(52): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()","#27 /home/faks_api_noker/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle()","#28 /home/faks_api_noker/public_html/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()","#29 /home/faks_api_noker/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle()","#30 /home/faks_api_noker/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()","#31 /home/faks_api_noker/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\\Pipeline\\Pipeline->then()","#32 /home/faks_api_noker/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()","#33 /home/faks_api_noker/public_html/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle()","#34 {main}"] []

**Comment by taylorotwell** [comment]
Nobody has shared a route file yet.

**Comment by brunogaspar** [comment]
@taylorotwell Seems routes like the following breaks:

```php
Route::get('foo', FooController::class)->name('foo');
```

**Comment by MarioPerini** [comment]
> @taylorotwell Seems routes like the following breaks:
> 
> ```
> Route::get('foo', FooController::class)->name('foo');
> ```

Can confirm, this also breaks: 
`Route::get('/', \App\Http\Livewire\Frontend\Login::class)->name('access.login');`

**Comment by cage81** [comment]
> Nobody has shared a route file yet.

Same here @taylorotwell. In a new project (Laravel Jetstream/Livewire), the only route I was working on is:

```
use App\Http\Livewire\Articles;

...

Route::get('/articles', Articles::class)->name('articles');
```

**Comment by driesvints** [comment]
@brunogaspar that route works for me in v8.70.0, please post the full routes file.

**Comment by cage81** [comment]
> @brunogaspar that route works for me in v8.70.0, please post the full routes file.

```
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Livewire\Articles;
use App\Http\Controllers\MailController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('dashboard');
});

Route::middleware(['auth:sanctum', 'verified'])->group(function () {
    Route::get('/dashboard', function () {
        return view('dashboard');
    })->name('dashboard');
});

Route::get('/articles', Articles::class)->name('articles');
Route::get('/testmail', [MailController::class, 'index']);
```

**Comment by edwinvdpol** [comment]
Sorry, wrong button... @cage81 beat me to the route file.

**Comment by taylorotwell** [comment]
Do you actually have a valid action? Does your controller contain an __invoke method?

**Comment by bambamboole** [comment]
It also happens on laravel/nova routes

**Comment by Faks** [comment]
I wonder, how different is RouteServiceProvider does that contributes to that issue.

**Comment by MarioPerini** [comment]
>  Does your controller contain an __invoke method?

No since its a livewire full page component

**Comment by cage81** [comment]
> Do you actually have a valid action? Does your controller contain an __invoke method?

Nope...same here, it's a Livewire full page component.

**Comment by driesvints** [comment]
@brunogaspar are you using Livewire as well?

**Comment by MarioPerini** [comment]
It also happens to livewire full page components which has __invoke from Livewire\Component

**Comment by brunogaspar** [comment]
> @brunogaspar are you using Livewire as well?

@driesvints Not using Livewire and my controller do have `__invoke()`.

I'm trying to understand what caused it to break, based on the changes.

**Comment by edwinvdpol** [comment]
I use [Laravel actions](https://laravelactions.com/2.x/basic-usage.html#running-as-a-controller)...

**Comment by Faks** [comment]
seems issue is in src/Illuminate/Routing/RouteRegistrar.php

**Comment by driesvints** [comment]
Does it work for anyone if you revert the following two changes?

![Screen Shot 2021-11-09 at 17 43 20](https://user-images.githubusercontent.com/594614/140967010-2dcf9860-a43b-431d-ab85-4c9f7a2b508d.jpg)

**Comment by brunogaspar** [comment]
> Does it work for anyone if you revert the following two changes? First file is `src/Illuminate/Routing/RouteRegistrar.php`
> 
> ![Screen Shot 2021-11-09 at 17 43 20](https://user-images.githubusercontent.com/594614/140967010-2dcf9860-a43b-431d-ab85-4c9f7a2b508d.jpg)

Seems to work for me

**Comment by brunogaspar** [comment]
```php
return $this->attribute($method, $parameters[0] ?? null);
```

Also works for me.

**Comment by driesvints** [comment]
Thanks all. We're gonna get that fixed. Hold on for now.

**Comment by cage81** [comment]
> Does it work for anyone if you revert the following two changes? First file is `src/Illuminate/Routing/RouteRegistrar.php`
> 
> ![Screen Shot 2021-11-09 at 17 43 20](https://user-images.githubusercontent.com/594614/140967010-2dcf9860-a43b-431d-ab85-4c9f7a2b508d.jpg)

Yes, it works again reverting back changes.

**Comment by taylorotwell** [comment]
Please try these changes and report back if it fixes your problem: https://github.com/laravel/framework/commit/5fda5a335bce1527e6796a91bb36ccb48d6807a8

**Comment by brunogaspar** [comment]
> Please try these changes and report back if it fixes your problem: [5fda5a3](https://github.com/laravel/framework/commit/5fda5a335bce1527e6796a91bb36ccb48d6807a8)

Works for me after those 2 changes.

**Comment by X-Coder264** [comment]
> Please try these changes and report back if it fixes your problem: [5fda5a3](https://github.com/laravel/framework/commit/5fda5a335bce1527e6796a91bb36ccb48d6807a8)

It works for me too with these changes.

**Comment by MarioPerini** [comment]
> Please try these changes and report back if it fixes your problem: [5fda5a3](https://github.com/laravel/framework/commit/5fda5a335bce1527e6796a91bb36ccb48d6807a8)

Yes works

**Comment by Faks** [comment]
fixed, one but broke other hmm.
 Invalid route action: [1\Spatie\StripeWebhooks\StripeWebhooksController].

  at vendor/laravel/framework/src/Illuminate/Routing/RouteAction.php:92
     88▕      */
     89▕     protected static function makeInvokable($action)
     90▕     {
     91▕         if (! method_exists($action, '__invoke')) {
  ➜  92▕             throw new UnexpectedValueException("Invalid route action: [{$action}].");
     93▕         }
     94▕ 
     95▕         return $action.'@__invoke';
     96▕     }

      +8 vendor frames 
  9   routes/api.php:48
      Illuminate\Support\Facades\Facade::__callStatic()

      +3 vendor frames 
  13  routes/api.php:152
      Illuminate\Support\Facades\Facade::__callStatic()

**Comment by taylorotwell** [comment]
@Faks will need a smaller reproducible example than that.

**Comment by taylorotwell** [comment]
Released 8.70.1.

**Comment by Faks** [comment]
@taylorotwell did update now everything returned to a stable working state.

**Comment by taylorotwell** [comment]
Test added to cover this case.

**Comment by edwinvdpol** [comment]
Thank you! 👍
