### ISSUE TITLE
Laravel 9 - Attach a file in an mail from a valid URL results in error

### ISSUE THREAD

**Issue by sergiq** [laravel/framework#41060]
- Laravel Version: 9.1.0
- PHP Version: PHP 8.1.2

### Description:
In Laravel 8, and previous one, you could attach a file from a given URL. Since Laravel 9 this throws an error. Furthermore, it's not possible to embed a file from a given URL inside the blade view with $message->embed()

```
    public function build()
    {
        return $this
            ->attach("https://domain.com/some_image.png")
            ->view('some.view');
    }
```

Error trace
```
Message: Path "https://******.png" is not readable.
File: /*****/vendor/symfony/mime/Part/DataPart.php
Line: 65

#0 /*******/vendor/symfony/mime/Email.php(494): Symfony\\Component\\Mime\\Part\\DataPart::fromPath()
#1 /*******/vendor/symfony/mime/Email.php(476): Symfony\\Component\\Mime\\Email->createDataPart()
#2 /*******/vendor/symfony/mime/Email.php(420): Symfony\\Component\\Mime\\Email->prepareParts()
#3 /*******/vendor/symfony/mime/Email.php(384): Symfony\\Component\\Mime\\Email->generateBody()
#4 /*******/vendor/symfony/mime/Message.php(117): Symfony\\Component\\Mime\\Email->getBody()
#5 [internal function]: Symfony\\Component\\Mime\\Message->toIterable()
#6 /*******/vendor/symfony/mime/RawMessage.php(34): iterator_to_array()
#7 /*******/vendor/symfony/mailer/SentMessage.php(88): Symfony\\Component\\Mime\\RawMessage->toString()
#8 /*******/vendor/laravel/framework/src/Illuminate/Mail/Transport/SesTransport.php(53): Symfony\\Component\\Mailer\\SentMessage->toString()
#9 /*******/vendor/symfony/mailer/Transport/AbstractTransport.php(68): Illuminate\\Mail\\Transport\\SesTransport->doSend()
#10 /*******/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(519): Symfony\\Component\\Mailer\\Transport\\AbstractTransport->send()
#11 /*******/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(285): Illuminate\\Mail\\Mailer->sendSymfonyMessage()
#12 /*******/vendor/laravel/framework/src/Illuminate/Mail/Mailable.php(211): Illuminate\\Mail\\Mailer->send()
#13 /*******/vendor/laravel/framework/src/Illuminate/Support/Traits/Localizable.php(19): Illuminate\\Mail\\Mailable->Illuminate\\Mail\\{closure}()
#14 /*******/vendor/laravel/framework/src/Illuminate/Mail/Mailable.php(212): Illuminate\\Mail\\Mailable->withLocale()
#15 /*******/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(307): Illuminate\\Mail\\Mailable->send()
#16 /*******/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(253): Illuminate\\Mail\\Mailer->sendMailable()
#17 /*******/vendor/laravel/framework/src/Illuminate/Mail/PendingMail.php(124): Illuminate\\Mail\\Mailer->send()
```

### Steps To Reproduce:

For attach method:
1. Create a mail file
2. Attach a file from an existent URL
3. Send it

For embed method:

1. Create a mail file with a view
2. add `{{$message->embed('a valid URL file')}}`
3. Send it

**Comment by sergiq** [comment]
Thanks @driesvints for your answer. A work arround for attach directly a file is calling
