### ISSUE TITLE
ParseError: syntax error, unexpected 'EnvironmentInterface' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) in /var/www/html/coldxlogistics/vendor/league/commonmark/src/MarkdownConverter.php:26

### ISSUE THREAD

**Issue by bilalswiftsolutions** [laravel/framework#41242]
- Laravel Version: 8.83
- PHP Version: 7.3
- Database Driver & Version: 5.7

### Description:
I am sending Notification in  my controller and it was working fine before now suddenly it satrts giving error

```
ParseError: syntax error, unexpected 'EnvironmentInterface' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) in /var/www/html/coldxlogistics/vendor/league/commonmark/src/MarkdownConverter.php:26
--
Stack trace:
#0 /var/www/html/coldxlogistics/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/var/www/html/c...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('League\\CommonMa...')
#2 /var/www/html/coldxlogistics/vendor/league/commonmark/src/CommonMarkConverter.php(25): spl_autoload_call('League\\CommonMa...')
#3 /var/www/html/coldxlogistics/vendor/composer/ClassLoader.php(444): include('/var/www/html/c...')
#4 /var/www/html/coldxlogistics/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/var/www/html/c...')
#5 [internal function]: Composer\Autoload\ClassLoader->loadClass('League\\CommonMa...')
#6 /var/www/html/coldxlogistics/vendor/laravel/framework/src/Illuminate/Mail/Markdown.php(106): spl_autoload_call('League\\CommonMa...')
#7 /var/www/html/coldxlogistics/storage/framework/views/973ada2e07f4525d630b1f018f1684e272fb4c29.php(4): Illuminate\Mail\Markdown::parse(Object(Illuminate\Support\HtmlString))
#8 /var/www/html/coldxlogistics/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(107): require('/var/www/html/c...')
#9 /var/www/html/coldxlogistics/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(108): Illuminate\Filesystem\Filesystem::Illuminate\Filesystem\{closure}()
#10 /var/www/html/coldxlogistics/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(58): Illuminate\Filesystem\Filesystem->getRequire('/var/www/html/c...', Array)
#11 /var/www/html/coldxlogistics/vendor/livewire/livewire/src/ComponentConcerns/RendersLivewireComponents.php(69): Illuminate\View\Engines\PhpEngine->evaluatePath('/var/www/html/c...', Array)
#12 /var/www/html/coldxlogistics/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(61): Livewire\CompilerEngineForIgnition->evaluatePath('/var/www/html/c...', Array)
#13 /var/www/html/coldxlogistics/vendor/facade/ignition/src/Views/Engines/CompilerEngine.php(37): Illuminate\View\Engines\CompilerEngine->get('/var/www/html/c...', Array)
#14 /var/www/html/coldxlogistics/vendor/livewire/livewire/src/ComponentConcerns/RendersLivewireComponents.php(35): Facade\Ignition\Views\Engines\CompilerEngine->get('/var/www/html/c...', Array)
#15 /var/www/html/coldxlogistics/vendor/laravel/framework/src/Illuminate/View/View.php(139): Livewire\CompilerEngineForIgnition->get('/var/www/html/c...', Array)
#16 /var/www/html/coldxlogistics/vendor/laravel/framework/src/Illuminate/View/View.php(122): Illuminate\View\View->getContents()
#17 /var/www/html/coldxlogistics/vendor/laravel/framework/src/Illuminate/View/View.php(91): Illuminate\View\View->renderContents()
#18 /var/www/html/coldxlogistics/vendor/laravel/framework/src/Illuminate/View/Concerns/ManagesComponents.php(104): Illuminate\View\View->render()
#19 /var/www/html/coldxlogistics/storage/framework/views/facd4043843aefc491d375902fb856a81fcf2d12.php(20): Illuminate\View\Factory->renderComponent()
#20 /var/www/html/coldxlogistics/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(107): require('/var/www/html/c...')
#21 /var/www/html/coldxlogistics/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(108): Illuminate\Filesystem\Filesystem::Illuminate\Filesystem\{closure}()
#22 /var/www/html/coldxlogistics/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(58): Illuminate\Filesystem\Filesystem->getRequire('/var/www/html/c...', Array)

</div></div><!--EndFragment-->
</body>
</html>

```

### Steps To Reproduce:

I don't know about reproducing this bug . But I think is because of php version may be. because on my local php 8  is install and on that it is working fine. But I can't update on Production server suddenly . Please provide guidance. Laravel 8 requirement is php 7.3 . It should work Fine

**Comment by WebKenth** [comment]
@bilalswiftsolutions  why are you using php 8 locally if your production server is running 7.3?

What's your deployment strategy? since the exception hints at a classloader problem have you tried running `composer dump` ? 

Do you have any caching layers on your production server? opcache?

**Comment by driesvints** [comment]
Please use the same PHP version in development as you do in production.
