### ISSUE TITLE
Using DB raw inside a migration hangs the migration

### ISSUE THREAD

**Issue by designermonkey** [laravel/framework#41319]
- Laravel Version: 8.80.0
- PHP Version: 7.4.28
- Database Driver & Version: mariadb 10.5 (docker)

### Description:

When using `DB::raw` for a column name (``$table->integer(DB::raw('`study.identifier`'));``) the code hangs and times out. The last version we used (an early v6) worked fine and since upgrading, many of our migrations will no longer run.

### Steps To Reproduce:

I can't provide a repo for this, but here is a failing migration:
```php
<?php declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Schema\Grammars\MySqlGrammar;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class CreateSomeTable extends Migration
{
    public function up()
    {
        Schema::create('table_name', function (Blueprint $table) {
            $table->increments('id');
            $table->integer(DB::raw('`separated.keyname`'));
        });
    }
}
```

---

Hunting through the code for a while shows me that an `Expression` is provided from `DB::raw` which is also handled later on in the code when the migration runs. I have no idea why this fails, and no errors whatsoever are emitted from Laravel, even with `-vvv` provided.

**Comment by designermonkey** [comment]
Why has this been closed?? I'm sorry but "I don't think" is not sufficient an answer to close an issue for functionality that has worked for years, and now doesn't.

**Comment by driesvints** [comment]
@designermonkey please show us where we document this usage.

**Comment by designermonkey** [comment]
I can't as it isn't but that doesn't mean it isn't possible. Software has undocumented features all over the world as the lack of documentation may have been a bug

This is the code path I can follow:

Schema::create (alias of Builder::create)
    Blueprint::create
    (methods from migration example applied)
    Builder::build
    Blueprint::build
    Blueprint::toSql
    MySqlGrammar::compileCreateTable
    MySqlGrammar::wrapTable
    Grammar::wrapTable
    Grammar::isExpression

That is the code path inside a migration file that clearly shows that `Expression` is tested for and handled. However, somewhere further in the process this stops working with no error.

I just looked up that we went from v6.20.x to v8.80.0 and it worked perfectly fine previously. Also, this is perfectly valid syntax in MySQL, so that can argue for it being supported can't it?

**Comment by driesvints** [comment]
@designermonkey you're definitely not an a**hole. You have a concern you're trying to validate. All I'm saying is that this seems to be undocumented and therefor I cannot verify if this was ever intended to work like this. Can you perhaps look through the test suite to see if this behavior is tested? If it isn't then I really fear we never intended this to be supported. 

> I just looked up that we went from v6.20.x to v8.80.0 and it worked perfectly fine previously.

If you could pinpoint the code or PR that broke this for you that could go a long way with us finding a fix.

**Comment by designermonkey** [comment]
A little further investigation by a colleague has shown that when we turn off xdeug we actually see the output of the error being generated:

```
[2022-03-07 11:41:06] development.ERROR: Illegal offset type {"exception":"[object] (ErrorException(code: 0): Illegal offset type at /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Schema/Blueprint.php:1708)
[stacktrace]
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Schema/Blueprint.php(1708): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'Illegal offset ...', '/var/www/html/v...', 1708, Array)
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(742): Illuminate\\Database\\Schema\\Blueprint->Illuminate\\Database\\Schema\\{closure}(Object(Illuminate\\Database\\Schema\\ColumnDefinition), 3)
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Schema/Blueprint.php(1709): Illuminate\\Support\\Collection->mapWithKeys(Object(Closure))
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Schema/Grammars/MySqlGrammar.php(201): Illuminate\\Database\\Schema\\Blueprint->autoIncrementingStartingValues()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Schema/Grammars/MySqlGrammar.php(106): Illuminate\\Database\\Schema\\Grammars\\MySqlGrammar->compileAutoIncrementStartingValues(Object(Illuminate\\Database\\Schema\\Blueprint))
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Schema/Blueprint.php(135): Illuminate\\Database\\Schema\\Grammars\\MySqlGrammar->compileCreate(Object(Illuminate\\Database\\Schema\\Blueprint), Object(Illuminate\\Support\\Fluent), Object(Illuminate\\Database\\MySqlConnection))
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Schema/Blueprint.php(108): Illuminate\\Database\\Schema\\Blueprint->toSql(Object(Illuminate\\Database\\MySqlConnection), Object(Illuminate\\Database\\Schema\\Grammars\\MySqlGrammar))
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Schema/Builder.php(364): Illuminate\\Database\\Schema\\Blueprint->build(Object(Illuminate\\Database\\MySqlConnection), Object(Illuminate\\Database\\Schema\\Grammars\\MySqlGrammar))
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Schema/Builder.php(227): Illuminate\\Database\\Schema\\Builder->build(Object(Illuminate\\Database\\Schema\\Blueprint))
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Illuminate\\Database\\Schema\\Builder->create('report_isolates...', Object(Closure))
#10 /var/www/html/database/migrations/2021_04_06_093757_create_table.php(52): Illuminate\\Support\\Facades\\Facade::__callStatic('create', Array)
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(394): CreateTable->up()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(403): Illuminate\\Database\\Migrations\\Migrator->Illuminate\\Database\\Migrations\\{closure}()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(202): Illuminate\\Database\\Migrations\\Migrator->runMigration(Object(CreateTable), 'up')
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(167): Illuminate\\Database\\Migrations\\Migrator->runUp('/var/www/html/d...', 1, false)
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(112): Illuminate\\Database\\Migrations\\Migrator->runPending(Array, Array)
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(85): Illuminate\\Database\\Migrations\\Migrator->run(Array, Array)
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(585): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->Illuminate\\Database\\Console\\Migrations\\{closure}()
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(94): Illuminate\\Database\\Migrations\\Migrator->usingConnection(NULL, Object(Closure))
#19 /var/www/html/app/Console/Migration/MigrateCommand.php(33): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->handle()
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Console\\Migration\\MigrateCommand->handle()
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(653): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\\Container\\Container->call(Array)
#26 /var/www/html/vendor/symfony/console/Command/Command.php(298): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#28 /var/www/html/vendor/symfony/console/Application.php(1015): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#29 /var/www/html/vendor/symfony/console/Application.php(299): Symfony\\Component\\Console\\Application->doRunCommand(Object(App\\Console\\Migration\\MigrateCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#30 /var/www/html/vendor/symfony/console/Application.php(171): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#31 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Application.php(94): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#32 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#33 /var/www/html/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#34 {main}
"} 

In Blueprint.php line 1708:
  Illegal offset type  
```

**Comment by designermonkey** [comment]
So the issue is that an `Expression` is being used as a key. If the line 1708 in `Blueprint.php` is changed from `: [$column->name => null];` to simply `: [];` it is fixed. As the collection is being filtered anyway, there's no need to add a null value.

I'm not a Laravel developer btw and have inherited a project, so I am not aware of whether this would cause any other issues. I guess with it being specifically for auto_increment columns it _probably_ won't?

**Comment by designermonkey** [comment]
In a wider discussion though, if `DB::raw` and `Expression` are not supported in column names, then some other safe way of providing the ability to name a column like `` `my.column` `` needs to be provided being that it is valid syntax.

**Comment by driesvints** [comment]
> If the line 1708 in Blueprint.php is changed from : [$column->name => null]; to simply : []; it is fixed. As the collection is being filtered anyway, there's no need to add a null value.

Good point. But what if if the column is an `autoIncrement`?
