### ISSUE TITLE
LogMessage not found

### ISSUE THREAD

**Issue by keizah7** [laravel/framework#41954]
- Laravel Version: 8.6.5
- PHP Version: 8.1.3
- Database Driver & Version: mysql 8

### Description:
I'm getting error when logging using info, but log still does the job.
`
[2022-04-13 14:15:35] local.INFO: callback  
`

PaymentOrderCompletedListener.php(29): (last line from my code in trace)
`Log::channel('payment-order')->info($event->type);`

config:
```
  'payment-order' => [
      'driver' => 'daily',
      'path' => storage_path('logs/payment-order.log'),
      'level' => 'info',
  ]
```

```
[2022-04-13 14:15:35] local.ERROR: Class "Facade\Ignition\LogRecorder\LogMessage" not found {"exception":"[object] (Error(code: 0): Class \"Facade\\Ignition\\LogRecorder\\LogMessage\" not found at /Users/arturas/code/Freelance/project-x/vendor/facade/ignition/src/LogRecorder/LogRecorder.php:39)
[stacktrace]
#0 /Users/arturas/code/Freelance/project-x/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(404): Facade\\Ignition\\LogRecorder\\LogRecorder->record(Object(Illuminate\\Log\\Events\\MessageLogged))
#1 /Users/arturas/code/Freelance/project-x/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(249): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}('Illuminate\\\\Log\\\\...', Array)
#2 /Users/arturas/code/Freelance/project-x/vendor/laravel/framework/src/Illuminate/Log/Logger.php(245): Illuminate\\Events\\Dispatcher->dispatch('Illuminate\\\\Log\\\\...')
#3 /Users/arturas/code/Freelance/project-x/vendor/laravel/framework/src/Illuminate/Log/Logger.php(186): Illuminate\\Log\\Logger->fireLogEvent('warning', 'Return type of ...', Array)
#4 /Users/arturas/code/Freelance/project-x/vendor/laravel/framework/src/Illuminate/Log/Logger.php(106): Illuminate\\Log\\Logger->writeLog('warning', 'Return type of ...', Array)
#5 /Users/arturas/code/Freelance/project-x/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(102): Illuminate\\Log\\Logger->warning('Return type of ...')
#6 /Users/arturas/code/Freelance/project-x/vendor/laravel/framework/src/Illuminate/Support/helpers.php(377): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}(Object(Illuminate\\Log\\Logger))
#7 /Users/arturas/code/Freelance/project-x/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(105): with(Object(Illuminate\\Log\\Logger), Object(Closure))
#8 /Users/arturas/code/Freelance/project-x/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(72): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleDeprecation('Return type of ...', '/Users/arturas/...', 397)
#9 /Users/arturas/code/Freelance/project-x/vendor/composer/ClassLoader.php(571): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8192, 'Return type of ...', '/Users/arturas/...', 397)
#10 /Users/arturas/code/Freelance/project-x/vendor/composer/ClassLoader.php(571): include('/Users/arturas/...')
#11 /Users/arturas/code/Freelance/project-x/vendor/composer/ClassLoader.php(428): Composer\\Autoload\\includeFile('/Users/arturas/...')
#12 /Users/arturas/code/Freelance/project-x/vendor/facade/ignition/src/LogRecorder/LogRecorder.php(39): Composer\\Autoload\\ClassLoader->loadClass('Facade\\\\Ignition...')
#13 /Users/arturas/code/Freelance/project-x/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(404): Facade\\Ignition\\LogRecorder\\LogRecorder->record(Object(Illuminate\\Log\\Events\\MessageLogged))
#14 /Users/arturas/code/Freelance/project-x/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(249): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}('Illuminate\\\\Log\\\\...', Array)
#15 /Users/arturas/code/Freelance/project-x/vendor/laravel/framework/src/Illuminate/Log/Logger.php(245): Illuminate\\Events\\Dispatcher->dispatch('Illuminate\\\\Log\\\\...')
#16 /Users/arturas/code/Freelance/project-x/vendor/laravel/framework/src/Illuminate/Log/Logger.php(186): Illuminate\\Log\\Logger->fireLogEvent('info', 'callback', Array)
#17 /Users/arturas/code/Freelance/project-x/vendor/laravel/framework/src/Illuminate/Log/Logger.php(130): Illuminate\\Log\\Logger->writeLog('info', 'callback', Array)
#18 /Users/arturas/code/Freelance/project-x/app/Listeners/PaymentOrderCompletedListener.php(29): Illuminate\\Log\\Logger->info('callback')
#19 /Users/arturas/code/Freelance/project-x/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(424): App\\Listeners\\PaymentOrderCompletedListener->handle(Object(App\\Events\\PaymentOrderCompleted))
#20 /Users/arturas/code/Freelance/project-x/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(249): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}('App\\\\Events\\\\Paym...', Array)
#21 /Users/arturas/code/Freelance/project-x/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(450): Illuminate\\Events\\Dispatcher->dispatch('App\\\\Events\\\\Paym...')
#22 /Users/arturas/code/Freelance/project-x/app/Services/Kevin/CallbackHandler.php(82): event(Object(App\\Events\\PaymentOrderCompleted))
#23 /Users/arturas/code/Freelance/project-x/app/Http/Controllers/Api/KevinController.php(37): App\\Services\\Kevin\\CallbackHandler->handle(Object(Illuminate\\Http\\Request))
#24 /Users/arturas/code/Freelance/project-x/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\\Http\\Controllers\\Api\\KevinController->callback(Object(Illuminate\\Http\\Request))
#25 /Users/arturas/code/Freelance/project-x/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('callback', Array)
#26 /Users/arturas/code/Freelance/project-x/vendor/laravel/framework/src/Illuminate/Routing/Route.php(262): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Http\\Controllers\\Api\\KevinController), 'callback')
#27 /Users/arturas/code/Freelance/project-x/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\Route->runController()
#28 /Users/arturas/code/Freelance/project-x/vendor/laravel/framework/src/Illuminate/Routing/Router.php(695): Illuminate\\Routing\\Route->run()
#29 /Users/arturas/code/Freelance/project-x/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#30 /Users/arturas/code/Freelance/project-x/app/Http/Middleware/Language.php(25): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#31 /Users/arturas/code/Freelance/project-x/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\Language->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#32 /Users/arturas/code/Freelance/project-x/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#33 /Users/arturas/code/Freelance/project-x/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#34 /Users/arturas/code/Freelance/project-x/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(127): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#35 /Users/arturas/code/Freelance/project-x/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(103): Illuminate\\Routing\\Middleware\\ThrottleRequests->handleRequest(Object(Illuminate\\Http\\Request), Object(Closure), Array)
#36 /Users/arturas/code/Freelance/project-x/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(55): Illuminate\\Routing\\Middleware\\ThrottleRequests->handleRequestUsingNamedLimiter(Object(Illuminate\\Http\\Request), Object(Closure), 'api', Object(Closure))
#37 /Users/arturas/code/Freelance/project-x/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\ThrottleRequests->handle(Object(Illuminate\\Http\\Request), Object(Closure), 'api')
#38 /Users/arturas/code/Freelance/project-x/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#39 /Users/arturas/code/Freelance/project-x/vendor/laravel/framework/src/Illuminate/Routing/Router.php(697): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#40 /Users/arturas/code/Freelance/project-x/vendor/laravel/framework/src/Illuminate/Routing/Router.php(672): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#41 /Users/arturas/code/Freelance/project-x/vendor/laravel/framework/src/Illuminate/Routing/Router.php(636): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#42 /Users/arturas/code/Freelance/project-x/vendor/laravel/framework/src/Illuminate/Routing/Router.php(625): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#43 /Users/arturas/code/Freelance/project-x/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(167): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#44 /Users/arturas/code/Freelance/project-x/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#45 /Users/arturas/code/Freelance/project-x/vendor/kabbouchi/nova-impersonate/src/Http/Middleware/Impersonate.php(23): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#46 /Users/arturas/code/Freelance/project-x/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): KABBOUCHI\\NovaImpersonate\\Http\\Middleware\\Impersonate->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#47 /Users/arturas/code/Freelance/project-x/nova/src/Http/Middleware/ServeNova.php(24): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#48 /Users/arturas/code/Freelance/project-x/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Laravel\\Nova\\Http\\Middleware\\ServeNova->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#49 /Users/arturas/code/Freelance/project-x/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#50 /Users/arturas/code/Freelance/project-x/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#51 /Users/arturas/code/Freelance/project-x/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#52 /Users/arturas/code/Freelance/project-x/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#53 /Users/arturas/code/Freelance/project-x/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#54 /Users/arturas/code/Freelance/project-x/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#55 /Users/arturas/code/Freelance/project-x/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#56 /Users/arturas/code/Freelance/project-x/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#57 /Users/arturas/code/Freelance/project-x/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#58 /Users/arturas/code/Freelance/project-x/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#59 /Users/arturas/code/Freelance/project-x/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#60 /Users/arturas/code/Freelance/project-x/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#61 /Users/arturas/code/Freelance/project-x/vendor/fruitcake/laravel-cors/src/HandleCors.php(52): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#62 /Users/arturas/code/Freelance/project-x/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#63 /Users/arturas/code/Freelance/project-x/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#64 /Users/arturas/code/Freelance/project-x/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Http\\Middleware\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#65 /Users/arturas/code/Freelance/project-x/vendor/itsgoingd/clockwork/Clockwork/Support/Laravel/ClockworkMiddleware.php(24): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#66 /Users/arturas/code/Freelance/project-x/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Clockwork\\Support\\Laravel\\ClockworkMiddleware->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#67 /Users/arturas/code/Freelance/project-x/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#68 /Users/arturas/code/Freelance/project-x/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#69 /Users/arturas/code/Freelance/project-x/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#70 /Users/arturas/code/Freelance/project-x/public/index.php(53): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#71 /Users/arturas/.composer/vendor/laravel/valet/server.php(234): require('/Users/arturas/...')
#72 {main}
"}
```

**Comment by anabeto93** [comment]
Hi @keizah7 , I tested with your config and it works without issues.

I hope these two images attached will help.

Config
![logging_config_keizah7](https://user-images.githubusercontent.com/7607657/163252471-4e69b966-7d73-4d00-bc3d-402559f53c48.png)

Log Sample
![no_issue_with_laravel](https://user-images.githubusercontent.com/7607657/163252511-d8faedb3-b52d-4c56-a7ab-eafefa77d0ff.png)

**Comment by keizah7** [comment]
> Hi @keizah7 , I tested with your config and it works without issues.
> 
> I hope these two images attached will help.
> 
> Config ![logging_config_keizah7](https://user-images.githubusercontent.com/7607657/163252471-4e69b966-7d73-4d00-bc3d-402559f53c48.png)
> 
> Log Sample ![no_issue_with_laravel](https://user-images.githubusercontent.com/7607657/163252511-d8faedb3-b52d-4c56-a7ab-eafefa77d0ff.png)

I had multiple logs at the bottom of the function, they worked well too, without any errors. For some reason I got error log only from this one

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
