### ISSUE TITLE
Deprecation warning when trying to trans() with a null value in replacements

### ISSUE THREAD

**Issue by oprypkhantc** [laravel/framework#42204]
- Laravel Version: 9.10.0
- PHP Version: 8.1.5

### Description:
Trying to feed `trans()` a second argument that is an array with a key and a null value results in a deprecation warning:
`local.WARNING: ErrorException: mb_substr(): Passing null to parameter #1 ($string) of type string is deprecated in /app/vendor/laravel/framework/src/Illuminate/Support/Str.php:941`

While that case isn't described in the Laravel documentation, it used to work and still does. I also believe it's reasonably common to occur, especially when just feeding the values from the database into the translator.

### Steps To Reproduce:

1. Configure the deprecations log as per docs
2. Run the following:
```php
trans('validation.after', [
	'date' => null,
]);
```
3. See a deprecation warning:
```log
[2022-04-30 20:42:31] local.WARNING: ErrorException: mb_substr(): Passing null to parameter #1 ($string) of type string is deprecated in /app/vendor/laravel/framework/src/Illuminate/Support/Str.php:941
Stack trace:
#0 /app/vendor/laravel/framework/src/Illuminate/Support/helpers.php(418): Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}()
#1 /app/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(106): with()
#2 /app/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(71): Illuminate\Foundation\Bootstrap\HandleExceptions->handleDeprecation()
#3 /app/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(229): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#4 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}()
#5 /app/vendor/laravel/framework/src/Illuminate/Support/Str.php(941): mb_substr()
#6 /app/vendor/laravel/framework/src/Illuminate/Support/Str.php(1011): Illuminate\Support\Str::substr()
#7 /app/vendor/laravel/framework/src/Illuminate/Translation/Translator.php(220): Illuminate\Support\Str::ucfirst()
#8 /app/vendor/laravel/framework/src/Illuminate/Translation/Translator.php(194): Illuminate\Translation\Translator->makeReplacements()
#9 /app/vendor/laravel/framework/src/Illuminate/Translation/Translator.php(124): Illuminate\Translation\Translator->getLine()
```

**Comment by driesvints** [comment]
Thanks for reporting this. I've sent in a PR for this: https://github.com/laravel/framework/pull/42216
