### ISSUE TITLE
Object of class Illuminate\Queue\Jobs\SyncJob could not be converted to string

### ISSUE THREAD

**Issue by juhotaipale** [laravel/framework#42406]
- Laravel Version: 9.12.2
- PHP Version: 8.1.1
- Database Driver & Version: MySQL 8.0

### Description:
Empty Laravel job runs successfully while giving following error message to the log. E

```
[2022-05-16 20:27:20] local.ERROR: Object of class Illuminate\Queue\Jobs\SyncJob could not be converted to string {"exception":"[object] (Error(code: 0): Object of class Illuminate\\Queue\\Jobs\\SyncJob could not be converted to string at C:\\code\\sensor-gateway\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\Logger.php:265)
[stacktrace]
#0 C:\\code\\sensor-gateway\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\Logger.php(182): Illuminate\\Log\\Logger->formatMessage(Object(Illuminate\\Queue\\Jobs\\SyncJob))
#1 C:\\code\\sensor-gateway\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\Logger.php(130): Illuminate\\Log\\Logger->writeLog('info', Object(Illuminate\\Queue\\Jobs\\SyncJob), Array)
#2 C:\\code\\sensor-gateway\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php(677): Illuminate\\Log\\Logger->info(Object(Illuminate\\Queue\\Jobs\\SyncJob), Array)
#3 C:\\code\\sensor-gateway\\vendor\\laravel\\framework\\src\\Illuminate\\Support\\Facades\\Facade.php(337): Illuminate\\Log\\LogManager->info(Object(Illuminate\\Queue\\Jobs\\SyncJob))
#4 C:\\code\\sensor-gateway\\app\\Providers\\AppServiceProvider.php(30): Illuminate\\Support\\Facades\\Facade::__callStatic('info', Array)
#5 C:\\code\\sensor-gateway\\vendor\\laravel\\framework\\src\\Illuminate\\Events\\Dispatcher.php(421): App\\Providers\\AppServiceProvider->App\\Providers\\{closure}(Object(Illuminate\\Queue\\Events\\JobProcessed))
#6 C:\\code\\sensor-gateway\\vendor\\laravel\\framework\\src\\Illuminate\\Events\\Dispatcher.php(249): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}('Illuminate\\\\Queu...', Array)
#7 C:\\code\\sensor-gateway\\vendor\\laravel\\framework\\src\\Illuminate\\Queue\\SyncQueue.php(87): Illuminate\\Events\\Dispatcher->dispatch('Illuminate\\\\Queu...')
#8 C:\\code\\sensor-gateway\\vendor\\laravel\\framework\\src\\Illuminate\\Queue\\SyncQueue.php(45): Illuminate\\Queue\\SyncQueue->raiseAfterJobEvent(Object(Illuminate\\Queue\\Jobs\\SyncJob))
#9 C:\\code\\sensor-gateway\\vendor\\laravel\\framework\\src\\Illuminate\\Bus\\Dispatcher.php(253): Illuminate\\Queue\\SyncQueue->push(Object(App\\Jobs\\ReceiveGatewayData))
#10 C:\\code\\sensor-gateway\\vendor\\laravel\\framework\\src\\Illuminate\\Bus\\Dispatcher.php(229): Illuminate\\Bus\\Dispatcher->pushCommandToQueue(Object(Illuminate\\Queue\\SyncQueue), Object(App\\Jobs\\ReceiveGatewayData))
#11 C:\\code\\sensor-gateway\\vendor\\laravel\\framework\\src\\Illuminate\\Bus\\Dispatcher.php(77): Illuminate\\Bus\\Dispatcher->dispatchToQueue(Object(App\\Jobs\\ReceiveGatewayData))
#12 C:\\code\\sensor-gateway\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bus\\PendingDispatch.php(193): Illuminate\\Bus\\Dispatcher->dispatch(Object(App\\Jobs\\ReceiveGatewayData))
#13 C:\\code\\sensor-gateway\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bus\\Dispatchable.php(17): Illuminate\\Foundation\\Bus\\PendingDispatch->__destruct()
#14 C:\\code\\sensor-gateway\
outes\\api.php(24): App\\Jobs\\ReceiveGatewayData::dispatch()
#15 C:\\code\\sensor-gateway\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php(237): Illuminate\\Routing\\RouteFileRegistrar->{closure}(Object(Illuminate\\Http\\Request))
#16 C:\\code\\sensor-gateway\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php(207): Illuminate\\Routing\\Route->runCallable()
#17 C:\\code\\sensor-gateway\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(725): Illuminate\\Routing\\Route->run()
#18 C:\\code\\sensor-gateway\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(141): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#19 C:\\code\\sensor-gateway\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Middleware\\SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#20 C:\\code\\sensor-gateway\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(180): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#21 C:\\code\\sensor-gateway\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Middleware\\ThrottleRequests.php(126): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#22 C:\\code\\sensor-gateway\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Middleware\\ThrottleRequests.php(102): Illuminate\\Routing\\Middleware\\ThrottleRequests->handleRequest(Object(Illuminate\\Http\\Request), Object(Closure), Array)
#23 C:\\code\\sensor-gateway\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Middleware\\ThrottleRequests.php(54): Illuminate\\Routing\\Middleware\\ThrottleRequests->handleRequestUsingNamedLimiter(Object(Illuminate\\Http\\Request), Object(Closure), 'api', Object(Closure))
#24 C:\\code\\sensor-gateway\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(180): Illuminate\\Routing\\Middleware\\ThrottleRequests->handle(Object(Illuminate\\Http\\Request), Object(Closure), 'api')
#25 C:\\code\\sensor-gateway\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#26 C:\\code\\sensor-gateway\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(726): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#27 C:\\code\\sensor-gateway\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(703): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#28 C:\\code\\sensor-gateway\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(667): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#29 C:\\code\\sensor-gateway\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(656): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#30 C:\\code\\sensor-gateway\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(167): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#31 C:\\code\\sensor-gateway\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(141): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#32 C:\\code\\sensor-gateway\\vendor\\laravel\
ova\\src\\Http\\Middleware\\ServeNova.php(23): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#33 C:\\code\\sensor-gateway\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(180): Laravel\\Nova\\Http\\Middleware\\ServeNova->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#34 C:\\code\\sensor-gateway\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#35 C:\\code\\sensor-gateway\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#36 C:\\code\\sensor-gateway\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#37 C:\\code\\sensor-gateway\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#38 C:\\code\\sensor-gateway\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#39 C:\\code\\sensor-gateway\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#40 C:\\code\\sensor-gateway\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#41 C:\\code\\sensor-gateway\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#42 C:\\code\\sensor-gateway\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#43 C:\\code\\sensor-gateway\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#44 C:\\code\\sensor-gateway\\vendor\\laravel\\framework\\src\\Illuminate\\Http\\Middleware\\HandleCors.php(62): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#45 C:\\code\\sensor-gateway\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(180): Illuminate\\Http\\Middleware\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#46 C:\\code\\sensor-gateway\\vendor\\laravel\\framework\\src\\Illuminate\\Http\\Middleware\\TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#47 C:\\code\\sensor-gateway\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(180): Illuminate\\Http\\Middleware\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#48 C:\\code\\sensor-gateway\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#49 C:\\code\\sensor-gateway\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(142): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#50 C:\\code\\sensor-gateway\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(111): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#51 C:\\code\\sensor-gateway\\public\\index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#52 C:\\code\\sensor-gateway\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\
esources\\server.php(16): require_once('C:\\\\code\\\\sensor-...')
#53 {main}
"} 
```

### Steps To Reproduce:

Dispatch following job from the api route.

api.php
```php
<?php

use App\Jobs\ReceiveGatewayData;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;

Route::post('/record', function (Request $request) {
    ReceiveGatewayData::dispatch();
});
```

ReceiveGatewayData.php
```php
<?php

namespace App\Jobs;

use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Queue\SerializesModels;

class ReceiveGatewayData implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    public function __construct()
    {
        //
    }

    public function handle()
    {
        //
    }
}
```

**Comment by eduance** [comment]
I wasn't able to recreate this issue within a fresh Laravel installation. Could you create a fresh repository containing this bug? Would not mind taking a look at it.

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
