### ISSUE TITLE
chunk() would trigger mb_strpos() error if there is a composite primary key

### ISSUE THREAD

**Issue by alucard001** [laravel/framework#42724]
- Laravel Version: 6.x (potential 9.x)
- PHP Version: 7.2
- Database Driver & Version: MySQL 5

### Description:
Create a simple db table with a composite primary key
Create a model has a `$primaryKey` defined like `$primaryKey = ['id','another_id'];`
When called `chunk()` using the model that consists of that primary key, it will trigger an error as follow:

```
ErrorException: mb_strpos() expects parameter 1 to be string, array given in C:\projects\my-project\vendor\laravel\framework\src\Illuminate\Support\Str.php:158
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'mb_strpos() exp...', 'C:\\projects\\ess...', 158, Array)
#1 C:\projects\my-project\vendor\laravel\framework\src\Illuminate\Support\Str.php(158): mb_strpos(Array, '.')
#2 C:\projects\my-project\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(365): Illuminate\Support\Str::contains(Array, '.')
#3 C:\projects\my-project\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1346): Illuminate\Database\Eloquent\Model->qualifyColumn(Array)
#4 C:\projects\my-project\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(683): Illuminate\Database\Eloquent\Model->getQualifiedKeyName()
#5 C:\projects\my-project\vendor\laravel\framework\src\Illuminate\Database\Concerns\BuildsQueries.php(20): Illuminate\Database\Eloquent\Builder->enforceOrderBy()
#6 C:\projects\my-project\app\Jobs\pendingBatchJobs.php(119): Illuminate\Database\Eloquent\Builder->chunk(500, Object(Closure))
```
The problem is in this function in `Model.php`:

```
    public function getQualifiedKeyName()
    {
        return $this->qualifyColumn($this->getKeyName());
    }
```
`getKeyName()` will return an array instead of string of primary key, result in causing `qualifyColumn()` to parse an array, which trigger errors.

Please take a look.  Thank you

**Comment by driesvints** [comment]
Composite primary keys are not supported.
