### ISSUE TITLE
($pieces) must be of type array, string given when executing a NOOP via FTP

### ISSUE THREAD

**Issue by realtebo** [laravel/framework#43142]
- Laravel Version: 8.83.18
- PHP Version: 8.1.#
- Database Driver & Version:

### Description:

We download a list of files. Succesfully. At a certain point we get this 

```
implode(): Argument #1 ($pieces) must be of type array, string given {"exception":"[object] (TypeError(code: 0): implode(): Argument #1 ($pieces) must be of type array, string given at C:\\laragon\\www\\mk-backend\\vendor\\league\\flysystem\\src\\Adapter\\Ftp.php:577)
[stacktrace]
#0 C:\\laragon\\www\\mk-backend\\vendor\\league\\flysystem\\src\\Adapter\\Ftp.php(577): implode(' ', NULL)
#1 C:\\laragon\\www\\mk-backend\\vendor\\league\\flysystem\\src\\Adapter\\Ftp.php(541): League\\Flysystem\\Adapter\\Ftp->getRawExecResponseCode('NOOP')
#2 C:\\laragon\\www\\mk-backend\\vendor\\league\\flysystem\\src\\Adapter\\AbstractFtpAdapter.php(648): League\\Flysystem\\Adapter\\Ftp->isConnected()
#3 C:\\laragon\\www\\mk-backend\\vendor\\league\\flysystem\\src\\Adapter\\Ftp.php(399): League\\Flysystem\\Adapter\\AbstractFtpAdapter->getConnection()
#4 C:\\laragon\\www\\mk-backend\\vendor\\league\\flysystem\\src\\Adapter\\AbstractFtpAdapter.php(610): League\\Flysystem\\Adapter\\Ftp->getMetadata('Wd-LinkImgC_Nuo...')
#5 C:\\laragon\\www\\mk-backend\\vendor\\league\\flysystem\\src\\Filesystem.php(58): League\\Flysystem\\Adapter\\AbstractFtpAdapter->has('Wd-LinkImgC_Nuo...')
#6 C:\\laragon\\www\\mk-backend\\vendor\\league\\flysystem\\src\\Filesystem.php(389): League\\Flysystem\\Filesystem->has('Wd-LinkImgC_Nuo...')
#7 C:\\laragon\\www\\mk-backend\\vendor\\league\\flysystem\\src\\Filesystem.php(180): League\\Flysystem\\Filesystem->assertPresent('Wd-LinkImgC_Nuo...')
#8 C:\\laragon\\www\\mk-backend\\vendor\\laravel\\framework\\src\\Illuminate\\Filesystem\\FilesystemAdapter.php(169): League\\Flysystem\\Filesystem->read('Wd-LinkImgC_Nuo...')
#9 C:\\laragon\\www\\mk-backend\\app\\Jobs\\ImportRelated\\EsprinetFtpXLSX\\ProcessProductsFileJob.php(219): Illuminate\\Filesystem\\FilesystemAdapter->get('Wd-LinkImgC_Nuo...')
#10 C:\\laragon\\www\\mk-backend\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(36): App\\Jobs\\ImportRelated\\EsprinetFtpXLSX\\ProcessProductsFileJob->handle()
#11 C:\\laragon\\www\\mk-backend\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#12 C:\\laragon\\www\\mk-backend\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#13 C:\\laragon\\www\\mk-backend\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application)
```

### Steps To Reproduce:

I cannot help to reproduce. But i cannot understand if the error ir mine, of the server, or of the package itself.,

I have no understand of WHY the ftp adapter is sending a NOOP. But of course the framework should not crash for a 'null' received in reply from the server

**Comment by bert-w** [comment]
That is another repo. Also if you can't reproduce it than its kinda hard to track down.
