### ISSUE TITLE
Closure dispatches fail if triggered from within an anonymous class

### ISSUE THREAD

**Issue by niekbr** [laravel/framework#43756]
- Laravel Version: 9.25.1
- PHP 8.1.8
- Database Driver & Version: sqlite

### Description:
Closure dispatches fail if triggered from within an anonymous class.
```php
$class = new class {
    function tryDispatch(): void
    {
        dispatch(function () {
            \Illuminate\Support\Facades\Log::info('Closure dispatch in anonymous class works');
        });
    }
};
```

### Steps To Reproduce:

[See this repository](https://github.com/niekbr/laravel-anonymous-class-dispatch-closure-test/commit/fa3232746803c100290ac6c758295fe51755f8ef)
- Install the repo above
- Set the following `.env`:
  - `QUEUE_CONNECTION` to something other than `sync`. (tried with `database` and `redis`)
  - Setup a database (tried with `mysql` and `sqlite`)
- Migrate
- Start the queue worker
- `php artisan serve`
- go to `localhost:8000`

The dispatched closure job outside the anonymous class succeeds (log appears), while the closure job within the anonymous class fails with the following exception:
```
[2022-08-18 11:12:29] local.ERROR: Class "class@anonymous" not found {"exception":"[object] (ErrorException(code: 0): Class \"class@anonymous\" not found at /home/niek/coding/dcc/laravel-anonymous-class-dispatch-closure-test/vendor/laravel/serializable-closure/src/Serializers/Native.php:193)
[stacktrace]
#0 /home/niek/coding/dcc/laravel-anonymous-class-dispatch-closure-test/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(257): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}()
#2 /home/niek/coding/dcc/laravel-anonymous-class-dispatch-closure-test/vendor/laravel/serializable-closure/src/Serializers/Native.php(193): Closure->bindTo()
#3 [internal function]: Laravel\\SerializableClosure\\Serializers\\Native->__unserialize()
#4 /home/niek/coding/dcc/laravel-anonymous-class-dispatch-closure-test/vendor/laravel/serializable-closure/src/Serializers/Signed.php(86): unserialize()
#5 [internal function]: Laravel\\SerializableClosure\\Serializers\\Signed->__unserialize()
#6 /home/niek/coding/dcc/laravel-anonymous-class-dispatch-closure-test/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(96): unserialize()
#7 /home/niek/coding/dcc/laravel-anonymous-class-dispatch-closure-test/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(257): Illuminate\\Queue\\CallQueuedHandler->getCommand()
#8 /home/niek/coding/dcc/laravel-anonymous-class-dispatch-closure-test/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(213): Illuminate\\Queue\\CallQueuedHandler->failed()
#9 /home/niek/coding/dcc/laravel-anonymous-class-dispatch-closure-test/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(192): Illuminate\\Queue\\Jobs\\Job->failed()
#10 /home/niek/coding/dcc/laravel-anonymous-class-dispatch-closure-test/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(582): Illuminate\\Queue\\Jobs\\Job->fail()
#11 /home/niek/coding/dcc/laravel-anonymous-class-dispatch-closure-test/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(528): Illuminate\\Queue\\Worker->failJob()
#12 /home/niek/coding/dcc/laravel-anonymous-class-dispatch-closure-test/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(452): Illuminate\\Queue\\Worker->markJobAsFailedIfWillExceedMaxAttempts()
#13 /home/niek/coding/dcc/laravel-anonymous-class-dispatch-closure-test/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(429): Illuminate\\Queue\\Worker->handleJobException()
#14 /home/niek/coding/dcc/laravel-anonymous-class-dispatch-closure-test/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(375): Illuminate\\Queue\\Worker->process()
#15 /home/niek/coding/dcc/laravel-anonymous-class-dispatch-closure-test/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(173): Illuminate\\Queue\\Worker->runJob()
#16 /home/niek/coding/dcc/laravel-anonymous-class-dispatch-closure-test/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(150): Illuminate\\Queue\\Worker->daemon()
#17 /home/niek/coding/dcc/laravel-anonymous-class-dispatch-closure-test/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(134): Illuminate\\Queue\\Console\\WorkCommand->runWorker()
#18 /home/niek/coding/dcc/laravel-anonymous-class-dispatch-closure-test/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Queue\\Console\\WorkCommand->handle()
#19 /home/niek/coding/dcc/laravel-anonymous-class-dispatch-closure-test/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#20 /home/niek/coding/dcc/laravel-anonymous-class-dispatch-closure-test/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#21 /home/niek/coding/dcc/laravel-anonymous-class-dispatch-closure-test/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#22 /home/niek/coding/dcc/laravel-anonymous-class-dispatch-closure-test/vendor/laravel/framework/src/Illuminate/Container/Container.php(651): Illuminate\\Container\\BoundMethod::call()
#23 /home/niek/coding/dcc/laravel-anonymous-class-dispatch-closure-test/vendor/laravel/framework/src/Illuminate/Console/Command.php(139): Illuminate\\Container\\Container->call()
#24 /home/niek/coding/dcc/laravel-anonymous-class-dispatch-closure-test/vendor/symfony/console/Command/Command.php(308): Illuminate\\Console\\Command->execute()
#25 /home/niek/coding/dcc/laravel-anonymous-class-dispatch-closure-test/vendor/laravel/framework/src/Illuminate/Console/Command.php(124): Symfony\\Component\\Console\\Command\\Command->run()
#26 /home/niek/coding/dcc/laravel-anonymous-class-dispatch-closure-test/vendor/symfony/console/Application.php(998): Illuminate\\Console\\Command->run()
#27 /home/niek/coding/dcc/laravel-anonymous-class-dispatch-closure-test/vendor/symfony/console/Application.php(299): Symfony\\Component\\Console\\Application->doRunCommand()
#28 /home/niek/coding/dcc/laravel-anonymous-class-dispatch-closure-test/vendor/symfony/console/Application.php(171): Symfony\\Component\\Console\\Application->doRun()
#29 /home/niek/coding/dcc/laravel-anonymous-class-dispatch-closure-test/vendor/laravel/framework/src/Illuminate/Console/Application.php(102): Symfony\\Component\\Console\\Application->run()
#30 /home/niek/coding/dcc/laravel-anonymous-class-dispatch-closure-test/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run()
#31 /home/niek/coding/dcc/laravel-anonymous-class-dispatch-closure-test/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#32 {main}
"} 
[2022-08-18 11:13:36] local.INFO: Anonymous dispatch works  
```

**Comment by driesvints** [comment]
You can't restore anonymous classes. I don't see a way this could possible work.
