### ISSUE TITLE
Possible bug related to DB::raw and $casts on model

### ISSUE THREAD

**Issue by caiokawasaki** [laravel/framework#43954]
- Laravel Version: 9.26.1
- PHP Version: 8.1.9
- Database Driver & Version: mysql (Docker - mysql/mysql-server:8.0)

### Description:

When I try to update a model with a custom query using `DB::raw()` to increment, I get the following error:

```
[2022-08-31 17:35:29] testing.ERROR: Object of class Illuminate\Database\Query\Expression could not be converted to int {"exception":"[object] (ErrorException(code: 0): Object of class Illuminate\\Database\\Query\\Expression could not be converted to int at /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php:726)
[stacktrace]
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(259): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(726): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(1988): Illuminate\\Database\\Eloquent\\Model->castAttribute()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(1938): Illuminate\\Database\\Eloquent\\Model->originalIsEquivalent()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(1872): Illuminate\\Database\\Eloquent\\Model->getDirty()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1014): Illuminate\\Database\\Eloquent\\Model->isDirty()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(885): Illuminate\\Database\\Eloquent\\Model->save()
#7 /var/www/html/app/Models/Invoice.php(196): Illuminate\\Database\\Eloquent\\Model->update()
#8 /var/www/html/app/Jobs/ResolveSentMessage.php(59): App\\Models\\Invoice->incrementOutgoingMessagesAmount()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Jobs\\ResolveSentMessage->handle()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(651): Illuminate\\Container\\BoundMethod::call()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(128): Illuminate\\Container\\Container->call()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}()
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(132): Illuminate\\Pipeline\\Pipeline->then()
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(124): Illuminate\\Bus\\Dispatcher->dispatchNow()
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Queue\\CallQueuedHandler->Illuminate\\Queue\\{closure}()
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(126): Illuminate\\Pipeline\\Pipeline->then()
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(70): Illuminate\\Queue\\CallQueuedHandler->dispatchThroughMiddleware()
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(98): Illuminate\\Queue\\CallQueuedHandler->call()
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/SyncQueue.php(43): Illuminate\\Queue\\Jobs\\Job->fire()
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Queue.php(57): Illuminate\\Queue\\SyncQueue->push()
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(246): Illuminate\\Queue\\Queue->pushOn()
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(229): Illuminate\\Bus\\Dispatcher->pushCommandToQueue()
#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(77): Illuminate\\Bus\\Dispatcher->dispatchToQueue()
#29 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Bus/PendingDispatch.php(193): Illuminate\\Bus\\Dispatcher->dispatch()
#30 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Bus/Dispatchable.php(18): Illuminate\\Foundation\\Bus\\PendingDispatch->__destruct()
#31 /var/www/html/app/Http/Controllers/Number/MessageController.php(18): App\\Jobs\\ResolveSentMessage::dispatch()
#32 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\\Http\\Controllers\\Number\\MessageController->sent()
#33 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()
#34 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(261): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#35 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(204): Illuminate\\Routing\\Route->runController()
#36 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(725): Illuminate\\Routing\\Route->run()
#37 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#38 /var/www/html/app/Http/Middleware/Authenticate.php(22): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#39 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): App\\Http\\Middleware\\Authenticate->handle()
#40 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#41 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#42 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#43 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(726): Illuminate\\Pipeline\\Pipeline->then()
#44 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(703): Illuminate\\Routing\\Router->runRouteWithinStack()
#45 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(667): Illuminate\\Routing\\Router->runRoute()
#46 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(656): Illuminate\\Routing\\Router->dispatchToRoute()
#47 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(167): Illuminate\\Routing\\Router->dispatch()
#48 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#49 /var/www/html/app/Http/Middleware/ForceJsonResponse.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#50 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): App\\Http\\Middleware\\ForceJsonResponse->handle()
#51 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#52 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#53 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#54 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#55 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#56 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#57 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#58 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#59 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#60 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#61 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#62 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\HandleCors->handle()
#63 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#64 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#65 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#66 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\\Pipeline\\Pipeline->then()
#67 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#68 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/MakesHttpRequests.php(538): Illuminate\\Foundation\\Http\\Kernel->handle()
#69 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/MakesHttpRequests.php(504): Illuminate\\Foundation\\Testing\\TestCase->call()
#70 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/MakesHttpRequests.php(346): Illuminate\\Foundation\\Testing\\TestCase->json()
#71 /var/www/html/tests/Feature/Number/MessageTest.php(35): Illuminate\\Foundation\\Testing\\TestCase->postJson()
#72 /var/www/html/vendor/phpunit/phpunit/src/Framework/TestCase.php(1545): Tests\\Feature\\Number\\MessageTest->test_add_sent_message_on_invoice()
#73 /var/www/html/vendor/phpunit/phpunit/src/Framework/TestCase.php(1151): PHPUnit\\Framework\\TestCase->runTest()
#74 /var/www/html/vendor/phpunit/phpunit/src/Framework/TestResult.php(726): PHPUnit\\Framework\\TestCase->runBare()
#75 /var/www/html/vendor/phpunit/phpunit/src/Framework/TestCase.php(903): PHPUnit\\Framework\\TestResult->run()
#76 /var/www/html/vendor/phpunit/phpunit/src/Framework/TestSuite.php(672): PHPUnit\\Framework\\TestCase->run()
#77 /var/www/html/vendor/phpunit/phpunit/src/Framework/TestSuite.php(672): PHPUnit\\Framework\\TestSuite->run()
#78 /var/www/html/vendor/phpunit/phpunit/src/Framework/TestSuite.php(672): PHPUnit\\Framework\\TestSuite->run()
#79 /var/www/html/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(673): PHPUnit\\Framework\\TestSuite->run()
#80 /var/www/html/vendor/phpunit/phpunit/src/TextUI/Command.php(143): PHPUnit\\TextUI\\TestRunner->run()
#81 /var/www/html/vendor/phpunit/phpunit/src/TextUI/Command.php(96): PHPUnit\\TextUI\\Command->run()
#82 /var/www/html/vendor/phpunit/phpunit/phpunit(98): PHPUnit\\TextUI\\Command::main()
#83 {main}
"}
```

### Steps To Reproduce:

This is my model:

```php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;

class Invoice extends Model
{
    use HasFactory;

    protected $fillable = [
        'contacts_amount',
        'outgoing_messages_amount',
    ];

    protected $casts = [
        'contacts_amount' => 'integer',
        'outgoing_messages_amount' => 'integer',
    ];

    protected $attributes = [
        'contacts_amount' => 0,
        'outgoing_messages_amount' => 0,
    ];

    public function incrementOutgoingMessagesAmount(
        int  $amount = 1,
        bool $incrementContact = false
    ): Invoice
    {
        $incrementContact ?
            $this->update([
                'contacts_amount' => DB::raw('contacts_amount + 1'),
                'outgoing_messages_amount' => DB::raw("outgoing_messages_amount + $amount"),
            ]) :
            $this->increment('outgoing_messages_amount', $amount);

        return $this;
    }
}
```

This is my code:

```php
if ($invoice = Invoice::first()) $invoice->incrementOutgoingMessagesAmount(
    incrementContact: true
);
```

When I try to call the `incrementOutgoingMessagesAmount()` method i receive the error listed above.

This is related to casts, if I remove the casts the code works correctly. Is this a bug or is it expected behavior?

**Comment by rodrigopedra** [comment]
try updating your code to this:

~~~php
public function incrementOutgoingMessagesAmount(
    int $amount = 1,
    bool $incrementContact = false
): Invoice {
    $incrementContact ?
        $this->newQuery()->update([
            'contacts_amount' => DB::raw('contacts_amount + 1'),
            'outgoing_messages_amount' => DB::raw("outgoing_messages_amount + $amount"),
        ]) :
        $this->increment('outgoing_messages_amount', $amount);

    return $this;
}
~~~

Note the `->newQuery()` before calling the `->update()` method.

`Model@update()` first fills the attribute and calls `Model@save` under the hood. So any casts will try to be applied.

`Model@newQuery()` will return a `Eloquent\Builder` instance, and then `Builder@update()` will handle expressions accordingly, as it will defer to the underlying `Database\Builder` instance. Global scopes will still be applied when calling `Model@newQuery()`

References:

https://github.com/laravel/framework/blob/0efbd7e6df26c48c3a2438fffefcdea932ec768f/src/Illuminate/Database/Eloquent/Model.php#L879-L886

https://github.com/laravel/framework/blob/0efbd7e6df26c48c3a2438fffefcdea932ec768f/src/Illuminate/Database/Eloquent/Model.php#L1367-L1370

https://github.com/laravel/framework/blob/0efbd7e6df26c48c3a2438fffefcdea932ec768f/src/Illuminate/Database/Eloquent/Builder.php#L998-L1001

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
