### ISSUE TITLE
Infinite dep resolving when we are using contextual binding of log channel without installed package 'spatie/laravel-ignition'

### ISSUE THREAD

**Issue by rnixik** [laravel/framework#45087]
- Laravel Version: 9.41.0
- PHP Version: 8.1.0
- Database Driver & Version: no

### Description:

Infinite dependency resolving when we are using contextual binding of log channel without installed package 'spatie/laravel-ignition'.

### Steps To Reproduce:

1. Create a new project from https://github.com/laravel/laravel

2. Write any service with `Psr\Log\LoggerInterface` dependency, DemoService:

```
<?php

namespace App\Services;

use Psr\Log\LoggerInterface;

class DemoService
{
    public function __construct(private readonly LoggerInterface $logger)
    {
    }

    public function demo(): void
    {
        $this->logger->debug('any');
    }
}

```

3. Write any console command to call this service, DemoCommand:

```
<?php

namespace App\Console\Commands;

use App\Services\DemoService;
use Illuminate\Console\Command;

class DemoCommand extends Command
{
    protected $signature = 'demo';

    public function handle(DemoService $demoService)
    {
        $demoService->demo();
        $this->line('Log has been written');

        return 0;
    }
}

```

4. Write contextual binding in AppServiceProvider.php:

```
public function register()
    {
        $this->app->when(DemoService::class)
            ->needs(LoggerInterface::class)
            ->give(function () {
                // debug_print_backtrace();
                return Log::channel('single');
            });
    }
```

5. Install composer packages without dev deps: `composer install --no-dev`
6. Run demo command `php artisan demo`

It should write log and exit, but in this case it crashes with `segmentation fault`, adding `debug_print_backtrace()` shows that we have infinite attempts to resolve logger. I found out that issue relates to `spatie/laravel-ignition` - we need it to work.

There is a part of backtraces without spatie/laravel-ignition:

```
#748 /app/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(332): Illuminate\Support\Facades\Facade::getFacadeRoot()
#749 /app/app/Providers/AppServiceProvider.php(29): Illuminate\Support\Facades\Facade::__callStatic('channel', Array)
#750 /app/vendor/laravel/framework/src/Illuminate/Container/Container.php(871): App\Providers\AppServiceProvider->App\Providers\{closure}(Object(Illuminate\Foundation\Application), Array)
#751 /app/vendor/laravel/framework/src/Illuminate/Container/Container.php(756): Illuminate\Container\Container->build(Object(Closure))
#752 /app/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(860): Illuminate\Container\Container->resolve('log', Array, true)
#753 /app/vendor/laravel/framework/src/Illuminate/Container/Container.php(692): Illuminate\Foundation\Application->resolve('log', Array)
#754 /app/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(845): Illuminate\Container\Container->make('log', Array)
#755 /app/vendor/laravel/framework/src/Illuminate/Container/Container.php(1419): Illuminate\Foundation\Application->make('log')
#756 /app/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(222): Illuminate\Container\Container->offsetGet('log')
#757 /app/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(193): Illuminate\Support\Facades\Facade::resolveFacadeInstance('log')
#758 /app/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(332): Illuminate\Support\Facades\Facade::getFacadeRoot()
#759 /app/app/Providers/AppServiceProvider.php(29): Illuminate\Support\Facades\Facade::__callStatic('channel', Array)
#760 /app/vendor/laravel/framework/src/Illuminate/Container/Container.php(871): App\Providers\AppServiceProvider->App\Providers\{closure}(Object(Illuminate\Foundation\Application), Array)
#761 /app/vendor/laravel/framework/src/Illuminate/Container/Container.php(756): Illuminate\Container\Container->build(Object(Closure))
#762 /app/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(860): Illuminate\Container\Container->resolve('log', Array, true)
#763 /app/vendor/laravel/framework/src/Illuminate/Container/Container.php(692): Illuminate\Foundation\Application->resolve('log', Array)
#764 /app/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(845): Illuminate\Container\Container->make('log', Array)
#765 /app/vendor/laravel/framework/src/Illuminate/Container/Container.php(1419): Illuminate\Foundation\Application->make('log')
#766 /app/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(222): Illuminate\Container\Container->offsetGet('log')
#767 /app/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(193): Illuminate\Support\Facades\Facade::resolveFacadeInstance('log')
#768 /app/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(332): Illuminate\Support\Facades\Facade::getFacadeRoot()
#769 /app/app/Providers/AppServiceProvider.php(29): Illuminate\Support\Facades\Facade::__callStatic('channel', Array)
#770 /app/vendor/laravel/framework/src/Illuminate/Container/Container.php(871): App\Providers\AppServiceProvider->App\Providers\{closure}(Object(Illuminate\Foundation\Application), Array)
#771 /app/vendor/laravel/framework/src/Illuminate/Container/Container.php(756): Illuminate\Container\Container->build(Object(Closure))
#772 /app/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(860): Illuminate\Container\Container->resolve('log', Array, true)
#773 /app/vendor/laravel/framework/src/Illuminate/Container/Container.php(692): Illuminate\Foundation\Application->resolve('log', Array)
#774 /app/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(845): Illuminate\Container\Container->make('log', Array)
#775 /app/vendor/laravel/framework/src/Illuminate/Container/Container.php(1029): Illuminate\Foundation\Application->make('log')
#776 /app/vendor/laravel/framework/src/Illuminate/Container/Container.php(945): Illuminate\Container\Container->resolveClass(Object(ReflectionParameter))
#777 /app/vendor/laravel/framework/src/Illuminate/Container/Container.php(906): Illuminate\Container\Container->resolveDependencies(Array)
#778 /app/vendor/laravel/framework/src/Illuminate/Container/Container.php(756): Illuminate\Container\Container->build('App\\Services\\De...')
#779 /app/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(860): Illuminate\Container\Container->resolve('App\\Services\\De...', Array, true)
#780 /app/vendor/laravel/framework/src/Illuminate/Container/Container.php(692): Illuminate\Foundation\Application->resolve('App\\Services\\De...', Array)
#781 /app/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(845): Illuminate\Container\Container->make('App\\Services\\De...', Array)
#782 /app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(181): Illuminate\Foundation\Application->make('App\\Services\\De...')
#783 /app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(124): Illuminate\Container\BoundMethod::addDependencyForCallParameter(Object(Illuminate\Foundation\Application), Object(ReflectionParameter), Array, Array)
#784 /app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\Container\BoundMethod::getMethodDependencies(Object(Illuminate\Foundation\Application), Array, Array)
#785 /app/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#786 /app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#787 /app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#788 /app/vendor/laravel/framework/src/Illuminate/Container/Container.php(651): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#789 /app/vendor/laravel/framework/src/Illuminate/Console/Command.php(178): Illuminate\Container\Container->call(Array)
#790 /app/vendor/symfony/console/Command/Command.php(308): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#791 /app/vendor/laravel/framework/src/Illuminate/Console/Command.php(148): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#792 /app/vendor/symfony/console/Application.php(1014): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#793 /app/vendor/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand(Object(App\Console\Commands\DemoCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#794 /app/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#795 /app/vendor/laravel/framework/src/Illuminate/Console/Application.php(102): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#796 /app/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(155): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#797 /app/artisan(37): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

```

And there is backtrace with `spatie/laravel-ignition`:

```
#0 /app/vendor/laravel/framework/src/Illuminate/Container/Container.php(871): App\Providers\AppServiceProvider->App\Providers\{closure}(Object(Illuminate\Foundation\Application), Array)
#1 /app/vendor/laravel/framework/src/Illuminate/Container/Container.php(756): Illuminate\Container\Container->build(Object(Closure))
#2 /app/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(860): Illuminate\Container\Container->resolve('log', Array, true)
#3 /app/vendor/laravel/framework/src/Illuminate/Container/Container.php(692): Illuminate\Foundation\Application->resolve('log', Array)
#4 /app/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(845): Illuminate\Container\Container->make('log', Array)
#5 /app/vendor/laravel/framework/src/Illuminate/Container/Container.php(1029): Illuminate\Foundation\Application->make('log')
#6 /app/vendor/laravel/framework/src/Illuminate/Container/Container.php(945): Illuminate\Container\Container->resolveClass(Object(ReflectionParameter))
#7 /app/vendor/laravel/framework/src/Illuminate/Container/Container.php(906): Illuminate\Container\Container->resolveDependencies(Array)
#8 /app/vendor/laravel/framework/src/Illuminate/Container/Container.php(756): Illuminate\Container\Container->build('App\\Services\\De...')
#9 /app/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(860): Illuminate\Container\Container->resolve('App\\Services\\De...', Array, true)
#10 /app/vendor/laravel/framework/src/Illuminate/Container/Container.php(692): Illuminate\Foundation\Application->resolve('App\\Services\\De...', Array)
#11 /app/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(845): Illuminate\Container\Container->make('App\\Services\\De...', Array)
#12 /app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(181): Illuminate\Foundation\Application->make('App\\Services\\De...')
#13 /app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(124): Illuminate\Container\BoundMethod::addDependencyForCallParameter(Object(Illuminate\Foundation\Application), Object(ReflectionParameter), Array, Array)
#14 /app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\Container\BoundMethod::getMethodDependencies(Object(Illuminate\Foundation\Application), Array, Array)
#15 /app/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#16 /app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#17 /app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#18 /app/vendor/laravel/framework/src/Illuminate/Container/Container.php(651): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#19 /app/vendor/laravel/framework/src/Illuminate/Console/Command.php(178): Illuminate\Container\Container->call(Array)
#20 /app/vendor/symfony/console/Command/Command.php(308): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#21 /app/vendor/laravel/framework/src/Illuminate/Console/Command.php(148): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#22 /app/vendor/symfony/console/Application.php(1014): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 /app/vendor/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand(Object(App\Console\Commands\DemoCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 /app/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 /app/vendor/laravel/framework/src/Illuminate/Console/Application.php(102): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#26 /app/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(155): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#27 /app/artisan(37): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
Log has been written
```

**Comment by driesvints** [comment]
> I found out that issue relates to spatie/laravel-ignition

Please open an issue on the ignition repo.

**Comment by rnixik** [comment]
@driesvints Laravel cannot work without 3rd party package. Could you please clarify you opinion?

**Comment by driesvints** [comment]
You said the issue is in the ignition package. We don't maintain it.

**Comment by rnixik** [comment]
@driesvints It is related to it but the problem is in Laravel. I created a demo project to reproduce the issue https://github.com/laravel/laravel/compare/9.x...rnixik:laravel:9.x

Forget about "spatie/laravel-ignition". The root issue that Laravel project is working ok on dev env but it **crashes on production** and the only difference is `composer install --no-dev`.

**Comment by X-Coder264** [comment]
https://github.com/laravel/framework/issues/44618
https://github.com/laravel/framework/issues/33114

;)

**Comment by rnixik** [comment]
Looks like we have a solution in ignition package :)18:34, 25 ноября 2022 г., Antonio Pauletich ***@***.***>:
#44618
#33114
;)

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
-- Отправлено из мобильного приложения Яндекс Почты

**Comment by rnixik** [comment]
Another possible solution is resolving $logger before.
```php
public function register()
{
        $logger = Log::channel('single');
        $this->app->when(DemoService::class)
            ->needs(LoggerInterface::class)
            ->give(function () use ($logger) {
                debug_print_backtrace();
                return $logger;
            });
}
```
