### ISSUE TITLE
Build Issues with v9.49.0

### ISSUE THREAD

**Issue by stevenmaguire** [laravel/framework#45890]
- Laravel Version: 9.49.0
- PHP Version: 8.2.1
- Database Driver & Version: MySQL 5.7

### Description:
When upgrading my project from 9.48.0 to 9.49.0 a new, unexpected file permissions issue prevents the project build from completing. The specific error message and truncated build log is below. The exception is being thrown during the `@php artisan package:discover --ansi` step. I've narrowed it down to the 9.49.0 particular version. Version 9.47.0 and 9.48.0 build just fine.

FWIW - this project is being built, and the exception handled, in Heroku's CI product.

The upgrade to 8.2 on 9.47.0 built and passed.
The upgrade to 9.48.0 from 9.47.0 built and passed.
The upgrade to 9.49.0 from 9.48.0 errored out.

The commit that triggered that erroring build ONLY included the laravel version bump.

<img width="1182" alt="CleanShot 2023-01-31 at 14 24 51@2x" src="https://user-images.githubusercontent.com/1851973/215874626-3bfda34c-25c8-4f2f-a833-6346e0369b25.png">

<img width="597" alt="CleanShot 2023-01-31 at 14 22 24@2x" src="https://user-images.githubusercontent.com/1851973/215874205-2d06ca43-5a84-4ec7-9a28-a23c9d760a9e.png">

```
       Generating optimized autoload files
       > Illuminate\Foundation\ComposerScripts::postAutoloadDump
       > @php artisan package:discover --ansi
       [2023-01-31 20:15:17] production.ERROR: file_put_contents(/app/bootstrap/cache/packages.phpQh1gkS): Failed to open stream: Permission denied {"exception":"[object] (ErrorException(code: 0): file_put_contents(/app/bootstrap/cache/packages.phpQh1gkS): Failed to open stream: Permission denied at /app/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:212)
       [stacktrace]
       #0 /app/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(266): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
       #1 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}()
       #2 /app/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(212): file_put_contents()
       #3 /app/vendor/laravel/framework/src/Illuminate/Foundation/PackageManifest.php(181): Illuminate\\Filesystem\\Filesystem->replace()
       #4 /app/vendor/laravel/framework/src/Illuminate/Foundation/PackageManifest.php(131): Illuminate\\Foundation\\PackageManifest->write()
       #5 /app/vendor/laravel/framework/src/Illuminate/Foundation/PackageManifest.php(107): Illuminate\\Foundation\\PackageManifest->build()
       #6 /app/vendor/laravel/framework/src/Illuminate/Foundation/PackageManifest.php(90): Illuminate\\Foundation\\PackageManifest->getManifest()
       #7 /app/vendor/laravel/framework/src/Illuminate/Foundation/PackageManifest.php(79): Illuminate\\Foundation\\PackageManifest->config()
       #8 /app/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/RegisterFacades.php(26): Illuminate\\Foundation\\PackageManifest->aliases()
       #9 /app/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(242): Illuminate\\Foundation\\Bootstrap\\RegisterFacades->bootstrap()
       #10 /app/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(383): Illuminate\\Foundation\\Application->bootstrapWith()
       #11 /app/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(153): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
       #12 /app/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle()
       #13 {main}
       "} 
       
       
       In Filesystem.php line 212:
                                                                                      
         file_put_contents(/app/bootstrap/cache/packages.phpQh1gkS): Failed to open   
         stream: Permission denied                                                    
                                                                                      
       
       Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1
 !     WARNING: A post-autoload-dump script terminated with an error
 !     ERROR: Dependency installation failed!
 !     
 !     The 'composer install' process failed with an error. The cause
 !     may be the download or installation of packages, or a pre- or
 !     post-install hook (e.g. a 'post-install-cmd' item in 'scripts')
 !     in your 'composer.json'.
 !     
 !     Typical error cases are out-of-date or missing parts of code,
 !     timeouts when making external connections, or memory limits.
 !     
 !     Check the above error output closely to determine the cause of
 !     the problem, ensure the code you're pushing is functioning
 !     properly, and that all local changes are committed correctly.
 !     
 !     For more information on builds for PHP on Heroku, refer to
 !     https://devcenter.heroku.com/articles/php-support
 !     
 !     REMINDER: the following warnings were emitted during the build;
 !     check the details above, as they may be related to this error:
 !     - A post-autoload-dump script terminated with an error
```

### Steps To Reproduce:

- Upgrade from 9.48.0 to 9.49.0
- Trigger Heroku CI build on PHP v8.2.1

**Comment by dwightwatson** [comment]
I'm seeing this too when actually building on Heroku (not using Heroku CI). I believe the relevant change is #45856. The change in permissions is preventing `package:discover` from completing.

**Comment by stevenmaguire** [comment]
Thanks for the report @dwightwatson. I appreciate that you found the possible offending commit!

**Comment by tomvo** [comment]
Adding on to this as it's also breaking builds on normal deploys (outside of Heroku)

**Comment by taylorotwell** [comment]
Reverted that change and tagged.

**Comment by taylorotwell** [comment]
Regardless, I would like to get to the bottom of what is causing that to break for some users. The current code is incorrect. The code is that is causing broken builds on Heroic (and maybe elsewhere) is the correct code as far as I can tell from all sources online and it works well on my machine and fixes the bug we were trying to fix.

**Comment by stevenmaguire** [comment]
Thanks @taylorotwell 

9.50.0 is building correctly on Heroku

<img width="455" alt="CleanShot 2023-02-01 at 09 34 36@2x" src="https://user-images.githubusercontent.com/1851973/216088294-cb017e8e-d44a-4f06-ab3a-1457f7d2e5b9.png">
