### ISSUE TITLE
TypeError: Illuminate\Bus\BatchFactory::make(): Argument #7 ($failedJobIds) must be of type array, null given

### ISSUE THREAD

**Issue by naciriii** [laravel/framework#46327]
- Laravel Version: 10.1.5
- PHP Version: 8.2.0
- Database Driver & Version: Mysql 8

### Description:
Right after the worker stopped due to a locked screen with exception: 
```php
Symfony\Component\Process\Exception\ProcessTimedOutException
```
After I restarted the worker I got the exception below:
```php
TypeError: Illuminate\Bus\BatchFactory::make(): Argument #7 ($failedJobIds) must be of type array, null given, called in **/vendor/laravel/framework/src/Illuminate/Bus/DatabaseBatchRepository.php on line 353 and defined in 

Stack trace:
#0 **/vendor/laravel/framework/src/Illuminate/Bus/DatabaseBatchRepository.php(353): Illuminate\Bus\BatchFactory->make(Object(Illuminate\Bus\DatabaseBatchRepository), '9896137d-589c-4...', 'Europace bulk i...', 7570, 3864, 1681, NULL, Array, Object(Carbon\CarbonImmutable), NULL, NULL)
#1 **/vendor/laravel/framework/src/Illuminate/Bus/DatabaseBatchRepository.php(84): Illuminate\Bus\DatabaseBatchRepository->toBatch(Object(stdClass))
#2 **/vendor/laravel/framework/src/Illuminate/Bus/Batchable.php(38): Illuminate\Bus\DatabaseBatchRepository->find('9896137d-589c-4...')
#3 **/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(191): HPE\Domain\Integrations\Europace\Jobs\EuropaceImport->batch()
#4 **/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(78): Illuminate\Queue\CallQueuedHandler->ensureSuccessfulBatchJobIsRecorded(Object(HPE\Domain\Integrations\Europace\Jobs\EuropaceImport))
#5 **/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(98): Illuminate\Queue\CallQueuedHandler->call(Object(Illuminate\Queue\Jobs\DatabaseJob), Array)
#6 **/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(425): Illuminate\Queue\Jobs\Job->fire()
#7 **/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(375): Illuminate\Queue\Worker->process('database', Object(Illuminate\Queue\Jobs\DatabaseJob), Object(Illuminate\Queue\WorkerOptions))
#8 **/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(326): Illuminate\Queue\Worker->runJob(Object(Illuminate\Queue\Jobs\DatabaseJob), 'database', Object(Illuminate\Queue\WorkerOptions))
#9 **/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(146): Illuminate\Queue\Worker->runNextJob('database', 'default', Object(Illuminate\Queue\WorkerOptions))
#10 **/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(129): Illuminate\Queue\Console\WorkCommand->runWorker('database', 'default')
#11 **/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\Queue\Console\WorkCommand->handle()
#12 **/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#13 **/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#14 **/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#15 **/vendor/laravel/framework/src/Illuminate/Container/Container.php(661): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#16 **/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\Container\Container->call(Array)
#17 **/vendor/symfony/console/Command/Command.php(312): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#18 **/vendor/laravel/framework/src/Illuminate/Console/Command.php(152): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#19 **/vendor/symfony/console/Application.php(1022): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 **/vendor/symfony/console/Application.php(314): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Queue\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 **/vendor/symfony/console/Application.php(168): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 **/vendor/laravel/framework/src/Illuminate/Console/Application.php(102): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 **/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(155): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 **/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 {main}
```
One possible fix or improvement is to cast the json decoded failed_job_ids column to an array thus even if it's a null or empty it'll return a [] and with that it should not break the batch: 
```php
 /**
     * Convert the given raw batch to a Batch object.
     *
     * @param  object  $batch
     * @return \Illuminate\Bus\Batch
     */
    protected function toBatch($batch)
    {
        return $this->factory->make(
            $this,
            $batch->id,
            $batch->name,
            (int) $batch->total_jobs,
            (int) $batch->pending_jobs,
            (int) $batch->failed_jobs,
            (array) json_decode($batch->failed_job_ids, true),
            $this->unserialize($batch->options),
            CarbonImmutable::createFromTimestamp($batch->created_at),
            $batch->cancelled_at ? CarbonImmutable::createFromTimestamp($batch->cancelled_at) : $batch->cancelled_at,
            $batch->finished_at ? CarbonImmutable::createFromTimestamp($batch->finished_at) : $batch->finished_at
        );
    }
```

### Steps To Reproduce:
This can not be reproduced easily , only if we try to simulate what happens, the moment when laravel tries to update the failed_job_ids column in job_batches table , the interruption occurs and we end up with an empty failed_job_ids colmn in job_batches table :
The interruption occurs here : 
```php
    public function incrementFailedJobs(string $batchId, string $jobId)
    {
        $values = $this->updateAtomicValues($batchId, function ($batch) use ($jobId) {
            return [
                'pending_jobs' => $batch->pending_jobs,
                'failed_jobs' => $batch->failed_jobs + 1,
                'failed_job_ids' => json_encode(array_values(array_unique(array_merge(json_decode($batch->failed_job_ids, true), [$jobId])))),
            ];
        });

        return new UpdatedBatchJobCounts(
            $values['pending_jobs'],
            $values['failed_jobs']
        );
    }
```
And more precisely here : 
```php
 protected function updateAtomicValues(string $batchId, Closure $callback)
    {
        return $this->connection->transaction(function () use ($batchId, $callback) {
            $batch = $this->connection->table($this->table)->where('id', $batchId)
                        ->lockForUpdate()
                        ->first();

            return is_null($batch) ? [] : tap($callback($batch), function ($values) use ($batchId) {
            // INTERRUPTED HERE DURING UPDATE SINCE IT'S a FULL UPDATE 
                $this->connection->table($this->table)->where('id', $batchId)->update($values);
            });
        });
    }
```

what we can simulate to test:
- Create a batch and run it through cli or whatever
- Run the queue worker for a couple of seconds (until one of the jobs was executed at least)
- stop the worker
- Check the database table and overwrite the failed_job_ids column in job_batches table and set it to NULL or empty string
- Run the queue worker
- Check the failed_jobs table or the logs file you 'll get the same exception as mentioned above in description

**Comment by mstralka** [comment]
Thanks for fixing this. Could this be backported to Laravel 8? We can't upgrade yet. If not, we'll create our own `BusServiceProvider` and `DatabaseBatchFactory` with the fix applied

**Comment by driesvints** [comment]
@mstralka Laravel v8 is closed for bug fixes, sorry.

**Comment by mstralka** [comment]
OK thanks Dries. I backported the change myself until we can upgrade!
