### ISSUE TITLE
in_array(): Argument #2 ($haystack) must be of type array, null given

### ISSUE THREAD

**Issue by philharmonie** [laravel/framework#46643]
- Laravel Version: 10.5.1
- PHP Version: 8.2.1
- Database Driver & Version: Not applicable

### Description:
I am not an php expert, that is able to debug this code on my own, but I assume, since Laravel 10 there is an Issue in `laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php`. I came around this issue using an external library [MacsiDigital/laravel-zoom](https://github.com/MacsiDigital/laravel-zoom) but the issue is not coming from that library. It just showed me the issue.

### Steps To Reproduce:
Install the library and run:
```php
$user = Zoom::user()->find('me');
dd($user->meetings());
```
: `in_array(): Argument #2 ($haystack) must be of type array, null given` for `vendor / laravel / framework / src / Illuminate / Database / Eloquent / Concerns / HasAttributes.php: 2082`.

It shows that `$this->getDates()` returns null for some reason, what is weird, as the function can't return null, from what I understand.

I believe someone who understand the framework better would understand the issue from just looking at the stack, so here it is:
```
[2023-03-31 12:27:14] staging.ERROR: in_array(): Argument #2 ($haystack) must be of type array, null given {"userId":25,"exception":"[object] (TypeError(code: 0): in_array(): Argument #2 ($haystack) must be of type array, null given at /var/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php:1078)
[stacktrace]
#0 /var/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(1078): in_array('exists', NULL, true)
#1 /var/www/vendor/macsidigital/laravel-api-client/src/Traits/HasAttributes.php(84): MacsiDigital\\API\\Support\\Resource->isDateAttribute('exists')
#2 /var/www/vendor/macsidigital/laravel-api-client/src/Support/Resource.php(168): MacsiDigital\\API\\Support\\Resource->setAttribute('exists', true)
#3 /var/www/vendor/macsidigital/laravel-api-client/src/Support/Resource.php(54): MacsiDigital\\API\\Support\\Resource->__set('exists', true)
#4 /var/www/vendor/macsidigital/laravel-api-client/src/Support/Resource.php(68): MacsiDigital\\API\\Support\\Resource->newInstance(Array, true)
#5 /var/www/vendor/macsidigital/laravel-api-client/src/Support/Relations/HasOne.php(49): MacsiDigital\\API\\Support\\Resource->newFromBuilder(Array)
#6 /var/www/vendor/macsidigital/laravel-api-client/src/Support/Relations/HasOne.php(29): MacsiDigital\\API\\Support\\Relations\\HasOne->hydrate(Array)
#7 /var/www/vendor/macsidigital/laravel-api-client/src/Support/Relations/HasOne.php(23): MacsiDigital\\API\\Support\\Relations\\HasOne->boot()
#8 /var/www/vendor/macsidigital/laravel-api-client/src/Traits/HasRelationships.php(61): MacsiDigital\\API\\Support\\Relations\\HasOne->__construct('MacsiDigital\\\\Zo...', Object(MacsiDigital\\Zoom\\Meeting), 'recurrence', 'meeting_id', Array)
#9 /var/www/vendor/macsidigital/laravel-zoom/src/Meeting.php(37): MacsiDigital\\API\\Support\\Resource->hasOne('MacsiDigital\\\\Zo...')
#10 /var/www/vendor/macsidigital/laravel-api-client/src/Traits/HasAttributes.php(130): MacsiDigital\\Zoom\\Meeting->recurrence()
#11 /var/www/vendor/macsidigital/laravel-api-client/src/Traits/HasAttributes.php(108): MacsiDigital\\API\\Support\\Resource->setRelationAttribute('recurrence', Array)
#12 /var/www/vendor/macsidigital/laravel-api-client/src/Support/Resource.php(34): MacsiDigital\\API\\Support\\Resource->setAttribute('recurrence', Array)
#13 /var/www/vendor/macsidigital/laravel-api-client/src/Support/Resource.php(21): MacsiDigital\\API\\Support\\Resource->fill(Array)
#14 /var/www/vendor/macsidigital/laravel-api-client/src/Support/Resource.php(52): MacsiDigital\\API\\Support\\Resource->__construct(Object(MacsiDigital\\Zoom\\Support\\Entry), Array)
#15 /var/www/vendor/macsidigital/laravel-api-client/src/Support/Relations/Relation.php(21): MacsiDigital\\API\\Support\\Resource->newInstance(Array)
#16 /var/www/vendor/macsidigital/laravel-api-client/src/Support/Relations/HasMany.php(98): MacsiDigital\\API\\Support\\Relations\\Relation->newRelation(Array)
#17 /var/www/vendor/macsidigital/laravel-api-client/src/Support/Relations/HasMany.php(136): MacsiDigital\\API\\Support\\Relations\\HasMany->make(Array)
#18 /var/www/app/Services/ZoomService.php(61): MacsiDigital\\API\\Support\\Relations\\HasMany->create(Array)
#19 /var/www/app/Services/ZoomService.php(75): App\\Services\\ZoomService::createMeeting(Object(Carbon\\Carbon), Object(Carbon\\Carbon), 'MPU-Wochenendse...', 0)
#20 /var/www/app/Http/Controllers/SeminarController.php(60): App\\Services\\ZoomService::makeMeetingUrl('App\\\\Models\\\\Semi...', Object(Carbon\\Carbon), Object(Carbon\\Carbon), 'MPU-Wochenendse...')
#21 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\\Http\\Controllers\\SeminarController->store(Object(App\\Http\\Requests\\StoreSeminarRequest))
#22 /var/www/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(43): Illuminate\\Routing\\Controller->callAction('store', Array)
#23 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Route.php(260): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Http\\Controllers\\SeminarController), 'store')
#24 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\Route->runController()
#25 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(798): Illuminate\\Routing\\Route->run()
#26 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#27 /var/www/app/Http/Middleware/IsAdminMiddleware.php(22): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#28 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): App\\Http\\Middleware\\IsAdminMiddleware->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#29 /var/www/vendor/laravel/framework/src/Illuminate/Auth/Middleware/EnsureEmailIsVerified.php(30): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#30 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Auth\\Middleware\\EnsureEmailIsVerified->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#31 /var/www/app/Http/Middleware/BackToPortal.php(23): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#32 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): App\\Http\\Middleware\\BackToPortal->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#33 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#34 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#35 /var/www/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(45): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#36 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Auth\\Middleware\\Authenticate->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#37 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#38 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#39 /var/www/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#40 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#41 /var/www/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#42 /var/www/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest(Object(Illuminate\\Http\\Request), Object(Illuminate\\Session\\Store), Object(Closure))
#43 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#44 /var/www/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#45 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#46 /var/www/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#47 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#48 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#49 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(799): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#50 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(776): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#51 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(740): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#52 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(729): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#53 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(200): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#54 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#55 /var/www/vendor/livewire/livewire/src/DisableBrowserCache.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#56 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Livewire\\DisableBrowserCache->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#57 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#58 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#59 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#60 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#61 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#62 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#63 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#64 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#65 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#66 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#67 /var/www/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#68 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#69 /var/www/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#70 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#71 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#72 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(175): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#73 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(144): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#74 /var/www/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#75 {main}
"} 
```

**Comment by driesvints** [comment]
There still seems to be usages of $dates in this library which Laravel v10 doesn't supports anymore

https://github.com/MacsiDigital/laravel-zoom/blob/106ecd44b77700a234a2bef8fd775ff3f7a48d2e/src/Webinar.php#L25
https://github.com/MacsiDigital/laravel-zoom/blob/106ecd44b77700a234a2bef8fd775ff3f7a48d2e/src/Meeting.php#L25

**Comment by philharmonie** [comment]
Wow that's the issue? Maybe Laravel could treat more intuitively, as this is such a new update. Thank you.

**Comment by driesvints** [comment]
If you can reproduce it on a fresh laravel app without that package feel free to post that as a new issue and I'll have a look.
