### ISSUE TITLE
App crash with invalid cookie name

### ISSUE THREAD

**Issue by TheAndrey** [laravel/framework#47913]
### Laravel Version

10.16.1

### PHP Version

8.1.21

### Description

I found that intentionally renaming the session cookie causes the application to crash. Adding **[]** at the end of cookie name causes the application to perceive the value as an array.

![2023-08-01_004556](https://github.com/laravel/framework/assets/6772452/eb7b57bb-2228-422d-a256-fd4662d3846d)

## Error log
```
Symfony\Component\HttpFoundation\Exception\BadRequestException: Input value "laravel_session" contains a non-scalar value. in file vendor\symfony\http-foundation\InputBag.php on line 37

#0 vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(160): Symfony\Component\HttpFoundation\InputBag->get()
#1 vendor\laravel\framework\src\Illuminate\Support\helpers.php(307): Illuminate\Session\Middleware\StartSession->Illuminate\Session\Middleware\{closure}()
#2 vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(161): tap()
#3 vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(57): Illuminate\Session\Middleware\StartSession->getSession()
#4 vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(180): Illuminate\Session\Middleware\StartSession->handle()
#5 vendor\laravel\framework\src\Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#6 vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(180): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle()
#7 vendor\laravel\framework\src\Illuminate\Cookie\Middleware\EncryptCookies.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#8 vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(180): Illuminate\Cookie\Middleware\EncryptCookies->handle()
#9 vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#10 vendor\laravel\framework\src\Illuminate\Routing\Router.php(800): Illuminate\Pipeline\Pipeline->then()
#11 vendor\laravel\framework\src\Illuminate\Routing\Router.php(777): Illuminate\Routing\Router->runRouteWithinStack()
#12 vendor\laravel\framework\src\Illuminate\Routing\Router.php(741): Illuminate\Routing\Router->runRoute()
#13 vendor\laravel\framework\src\Illuminate\Routing\Router.php(730): Illuminate\Routing\Router->dispatchToRoute()
#14 vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(200): Illuminate\Routing\Router->dispatch()
#15 vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(141): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}()
#16 vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#17 vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull.php(31): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
#18 vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(180): Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull->handle()
#19 vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#20 vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TrimStrings.php(40): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
#21 vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(180): Illuminate\Foundation\Http\Middleware\TrimStrings->handle()
#22 vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#23 vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(180): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle()
#24 vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance.php(86): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#25 vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(180): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance->handle()
#26 vendor\laravel\framework\src\Illuminate\Http\Middleware\HandleCors.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#27 vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(180): Illuminate\Http\Middleware\HandleCors->handle()
#28 vendor\laravel\framework\src\Illuminate\Http\Middleware\TrustProxies.php(39): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#29 vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(180): Illuminate\Http\Middleware\TrustProxies->handle()
#30 vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#31 vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(175): Illuminate\Pipeline\Pipeline->then()
#32 vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(144): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
#33 public\index.php(52): Illuminate\Foundation\Http\Kernel->handle()
#34 {main}
```

### Steps To Reproduce

1. Create a new Laravel project.
2. Start integrated or another web server.
3. Visit main page of application in browser.
4. Open DevTools and edit `laravel_session` cookie name by adding `[]` at the end.
5. Reload page. You will see an error message.

**Comment by TheAndrey** [comment]
Also I have same issue when trying to get string value from request. I'm using `Request::string()` method to get string value from request data. Using this method, I expect to get a string or an null value. When user passes an array as a value, this leads to the following error:

```
Array to string conversion at vendor/laravel/framework/src/Illuminate/Support/Stringable.php:33

#0 vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(254): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 vendor/laravel/framework/src/Illuminate/Support/Stringable.php(33): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}()
#2 vendor/laravel/framework/src/Illuminate/Support/Str.php(68): Illuminate\\Support\\Stringable->__construct()
#3 vendor/laravel/framework/src/Illuminate/Support/helpers.php(289): Illuminate\\Support\\Str::of()
#4 vendor/laravel/framework/src/Illuminate/Http/Concerns/InteractsWithInput.php(329): str()
#5 app/Http/Controllers/IndexController.php(153): Illuminate\\Http\\Request->string()
```

**Comment by crynobone** [comment]
I don't believe we should attempt to handle if the `laravel_session` cookie that has been tampered with and returning a 500 HTTP error should be sufficient in this case.

**Comment by crynobone** [comment]
1. your application log shouldn't be web accessible as described in our documentation.
2. The error page you posted above are only meant for local development. Production app will only show a generic 500 error page
