### ISSUE TITLE
Adding a macro to Response trigger a server exception in predis

### ISSUE THREAD

**Issue by frobben** [laravel/framework#48006]
### Laravel Version

9.26.1

### PHP Version

8.1

### Description

After adding a macro to the response in our AppServiceProvider as shown in the documentation, the following error was trigger with every jobs going throught Laravel Horizon. The jobs are executed normally and no error is shown on Horizon, only in laravel's logs. 

The error : 

```
ERR Error running script (call to f_0ac1d0b183ba9e097017cf4800a6a65400ae3539): @user_script:11: user_script:11: attempt to perform arithmetic on a nil value {"url":"https://www.blabla","lang":"fr","exception":"[object] (Predis\\Response\\ServerException(code: 0): ERR Error running script (call to f_0ac1d0b183ba9e097017cf4800a6a65400ae3539): @user_script:11: user_script:11: attempt to perform arithmetic on a nil value at /home/forge/blabla/vendor/predis/predis/src/Client.php:354)
[stacktrace]
#0 /home/forge/blabla/vendor/predis/predis/src/Client.php(322): Predis\\Client->onErrorResponse()
#1 /home/forge/blabla/vendor/predis/predis/src/Client.php(301): Predis\\Client->executeCommand()
#2 /home/forge/blabla/vendor/laravel/framework/src/Illuminate/Redis/Connections/Connection.php(116): Predis\\Client->__call()
#3 /home/forge/blabla/vendor/laravel/framework/src/Illuminate/Redis/Connections/Connection.php(216): Illuminate\\Redis\\Connections\\Connection->command()
#4 /home/forge/blabla/vendor/laravel/horizon/src/Repositories/RedisMetricsRepository.php(200): Illuminate\\Redis\\Connections\\Connection->__call()
#5 /home/forge/blabla/vendor/laravel/horizon/src/Listeners/UpdateJobMetrics.php(53): Laravel\\Horizon\\Repositories\\RedisMetricsRepository->incrementQueue()
#6 /home/forge/blabla/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(441): Laravel\\Horizon\\Listeners\\UpdateJobMetrics->handle()
#7 /home/forge/blabla/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(249): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}()
#8 /home/forge/blabla/vendor/laravel/horizon/src/RedisQueue.php(196): Illuminate\\Events\\Dispatcher->dispatch()
#9 /home/forge/blabla/vendor/laravel/horizon/src/RedisQueue.php(165): Laravel\\Horizon\\RedisQueue->event()
#10 /home/forge/blabla/vendor/laravel/framework/src/Illuminate/Queue/Jobs/RedisJob.php(84): Laravel\\Horizon\\RedisQueue->deleteReserved()
#11 /home/forge/blabla/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(82): Illuminate\\Queue\\Jobs\\RedisJob->delete()
#12 /home/forge/blabla/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(98): Illuminate\\Queue\\CallQueuedHandler->call()
#13 /home/forge/blabla/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(425): Illuminate\\Queue\\Jobs\\Job->fire()
#14 /home/forge/blabla/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(375): Illuminate\\Queue\\Worker->process()
#15 /home/forge/blabla/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(173): Illuminate\\Queue\\Worker->runJob()
#16 /home/forge/blabla/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(147): Illuminate\\Queue\\Worker->daemon()
#17 /home/forge/blabla/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(130): Illuminate\\Queue\\Console\\WorkCommand->runWorker()
#18 /home/forge/blabla/vendor/laravel/horizon/src/Console/WorkCommand.php(51): Illuminate\\Queue\\Console\\WorkCommand->handle()
#19 /home/forge/blabla/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Laravel\\Horizon\\Console\\WorkCommand->handle()
#20 /home/forge/blabla/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#21 /home/forge/blabla/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#22 /home/forge/blabla/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#23 /home/forge/blabla/vendor/laravel/framework/src/Illuminate/Container/Container.php(661): Illuminate\\Container\\BoundMethod::call()
#24 /home/forge/blabla/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call()
#25 /home/forge/blabla/vendor/symfony/console/Command/Command.php(312): Illuminate\\Console\\Command->execute()
#26 /home/forge/blabla/vendor/laravel/framework/src/Illuminate/Console/Command.php(153): Symfony\\Component\\Console\\Command\\Command->run()
#27 /home/forge/blabla/vendor/symfony/console/Application.php(1022): Illuminate\\Console\\Command->run()
#28 /home/forge/blabla/vendor/symfony/console/Application.php(314): Symfony\\Component\\Console\\Application->doRunCommand()
#29 /home/forge/blabla/vendor/symfony/console/Application.php(168): Symfony\\Component\\Console\\Application->doRun()
#30 /home/forge/blabla/vendor/laravel/framework/src/Illuminate/Console/Application.php(102): Symfony\\Component\\Console\\Application->run()
#31 /home/forge/blabla/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(155): Illuminate\\Console\\Application->run()
#32 /home/forge/blabla/artisan(38): Illuminate\\Foundation\\Console\\Kernel->handle()
#33 {main}
"} 
```

After surrounding the macro with `if (!App::runningInConsole())`, the error stop triggering.

### Steps To Reproduce

On a project using queue and Horizon add this bit of code to the AppServiceProvider :
```php
Response::macro('toJsend', function(array $data = [], string $status = 'success', $errorMessage = "",int $errorCode = 200) {

            if ($status !== 'success' && $status !== 'fail' && $status !== 'error') throw new Exception('Unknown status ' . $status);

            $response = [
                "status" => $status,
            ];

            if (!empty($data) || $status !== "error") {
                $response["data"] = $data;
            }

            if ($status === 'error') {
                $response['message'] = $errorMessage;
                $response['code'] = $errorCode;
            }

            return Response::make($response);
        });
```
        
And run a job in a queue to trigger the error

**Comment by crynobone** [comment]
Hi there,

Thanks for reporting the problem you are encountering, but it looks like this is a question which may be better suited for a support channel. We only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repository you can try one of the following channels:

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
