### ISSUE TITLE
PHPUnit 10.4.0 failing with Fatal error: Uncaught Illuminate\Contracts\Container\BindingResolutionException: Target [Illuminate\Contracts\Debug\ExceptionHandler] is not instantiable.

### ISSUE THREAD

**Issue by simonworkhouse** [laravel/framework#48651]
### Laravel Version

10.26.2

### PHP Version

8.2.11

### Database Driver & Version

N/A

### Description

This error triggers when using `phpunit/phpunit` version `10.4.0` but not for version `10.3.5`.

Here is an example error from our failing BitBucket Pipelines:

```
Fatal error: Uncaught Illuminate\Contracts\Container\BindingResolutionException: Target [Illuminate\Contracts\Debug\ExceptionHandler] is not instantiable. in /opt/atlassian/pipelines/agent/build/vendor/laravel/framework/src/Illuminate/Container/Container.php:1126
Stack trace:
#0 /opt/atlassian/pipelines/agent/build/vendor/laravel/framework/src/Illuminate/Container/Container.php(921): Illuminate\Container\Container->notInstantiable('Illuminate\\Cont...')
#1 /opt/atlassian/pipelines/agent/build/vendor/laravel/framework/src/Illuminate/Container/Container.php(795): Illuminate\Container\Container->build('Illuminate\\Cont...')
#2 /opt/atlassian/pipelines/agent/build/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(937): Illuminate\Container\Container->resolve('Illuminate\\Cont...', Array, true)
#3 /opt/atlassian/pipelines/agent/build/vendor/laravel/framework/src/Illuminate/Container/Container.php(731): Illuminate\Foundation\Application->resolve('Illuminate\\Cont...', Array)
#4 /opt/atlassian/pipelines/agent/build/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(922): Illuminate\Container\Container->make('Illuminate\\Cont...', Array)
#5 /opt/atlassian/pipelines/agent/build/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(287): Illuminate\Foundation\Application->make('Illuminate\\Cont...')
#6 /opt/atlassian/pipelines/agent/build/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(206): Illuminate\Foundation\Bootstrap\HandleExceptions->getExceptionHandler()
#7 /opt/atlassian/pipelines/agent/build/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(188): Illuminate\Foundation\Bootstrap\HandleExceptions->renderForConsole(Object(ArgumentCountError))
#8 /opt/atlassian/pipelines/agent/build/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(254): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(ArgumentCountError))
#9 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}(Object(ArgumentCountError))
#10 {main}
  thrown in /opt/atlassian/pipelines/agent/build/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 1126
```

### Steps To Reproduce

Will work on steps to reproduce if absolutely required.

**Comment by crynobone** [comment]
Hey there, thanks for reporting this issue.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue *as one separate commit* on the main/master branch and share the repository here?

Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com/) properly set up.

    laravel new bug-report --github="--public"

Do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by simonworkhouse** [comment]
Steps to reproduce:

```
composer create-project laravel/laravel buggy-bug
cd buggy-bug
composer require --dev brianium/paratest
php artisan test --parallel --no-coverage
```

**Comment by crynobone** [comment]
https://github.com/paratestphp/paratest/releases/tag/v7.2.9

Paratest just release a patch, can you retest again.

**Comment by simonworkhouse** [comment]
Excellent, all functioning as expected now.
