### ISSUE TITLE
Cache mocking in tests errors when using CacheBasedMaintenanceMode

### ISSUE THREAD

**Issue by ziadoz** [laravel/framework#49164]
### Laravel Version

10.34.0

### PHP Version

8.2

### Description

`Cache` facade mock expectations fail when the `CacheBasedMaintenanceMode` driver is configured.

I think the driver is configuring the cache store before the mocking occurs, which is perhaps tripping it up later in the test.

### Steps To Reproduce

This feature test will pass when in a fresh Laravel application.

```
<?php

namespace Tests\Feature;

use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\Route;
use Tests\TestCase;

class CacheTest extends TestCase
{
    public function test_cache_put(): void
    {
        Route::get('/cache-put', function () {
            Cache::put('foo', 'bar');
            return Cache::get('foo');
        });

        Cache::shouldReceive('put')->once()->with('foo', 'bar');
        Cache::shouldReceive('get')->once()->with('foo');

        $this->get('/cache-put');
    }
}
```

However, if you enable the cache-based maintenance mode in `config/app.php` like this:

```
    'maintenance' => [
        'driver' => 'cache',
        // 'store' => 'redis',
    ],
```

The first expectation fails:

```
1) Tests\Feature\CacheTest::test_cache_put
Mockery\Exception\InvalidCountException: Method put('foo', 'bar') from Mockery_0_Illuminate_Cache_CacheManager should be called
 exactly 1 times but called 0 times.

/usr/src/myapp/vendor/mockery/mockery/library/Mockery/CountValidator/Exact.php:28
/usr/src/myapp/vendor/mockery/mockery/library/Mockery/Expectation.php:298
/usr/src/myapp/vendor/mockery/mockery/library/Mockery/ExpectationDirector.php:109
/usr/src/myapp/vendor/mockery/mockery/library/Mockery/Container.php:289
/usr/src/myapp/vendor/mockery/mockery/library/Mockery/Container.php:274
/usr/src/myapp/vendor/mockery/mockery/library/Mockery.php:194
/usr/src/myapp/vendor/laravel/framework/src/Illuminate/Foundation/Testing/TestCase.php:221
```

The `logs/laravel.log` file has this in it:

```
[2023-11-28 17:54:03] testing.ERROR: Received Mockery_0_Illuminate_Cache_CacheManager::store(), but no expectations were specified {"exception":"[object] (Mockery\\Exception\\BadMethodCallException(code: 0): Received Mockery_0_Illuminate_Cache_CacheManager::store(), but no expectations were specified at /usr/src/myapp/vendor/mockery/mockery/library/Mockery/Loader/EvalLoader.php(24) : eval()'d code:923)
[stacktrace]
#0 /usr/src/myapp/vendor/mockery/mockery/library/Mockery/Loader/EvalLoader.php(24) : eval()'d code(979): Mockery_0_Illuminate_Cache_CacheManager->_mockery_handleMethodCall('store', Array)
#1 /usr/src/myapp/vendor/laravel/framework/src/Illuminate/Foundation/CacheBasedMaintenanceMode.php(95): Mockery_0_Illuminate_Cache_CacheManager->store('array')
#2 /usr/src/myapp/vendor/laravel/framework/src/Illuminate/Foundation/CacheBasedMaintenanceMode.php(75): Illuminate\\Foundation\\CacheBasedMaintenanceMode->getStore()
#3 /usr/src/myapp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(54): Illuminate\\Foundation\\CacheBasedMaintenanceMode->active()
#4 /usr/src/myapp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#5 /usr/src/myapp/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#6 /usr/src/myapp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#7 /usr/src/myapp/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#8 /usr/src/myapp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#9 /usr/src/myapp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#10 /usr/src/myapp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(175): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#11 /usr/src/myapp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(144): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#12 /usr/src/myapp/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/MakesHttpRequests.php(573): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#13 /usr/src/myapp/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/MakesHttpRequests.php(334): Illuminate\\Foundation\\Testing\\TestCase->call('GET', '/cache-put', Array, Array, Array, Array)
#14 /usr/src/myapp/tests/Feature/CacheTest.php(22): Illuminate\\Foundation\\Testing\\TestCase->get('/cache-put')
#15 /usr/src/myapp/vendor/phpunit/phpunit/src/Framework/TestCase.php(1114): Tests\\Feature\\CacheTest->test_cache_put()
#16 /usr/src/myapp/vendor/laravel/framework/src/Illuminate/Foundation/Testing/TestCase.php(174): PHPUnit\\Framework\\TestCase->runTest()
#17 /usr/src/myapp/vendor/phpunit/phpunit/src/Framework/TestCase.php(653): Illuminate\\Foundation\\Testing\\TestCase->runTest()
#18 /usr/src/myapp/vendor/phpunit/phpunit/src/Framework/TestRunner.php(103): PHPUnit\\Framework\\TestCase->runBare()
#19 /usr/src/myapp/vendor/phpunit/phpunit/src/Framework/TestCase.php(489): PHPUnit\\Framework\\TestRunner->run(Object(Tests\\Feature\\CacheTest))
#20 /usr/src/myapp/vendor/phpunit/phpunit/src/Framework/TestSuite.php(340): PHPUnit\\Framework\\TestCase->run()
#21 /usr/src/myapp/vendor/phpunit/phpunit/src/Framework/TestSuite.php(340): PHPUnit\\Framework\\TestSuite->run()
#22 /usr/src/myapp/vendor/phpunit/phpunit/src/Framework/TestSuite.php(340): PHPUnit\\Framework\\TestSuite->run()
#23 /usr/src/myapp/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(63): PHPUnit\\Framework\\TestSuite->run()
#24 /usr/src/myapp/vendor/phpunit/phpunit/src/TextUI/Application.php(189): PHPUnit\\TextUI\\TestRunner->run(Object(PHPUnit\\TextUI\\Configuration\\Configuration), Object(PHPUnit\\Runner\\ResultCache\\DefaultResultCache), Object(PHPUnit\\Framework\\TestSuite))
#25 /usr/src/myapp/vendor/phpunit/phpunit/phpunit(99): PHPUnit\\TextUI\\Application->run(Array)
#26 /usr/src/myapp/vendor/bin/phpunit(122): include('/usr/src/myapp/...')
#27 {main}
"} 
```

**Comment by crynobone** [comment]
Hey there,

While this may be a legitimate issue, can you first try posting your problem or question on one of the support channels below? If this issue can be definitively identified as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!

**Comment by ziadoz** [comment]
@crynobone I'd appreciate if someone could take another look at this, as it's definitely a bug.

[Here's a repo](https://github.com/ziadoz/laravel-cache-mocking-bug) that contains a fresh Laravel application. All I've added is a [feature test](https://github.com/ziadoz/laravel-cache-mocking-bug/blob/main/tests/Feature/CacheTest.php) which proves the bug. The [readme](https://github.com/ziadoz/laravel-cache-mocking-bug/blob/main/README.md) contains two commands to run the test with maintenance mode in `file`  (passes) and `cache` (fails) modes.
