### ISSUE TITLE
Getting Error While Installing Laravel 11 in Linux Mint Environment

### ISSUE THREAD

**Issue by arif98741** [laravel/framework#50732]
### Laravel Version

11.0.3

### PHP Version

8.2.17

### Database Driver & Version

not needed

### Description

I was trying to install latest laravel on linux vm(Linux Mint). I am getting below error while installing. Please take a look

```
PHP Fatal error:  Uncaught Error: Class "Normalizer" not found in /usr/share/php/Symfony/Component/String/AbstractUnicodeString.php:31
Stack trace:
#0 /usr/share/php/Symfony/Component/Console/Helper/ProgressBar.php(383): Symfony\Component\Console\Helper\Helper::width()
#1 /usr/share/php/Symfony/Component/Console/Helper/ProgressBar.php(322): Symfony\Component\Console\Helper\ProgressBar->setMaxSteps()
#2 /usr/share/php/Composer/Util/Loop.php(89): Symfony\Component\Console\Helper\ProgressBar->start()
#3 /usr/share/php/Composer/Installer/InstallationManager.php(497): Composer\Util\Loop->wait()
#4 /usr/share/php/Composer/Installer/InstallationManager.php(362): Composer\Installer\InstallationManager->waitOnPromises()
#5 /usr/share/php/Composer/Installer/InstallationManager.php(282): Composer\Installer\InstallationManager->downloadAndExecuteBatch()
#6 /usr/share/php/Composer/Installer.php(754): Composer\Installer\InstallationManager->execute()
#7 /usr/share/php/Composer/Installer.php(583): Composer\Installer->doInstall()
#8 /usr/share/php/Composer/Installer.php(279): Composer\Installer->doUpdate()
#9 /usr/share/php/Composer/Command/CreateProjectCommand.php(271): Composer\Installer->run()
#10 /usr/share/php/Composer/Command/CreateProjectCommand.php(150): Composer\Command\CreateProjectCommand->installProject()
#11 /usr/share/php/Symfony/Component/Console/Command/Command.php(298): Composer\Command\CreateProjectCommand->execute()
#12 /usr/share/php/Symfony/Component/Console/Application.php(1015): Symfony\Component\Console\Command\Command->run()
#13 /usr/share/php/Symfony/Component/Console/Application.php(299): Symfony\Component\Console\Application->doRunCommand()
#14 /usr/share/php/Composer/Console/Application.php(336): Symfony\Component\Console\Application->doRun()
#15 /usr/share/php/Symfony/Component/Console/Application.php(171): Composer\Console\Application->doRun()
#16 /usr/share/php/Composer/Console/Application.php(131): Symfony\Component\Console\Application->run()
#17 /usr/bin/composer(84): Composer\Console\Application->run()
#18 {main}
  thrown in /usr/share/php/Symfony/Component/String/AbstractUnicodeString.php on line 31

Fatal error: Uncaught Error: Class "Normalizer" not found in /usr/share/php/Symfony/Component/String/AbstractUnicodeString.php:31
Stack trace:
#0 /usr/share/php/Symfony/Component/Console/Helper/ProgressBar.php(383): Symfony\Component\Console\Helper\Helper::width()
#1 /usr/share/php/Symfony/Component/Console/Helper/ProgressBar.php(322): Symfony\Component\Console\Helper\ProgressBar->setMaxSteps()
#2 /usr/share/php/Composer/Util/Loop.php(89): Symfony\Component\Console\Helper\ProgressBar->start()
#3 /usr/share/php/Composer/Installer/InstallationManager.php(497): Composer\Util\Loop->wait()
#4 /usr/share/php/Composer/Installer/InstallationManager.php(362): Composer\Installer\InstallationManager->waitOnPromises()
#5 /usr/share/php/Composer/Installer/InstallationManager.php(282): Composer\Installer\InstallationManager->downloadAndExecuteBatch()
#6 /usr/share/php/Composer/Installer.php(754): Composer\Installer\InstallationManager->execute()
#7 /usr/share/php/Composer/Installer.php(583): Composer\Installer->doInstall()
#8 /usr/share/php/Composer/Installer.php(279): Composer\Installer->doUpdate()
#9 /usr/share/php/Composer/Command/CreateProjectCommand.php(271): Composer\Installer->run()
#10 /usr/share/php/Composer/Command/CreateProjectCommand.php(150): Composer\Command\CreateProjectCommand->installProject()
#11 /usr/share/php/Symfony/Component/Console/Command/Command.php(298): Composer\Command\CreateProjectCommand->execute()
#12 /usr/share/php/Symfony/Component/Console/Application.php(1015): Symfony\Component\Console\Command\Command->run()
#13 /usr/share/php/Symfony/Component/Console/Application.php(299): Symfony\Component\Console\Application->doRunCommand()
#14 /usr/share/php/Composer/Console/Application.php(336): Symfony\Component\Console\Application->doRun()
#15 /usr/share/php/Symfony/Component/Console/Application.php(171): Composer\Console\Application->doRun()
#16 /usr/share/php/Composer/Console/Application.php(131): Symfony\Component\Console\Application->run()
#17 /usr/bin/composer(84): Composer\Console\Application->run()
#18 {main}
  thrown in /usr/share/php/Symfony/Component/String/AbstractUnicodeString.php on line 31
```

### Steps To Reproduce

`composer create-project --prefer-dist laravel/laravel l11`

**Comment by crynobone** [comment]
`Normalizer` should be available with `intl` php extension or via https://github.com/symfony/polyfill-intl-normalizer

**Comment by arif98741** [comment]
> `Normalizer` should be available with `intl` php extension or via https://github.com/symfony/polyfill-intl-normalizer

I installed intl extension for php8.2
