### ISSUE TITLE
Calling Artisan::call('route:list') produces an error

### ISSUE THREAD

**Issue by espenkn** [laravel/framework#50782]
### Laravel Version

11.1.0

### PHP Version

8.2.17

### Description

When i run `Artisan::call('route:list')`

from a controller I get an error saying `Target class [web] does not exist.` but if i capture the output with a BufferedOutput the contents of output is the expected value.

Looks like the command is trying resolve the 'web' middleware and that results in a BindingResolutionException.

Is this a bug or a usage error from my side? 

### Steps To Reproduce

```php

class AdminController extends Controller
{
    function ApiTester()
    {
        Artisan::call('route:list');
        // This view will print the exception
        return view('admin.apitester');
    }
}
```

**Comment by joy2362** [comment]
@esbenp are you trying this in the web route or API route?

**Comment by espenkn** [comment]
This is in the web route

**Comment by driesvints** [comment]
I'm not sure it makes sense to call this command in that way.

**Comment by espenkn** [comment]
> I'm not sure it makes sense to call this command in that way.

So i have a web page where i can experiment with the API that works and is a great timesaver, but I thought It would be nice to list out the defined API routes in the browser so I dont have to look that up. So for my app this makes perfect sense. I do capture the output and presetnt that in my api tester page and everything works, but this also generates the exception as a side effect. I PRESENTED THE MINIMAL EXAMPLES TO REPORDUCE not what i do exactly.

**Comment by joy2362** [comment]
sorry i'm late but i think instaed of artisan route:list this following function give you everything you need " $routes = Route::getRoutes();"

**Comment by espenkn** [comment]
Thanks @joy2362 for putting me on the right path. Super happy that you commented since I had more or less given up on this.
I managed from your comment to get to this solution witch is enough for me. 
Thank you so much @joy2362

```php
$routes = Route::getRoutes();
$api_routes = $this->filterApiRoutes($routes->get());
```

```php
private function filterApiRoutes($routes)
{
    $api_routes = array_filter($routes, function($route) {
        // Check if the uri starts with the api prefix
        return substr($route->uri, 0, 4) == 'api/';
    });

    return $api_routes;
}
```

```blade
<table class="table table-striped">
    <tr>
        <th>Methods</th>
        <th>URI</th>
    </tr>
    @foreach ($routes as $route)
        <tr>
            <td>{{ implode(' | ', $route->methods) }}</td>
            <td>{{ $route->uri }}</td>
        </tr>
    @endforeach
</table>
```

**Comment by espenkn** [comment]
> try this its work for me
> 
> ```
> \Illuminate\Support\Facades\Artisan::call('route:list' , ['--path' => 'api/']);
> 
> $result = \Illuminate\Support\Facades\Artisan::output();
> 
> dd($result);
> ```

@joy2362  Thanks so much for your assistance, but unfortunately I have the same issue with that approach. The `dd` is perfect, exactly what I want, but when i pass that into a view it enters into a semi broken exception handling view where I see the error saying `Target class [web] does not exist.` but the view renders but then wrapped in the typical exception handling view. The data is there and perfect, but the page is wrapped in Laravel's handler. I can post a screen shot later if interesting.

**Comment by joy2362** [comment]
would you share your blade file so that i can check what's going wrong?

**Comment by espenkn** [comment]
@joy2362  First thing tomorrow, thanks :-)

**Comment by espenkn** [comment]
So sorry for the delay. In blade I don\t have to do anything to trigger the issue, the fact that I have call to `Artisan::call('route:list');` in the controller is all that is needed for the page to render like this screen shoot. Notice that my page renders out at the top and the exception pages gets printed bellow, all the data is in the page except that the styling from Laravel interferes a bit with the pages design.

![image](https://github.com/laravel/framework/assets/1725972/7e62fd04-af13-494e-869a-28ea99a24aba)

**Comment by joy2362** [comment]
ok i'll check and let you know it's look interesting issue to me

**Comment by LukeSavefrogs** [comment]
Same problem here

- `storage/framework/artisan.php`
    ```php
    <?php
    
    use App\Http\Controllers\ExecuteArtisanCommandController;
    use Illuminate\Foundation\Http\Middleware\VerifyCsrfToken;
    use Illuminate\Support\Facades\Route;
    
    Route::get('/execute/{command}', ExecuteArtisanCommandController::class)->withoutMiddleware([VerifyCsrfToken::class]);
    ```
- `app/Http/Controllers/ExecuteArtisanCommandController.php`:
  ```php
  <?php
  
  namespace App\Http\Controllers;
  
  use Illuminate\Http\Request;
  use Illuminate\Http\Response;
  use Illuminate\Support\Facades\Artisan;
  use Illuminate\Support\Facades\Log;
  use Symfony\Component\Console\Output\BufferedOutput;
  
  class ExecuteArtisanCommandController extends Controller
  {
      /**
       * Handle the incoming request.
       */
      public function __invoke(Request $request, Response $response, $command)
      {
          $params = $request->all();
          Log::info('Executing Artisan command: ' . $command . ' with params: ' . json_encode($params));
  
          $outputBuffer = new BufferedOutput();
          try {
              $rc = Artisan::call($command, $params, $outputBuffer);
          } catch (\Illuminate\Contracts\Container\BindingResolutionException $e) {
              Log::error('Error getting output from Artisan command: ' . $command . ' with params: ' . json_encode($params) . ' - ' . $e->getMessage());
              return response()->json([
                  'success' => false,
                  'output' => $e->getMessage(),
                  'returnCode' => -1,
              ]);
          }
          
          $output = $outputBuffer->fetch();
  
          Log::info('Artisan command output: ' . PHP_EOL . implode("\n", array_map(function ($line) {
              return '    | ' . $line;
          }, explode("\n", $output))));
  
          return response()->json(array(
              'success' => true,
              'output' => $output,
              'returnCode' => $rc,
          ));
      }
  }
  ```


Reading the log file:
```
[2025-01-09 16:27:31] local.INFO: Executing Artisan command: route:list with params: {"--except-vendor":"true"}

[2025-01-09 16:27:31] local.INFO: Artisan command output: 
    |
    |   GET|HEAD        / ..........................................................
    |   GET|HEAD        api/assignees ..............................................
    |   GET|HEAD        api/assignments ............................................
    |   GET|HEAD        api/user ...................................................
    [................. More rows .................]
    |                                                            Showing [31] routes
    |
    |
[2025-01-09 16:27:31] local.ERROR: Target class [web] does not exist. {"exception":"[object] (Illuminate\\Contracts\\Container\\BindingResolutionException(code: 0): Target class [web] does not exist. at /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:946)
[stacktrace]
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(819): Illuminate\\Container\\Container->build('web')
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1048): Illuminate\\Container\\Container->resolve('web', Array, true)
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(755): Illuminate\\Foundation\\Application->resolve('web', Array)
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1030): Illuminate\\Container\\Container->make('web', Array)
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(258): Illuminate\\Foundation\\Application->make('web')
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(216): Illuminate\\Foundation\\Http\\Kernel->terminateMiddleware(Object(Illuminate\\Http\\Request), Object(Illuminate\\Http\\JsonResponse))
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1192): Illuminate\\Foundation\\Http\\Kernel->terminate(Object(Illuminate\\Http\\Request), Object(Illuminate\\Http\\JsonResponse))
#7 /var/www/html/public/index.php(17): Illuminate\\Foundation\\Application->handleRequest(Object(Illuminate\\Http\\Request))
#8 {main}

[previous exception] [object] (ReflectionException(code: -1): Class \"web\" does not exist at /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:944)
[stacktrace]
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(944): ReflectionClass->__construct('web')
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(819): Illuminate\\Container\\Container->build('web')
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1048): Illuminate\\Container\\Container->resolve('web', Array, true)
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(755): Illuminate\\Foundation\\Application->resolve('web', Array)
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1030): Illuminate\\Container\\Container->make('web', Array)
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(258): Illuminate\\Foundation\\Application->make('web')
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(216): Illuminate\\Foundation\\Http\\Kernel->terminateMiddleware(Object(Illuminate\\Http\\Request), Object(Illuminate\\Http\\JsonResponse))
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1192): Illuminate\\Foundation\\Http\\Kernel->terminate(Object(Illuminate\\Http\\Request), Object(Illuminate\\Http\\JsonResponse))
#8 /var/www/html/public/index.php(17): Illuminate\\Foundation\\Application->handleRequest(Object(Illuminate\\Http\\Request))
#9 {main}
"}
```

## Considerations
I can confirm as said by @espenkn that the output starts as it should with the correct data, just to crash right after:
```
$ curl -s -X GET -G "http://localhost:8080/execute/route:list" -d "--except-vendor=true" | head -n 10
{"success":true,"output":"\n  GET|HEAD        \/ .......................................................... \n  GET|HEAD        api\/assignees .............................................. \n  GET|HEAD        api\/assignments ............................................ \n [................. More rows .................]\n                                                         Showing [31] routes\n\n","returnCode":0}<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta
        name="viewport"
        content="width=device-width, initial-scale=1"
    />
[...]
```
If I try with other commands it works as expected, for example `migrate:fresh`:
```
$ curl -s -X GET -G "http://localhost:8080/execute/migrate:fresh" -d "--seed=true" | head -n 10
{"success":true,"output":"\n  Dropping all tables .......................................... 308.96ms DONE\n\n   INFO  Preparing database.  \n\n  Creating migration table ...................................... 62.34ms DONE\n\n   INFO  Running migrations.  \n\n  0001_01_01_000000_create_users_table ......................... 201.69ms DONE\n  0001_01_01_000001_create_cache_table .......................... 62.07ms DONE\n  0001_01_01_000002_create_jobs_table .......................... 130.83ms DONE\n  0001_01_01_000003_create_app_tables .......................... 921.08ms DONE\n  2024_12_18_160310_create_personal_access_tokens_table ......... 75.16ms DONE\n  2024_12_31_154058_add_two_factor_columns_to_users_table ...... 152.73ms DONE\n  2024_12_31_154148_create_teams_table ......................... 100.04ms DONE\n  2024_12_31_154149_create_team_user_table ...................... 52.20ms DONE\n  2024_12_31_154150_create_team_invitations_table .............. 215.56ms DONE\n\n\n   INFO  Seeding database.  \n\n  Database\\Seeders\\UserSeeder ........................................ RUNNING  \n  Database\\Seeders\\UserSeeder .................................... 739 ms DONE  \n\n","returnCode":0}
```
