### ISSUE TITLE
Broadcast::auth($request); gives error in pusher

### ISSUE THREAD

**Issue by Ankush-Hegde** [laravel/framework#51639]
### Laravel Version

8.83.27

### PHP Version

8.2.7

### Database Driver & Version

MySql

### Description

i want to authenticate the a channel to subscribe to that perticular channel.
below is the App\Events code
```
class SendMessage implements ShouldBroadcast
{
    use Dispatchable, InteractsWithSockets, SerializesModels;

    public $message;
    public $chatId;

    /**
     * Create a new event instance.
     *
     * @return void
     */
    public function __construct(array $input)
    {
        $this->message = $input['message];
         $this->chatId = $input['chatId'];
    }

    /**
     * Get the channels the event should broadcast on.
     *
     * @return \Illuminate\Broadcasting\Channel|array
     */
    public function broadcastOn()
    {
        return new PrivateChannel('chatId_'.$this->chatId);
    }
}
```

below code is from routes/channels.php

```
Broadcast::channel('chatId_{chatId}', function () {
    return true;
});
```

this is the rout
```
Route::post('/broadcasting/auth', [Websocket::class, 'authorizePrivateChannel']);
```

it works fine when 
```
class Websocket extends Controller
{
    public function authorizePrivateChannel(Request $request)
    {
        $response = $pusher->authorizePresenceChannel(
            $channelName,
            $socketId,
            $userId,
            $presence_data
        );

        return response($response);
    }
}
```

### Steps To Reproduce

when i replace 

```
$response = $pusher->authorizePresenceChannel(
            $channelName,
            $socketId,
            $userId,
            $presence_data
        );

        return response($response);
```
with 
```
return Broadcast::auth($request);
```

i get the error

```
"error": {
        "code": "SERVER_ERROR",
        "description": "",
        "data": {
            "internal_message": ""
        },
        "stack_trace": "#0 C:\\Users\\dell\\Desktop\\chat\\karavali-karimani-backend\\vendor\\laravel\\framework\\src\\Illuminate\\Broadcasting\\BroadcastManager.php(384): Illuminate\\Broadcasting\\Broadcasters\\PusherBroadcaster->auth()\n#1 C:\\Users\\dell\\Desktop\\chat\\karavali-karimani-backend\\vendor\\laravel\\framework\\src\\Illuminate\\Support\\Facades\\Facade.php(261): Illuminate\\Broadcasting\\BroadcastManager->__call()\n#2 
```

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!
