### ISSUE TITLE
Can't exclude route from CSRF validation when route is defined in `then`

### ISSUE THREAD

**Issue by edalzell** [laravel/framework#52210]
### Laravel Version

11.16.0

### PHP Version

8.3.9

### Database Driver & Version

sqlite

### Description

If you define a route in an additional routes file and load it via `then` in `app.php`, you can't exclude that route from csrf by name.

### Steps To Reproduce

In `routes/webhooks.php`:

```php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/foo', function () {
    return view('welcome');
})->name('foo');
```

In app.php:

```php
<?php

use Illuminate\Foundation\Application;
use Illuminate\Foundation\Configuration\Exceptions;
use Illuminate\Foundation\Configuration\Middleware;
use Illuminate\Support\Facades\Route;

return Application::configure(basePath: dirname(__DIR__))
    ->withRouting(
        web: __DIR__.'/../routes/web.php',
        commands: __DIR__.'/../routes/console.php',
        health: '/up',
        then: function () {
            Route::prefix('foo')->group(base_path('routes/webhooks.php'));
        }
    )
    ->withMiddleware(function (Middleware $middleware) {
        $middleware->validateCsrfTokens(except: [route('foo')]);
    })
    ->withExceptions(function (Exceptions $exceptions) {
        //
    })->create();
```

When you load the site you get an error:

```
Fatal error: Uncaught ReflectionException: Class "config" does not exist in /Users/erin/Sites/route/vendor/laravel/framework/src/Illuminate/Container/Container.php:938 Stack trace: #0 /Users/erin/Sites/route/vendor/laravel/framework/src/Illuminate/Container/Container.php(938): ReflectionClass->__construct('config') #1 /Users/erin/Sites/route/vendor/laravel/framework/src/Illuminate/Container/Container.php(815): Illuminate\Container\Container->build('config') #2 /Users/erin/Sites/route/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1046): Illuminate\Container\Container->resolve('config', Array, true) #3 /Users/erin/Sites/route/vendor/laravel/framework/src/Illuminate/Container/Container.php(751): Illuminate\Foundation\Application->resolve('config', Array) #4 /Users/erin/Sites/route/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1028): Illuminate\Container\Container->make('config', Array) #5 /Users/erin/Sites/route/vendor/laravel/framework/src/Illuminate/Container/Container.php(1570): Illuminate\Foundation\Application->make('config') #6 /Users/erin/Sites/route/vendor/laravel/framework/src/Illuminate/Routing/RoutingServiceProvider.php(67): Illuminate\Container\Container->offsetGet('config') #7 /Users/erin/Sites/route/vendor/laravel/framework/src/Illuminate/Container/Container.php(931): Illuminate\Routing\RoutingServiceProvider->Illuminate\Routing\{closure}(Object(Illuminate\Foundation\Application), Array) #8 /Users/erin/Sites/route/vendor/laravel/framework/src/Illuminate/Container/Container.php(815): Illuminate\Container\Container->build(Object(Closure)) #9 /Users/erin/Sites/route/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1046): Illuminate\Container\Container->resolve('url', Array, true) #10 /Users/erin/Sites/route/vendor/laravel/framework/src/Illuminate/Container/Container.php(751): Illuminate\Foundation\Application->resolve('url', Array) #11 /Users/erin/Sites/route/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1028): Illuminate\Container\Container->make('url', Array) #12 /Users/erin/Sites/route/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(124): Illuminate\Foundation\Application->make('url', Array) #13 /Users/erin/Sites/route/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(838): app('url') #14 /Users/erin/Sites/route/bootstrap/app.php(18): route('foo') #15 /Users/erin/Sites/route/vendor/laravel/framework/src/Illuminate/Foundation/Configuration/ApplicationBuilder.php(250): {closure}(Object(Illuminate\Foundation\Configuration\Middleware)) #16 /Users/erin/Sites/route/vendor/laravel/framework/src/Illuminate/Container/Container.php(1418): Illuminate\Foundation\Configuration\ApplicationBuilder->Illuminate\Foundation\Configuration\{closure}(Object(Illuminate\Foundation\Http\Kernel), Object(Illuminate\Foundation\Application)) #17 /Users/erin/Sites/route/vendor/laravel/framework/src/Illuminate/Container/Container.php(1354): Illuminate\Container\Container->fireCallbackArray(Object(Illuminate\Foundation\Http\Kernel), Array) #18 /Users/erin/Sites/route/vendor/laravel/framework/src/Illuminate/Container/Container.php(1340): Illuminate\Container\Container->fireAfterResolvingCallbacks('Illuminate\\Cont...', Object(Illuminate\Foundation\Http\Kernel)) #19 /Users/erin/Sites/route/vendor/laravel/framework/src/Illuminate/Container/Container.php(833): Illuminate\Container\Container->fireResolvingCallbacks('Illuminate\\Cont...', Object(Illuminate\Foundation\Http\Kernel)) #20 /Users/erin/Sites/route/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1046): Illuminate\Container\Container->resolve('Illuminate\\Cont...', Array, true) #21 /Users/erin/Sites/route/vendor/laravel/framework/src/Illuminate/Container/Container.php(751): Illuminate\Foundation\Application->resolve('Illuminate\\Cont...', Array) #22 /Users/erin/Sites/route/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1028): Illuminate\Container\Container->make('Illuminate\\Cont...', Array) #23 /Users/erin/Sites/route/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1186): Illuminate\Foundation\Application->make('Illuminate\\Cont...') #24 /Users/erin/Sites/route/public/index.php(17): Illuminate\Foundation\Application->handleRequest(Object(Illuminate\Http\Request)) #25 /Applications/Herd.app/Contents/Resources/valet/server.php(155): require('/Users/erin/Sit...') #26 {main} Next Illuminate\Contracts\Container\BindingResolutionException: Target class [config] does not exist. in /Users/erin/Sites/route/vendor/laravel/framework/src/Illuminate/Container/Container.php:940 Stack trace: #0 /Users/erin/Sites/route/vendor/laravel/framework/src/Illuminate/Container/Container.php(815): Illuminate\Container\Container->build('config') #1 /Users/erin/Sites/route/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1046): Illuminate\Container\Container->resolve('config', Array, true) #2 /Users/erin/Sites/route/vendor/laravel/framework/src/Illuminate/Container/Container.php(751): Illuminate\Foundation\Application->resolve('config', Array) #3 /Users/erin/Sites/route/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1028): Illuminate\Container\Container->make('config', Array) #4 /Users/erin/Sites/route/vendor/laravel/framework/src/Illuminate/Container/Container.php(1570): Illuminate\Foundation\Application->make('config') #5 /Users/erin/Sites/route/vendor/laravel/framework/src/Illuminate/Routing/RoutingServiceProvider.php(67): Illuminate\Container\Container->offsetGet('config') #6 /Users/erin/Sites/route/vendor/laravel/framework/src/Illuminate/Container/Container.php(931): Illuminate\Routing\RoutingServiceProvider->Illuminate\Routing\{closure}(Object(Illuminate\Foundation\Application), Array) #7 /Users/erin/Sites/route/vendor/laravel/framework/src/Illuminate/Container/Container.php(815): Illuminate\Container\Container->build(Object(Closure)) #8 /Users/erin/Sites/route/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1046): Illuminate\Container\Container->resolve('url', Array, true) #9 /Users/erin/Sites/route/vendor/laravel/framework/src/Illuminate/Container/Container.php(751): Illuminate\Foundation\Application->resolve('url', Array) #10 /Users/erin/Sites/route/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1028): Illuminate\Container\Container->make('url', Array) #11 /Users/erin/Sites/route/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(124): Illuminate\Foundation\Application->make('url', Array) #12 /Users/erin/Sites/route/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(838): app('url') #13 /Users/erin/Sites/route/bootstrap/app.php(18): route('foo') #14 
```

**Comment by edalzell** [comment]
Ya I know the work-around but it seems to defeat the purpose of defining a name, if you can't use it.

**Comment by edalzell** [comment]
> You are trying to roof a house that hasn’t been built.

Ha, made me laugh

**Comment by crynobone** [comment]
https://laravel.com/docs/10.x/csrf#csrf-excluding-uris

The feature never accepted route so this doesn't qualify as a bug.
