### ISSUE TITLE
No automatic database reconnect on "Operation now in progress" query error

### ISSUE THREAD

**Issue by thbley** [laravel/framework#52759]
### Laravel Version

11.21.0

### PHP Version

8.3.10

### Database Driver & Version

'driver' => 'mysql', MariaDB 10.1.48

### Description

```
PDOException: SQLSTATE[HY000] [2002] Operation now in progress in vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:65
Stack trace:
#0 vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(65): PDO->__construct()
#1 vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(44): Illuminate\Database\Connectors\Connector->createPdoConnection()
#2 vendor/laravel/framework/src/Illuminate/Database/Connectors/MySqlConnector.php(24): Illuminate\Database\Connectors\Connector->createConnection()
#3 vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php(185): Illuminate\Database\Connectors\MySqlConnector->connect()
#4 [internal function]: Illuminate\Database\Connectors\ConnectionFactory->Illuminate\Database\Connectors\{closure}()
#5 vendor/laravel/framework/src/Illuminate/Database/Connection.php(1231): call_user_func()
#6 vendor/laravel/framework/src/Illuminate/Database/Connection.php(1267): Illuminate\Database\Connection->getPdo()
#7 vendor/laravel/framework/src/Illuminate/Database/Connection.php(512): Illuminate\Database\Connection->getReadPdo()
#8 vendor/laravel/framework/src/Illuminate/Database/Connection.php(407): Illuminate\Database\Connection->getPdoForSelect()
#9 vendor/laravel/framework/src/Illuminate/Database/Connection.php(812): Illuminate\Database\Connection->Illuminate\Database\{closure}()
#10 vendor/laravel/framework/src/Illuminate/Database/Connection.php(779): Illuminate\Database\Connection->runQueryCallback()
#11 vendor/laravel/framework/src/Illuminate/Database/Connection.php(398): Illuminate\Database\Connection->run()
#12 vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3088): Illuminate\Database\Connection->select()
#13 vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3073): Illuminate\Database\Query\Builder->runSelect()
#14 vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3661): Illuminate\Database\Query\Builder->Illuminate\Database\Query\{closure}()
#15 vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3072): Illuminate\Database\Query\Builder->onceWithColumns()
#16 vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(759): Illuminate\Database\Query\Builder->get()
#17 vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(741): Illuminate\Database\Eloquent\Builder->getModels()
```

Versions:
"name": "laravel/horizon",
"version": "v5.27.1",

Related: https://laracasts.com/discuss/channels/laravel/operation-now-in-progress-errors-on-redismysql-connections

My suggestion:

extend vendor/laravel/framework/src/Illuminate/Database/DetectsLostConnections.php with "SQLSTATE[HY000] [2002] Operation now in progress"

### Steps To Reproduce

Not directly reproducable, happens from time to time in horizon jobs.

**Comment by buismaarten** [comment]
You can open a PR instead of an issue and see what happens

**Comment by thbley** [comment]
Sorry, I can't contribute code at the moment due to legal restrictions.

**Comment by webartisan10** [comment]
https://github.com/laravel/framework/pull/52805

**Comment by GrahamCampbell** [comment]
I believe this issue can be closed. The PR did not properly preference the issue (https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests), thus it did not close automatically.
