### ISSUE TITLE
Laravel app crashes when I call fwrite for one string specifically

### ISSUE THREAD

**Issue by FabioNevesRezende** [laravel/framework#52886]
### Laravel Version

11.9

### PHP Version

8.3.11

### Description

(this discussion started in [stackoverflow](https://stackoverflow.com/q/79010436/2414842) and I decided to move it here)
I have this helper function I use to log (into the serverside output) some events in my laravel app and is just working fine, but for a reason I can't understand it fails with this specific case:

    if(!defined('STDIN'))  define('STDIN',  fopen('php://stdin',  'rb'));
    if(!defined('STDOUT')) define('STDOUT', fopen('php://stdout', 'wb'));
    if(!defined('STDERR')) define('STDERR', fopen('php://stderr', 'wb'));

    class Funcoes{
     public static function consolelog(...$args): void{
        foreach ($args as $arg) {
            if (is_object($arg) || is_array($arg) || is_resource($arg)) {
                $output = print_r($arg, true);
            } else {
                $output = (string) $arg;
            }

            fwrite(STDOUT, $output . "\n");
         }
     }
    }

In a middleware I verify a case where I want to abort a request but instead the app is just crashing when I try to print the string `" URI:"` and it makes no sense to me why is it happening just for this case:

    Funcoes::consolelog("Requisição inválida, headers:\n");
    Funcoes::consolelog(getallheaders());
    Funcoes::consolelog(" Remote addr:");
    Funcoes::consolelog($_SERVER['REMOTE_ADDR']);
    Funcoes::consolelog(" URI:"); // it fails here without even printing the string
    Funcoes::consolelog($_SERVER['REQUEST_URI']);
    abort(400);

Error message:

>In ServeCommand.php line 381:
                         
  >Undefined array key 1 

Apparently the error is being caused by [this part](https://github.com/laravel/framework/blob/11.x/src/Illuminate/Foundation/Console/ServeCommand.php#L305) of the code 

The full stack trace in laravel logs:

    [2024-09-21 20:52:46] local.ERROR: Undefined array key 1 {"exception":"[object] (ErrorException(code: 0): Undefined array key 1 at /home/user/src/LaravelProj/vendor/laravel/framework/src/Illuminate/Foundation/Console/ServeCommand.php:381)
    [stacktrace]
    #0 /home/user/src/LaravelProj/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(256): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
    #1 /home/user/src/LaravelProj/vendor/laravel/framework/src/Illuminate/Foundation/Console/ServeCommand.php(381): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}()
    #2 /home/user/src/LaravelProj/vendor/laravel/framework/src/Illuminate/Foundation/Console/ServeCommand.php(306): Illuminate\\Foundation\\Console\\ServeCommand->getRequestPortFromLine()
    #3 /home/user/src/LaravelProj/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(257): Illuminate\\Foundation\\Console\\ServeCommand->Illuminate\\Foundation\\Console\\{closure}()
    #4 /home/user/src/LaravelProj/vendor/laravel/framework/src/Illuminate/Foundation/Console/ServeCommand.php(279): Illuminate\\Support\\Collection->each()
    #5 /home/user/src/LaravelProj/vendor/laravel/framework/src/Illuminate/Foundation/Console/ServeCommand.php(261): Illuminate\\Foundation\\Console\\ServeCommand->flushOutputBuffer()
    #6 /home/user/src/LaravelProj/vendor/symfony/process/Process.php(1306): Illuminate\\Foundation\\Console\\ServeCommand->Illuminate\\Foundation\\Console\\{closure}()
    #7 /home/user/src/LaravelProj/vendor/symfony/process/Process.php(1417): Symfony\\Component\\Process\\Process->Symfony\\Component\\Process\\{closure}()
    #8 /home/user/src/LaravelProj/vendor/symfony/process/Process.php(1337): Symfony\\Component\\Process\\Process->readPipes()
    #9 /home/user/src/LaravelProj/vendor/symfony/process/Process.php(860): Symfony\\Component\\Process\\Process->updateStatus()
    #10 /home/user/src/LaravelProj/vendor/laravel/framework/src/Illuminate/Foundation/Console/ServeCommand.php(105): Symfony\\Component\\Process\\Process->isRunning()
    #11 /home/user/src/LaravelProj/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Foundation\\Console\\ServeCommand->handle()
    #12 /home/user/src/LaravelProj/vendor/laravel/framework/src/Illuminate/Container/Util.php(43): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
    #13 /home/user/src/LaravelProj/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(95): Illuminate\\Container\\Util::unwrapIfClosure()
    #14 /home/user/src/LaravelProj/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
    #15 /home/user/src/LaravelProj/vendor/laravel/framework/src/Illuminate/Container/Container.php(690): Illuminate\\Container\\BoundMethod::call()
    #16 /home/user/src/LaravelProj/vendor/laravel/framework/src/Illuminate/Console/Command.php(213): Illuminate\\Container\\Container->call()
    #17 /home/user/src/LaravelProj/vendor/symfony/console/Command/Command.php(279): Illuminate\\Console\\Command->execute()
    #18 /home/user/src/LaravelProj/vendor/laravel/framework/src/Illuminate/Console/Command.php(182): Symfony\\Component\\Console\\Command\\Command->run()
    #19 /home/user/src/LaravelProj/vendor/symfony/console/Application.php(1045): Illuminate\\Console\\Command->run()
    #20 /home/user/src/LaravelProj/vendor/symfony/console/Application.php(316): Symfony\\Component\\Console\\Application->doRunCommand()
    #21 /home/user/src/LaravelProj/vendor/symfony/console/Application.php(167): Symfony\\Component\\Console\\Application->doRun()
    #22 /home/user/src/LaravelProj/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(197): Symfony\\Component\\Console\\Application->run()
    #23 /home/user/src/LaravelProj/artisan(33): Illuminate\\Foundation\\Console\\Kernel->handle()
    #24 {main}

### Steps To Reproduce

- Create a brand new laravel app

`     composer create-project laravel/laravel Imageboard`
    
    
 - Add the following Service Providers and Helper functions:
 
 **app/Providers/FuncoesProvider.php:**
```
<?php

namespace App\Providers;

use Illuminate\Support\ServiceProvider;

if(!defined('STDIN'))  define('STDIN',  fopen('php://stdin',  'rb'));
if(!defined('STDOUT')) define('STDOUT', fopen('php://stdout', 'wb'));
if(!defined('STDERR')) define('STDERR', fopen('php://stderr', 'wb'));

class FuncoesProvider extends ServiceProvider
{
    /**
     * Register services.
     */
    public function register(): void
    {
        $this->app->bind('App\Helpers\Funcoes', function () {
            return new \App\Helpers\Funcoes();
        });
    }

    /**
     * Bootstrap services.
     */
    public function boot(): void
    {
        //
    }
}
```

**app/Helpers/Funcoes.php**
```

<?php

namespace App\Helpers;

class Funcoes
{
    public static function consolelog(...$args): void{
        foreach ($args as $arg) {
            if (is_object($arg) || is_array($arg) || is_resource($arg)) {
                $output = print_r($arg, true);
            } else {
                $output = (string) $arg;
            }

            fwrite(STDOUT, $output . "\n");
         }
    }
}

```

Call the consolelog function from any controller with " URI:" as a parameter:

`Funcoes::consolelog(" URI:");`

**Expected result:**
 Being able to call fwrite with any string I want
 
**Actual result:**
App crashes and stops (stack trace in description), I can't print the "URI:" string, it makes me think now if there are other strings that can give me errors and make my app crash unexpectedly

**Comment by crynobone** [comment]
Hey there,

While this may be a legitimate issue, can you first try posting your problem or question on one of the support channels below? If this issue can be definitively identified as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!

**Comment by FabioNevesRezende** [comment]
@crynobone I did posted on stackoverflow, I even posted the link https://stackoverflow.com/q/79010436/2414842

**Comment by halfer** [comment]
I am getting this also on Laravel 10.45.1, in `artisan serve`, but only under heavy load. It is highly unpredictable. It usually appears of a few minutes of browser tests:

```
  2024-10-03 20:53:36 ................................................... ~ 0s
  2024-10-03 20:53:36 /frameworks/flowbite.min.js ....................... ~ 0s
  2024-10-03 20:53:36 ................................................... ~ 1s
  2024-10-03 20:53:37 /build/assets/app-Cru4FPcD.css .................... ~ 0s
  2024-10-03 20:53:37 /build/assets/app-CL4i2NMQ.js ..................... ~ 0s
  2024-10-03 20:53:37 /frameworks/flowbite.min.js ....................... ~ 0s
  2024-10-03 20:53:37 /vendor/livewire/livewire.min.js?id=923613aa ...... ~ 0s
  2024-10-03 20:53:37 ................................................... ~ 0s
  2024-10-03 20:53:37 /build/assets/app-Cru4FPcD.css .................... ~ 0s
  2024-10-03 20:53:37 /build/assets/app-CL4i2NMQ.js ..................... ~ 0s
  2024-10-03 20:53:37 /frameworks/flowbite.min.js ....................... ~ 0s
  2024-10-03 20:53:37 /vendor/livewire/livewire.min.js?id=923613aa ...... ~ 0s
  2024-10-03 20:53:37 /images/information.png ........................... ~ 0s
  2024-10-03 20:53:37 ................................................... ~ 0s
  2024-10-03 20:53:37 /images/arrow-rotate-clockwise-icon.png ........... ~ 0s

In ServeCommand.php line 278:
                         
  Undefined array key 0  
```

This refers to this line in the serve logic:

```
            } elseif (str($line)->contains(' Closing')) {
                $requestPort = $this->getRequestPortFromLine($line);

                if (empty($this->requestsPool[$requestPort])) {
                    return;
                }

                [$startDate, $file] = $this->requestsPool[$requestPort]; // <-- line 278

                $formattedStartedAt = $startDate->format('Y-m-d H:i:s');

                unset($this->requestsPool[$requestPort]);
```

I wonder, should we just use the PHP internal server?

**Comment by halfer** [comment]
It looks like `$requestPort` could be derived wrongly from `getRequestPortFromLine`, so I wonder if maybe `$line` causes it to malform. Either that, or `$this->requestsPool` is subject to some kind of race condition, and thus it is already `unset()` by the time it does the lookup in L278. @crynobone, do you think think the above information provides enough information to debug this?

**Comment by halfer** [comment]
> I wonder, should we just use the PHP internal server?

Answering my own question here, no; Livewire seems to fail with this.

**Comment by halfer** [comment]
Darn, I was hoping bcc30449455e was going to sort it out for me, in a Laravel 10->11 upgrade, but I still get a crash. I will look tomorrow to see what the exact nature is; I still suspect the `serve` command.
