### ISSUE TITLE
Upgrading to Laravel 11, using scheme to obtain column information reports an error

### ISSUE THREAD

**Issue by xyj2156** [laravel/framework#53220]
### Laravel Version

11.28.0

### PHP Version

8.2.17

### Database Driver & Version

Mysql 5.6 for AliYun RDS rds_20200430

### error message
```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'generation_expression' in 'field list' (Connection: mysql_api, SQL: select column_name as `name`, data_type as `type_name`, column_type as `type`, collation_name as `collation`, is_nullable as `nullable`, column_default as `default`, column_comment as `comment`, generation_expression as `expression`, extra as `extra` from information_schema.columns where table_schema = 'database' and table_name = 'table' order by ordinal_position asc) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'generation_expression' in 'field list' (Connection: mysql_api, SQL: select column_name as `name`, data_type as `type_name`, column_type as `type`, collation_name as `collation`, is_nullable as `nullable`, column_default as `default`, column_comment as `comment`, generation_expression as `expression`, extra as `extra` from information_schema.columns where table_schema = 'database' and table_name = 'table' order by ordinal_position asc) at /data/wwwroot/SuNong-Laravel/vendor/laravel/framework/src/Illuminate/Database/Connection.php:825)
```

### stacktrace
```
#1 /data/wwwroot/vendor/laravel/framework/src/Illuminate/Database/Connection.php(398): Illuminate\\Database\\Connection->run('select column_n...', Array, Object(Closure))
#2 /data/wwwroot/vendor/laravel/framework/src/Illuminate/Database/Connection.php(385): Illuminate\\Database\\Connection->select('select column_n...', Array, false)
#3 /data/wwwroot/vendor/laravel/framework/src/Illuminate/Database/Schema/MySqlBuilder.php(88): Illuminate\\Database\\Connection->selectFromWriteConnection('select column_n...')
#4 /data/wwwroot/vendor/laravel/framework/src/Illuminate/Database/Schema/Builder.php(312): Illuminate\\Database\\Schema\\MySqlBuilder->getColumns('sn_department')
#5 /data/wwwroot/app/Http/Controllers/Manage/SubmitSystem/Tools/DataBaseController.php(235): Illuminate\\Database\\Schema\\Builder->getColumnListing('department')
#6 /data/wwwroot/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\\Http\\Controllers\\Manage\\SubmitSystem\\Tools\\DataBaseController->query(Object(Illuminate\\Http\\Request), NULL)
#7 /data/wwwroot/app/Http/Controllers/Controller.php(56): Illuminate\\Routing\\Controller->callAction('query', Array)

```

### Steps To Reproduce

``` php
<?php

use Illuminate\Support\Facades\Schema;

$scheme = Scheme::connection('mysql');

$columns  = $scheme -> getColumnListing('table');
```

**Comment by hafezdivandari** [comment]
Laravel 8.x+ requires MySQL 5.7+

**Comment by xyj2156** [comment]
thank you
