### ISSUE TITLE
Sessions stored in database causes exception

### ISSUE THREAD

**Issue by G1FEF** [laravel/framework#53697]
### Laravel Version

11.33.2

### PHP Version

8.2.26

### Database Driver & Version

MariaDB 10.11.6

### Description

When using the database backend to store sessions and the remote client's "user agent" field contains invalid characters, i.e. not unicode, this causes a PDOException(code: 22007) in laravel/framework/src/Illuminate/Database/Connection.php:596

Stack trace:

```
[2024-11-27 05:36:52] local.ERROR: SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\xA1\xB1)' for column `portal`.`sessions`.`user_agent` at row 1 (Connection: mariadb, SQL: update `sessions` set `payload` = YTozOntzOjY6Il90b2tlbiI7czo0MDoiZGFDbzFPTHhmd0lHSll3OXR3b3pEZEp4NEJwRE5razYxbklpYTF2byI7czo5OiJfcHJldmlvdXMiO2E6MTp7czozOiJ1cmwiO3M6MjM6Imh0dHBzOi8vcG9ydGFsLmFtcHIub3JnIjt9czo2OiJfZmxhc2giO2E6Mjp7czozOiJvbGQiO2E6MDp7fXM6MzoibmV3IjthOjA6e319fQ==, `last_activity` = 1732685812, `user_id` = ?, `ip_address` = 143.92.34.18, `user_agent` = Mozilla/5.0 (compatible; Yahoo! Slurp China; http://misc.yahoo.com.cn/help.html??) where `id` = 23dKHUPVlTSY6LScSWxDHtPSyVbDQctwma9ghOiw) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 22007): SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\\xA1\\xB1)' for column `portal`.`sessions`.`user_agent` at row 1 (Connection: mariadb, SQL: update `sessions` set `payload` = YTozOntzOjY6Il90b2tlbiI7czo0MDoiZGFDbzFPTHhmd0lHSll3OXR3b3pEZEp4NEJwRE5razYxbklpYTF2byI7czo5OiJfcHJldmlvdXMiO2E6MTp7czozOiJ1cmwiO3M6MjM6Imh0dHBzOi8vcG9ydGFsLmFtcHIub3JnIjt9czo2OiJfZmxhc2giO2E6Mjp7czozOiJvbGQiO2E6MDp7fXM6MzoibmV3IjthOjA6e319fQ==, `last_activity` = 1732685812, `user_id` = ?, `ip_address` = 143.92.34.18, `user_agent` = Mozilla/5.0 (compatible; Yahoo! Slurp China; http://misc.yahoo.com.cn/help.html��) where `id` = 23dKHUPVlTSY6LScSWxDHtPSyVbDQctwma9ghOiw) at /home/webhosts/portal/https/vendor/laravel/framework/src/Illuminate/Database/Connection.php:825)
[stacktrace]
#0 /home/webhosts/portal/https/vendor/laravel/framework/src/Illuminate/Database/Connection.php(779): Illuminate\\Database\\Connection->runQueryCallback()
#1 /home/webhosts/portal/https/vendor/laravel/framework/src/Illuminate/Database/Connection.php(584): Illuminate\\Database\\Connection->run()
#2 /home/webhosts/portal/https/vendor/laravel/framework/src/Illuminate/Database/Connection.php(536): Illuminate\\Database\\Connection->affectingStatement()
#3 /home/webhosts/portal/https/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3866): Illuminate\\Database\\Connection->update()
#4 /home/webhosts/portal/https/vendor/laravel/framework/src/Illuminate/Session/DatabaseSessionHandler.php(173): Illuminate\\Database\\Query\\Builder->update()
#5 /home/webhosts/portal/https/vendor/laravel/framework/src/Illuminate/Session/DatabaseSessionHandler.php(140): Illuminate\\Session\\DatabaseSessionHandler->performUpdate()
#6 /home/webhosts/portal/https/vendor/laravel/framework/src/Illuminate/Session/Store.php(172): Illuminate\\Session\\DatabaseSessionHandler->write()
#7 /home/webhosts/portal/https/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(245): Illuminate\\Session\\Store->save()
#8 /home/webhosts/portal/https/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(130): Illuminate\\Session\\Middleware\\StartSession->saveSession()
#9 /home/webhosts/portal/https/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#10 /home/webhosts/portal/https/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Session\\Middleware\\StartSession->handle()
#11 /home/webhosts/portal/https/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#12 /home/webhosts/portal/https/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#13 /home/webhosts/portal/https/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(75): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#14 /home/webhosts/portal/https/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#15 /home/webhosts/portal/https/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#16 /home/webhosts/portal/https/vendor/laravel/framework/src/Illuminate/Routing/Router.php(807): Illuminate\\Pipeline\\Pipeline->then()
#17 /home/webhosts/portal/https/vendor/laravel/framework/src/Illuminate/Routing/Router.php(786): Illuminate\\Routing\\Router->runRouteWithinStack()
#18 /home/webhosts/portal/https/vendor/laravel/framework/src/Illuminate/Routing/Router.php(750): Illuminate\\Routing\\Router->runRoute()
#19 /home/webhosts/portal/https/vendor/laravel/framework/src/Illuminate/Routing/Router.php(739): Illuminate\\Routing\\Router->dispatchToRoute()
#20 /home/webhosts/portal/https/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(201): Illuminate\\Routing\\Router->dispatch()
#21 /home/webhosts/portal/https/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#22 /home/webhosts/portal/https/app/Http/Middleware/HSTS.php(13): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#23 /home/webhosts/portal/https/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): App\\Http\\Middleware\\HSTS->handle()
#24 /home/webhosts/portal/https/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#25 /home/webhosts/portal/https/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#26 /home/webhosts/portal/https/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#27 /home/webhosts/portal/https/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#28 /home/webhosts/portal/https/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(51): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#29 /home/webhosts/portal/https/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#30 /home/webhosts/portal/https/vendor/laravel/framework/src/Illuminate/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#31 /home/webhosts/portal/https/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\ValidatePostSize->handle()
#32 /home/webhosts/portal/https/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(110): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#33 /home/webhosts/portal/https/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#34 /home/webhosts/portal/https/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#35 /home/webhosts/portal/https/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\HandleCors->handle()
#36 /home/webhosts/portal/https/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(58): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#37 /home/webhosts/portal/https/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#38 /home/webhosts/portal/https/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#39 /home/webhosts/portal/https/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Pipeline\\Pipeline->then()
#40 /home/webhosts/portal/https/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#41 /home/webhosts/portal/https/public/index.php(51): Illuminate\\Foundation\\Http\\Kernel->handle()
#42 {main}
```

### Steps To Reproduce

Setup a Laravel app to use the database storage for sessions and wait for an invalid user agent, e.g:

`Mozilla/5.0 (compatible; Yahoo! Slurp China; http://misc.yahoo.com.cn/help.html��`

**Comment by crynobone** [comment]
Seems like `mariadb` was configured with an incorrect collation/charset.

**Comment by crynobone** [comment]
Hey there,

While this may be a legitimate issue, can you first try posting your problem or question on one of the support channels below? If this issue can be definitively identified as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
