### ISSUE TITLE
Connection made with `DB::build()` fails to reconnect

### ISSUE THREAD

**Issue by sebdesign** [laravel/framework#53886]
### Laravel Version

11.35.1

### PHP Version

8.3.13

### Database Driver & Version

MariaDB 10.11.10

### Description

When I make a database connection using `DB::build()`, if that connection fails due to a lost connection, the DatabaseManager tries to reconnect but I receive the following error.

```log
[2024-12-13 15:40:49] production.ERROR: Database connection [projects] not configured. {"userId":1,"exception":"[object] (InvalidArgumentException(code: 0): Database connection [projects] not configured. at vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php:205)
[stacktrace]
#0 vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(168): Illuminate\\Database\\DatabaseManager->configuration('projects')                                                   
#1 vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(351): Illuminate\\Database\\DatabaseManager->makeConnection('projects')                                                  
#2 vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(319): Illuminate\\Database\\DatabaseManager->refreshPdoConnections('projects')                                           
#3 vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(73): Illuminate\\Database\\DatabaseManager->reconnect('projects')                                                        
#4 [internal function]: Illuminate\\Database\\DatabaseManager->Illuminate\\Database\\{closure}(Object(Illuminate\\Database\\MySqlConnection))                  
#5 vendor/laravel/framework/src/Illuminate/Database/Connection.php(995): call_user_func(Object(Closure), Object(Illuminate\\Database\\MySqlConnection))                                          
#6 vendor/laravel/framework/src/Illuminate/Database/Connection.php(977): Illuminate\\Database\\Connection->reconnect()
#7 vendor/laravel/framework/src/Illuminate/Database/Connection.php(958): Illuminate\\Database\\Connection->tryAgainIfCausedByLostConnection(Object(Illuminate\\Database\\QueryException), 'select count(*)...', Array, Object(Closure))
#8 vendor/laravel/framework/src/Illuminate/Database/Connection.php(781): Illuminate\\Database\\Connection->handleQueryException(Object(Illuminate\\Database\\QueryException), 'select count(*)...', Array, Object(Closure))
#9 vendor/laravel/framework/src/Illuminate/Database/Connection.php(398): Illuminate\\Database\\Connection->run('select count(*)...', Array, Object(Closure))
#10 vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3133): Illuminate\\Database\\Connection->select('select count(*)...', Array, true)
#11 vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3118): Illuminate\\Database\\Query\\Builder->runSelect()
#12 vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3706): Illuminate\\Database\\Query\\Builder->Illuminate\\Database\\Query\\{closure}()
#13 vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3117): Illuminate\\Database\\Query\\Builder->onceWithColumns(Array, Object(Closure))
#14 vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3633): Illuminate\\Database\\Query\\Builder->get(Array)
#15 vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3561): Illuminate\\Database\\Query\\Builder->aggregate('count', Array)
```

### Steps To Reproduce

Create an on-demand database connection:

```php
$connection = DB::build([
    'name' => 'projects',
    'driver' => 'mysql',
    'database' => 'forge',
    'username' => 'root',
    'password' => 'secret',
]);

$connection->reconnect();
```

**Comment by sebdesign** [comment]
The problem on the DatabaseManager is that the `refreshPdoConnections()` method calls the `makeConnection()` method which attempts to get the config from the `config/database.php`. Since the connection is built on the fly and does not exists on the config file, it throws an `InvalidArgumentException`.

**Comment by crynobone** [comment]
Fixed via https://github.com/laravel/framework/pull/53914
