### ISSUE TITLE
Log failed Iron jobs to failed_jobs table

### ISSUE THREAD

**Issue by dmyers** [laravel/framework#6884]
[Iron](http://status.iron.io) is currently down and jobs don't seem to be going to the `failed_jobs` table.

![screen shot 2015-01-02 at 10 06 17 pm](https://cloud.githubusercontent.com/assets/207171/5601543/9cf413ee-92cb-11e4-8963-7cc6ba6b74ec.png)

```txt
exception 'Http_Exception' with message 'http error: 503 | Service unavailable' in /var/app/current/vendor/iron-io/iron_core/IronCore.class.php:346

Stack trace:

#0 /var/app/current/vendor/iron-io/iron_core/IronCore.class.php(340): IronCore->reportHttpError(503, 'Service unavail...')

#1 /var/app/current/vendor/iron-io/iron_core/IronCore.class.php(299): IronCore->callWithRetries()

#2 /var/app/current/vendor/iron-io/iron_mq/IronMQ.class.php(273): IronCore->apiCall('POST', 'projects/534d7b...', Array)

#3 /var/app/current/vendor/laravel/framework/src/Illuminate/Queue/IronQueue.php(80): IronMQ->postMessage('default', 'eyJpdiI6ImFKeWc...', Array)

#4 /var/app/current/vendor/laravel/framework/src/Illuminate/Queue/IronQueue.php(65): Illuminate\Queue\IronQueue->pushRaw('{"job":"Worker\\...', NULL)

#5 [internal func
 tion]: Illuminate\Queue\IronQueue->push('....', Array)

#6 /var/app/current/vendor/laravel/framework/src/Illuminate/Queue/QueueManager.php(220): call_user_func_array(Array, Array)

**Comment by GrahamCampbell** [comment]
Yeh. Ironmq is meant to be persisting your jobs for you. Not laravel. The failed jobs table is not for jobs that couldn't be queues, but for jobs that failed while being executed.

**Comment by dmyers** [comment]
Oh I gotcha, didn't realize that thanks Graham.
