### ISSUE TITLE
Laravel make:provider throws exception with provider name is not specified

### ISSUE THREAD

**Issue by BardiaAfshin** [laravel/framework#7153]
When you attempt to use the artisan CLI to generate a provider via

```sh
./artisan make:provider
```

you get an exception
```sh
 artisan make:provider
exception 'RuntimeException' with message 'Not enough arguments.' in /Users/bafshin/workspace/expeditions/laravel/develop-laravel/vendor/symfony/console/Symfony/Component/Console/Input/Input.php:77
Stack trace:
#0 /Users/bafshin/workspace/expeditions/laravel/develop-laravel/vendor/symfony/console/Symfony/Component/Console/Command/Command.php(248): Symfony\Component\Console\Input\Input->validate()
#1 /Users/bafshin/workspace/expeditions/laravel/develop-laravel/vendor/laravel/framework/src/Illuminate/Console/Command.php(101): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /Users/bafshin/workspace/expeditions/laravel/develop-laravel/vendor/symfony/console/Symfony/Component/Console/Application.php(874): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /Users/bafshin/workspace/expeditions/laravel/develop-laravel/vendor/symfony/console/Symfony/Component/Console/Application.php(195): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Foundation\Console\ProviderMakeCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /Users/bafshin/workspace/expeditions/laravel/develop-laravel/vendor/symfony/console/Symfony/Component/Console/Application.php(126): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /Users/bafshin/workspace/expeditions/laravel/develop-laravel/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(91): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /Users/bafshin/workspace/expeditions/laravel/develop-laravel/artisan(34): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 {main}
```

It'd be nice if this exception was transformed to a message that simply described the command, and it's requirements 

ie
'you need to specify a provider name'

**Comment by GrahamCampbell** [comment]
This exception is quite readable. TBH, I think we should use the symfony exception handler in the cli, it produces a better message for this exception.
