### ISSUE TITLE
[L5] app:name does work only once

### ISSUE THREAD

**Issue by nonamez** [laravel/framework#7285]
So, when use app:name for the first time is everything ok, but after the first time it fails.

```bash
MacBook-Pro-:$ php artisan app:name portfolio
Application namespace set!
MacBook-Pro:$ php artisan app:name PersonalSpace
PHP Fatal error:  Uncaught exception 'ReflectionException' with message 'Class portfolio\Console\Kernel does not exist' in /Users/*******/Sites/*******/vendor/laravel/framework/src/Illuminate/Container/Container.php:776
Stack trace:
#0 /Users/*******/Sites/*******/vendor/laravel/framework/src/Illuminate/Container/Container.php(776): ReflectionClass->__construct('portfolio\\Conso...')
#1 /Users/*******/Sites/*******/vendor/laravel/framework/src/Illuminate/Container/Container.php(656): Illuminate\Container\Container->build('portfolio\\Conso...', Array)
#2 /Users/*******/Sites/*******/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(572): Illuminate\Container\Container->make('portfolio\\Conso...', Array)
#3 /Users/*******/Sites/*******/vendor/laravel/framework/src/Illuminate/Container/Container.php(229): Illuminate\Foundation\Application->make('portfolio\\Conso...', Array)
#4 /Users/*******/Sites/*******/vendor/laravel/framework/src/Illuminate/Container/Container.php(773): Illuminate\Container\Container->Illumin in /Users/*******/Sites/*******/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 776

Fatal error: Uncaught exception 'ReflectionException' with message 'Class portfolio\Console\Kernel does not exist' in /Users/*******/Sites/*******/vendor/laravel/framework/src/Illuminate/Container/Container.php:776
Stack trace:
#0 /Users/*******/Sites/*******/vendor/laravel/framework/src/Illuminate/Container/Container.php(776): ReflectionClass->__construct('portfolio\\Conso...')
#1 /Users/*******/Sites/*******/vendor/laravel/framework/src/Illuminate/Container/Container.php(656): Illuminate\Container\Container->build('portfolio\\Conso...', Array)
#2 /Users/*******/Sites/*******/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(572): Illuminate\Container\Container->make('portfolio\\Conso...', Array)
#3 /Users/*******/Sites/*******/vendor/laravel/framework/src/Illuminate/Container/Container.php(229): Illuminate\Foundation\Application->make('portfolio\\Conso...', Array)
#4 /Users/*******/Sites/*******/vendor/laravel/framework/src/Illuminate/Container/Container.php(773): Illuminate\Container\Container->Illumin in /Users/*******/Sites/*******/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 776
```

P.S. 
```bash
MacBook-Pro-:$ php artisan dump-autoload
PHP Fatal error:  Uncaught exception 'ReflectionException' with message 'Class portfolio\Console\Kernel does not exist' in /Users/********/Sites/********/vendor/laravel/framework/src/Illuminate/Container/Container.php:776

**Comment by pavankumar0440** [comment]
+1

**Comment by dangreaves** [comment]
I cannot reproduce this with a fresh L5 install but it might be worth doing a search for `"portfolio\"` in your entire codebase after running `php artisan app:name PersonalSpace`.

This will give a much better indication of what is stuck in the old namespace and a possible cause.

**Comment by jhkrischel** [comment]
The only way I was able to get a new app working, with a rename, was by running dump-autoload after the rename:

```
laravel new project; cd project
php artisan app:name NewProject
composer dump-autoload
```

Without the dump-autoload, I'd get a ReflectionException:

```
Fatal error: Uncaught exception 'ReflectionException' with message 'Class NewProject\Http\Kernel does not exist' in /home/vagrant/Code/project/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 776
```

**Comment by bradleySuira** [comment]
Hi, set the correct Name of your app in vendor/composer/autoload_psr4.php, find this line: 'YourAppName\\' => array($baseDir . '/app'), then you can run composer dump-autoload and after php artisan app:name NewAppName

**Comment by lorey** [comment]
Had the same problem on a fresh installation. ``composer dump-autoload`` fixed the problem. Shouldn't this be in the documentation?

**Comment by jakesyl** [comment]
+1

**Comment by Helg18** [comment]
+bradleySuira Told:
" Hi, set the correct Name of your app in vendor/composer/autoload_psr4.php, find this line: 'YourAppName\' => array($baseDir . '/app'), then you can run composer dump-autoload and after php artisan app:name NewAppName  ..."

Work for me.

**Comment by AbdullahiAbdulkabir** [comment]
What I simply did was to do composer dump-autoload and everything went well
