### ISSUE TITLE
Better error output

### ISSUE THREAD

**Issue by harikt** [laravel/framework#7535]
Hi, 

Was trying `php artisan make:console` and noticed 

```
exception 'RuntimeException' with message 'Not enough arguments.' in /laravel-test/vendor/symfony/console/Symfony/Component/Console/Input/Input.php:77
Stack trace:
#0 /laravel-test/vendor/symfony/console/Symfony/Component/Console/Command/Command.php(248): Symfony\Component\Console\Input\Input->validate()
#1 /laravel-test/vendor/laravel/framework/src/Illuminate/Console/Command.php(101): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /laravel-test/vendor/symfony/console/Symfony/Component/Console/Application.php(874): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /laravel-test/vendor/symfony/console/Symfony/Component/Console/Application.php(195): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Foundation\Console\ConsoleMakeCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /laravel-test/vendor/symfony/console/Symfony/Component/Console/Application.php(126): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /laravel-test/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(91): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /laravel-test/artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 {main}
```

My experience working with Symfony console is it provides did you mean, or displays the help command. Can we make it some what similar than exceptions ?

Thank you.

**Comment by taylorotwell** [comment]
This is fixed in recent commit. Will be tagged stable today probably! :)

**Comment by harikt** [comment]
Thank you @taylorotwell . Same errors happened for other commands. Hope that also got fixed.
