### ISSUE TITLE
Session regenerated on every request because of filesystem issue

### ISSUE THREAD

**Issue by appcia** [laravel/framework#8007]
When I attempt to log in I have:

```
[2015-03-15 17:37:52] local.ERROR: exception 'ErrorException' with message 'file_put_contents(): Exclusive locks are not supported for this stream' in /home/vagrant/Projects/jackonet/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:74
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'file_put_conten...', '/home/vagrant/P...', 74, Array)
#1 /home/vagrant/Projects/jackonet/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(74): file_put_contents('/home/vagrant/P...', 'a:5:{s:6:"_toke...', 2)
#2 /home/vagrant/Projects/jackonet/vendor/laravel/framework/src/Illuminate/Session/FileSessionHandler.php(70): Illuminate\Filesystem\Filesystem->put('/home/vagrant/P...', 'a:5:{s:6:"_toke...', true)
#3 /home/vagrant/Projects/jackonet/vendor/laravel/framework/src/Illuminate/Session/Store.php(255): Illuminate\Session\FileSessionHandler->write('aacb734a24ffe43...', 'a:5:{s:6:"_toke...')
#4 /home/vagrant/Projects/jackonet/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(89): Illuminate\Session\Store->save()
#5 /home/vagrant/Projects/jackonet/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(131): Illuminate\Session\Middleware\StartSession->terminate(Object(Illuminate\Http\Request), Object(Illuminate\Http\Response))
#6 /home/vagrant/Projects/jackonet/public/index.php(57): Illuminate\Foundation\Http\Kernel->terminate(Object(Illuminate\Http\Request), Object(Illuminate\Http\Response))
#7 {main}  
```

I am forced to use 'cookie' session driver because of above error.

**Comment by JoostK** [comment]
There's a multitude of sessions drivers available besides file and cookie.

**Comment by appcia** [comment]
Yes I know, but it is a little bit annoying because I am using homestead with default configuration.

**Comment by appcia** [comment]
I am not understand why is it closed now. I migrated to L5 but everything works fine. After `composer update` some time ago issue occurred so it is rather fixable.

**Comment by GrahamCampbell** [comment]
We already had a long discussion about this before.

**Comment by GrahamCampbell** [comment]
Feel free to read it.
