### ISSUE TITLE
Homestead: psych.rb error

### ISSUE THREAD

**Issue by Jamesking56** [laravel/framework#9728]
Hello,

I'm getting a weird error with Laravel Homestead.

I'm running Mac OS X 10.10.4, Vagrant 1.7.4 and Homestead 2.1.5. When I run `homestead up` I get this Ruby error:

````
/opt/vagrant/embedded/lib/ruby/2.0.0/psych.rb:205:in `parse': (<unknown>): did not find expected alphabetic or numeric character while scanning an alias at line 21 column 12 (Psych::SyntaxError)
        from /opt/vagrant/embedded/lib/ruby/2.0.0/psych.rb:205:in `parse_stream'
        from /opt/vagrant/embedded/lib/ruby/2.0.0/psych.rb:153:in `parse'
        from /opt/vagrant/embedded/lib/ruby/2.0.0/psych.rb:129:in `load'
        from /Users/Jamesking56/Sites/personal/licenseapp/Vagrantfile:18:in `block in <top (required)>'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/config/v2/loader.rb:37:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/config/v2/loader.rb:37:in `load'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/config/loader.rb:103:in `block (2 levels) in load'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/config/loader.rb:97:in `each'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/config/loader.rb:97:in `block in load'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/config/loader.rb:94:in `each'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/config/loader.rb:94:in `load'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/vagrantfile.rb:28:in `initialize'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:689:in `new'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:689:in `vagrantfile'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:441:in `host'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:207:in `block in action_runner'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:33:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:33:in `run'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:428:in `hook'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:671:in `unload'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/bin/vagrant:177:in `ensure in <main>'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/bin/vagrant:177:in `<main>'
````

**Comment by tshafer** [comment]
Did you edit the homestead.yaml file at all?

**Comment by Jamesking56** [comment]
I found out why, my YAML wasn't syntactically correct so I used a YAML linter to fix it.
